### ISSUE TITLE
Can't get orientation data from controller emulator on certain phones

### ISSUE THREAD

**Issue by jdknox** [googlevr/gvr-android-sdk#100]
I installed the Daydream controller emulator on my Droid X (KitKat 4.4 via CM11), but the orientation information does not get sent to my headset. I followed the instructions from [here](https://developers.google.com/vr/concepts/dev-kit-setup#set_up_the_controller_phone), but only the button presses are recognized in the demo paint app discussed on that page, not the orientation of the controller.

I have also tested the controller emulator on a Nexus 5 and Nexus 7, and it works fine, so I know I have the headset setup correctly.

**Comment by sigmaxipi** [comment]
The [Droid X doesn't have a gyroscope](http://www.gsmarena.com/motorola_droid_x-3473.php) so it can't be used as a controller.

**Comment by jdknox** [comment]
I should have checked that.  I was only considering the accelerometer.

**Comment by sigmaxipi** [comment]
Docs have been updated.
