### ISSUE TITLE
Can't build the NDK-Beta version of Treasure Hunt

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [googlevr/gvr-android-sdk#104]
A fresh cloning yields a valid project that can't be built with Android Studio 2.1.1 and NDK 12, it seems.
I've attached the compiler output. I believe it's valid to note that I'm used to build and run Cardboard NDK apps with the older 0.7 SDK all the time - even with the lastest alpha 0.8.0 version of the experimental ndk gradle plugin.

Is there any special requirement for building it?
[output.txt](https://github.com/googlevr/gvr-android-sdk/files/288078/output.txt)

**Comment by sigmaxipi** [comment]
What happens when you run `gradlew build` on the command line in a fresh clone without using Android Studio? Also, the current **treasurehunt/build.gradle** file is configured to use **gradle-experimental:0.4.0" for now.

The relevant error in your log is **error: 'thread' in namespace 'std' does not name a type
   std::thread audio_initialization_thread_;**. In your previous NDK projects, were you able to reference std::thread? If no, there might be something wrong with your C++11 configuration.

**Comment by TheFakeMontyOnTheRun** [comment]
Hello @sigmaxipi,
tried your suggestion, but the result was the same.

To be fair, I tried using std::mutex in the past and faced similar issues. How integrated with my host's toolchain is NDK? I kinda expected it to use it's own stuff - and since I have't touched it, everything should be ok.

**Comment by jdduke** [comment]
Which version of gcc are you using? And which NDK version? I believe std::thread may require either clang or gcc 4.8. If that's an issue for you, we could probably remove the std::thread dependency in the NDK sample(s) altogether.

**Comment by TheFakeMontyOnTheRun** [comment]
AFAIK, the newest stable NDK version defaults to Clang, right? I'm no NDK 12. Maybe I could try moving into the bleeding edge (since I'm already using gradle-experimental, after all)?

**Comment by TheFakeMontyOnTheRun** [comment]
I could try removing it, if that's of any help, so we would be sure if the culprit lies on `std::thread`.

**Comment by TheFakeMontyOnTheRun** [comment]
By simply commenting out anything touched by the audio initialization thread, I was able to finally run the demo. Thanks!

(sorry it took me so long. I was incredibly busy).

**Comment by TheFakeMontyOnTheRun** [comment]
Also, after updating my NDK to the newest version (just released, it seems), the pristine version from the repo now works.
