### ISSUE TITLE
loadVideo  not supported  remote URL？？

### ISSUE THREAD

**Issue by honjane** [googlevr/gvr-android-sdk#105]
VrVideoView.loadVideo(Uri.prase("http://host/test.mp4"));

`java.io.FileNotFoundException: /mp43/33279-OneRepublicFtTimbaland-Apologize[68mtv.com].mp4: open failed: ENOENT (No such file or directory)`

It seems to be accessing the sdcard file， not accessing the remote file
@tjohns @dav-cz @borismus @belm0

**Comment by honjane** [comment]
Upgrade to v0.8.0 ，is working

**Comment by nihalmehdi** [comment]
Wants to try work around .. here it is..
public class DownloadVideoTask extends AsyncTask<String, Void, Uri> {
    String videoUrl ="http://host/test.mp4"
    private VrVideoView vrvideoView;
    private Context context;
    DownloadVideoTask (VrVideoView vrvideoView,Context context)
    {
        this.vrvideoView = vrvideoView;
        this.context = context;
    }

    @Override
    protected Uri doInBackground(String... url) {
        //HttpsURLConnection.setDefaultSSLSocketFactory(new NoSSLv3Factory());
        HttpURLConnection urlConnection = null;
        String fileName = "dubai1.mp4";
        String filepath = context.getFilesDir() + File.separator + fileName;
        File file = null;
        try {
            URL videoUri = new java.net.URL(videoUrl);
            urlConnection = (HttpURLConnection) videoUri.openConnection();
            urlConnection.connect();
            InputStream in = urlConnection.getInputStream();
            FileOutputStream output = context.openFileOutput(fileName, context.MODE_PRIVATE);
            Utility.copyFile(in,output);
        }
        catch (java.net.MalformedURLException mex){
            String test = mex.toString();
            //Toast.makeText("Utility", mex.getMessage(), Toast.LENGTH_LONG);
        }
        catch (Exception ex)
        {
            String test = ex.toString();
            //Toast.makeText("tag",ex.getMessage(),Toast.LENGTH_LONG);
        }
        finally {
            if( urlConnection!= null ) {
                urlConnection.disconnect();
            }
        }

        return Uri.parse(filepath);
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    @Override
    protected void onPostExecute(Uri videoUri) {
        try {
            vrvideoView.loadVideo(videoUri);
            vrvideoView.playVideo();
        }
        catch (Exception ex){
            String msg = ex.getMessage();
     
        }

    }
}

**Comment by nathanmartz** [comment]
Looks like this is resolved.
