### ISSUE TITLE
MX4 Pro(meizu) will auto-rotate when play vr vedio

### ISSUE THREAD

**Issue by xm007forgithub** [googlevr/gvr-android-sdk#106]
I am a chinese developer,my phone is MX4 Pro(meizu).When I play vr vedio , the picture will auto-rotate.

**Comment by nihalmehdi** [comment]
Disable auto-rotate in your phone from setting option...

**Comment by dav-cz** [comment]
What @nihalmehdi (thanks!) suggested should work. Please re-open if you think there's an issue with the SDK itself.
