### ISSUE TITLE
How to trigger onCardboardTrigger from VrPanoramaView

### ISSUE THREAD

**Issue by nihalmehdi** [googlevr/gvr-android-sdk#107]

**Comment by sigmaxipi** [comment]
What are you trying to do? Are you referring to [GvrActivity.onCardboardTrigger()](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrActivity.html#public-methods_2)? VrPanoramaView doesn't extend GvrActivity so this functionality isn't available. Instead use [VrEventListener.onClick()](https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/common/VrEventListener.html#public-methods_2) via [VrPanoramaView.setEventListener()](https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/pano/VrPanoramaView.html#public-methods_2)

**Comment by nihalmehdi** [comment]
I wants to navigate to another view when i am within Full VR Panorma View using magnetic latch. Does VrEventListener.onClick() works on magnetic latch movement.

**Comment by dav-cz** [comment]
VrPanoramaView doesn't support magnet clicks. We now consider magnet clicks deprecated (not reliable across all phones) so we didn't add support for new code, see 0.8 release note here:
https://developers.google.com/vr/android/release-notes#new

**Comment by nihalmehdi** [comment]
Thanks Dav for the update... when can we expect new device with controller..
