### ISSUE TITLE
It will be great to have a Maven repository with this library's artifacts

### ISSUE THREAD

**Issue by albertoruibal** [googlevr/gvr-android-sdk#114]
I want to distribute some code with demos using this library and it will be much easier if you publish the artifacts in Bintray/JCenter or in Maven Central.

Do you have any plans to create a Maven repository?

**Comment by sigmaxipi** [comment]
Yes. We're working on distributing via a standard repository instead of just shipping .aar files. Stay tuned.

**Comment by albertoruibal** [comment]
Great! Thank you!

**Comment by leewp** [comment]
Excuse me ,how long it will be

**Comment by nathanmartz** [comment]
Sorry, leewp, but we generally can't make promises around specific release timing here.

**Comment by leewp** [comment]
OK，Thank you!

**Comment by CAMOBAP795** [comment]
I don't know is it official or not but I found dependencies here https://bintray.com/mobialia

Template:
https://bintray.com/mobialia/maven/com.google.gvr.*

Examples:
https://bintray.com/mobialia/maven/com.google.gvr.base
https://bintray.com/mobialia/maven/com.google.gvr.audio
https://bintray.com/mobialia/maven/com.google.gvr.common

**Comment by albertoruibal** [comment]
No, it's not official. I created this alternative repo to distribute our jmini3d-vr-demo in github. I will keep it updated while the official repo is not published.

**Comment by b95505017** [comment]
Any news here? It seems that gvr still not distribute to jCenter.

**Comment by albertoruibal** [comment]
Finally, there is an official repository at http://google.bintray.com/googlevr

More info at: https://developers.google.com/vr/android/get-started
