### ISSUE TITLE
VrVideoView Doesn't Support HLS Playback

### ISSUE THREAD

**Issue by azeemmohd** [googlevr/gvr-android-sdk#116]
I have a use-case where I need to play HLS Streams of mono 360 videos in VrVideoView widget. I see that this widget is backed by the ExoPlayer, but is using a HttpDataSource instead of a HLS data source in case the uri provided is for a HLS stream.

I will be very thankful if you can make a quick fix for supporting HLS Streams via the VrVideoView widget.

**Comment by azeemmohd** [comment]
Sample HLS stream that I am testing: httplive://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8

**Comment by dav-cz** [comment]
Hi @azeemmohd, we had an issue with the push yesterday. With today's update you'll find HLS support in VrVideoView. 
Use the loadVideo(url, options) function, with options.inputFormat = Options.FORMAT_HLS.

In particular your video now works with the sample video app:

> adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -d "http://vevoplaylist-live.hls.adaptive.level3.net/vevo/ch1/appleman.m3u8" --ei inputFormat 2

**Comment by azeemmohd** [comment]
@dav-cz : That's awesome, thanks a lot.
