### ISSUE TITLE
rightEye not null in Renderer.onDrawFrame when VR Mode is disabled

### ISSUE THREAD

**Issue by RikHeijdens** [googlevr/gvr-android-sdk#120]
According to the [documentation](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView.Renderer#public-methods) the rightEye should be null when VR Mode is disabled.

This does not appear to be the case for version 0.8.0/1 of the GVR SDK.

**Comment by dav-cz** [comment]
Thanks for report, this should be fixed in our next release.

**Comment by dav-cz** [comment]
Fixed in 0.8.5

**Comment by RikHeijdens** [comment]
Thanks! Where can I find release notes for 0.8.5? They do not appear to be on the release notes page (yet).

**Comment by nathanmartz** [comment]
They'll be on the site by the end of the week.
