### ISSUE TITLE
Incorrect initial yaw using VrView

### ISSUE THREAD

**Issue by richardchen331** [googlevr/gvr-android-sdk#122]
When using the sample VrView app (simplepanowidget or simplevideowidget), the yaw is off by 180 degrees (i.e. looking at the scene on the left/right edge of the equirectangular image/video, instead of looking at the scene in the middle). This doesn't seems to be the intended behavior.

**Comment by xieqiupeng** [comment]
I have the same question.

**Comment by dav-cz** [comment]
Thanks for the reports. This will be fixed in our upcoming release.

**Comment by dav-cz** [comment]
Fixed with v 0.9.0
