### ISSUE TITLE
360 video orientation change issue

### ISSUE THREAD

**Issue by KCHariram** [googlevr/gvr-android-sdk#125]
Hi

I have integrated this SDK in my application. I will show the VrVideoView as the fullscreen using match parent. and i locked the screen for better user experience to view the 360 video, but i have done some controls over the screen. How can i change the position when change orientation.

OR

Please suggest any alternate idea.
1. Screen not rotate when change orientation
2, Update the icon position when change the orientation

**Comment by dav-cz** [comment]
I'm not sure I understand the issue ... 

"How can i change the position when change orientation."
what position? what orientation?

**Comment by RamIndani** [comment]
@KCHariram I am not sure what exactly you are trying to do but see if approach mentioned in #135 works for you.

**Comment by dav-cz** [comment]
Closing this for now. @KCHariram please reopen with more details if #135 doesn't solve it (thanks @RamIndani !)
