### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by rhsu0268** [googlevr/gvr-android-sdk#126]
Does anyone have any idea on how to create a button inside the panorama view? By this, I don't mean the buttons that bring you to the VR or full screen view. 

I want the button to show up inside the VR and full screen views but they just disappear once you get onto it. Please advise. 

Thanks,
Richard

**Comment by nathanmartz** [comment]
You would need to use the lower level GVRView APIs and write OpenGL code to render the buttons. You can't use regular android UI elements in VR.
