### ISSUE TITLE
Going back to previous Activity from full screen mode

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#128]
Based on response on following issue I was able to implement a "always full screen" mode. 
https://github.com/googlevr/gvr-android-sdk/issues/66

For reference I am doing the following
```
 ((ViewGroup)((ViewGroup)((ViewGroup)((ViewGroup)((ViewGroup)findViewById(R.id.main_layout))
                .getChildAt(0))
                .getChildAt(0))
                .getChildAt(1))
                .getChildAt(2))
                .getChildAt(1)
                .performClick();
```

Now I'd like to be able to go from the full screen mode directly back to previous activity but cannot find a way to hijack the back button press. I've tried the following to no avail
```
  @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (Integer.parseInt(android.os.Build.VERSION.SDK) > 5
                && keyCode == KeyEvent.KEYCODE_BACK
                && event.getRepeatCount() == 0) {
            onBackPressed();
            return true;
        }
        return super.onKeyDown(keyCode, event);
    }


    @Override
    public void onBackPressed() {
        super.onBackPressed();
        finish();

    }
```

Any help/suggestions would be appreciated

**Comment by hegazy** [comment]
```
videoWidgetView.post(new Runnable() {
            @Override
            public void run() {
                videoWidgetView.fullScreenDialog.setOnDismissListener(new DialogInterface.OnDismissListener() {
                    @Override
                    public void onDismiss(DialogInterface dialog) {
                        videoWidgetView.setVisibility(View.INVISIBLE);
                        finish();
                    }
                });
            }
        });
```
I'm using this. I think it's time to add these options to the library.

**Comment by nathanmartz** [comment]
Thanks for posting this workaround. The demand is pretty obvious for programatic control of view modes, so we're planning to add that in the next release.

**Comment by hegazy** [comment]
@nathanmartz That will be very cool!

**Comment by dav-cz** [comment]
With v0.9.0 there's now an [official API](https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/common/VrWidgetView.html#setDisplayMode(int)) for this.

**Comment by electmk** [comment]
@dav-cz 
How to go from the full screen mode directly back to previous activity ??

**Comment by Awsom3D** [comment]
@dav-cz 
I don't see how the official API fix this problem.
Exiting the fullscreen mode still does not exit the activity.

@electmk the code from @hegazy worked on older version of the gvr-android-sdk : 1.20.0 for instance.

**Comment by Awsom3D** [comment]
@electmk the solution is to use the onDisplayModeChanged callback from VrPanoramaEventListener.

```
@Override
public void onDisplayModeChanged(int newDisplayMode) {
    super.onDisplayModeChanged(newDisplayMode);
    if (newDisplayMode == VrWidgetView.DisplayMode.EMBEDDED) {
        VrPanoramaActivity.this.finish();
    }
}
```

**Comment by electmk** [comment]
@Awsom3D 
I got error (Method does not override method from its superclass) when i put the method in VrPanoramaActivity

**Comment by Awsom3D** [comment]
@electmk as said before the onDisplayModeChanged callback is from VrPanoramaEventListener, not VrPanoramaActivity.

From your VrPanoramaActivity onCreate you should set a VrPanoramaEventListener on your VrPanoramaView :

```
panoWidgetView = (VrPanoramaView) findViewById(R.id.pano_view);
panoWidgetView.setEventListener(new ActivityEventListener());
```

Then from this listener, override the onDisplayModeChanged callback

```
private class ActivityEventListener extends VrPanoramaEventListener {
  @Override
  public void onDisplayModeChanged(int newDisplayMode) {
  [...]
```

**Comment by electmk** [comment]
@Awsom3D 
It's worked .. thank you 
But it shows a black screen for seconds before finish .. Can I avoid this?

**Comment by Awsom3D** [comment]
@electmk sorry, no clue.
