### ISSUE TITLE
Mismatch between Cardboard (2015) specification and QR code info

### ISSUE THREAD

**Issue by shirj** [googlevr/gvr-android-sdk#129]
_(I understand this is not really a code issue with this project, but this is probably the closest related project where I could find an answer)_

I am working on a project that requires accurate knowledge of the Field of View (FOV) of the Cardboard viewer.

In "Google Cardboard IO 2015 Technical Specifications.pdf" (which is a part of the [Google Cardboard Manufacturer Kit (.zip)](https://vr.google.com/cardboard/downloads/wwgc_manufacturers_kit.zip) or also [available here](http://schd.ws/hosted_files/ssslc2016/0b/Google%20Cardboard%20IO%202015%20Technical%20Specifications.pdf#page=3)) it specifies on _page 3_:

> Google Cardboard (I/O 2015 edition) contains custom designed, **80° FOV**, 34 mm diameter lenses.

However, when I decoded the QR code on the Cardboard with [this CardboardDevice.proto message definition](https://github.com/google/wwgc/blob/master/www/CardboardDevice.proto), I obtained the following information:

> vendor: "Google"
> model: "Cardboard"
> screen_to_lens_distance: 0.0392999984324
> inter_lens_distance: 0.0639000013471
> **left_eye_field_of_view_angles: 60.0**
> **left_eye_field_of_view_angles: 60.0**
> **left_eye_field_of_view_angles: 60.0**
> **left_eye_field_of_view_angles: 60.0**
> tray_to_lens_distance: 0.035000000149
> ...

Therefore the QR code is suggesting that this Cardboard has a **120° FOV**.

Why is there a mismatch between the two sources? And which is the correct number? If the number on in the QR code is wrong, then does it mean that this SDK has always been rendering incorrectly for the Cardboard Viewer? 

Thanks!

**Comment by dav-cz** [comment]
Thanks for the report, I forwarded this to relevant folks.

**Comment by Azlun** [comment]
really looking for a simple web based or offline tools can decode current_device_param files from different cardboard versions.

**Comment by jdduke** [comment]
The FOV angles in the headset proto aren't meant to be perfectly representative of the headset's actual FOV. Rather, they're used as an optimization to avoid rendering pixels that cannot be seen, and are generally *larger* than the actual FOV.
