### ISSUE TITLE
Buffering problems on Nexus 5x N beta 4

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#130]
When using a Nexus 5x running android N preview 4, playing a remote video using the following command:
adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -d "http://video1.nytimes.com/video/360-demo/cool.mp4" --ei inputFormat 1

Causes a video that is very laggy. By that I mean the video will play for 1 second then stop audio/video. Few seconds later it will start video/audio again. This is over a 4g connection that has no problems playing other videos (youtube or within NYT app for example) 

Using HLS has no issues, similar Android M has no issues on same hardware.  Thanks for help :-)

**Comment by nathanmartz** [comment]
So, you're saying that HLS "just works"? If so, then I highly recommend HLS.

**Comment by digitalbuddha** [comment]
Even if we can use HLS it seems like SDK issues that are specific to a Nexus Phone and a public API need to be addressed.

**Comment by jdduke** [comment]
For now the solution is as discussed, using HLS. We might consider streaming improvements at later date.
