### ISSUE TITLE
VrVideoView orientation does not change when used with onConfigurationChanged and android:configChanges="orientation|keyboard|keyboardHidden|screenSize" in AndroidManifest.xml

### ISSUE THREAD

**Issue by RamIndani** [googlevr/gvr-android-sdk#135]
Hi,

I am using VrVideoView to render 360 video from a fragment and specified android:configChanges="orientation|keyboard|keyboardHidden|screenSize" in my AndroidManifest.xml for the Activity which holds this fragment. I am managing orientation change using onConfigurationChanged in side fragment and what I have observed is when there is change in orientation VrVideoView does not change the video orientation the way it does in the Google Code lab [CodeLab URL](https://codelabs.developers.google.com/codelabs/vr_view_app_101/index.html?index=..%2F..%2Findex#0)
When video is loaded in portrait it looks good.
![gvr1](https://cloud.githubusercontent.com/assets/3529605/16434643/da0e2a82-3d45-11e6-90d0-003f0c2770a1.png)

If i rotate my phone to Landscape

![gvr2](https://cloud.githubusercontent.com/assets/3529605/16434651/eb38a1fc-3d45-11e6-8019-d1c864d2d44a.png)

To verify I rotated above image and it appears as expected.
![gvr2 - after rotate](https://cloud.githubusercontent.com/assets/3529605/16434657/f3d48c68-3d45-11e6-83eb-b573cdacec40.png)

Look forward towards your response

**Comment by RamIndani** [comment]
The solution so far is to inflate the landscape/horizontal fragment view again, remove previous fragment from parent view and attach new fragment. This works only when you are not allowing activity to destroy when orientation changes.

**Comment by ariviere** [comment]
The issue with this method is that you have a black screen while going from portrait to landscape and vice versa. Isn't it possible to have "android:configChanges="orientation|keyboard|keyboardHidden|screenSize" and to tell your video that the orientation changed so it can adapt automatically ?

**Comment by RamIndani** [comment]
Most probably you are experiencing black screen because your view is destroyed and recreated, try reloading video when orientation changes. I assumed some things before commenting, what I am saying may not apply for you but if you haven't given try to it then please try once. To better understand what I am saying is to refer android docs regarding orientation change handling in android [here](handling orientation changes android)

**Comment by ariviere** [comment]
I will try it ASAP, thanks for the fast answer :)

**Comment by ariviere** [comment]
Yes, my view is destroyed and recreated but if I don't use configChanges="orientation|keyboard|keyboardHidden|screenSize". But if I use it, it won't be destroyed and recreated. My problem is that the video doesn't have the correct orientation if I do that just like your screenshot.

By removing the previous fragment and attach a new fragment, I guess you destroy and recreate the video, so you also have a black screen right ? And the problem would be the same by reloading the video (except if you use a method I don't know).

I guess what you didn't understand is that the video is starting after the black screen, but I want to avoid it and keep a clean user experience.

**Comment by RamIndani** [comment]
Yes, that's why I said for now this is the solution, another question raises when implementing orientation changes is "How do you know if user is rotating to change the app orientation or rotating to view 360 video at certain angle?". If you find any better solution then please share.
