### ISSUE TITLE
How to show head coordinates?

### ISSUE THREAD

**Issue by lukassruc** [googlevr/gvr-android-sdk#137]
Hello,
I would like to add to this sample app coordinates which will show head rotation (something like: x=?; y=?; z=?...).
I tried head.Transform, but it didn´work.
I have no idea how to do it... Does anyone of you?
Thanks

**Comment by sigmaxipi** [comment]
Do you want rotation or direction? For rotation, use [HeadTransform.getEulerAngles](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/HeadTransform.html#getEulerAngles(float[], int)) to get pitch, yaw, and roll. For direction, use [.getForwardVector](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/HeadTransform.html#getForwardVector(float[], int)) to get an x,y,z vector.

**Comment by lukassruc** [comment]
I used HeadTransform in SimpleVrVideoActivity app, but it didn´t work. Is there any option how to show x,y,z vector concretely in this app?
(I don´t know how to involve the HeadTransform class into this app..)
Thank you

**Comment by dav-cz** [comment]
We'll have a new API for this in our upcoming release.
See this other issue that tracks this:
https://github.com/googlevr/gvr-android-sdk/issues/143
