### ISSUE TITLE
Google VR for x86

### ISSUE THREAD

**Issue by isometriq** [googlevr/gvr-android-sdk#138]
Is it possible to use the GoogleVR framework on Android emulators, on a x86 platform?
Seems to be limited to ARM processors...
If there is a way, how can it be done?

**Comment by isometriq** [comment]
Ok, I was able to make it work!

1. unzip the "base.aar" file
2. go to "/jni"
3. create a folder "x86"
4. copy the "libgvrbase.so" file from here:
https://github.com/googlevr/gvr-android-sdk/tree/master/libraries/native/x86
5. zip the contents (and rename back to "base.aar" file), cleanup, etc
6. compile and run

IMPORTANT: I had to make sure the ".aar" file and ".so" were from the same version (got all the files from tag 0.8.1)

This now it works in the Nexus5 API21 emulator with recommended settings and HAXM accelerated.

Found the hints here:
https://github.com/googlevr/gvr-android-sdk/tree/master/libraries/native

**Comment by sigmaxipi** [comment]
You don't need to add these files to the .aar. See the instructions at [samples/sdk-simplepanowidget/build.gradle](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-simplepanowidget/build.gradle) for info on how to properly configure your build system.
