### ISSUE TITLE
panoWidgetView图片显示不对

### ISSUE THREAD

**Issue by jksfood** [googlevr/gvr-android-sdk#139]
为什么demo中的全景图片是上下两部分的那种，我们一般用的就是一个180度的全景图片啊，panoWidgetView会把这种图片拉伸，但是上下部分都是圆形黑色的，这不是我想要的效果啊

**Comment by vinjn** [comment]
Please use English

**Comment by jksfood** [comment]
OK,sorry for my bad english!
Why demo of the panoramic picture is on the two parts of the kind, we generally use is a 180 degree panoramic picture ah, panoWidgetView will put this picture drawing, but part of the round black, this is not what I want results.

**Comment by jksfood** [comment]
is it need special type  360 image?

**Comment by xieqiupeng** [comment]
that form of picture or video used for 3d mode. the top picture will be rendered for your left eye,the bottom one for your right eye. 3d is difference from panorama. it makes feeling stereo not wide,话说use english very 费劲。

**Comment by jksfood** [comment]
http://7xs0qt.media1.z0.glb.clouddn.com/search/index/1467357613879.jpg       like this image,why it is mot useful?

**Comment by jksfood** [comment]
@xieqiupeng  is that means :http://7xs0qt.media1.z0.glb.clouddn.com/search/index/1467357613879.jpg    this photo is 3d,but the cardboard can only support panorama?

**Comment by nathanmartz** [comment]
VR view only supports 360 images. They can be mono or stereo. If they are mono, they should be 2:1 aspect ratio. 1:1 for stereo images. You can find more on the specs here: developers.google.com/vr/concepts/vrview
