### ISSUE TITLE
lost yaw angle in vrvideoview, but pitch angle is right.

### ISSUE THREAD

**Issue by xieqiupeng** [googlevr/gvr-android-sdk#140]
I change the vrvideoview from fullscreen mode to normal mode or oppsite. it make the render lost yaw angle, but pitch angle keeps right.

**Comment by koubiak** [comment]
Do you mean that tracking does not work for yaw when in fullscreen or that orientation gets reset when you transition between modes? 

'Reset' restarts the tracker and therefore you should see the same part of the panorama when starting in the newly transitioned view.

**Comment by xieqiupeng** [comment]
yes, when I transform the mode from EMBEDDED to FULLSCREEN, I want to keep my yaw .do not reset it ,I found out the pitch is still works,but yaw is reset.

**Comment by xieqiupeng** [comment]
yes, when I transform the mode from EMBEDDED to FULLSCREEN, I want to keep my yaw .do not reset it ,I find out the pitch is still works,but yaw has been reseted.

**Comment by koubiak** [comment]
We will investigate and update you.

**Comment by xieqiupeng** [comment]
thank you very much.

**Comment by dav-cz** [comment]
FYI this will be fixed in our upcoming release.

**Comment by dav-cz** [comment]
Fixed with v 0.9.0
https://developers.google.com/vr/android/release-notes
