### ISSUE TITLE
simplevideowidget cannot run on Huawei devices

### ISSUE THREAD

**Issue by sheeyphone** [googlevr/gvr-android-sdk#142]
Hi
I want to use this sdk to play 360video on my app.
It's pretty easy to add in but got some problems on Huawei devices.
Such as Huawei Honor6, Huawei Mate7, Huawei Mate8 and so on...
I think it should be incompatible with Huawei SOC？
Hope to fix it soon.. Thanks!

**Comment by sheeyphone** [comment]
When I run the sample called simplevideowidget on Huawei Devices.
I could get some audio output from my phone but the VrVideoView is still black!

**Comment by nathanmartz** [comment]
Hi. What errors do you see in the logcat?

**Comment by sheeyphone** [comment]
logcat:

07-11 11:54:06.111 9957-9957/com.google.vr.sdk.samples.simplevideowidget I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
07-11 11:54:06.236 9957-9957/com.google.vr.sdk.samples.simplevideowidget I/ExoPlayerImpl: Init 1.5.8
07-11 11:54:06.322 9957-9957/com.google.vr.sdk.samples.simplevideowidget I/SimpleVrVideoActivity: Intent is not ACTION_VIEW. Using the default video.
07-11 11:54:06.328 9957-10014/com.google.vr.sdk.samples.simplevideowidget I/VrWidgetRenderer: Native renderer has just been destroyed. Dropping request.
07-11 11:54:06.329 9957-10015/com.google.vr.sdk.samples.simplevideowidget I/SphericalMetadataMP4: Located spherical metadata:
                                                                                                  <?xml version="1.0"?><rdf:SphericalVideo
                                                                                                  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
                                                                                                  xmlns:GSpherical="http://ns.google.com/videos/1.0/spherical/"><GSpherical:Spherical>true</GSpherical:Spherical><GSpherical:Stitched>true</GSpherical:Stitched><GSpherical:StitchingSoftware>Spherical Metadata Tool</GSpherical:StitchingSoftware><GSpherical:ProjectionType>equirectangular</GSpherical:ProjectionType><GSpherical:StereoMode>top-bottom</GSpherical:StereoMode></rdf:SphericalVideo>
07-11 11:54:06.415 9957-10016/com.google.vr.sdk.samples.simplevideowidget E/HAL: load: id=gralloc != hmi->id=gralloc
07-11 11:54:06.416 9957-10016/com.google.vr.sdk.samples.simplevideowidget I/OpenGLRenderer: Initialized EGL, version 1.4
07-11 11:54:06.478 9957-10014/com.google.vr.sdk.samples.simplevideowidget W/art: Attempt to remove non-JNI local reference, dumping thread
07-11 11:54:06.539 9957-10035/com.google.vr.sdk.samples.simplevideowidget I/System: core_booster, getBoosterConfig = false
07-11 11:54:06.601 9957-10038/com.google.vr.sdk.samples.simplevideowidget I/System: core_booster, getBoosterConfig = false
07-11 11:54:06.771 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported profile 64 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported profile 64 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported profile 64 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported profile 64 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported profile 64 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported profile 64 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized level 0 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile 0 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized level 0 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile 0 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized level 0 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile 0 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized level 0 for video/avc
07-11 11:54:06.772 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile 0 for video/avc
07-11 11:54:06.775 9957-10013/com.google.vr.sdk.samples.simplevideowidget I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
07-11 11:54:06.775 9957-10013/com.google.vr.sdk.samples.simplevideowidget I/VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
07-11 11:54:06.783 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported mime video/x-pn-realvideo
07-11 11:54:06.787 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported mime video/mpeg
07-11 11:54:06.791 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
07-11 11:54:06.792 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile/level 0/2 for video/mpeg2
07-11 11:54:06.792 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
07-11 11:54:06.796 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
07-11 11:54:06.803 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported mime video/vc1
07-11 11:54:06.811 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unsupported mime video/x-flv
07-11 11:54:06.815 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile/level 0/0 for video/mpeg2
07-11 11:54:06.815 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile/level 0/2 for video/mpeg2
07-11 11:54:06.815 9957-10013/com.google.vr.sdk.samples.simplevideowidget W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
07-11 11:54:06.849 9957-10013/com.google.vr.sdk.samples.simplevideowidget I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
07-11 11:54:06.869 9957-10059/com.google.vr.sdk.samples.simplevideowidget I/OMXClient: Using client-side OMX mux.
07-11 11:54:06.889 9957-10059/com.google.vr.sdk.samples.simplevideowidget I/IMG-OMX: IMG_OMXLibWrapper library libomx_vxd.so mLibHandle:0xb2c4d004
07-11 11:54:06.893 9957-10059/com.google.vr.sdk.samples.simplevideowidget I/IMG-OMX: IMG_OMXLibWrapper library libomx_vxe.so mLibHandle:0xb2c4d344
07-11 11:54:06.893 9957-10059/com.google.vr.sdk.samples.simplevideowidget E/IMGTOPAZ: OMX_Init done
07-11 11:54:06.893 9957-10059/com.google.vr.sdk.samples.simplevideowidget E/IMGTOPAZ: Encoder nIndex is overflow or ComponentName is NULL
07-11 11:54:06.912 9957-10060/com.google.vr.sdk.samples.simplevideowidget I/SoftAAC2: limiting to stereo output
07-11 11:54:06.912 9957-10060/com.google.vr.sdk.samples.simplevideowidget I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
07-11 11:54:06.920 9957-10063/com.google.vr.sdk.samples.simplevideowidget I/OMXClient: Using client-side OMX mux.
07-11 11:54:06.925 9957-10062/com.google.vr.sdk.samples.simplevideowidget I/MediaCodec: [OMX.IMG.MSVDX.Decoder.AVC] setting surface generation to 10195969
07-11 11:54:06.927 9957-10063/com.google.vr.sdk.samples.simplevideowidget I/HwExtendedCodec: mime is [video/avc] at setVideoFormat
07-11 11:54:06.985 9957-10013/com.google.vr.sdk.samples.simplevideowidget I/AudioTrack-JNI: audioTrack send start state to pg
07-11 11:54:07.054 9957-9957/com.google.vr.sdk.samples.simplevideowidget I/SimpleVrVideoActivity: Sucessfully loaded video 10027
07-11 11:54:07.056 9957-10014/com.google.vr.sdk.samples.simplevideowidget W/GLConsumer: [SurfaceTexture-1-9957-0] bindTextureImage: clearing GL error: 0x500

**Comment by LeeSniper** [comment]
I got the same problem. When I run my app on HM2A, the video was played correctly. But when I tried to run my app on Huawei mate8 there was only sound but VrVideoView was black.

**Comment by jdduke** [comment]
This looks like an issue with the decoder on the device. Let us know if the problem persists with the latest SDK release.
