### ISSUE TITLE
Determine Head Position in VrPanoramaView

### ISSUE THREAD

**Issue by marcelvoss95** [googlevr/gvr-android-sdk#143]
Is there away to get Information, where the user is looking while in VR-Mode of VrPanoramaView?

**Comment by nathanmartz** [comment]
There is not currently, but it's a popular request.

**Comment by marcelvoss95** [comment]
Is it possible to render Panorama Image into GvrView to use HeadTransform ?

**Comment by dav-cz** [comment]
With v 0.9.0 there's now [an API](https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/common/VrWidgetView.html#getHeadRotation(float[])) to return the head position with yaw, pitch angles.
