### ISSUE TITLE
Tear in VR Video Widget View

### ISSUE THREAD

**Issue by rneogy** [googlevr/gvr-android-sdk#146]
This has been happening for a while now (I first implemented this in May), but I never thought to post here. When using the VR Video Widget, there is a section of noise in the video, completely unexplained, but always in the same place. I'm not really sure why this is here. I've tried running the same application on my android phone (HTC One M7) and it works fine, but on this android device, it creates this tear. VR Panorama View works fine on this device. Does this video widget not work on all resolution screens, such as a 640x360 screen?

![sphericalvideocrack](https://cloud.githubusercontent.com/assets/10761674/16630955/842719c6-438a-11e6-8128-53d8de9fcb98.png)

**Comment by dav-cz** [comment]
So on what Android device do you see the issue?
Could you provide a link to your video somehow? 

Also do you see this issue if you play this video with Media Player or ExoPlayer directly?

**Comment by rneogy** [comment]
Google Glass. I don't think I would - as I said, it works perfectly on other android devices. I'll try and take a video soon.

**Comment by nathanmartz** [comment]
Very likely there is an encoding issue in that video that for some reason
most phones handle but your Google Glass decoder has an issue with.

**Comment by sigmaxipi** [comment]
Does the video play properly with another video player on Glass? That would isolate an issue with the decoder. Also, does this happen with videos of other sizes? Some decoders assume the video is a multiple of 32 (or another number) and cause a mismatch between the video decoding and GL rendering. Try videos that are 1920x1080 and also 1024x1024.

**Comment by dav-cz** [comment]
Closing this, most likely it's a platform issue for which we can't do much.
Please re-open with more specifics once you've tried what @sigmaxipi suggested.
