### ISSUE TITLE
onCardboardTrigger() event information

### ISSUE THREAD

**Issue by RikHeijdens** [googlevr/gvr-android-sdk#149]
The GVRView allows you to set a CardboardTriggerListener through the `setOnCardboardTriggerListener(Runnable r)` method.

There appear to be several ways to trigger the listener:

- Touching the view
- Using a magnet

When the listener is triggered there doesn't seem to be a way to detect how the listener was triggered. We would like to be able to detect whether the listener was triggered through a magnet pull or by touching the view.

The reason for that is that we are running into issues with magnetic phone covers, when a magnetic phone cover is used and a user shuts the cover, the onCardboardTrigger event listener will be called several times, which causes our application to behave funky. Ideally we'd have some way to ignore magnetic triggers (if they happen repeatedly).

**Comment by nathanmartz** [comment]
We're actually going to be removing support for the magnet trigger in the next release or the one after, so that will hopefully fix your problem :)

**Comment by dav-cz** [comment]
Closing as obsolete since support for magnet triggers have been officially removed.
https://developers.google.com/vr/android/release-notes
