### ISSUE TITLE
how to get a frame from VRvideo View

### ISSUE THREAD

**Issue by prathimode** [googlevr/gvr-android-sdk#150]
Is it possible to get a frame from a VRVideoView at a particular time?

**Comment by prathimode** [comment]
Actually i want to take a screenshot of the view which i am seeing in VR. How can that achieved?

**Comment by nathanmartz** [comment]
The best solution would be to use the built in android screen shot tools. We do not plan to add frame capture to the GVR SDK.

**Comment by prathimode** [comment]
Can you  please point which Screen shot tools i can use here?

**Comment by nathanmartz** [comment]
That's a standard Android question. A bit of web searching should get you sorted out.

**Comment by prathimode** [comment]
@nathanmartz yes there are some solution but most of them are with getting the content of view and another is to use the adb commend but for that you need a rooted device. but both is not feasible for me here as in case of view content data is not coming for video so i was looking for frame extraction from the video itself.
