### ISSUE TITLE
 the font error

### ISSUE THREAD

**Issue by yubaolinfish** [googlevr/gvr-android-sdk#157]
Hello, simpleVideoWidget click on the fullScreen button ,  the font so that the trouble to resolve under, thank you. 
![device-2016-07-14-112442](https://cloud.githubusercontent.com/assets/10411717/16827561/6ac26e32-49ba-11e6-9f06-7b1b5c0e6757.png)
![device-2016-07-14-112318](https://cloud.githubusercontent.com/assets/10411717/16827567/722de994-49ba-11e6-8f2a-e173fdcac49b.png)

**Comment by nathanmartz** [comment]
What version of the SDK are you using? I believe we fixed this in 0.8.1 or 0.8.5.

**Comment by yubaolinfish** [comment]
Two versions (0.8.1 and 0.8.5) have this issue.

![qq 20160714133743](https://cloud.githubusercontent.com/assets/10411717/16829107/a65eb122-49c8-11e6-8783-cff711afad8f.png).


0.8.5 gets here.
![qq 20160714134221](https://cloud.githubusercontent.com/assets/10411717/16829153/0bd56d02-49c9-11e6-9111-a5221ba256b0.png)

0.8.1 gets here.
![qq 20160714134258](https://cloud.githubusercontent.com/assets/10411717/16829157/17ece840-49c9-11e6-971d-ad05fa0e2cc2.png)

**Comment by nathanmartz** [comment]
Thanks for the bug report. What phone and OS are you using?

**Comment by yubaolinfish** [comment]
![device-2016-07-14-143233](https://cloud.githubusercontent.com/assets/10411717/16830302/9cf46fac-49d0-11e6-826d-5f05cabf6a33.png)

Thanks.

**Comment by nathanmartz** [comment]
Thanks again for all of the detail. This bug is in our internal tracker
now, but no firm ETA on a fix.

**Comment by cpena** [comment]
Hi, 
I have the same issue:
![image](https://cloud.githubusercontent.com/assets/1529176/18596778/4b194c92-7c21-11e6-8b3f-ca1dd6d4a286.png)

(The last button is an image)

The OS version is:
![image](https://cloud.githubusercontent.com/assets/1529176/18596831/81408704-7c21-11e6-8614-d9eb1a74ec0b.png)

Best regards,
Christian

**Comment by jdduke** [comment]
This appears to be an issue specific to Android 4.4.2, likely driver-related. We weren't able to find a sufficiently simple workaround, short of an Android upgrade.
