### ISSUE TITLE
Add Manual Scale, IPD and disable distortion correction buttons on Settings menu

### ISSUE THREAD

**Issue by andregm3** [googlevr/gvr-android-sdk#158]
Just like RiftCat (VRidge) implemented, you don't need to scan a QR Code for different IPD and Scale adjust every time some else use the glasses.

![viewport](https://cloud.githubusercontent.com/assets/4154732/16828879/3bca5586-496a-11e6-8559-feabfeac906c.png)

**Comment by andregm3** [comment]
Also a disable distortion correction button would be nice, and you can let only advanced users to access this if you want.

**Comment by mebalzer** [comment]
I would like throw my hat into the ring on this as well.  NEODiVR uPLAy lenses make most of the UI overlay visible, so a way to turn this off with the Google VR setting menu would be great.

**Comment by nathanmartz** [comment]
Thanks for the suggestions. Regarding the gear options, I recommend you implement them in VR or add an additional 2D button yourself. We are unlikely to add them anytime soon.

Regarding disabling elements of the UI, we've added more info in this very similar Unity thread: https://github.com/googlevr/gvr-unity-sdk/issues/266

**Comment by andregm3** [comment]
we don't want it only in our games, we want it in all.
