### ISSUE TITLE
How and rotation vector sensor with the rotation of the image?

### ISSUE THREAD

**Issue by ZacharyTech** [googlevr/gvr-android-sdk#159]
Hello, based on our own to do a panoramic ffmpeg player, you encounter a problem: when you drag an image can not be rotated in accordance with the pitch rotation center of the screen, are there any good solution for it?
How do you deal with this in nativeRenderFrame inside?

**Comment by nathanmartz** [comment]
This space is just for issues with the SDK. For "how to" questions please use Stackoverflow.
