### ISSUE TITLE
Missing Controller Paint APK

### ISSUE THREAD

**Issue by sakagemann** [googlevr/gvr-android-sdk#162]
The Controller Paint APK is linked twice [here](https://developers.google.com/vr/concepts/dev-kit-setup); however it now seems to missing from the repo.

**Comment by nathanmartz** [comment]
Thanks for the bug report. We caught this ourselves and are in the process
of fixing it.

**Comment by dav-cz** [comment]
This should be fixed now.

**Comment by JerryChin** [comment]
It's not fixed!
