### ISSUE TITLE
createSoundField error

### ISSUE THREAD

**Issue by xdf103** [googlevr/gvr-android-sdk#164]
When I use the GvrAudioEngine to create a sound field (createSoundField), I receive the following error:

W/WAVExtractor: More than 2 channels (4) in non-WAVE_EXT, unknown channel mask
E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found

The input file is a 4-channel FOA WAV file.

**Comment by jkammerl** [comment]
GVR uses OpenSL ES to decode sound files and it seems picky about the header format of Wav files. You could try reencoding the WAV file with tools like Audacity or ffmpeg which worked for me in the past. Alternatively, using a compressed multi-channel Ogg/Vorbis container should work as well.

**Comment by StefanLiu007** [comment]
Thanks
