### ISSUE TITLE
Control VRVideoView's volume

### ISSUE THREAD

**Issue by ariviere** [googlevr/gvr-android-sdk#165]
Is it possible to add method to the VRVideoView to control the volume ? I'd like to give the user the possibility to mute/unmute a video with a button and I don't see a method which would help me to achieve that.

**Comment by dav-cz** [comment]
Sounds like a reasonable request. Can probably be exposed through a SetVolume(0.0 ... 1.0) API.

It's going to be tricky for you to have user controls for it in VR though, is that OK?

**Comment by ariviere** [comment]
Cool, thanks! The idea is to have a mute/unmute button on the video before the user go in VR.

**Comment by dav-cz** [comment]
Just a quick update that this came in too late to be included in the release that we'll push in coming days, but we'll add it in the version after that one (~early Sept). Thanks for your patience!

**Comment by dav-cz** [comment]
This was added in v1.0.0

https://developers.google.com/vr/android/release-notes#gvr_sdk_for_android_v100
