### ISSUE TITLE
Cannot play MPEG-TS (HLS) through VrVideoView

### ISSUE THREAD

**Issue by yijianwang** [googlevr/gvr-android-sdk#169]
I tried to generate HLS stream to an Android device and use VrVideoView to play it. When I streamed a MP4 video, everything was fine. However, when I streamed my webcam, it failed.
I used h.264 in both cases, the only difference was that the webcam's capturing format is YUY2 while the MP4 video is YUV420. I'm not sure if the VrVideoView can only play HLS encoded with the YUV420 H264 codec because of the ExoPlayer.

**Comment by yijianwang** [comment]
Finally, I found the solution. Just as I inferred, I need to convert YUY2 to YUV420 before the H264 encoding and streaming.

**Comment by nathanmartz** [comment]
Great!
