### ISSUE TITLE
Why seperate SDKs for Android and iOS even though we have unity SDK for Goole VR?

### ISSUE THREAD

**Issue by gvsharma** [googlevr/gvr-android-sdk#172]
thanks for Google VR, why google given seperate SDKs for google VR in Android and iOS? also it gave for Unity.
we can deploy the app with Unity for both platforms,
So please clarify me if am asking wrong.

**Comment by nathanmartz** [comment]
Not all developers want to use Unity. The iOS and Android SDKs support native developers.
