### ISSUE TITLE
Feature Request: Media Controls

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#174]
When using a regular `MediaPlayer` I am able to hook in media controls. I'd like to request the same hook for GVR. Ideally I would be able to put a media controller in that has a play/pause/stop seek.

**Comment by nathanmartz** [comment]
We already provide API access for play/pause/stop/seek (iOS is the same but missing seek currently). What are you looking for that isn't there?

**Comment by dav-cz** [comment]
The only feature missing is being able to control the volume. So I'm closing this as a duplicate of 
https://github.com/googlevr/gvr-android-sdk/issues/165
