### ISSUE TITLE
videoWidgetView.getDuration() euqal to -1

### ISSUE THREAD

**Issue by yubaolinfish** [googlevr/gvr-android-sdk#175]
Hello, videoWidgetView.getDuration() euqal to -1  (simpleVideoWidget), thanks.

uri:
http://222.203.241.36:5001/nn_vod.ts?id=4215ca756d80e86bc4fe21710903b315&url_c1=56525f303732362e74732000&nn_ak=018234d1474795f92715562735fa1c6535&npips=219.232.84.70:5100&ncmsid=100187&ngs=5796bef7000c44e3b0d372ff635b1c27&nft=ts&nn_user_id=&ndi=&ndv=&nfm=&nst=iptv&nn_core_test=ganweijiang&nca=%26nn_cp%3d00030&nal=01f7be9657060745fb6057b10831952ed62c30f51b8057

**Comment by nathanmartz** [comment]
Looks like that file is encoded as a .ts which is not a supported format.
Use mp4 or HLS instead.

**Comment by yubaolinfish** [comment]
Does not support the play TS format of the video? but I can play the success.
