### ISSUE TITLE
Enabling head tracking

### ISSUE THREAD

**Issue by dwinnbrown** [googlevr/gvr-android-sdk#176]
Hi All,

I am using the SDK in my android app to display a 360 video with `VRVideoView` but don't seem to have the head tracking functionality...anyone else experienced this?

This is how I'm calling it:

 ```
@Nullable
        @Override
        public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
            View view = inflater.inflate(R.layout.fragment_fourth, container,false);
            videoWidgetView = (VrVideoView) view.findViewById(R.id.video_view);

            try {
                videoWidgetView.loadVideoFromAsset("video.mp4", null);
                videoWidgetView.pauseVideo();
            } catch(IOException ex) {
                //Do nothing
            }

            Button mClickButton1 = (Button) view.findViewById(R.id.button);
            mClickButton1.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                        videoWidgetView.playVideo();
                }
            });


            setRetainInstance(true);
            return view;
        }

        //Set title
        public void onResume(){
            super.onResume();
            ((MainActivity) getActivity()).setActionBarTitle("VR Experience");


        }
```
Thanks in advance

**Comment by nathanmartz** [comment]
What phone are you testing on? The phone has to have a gyro for head
tracking to work.

**Comment by dwinnbrown** [comment]
I think you may be correct, I was testing on a Vodafone Smart Prime 6 - (unfortunately don't have a nexus) and after some research it doesn't appear to have a gyro. I think my brothers old LG might have one though so will try it out on that if I can.

Thanks

**Comment by RajeshJadav** [comment]
I also want to use Head Tracking with VrPanoramaView. but i can not find any sample or guidelines for it. how can i determine head position in VrPanoramaView?

**Comment by dav-cz** [comment]
Closing this.

@dwinnbrown, your phone doesn't have a gyro so head tracking will not work correctly, sorry :/
@RajeshJadav, there's already an issue for this -- https://github.com/googlevr/gvr-android-sdk/issues/143
