### ISSUE TITLE
Customize VrPanoramaView in VRMode

### ISSUE THREAD

**Issue by RajeshJadav** [googlevr/gvr-android-sdk#177]
How can i make VrPanoramaView in full screen in VR mode currently it is showing with padding and curved edges with black background.

**Comment by nathanmartz** [comment]
In VR mode, it's expected that you'll have that padding and curve. The amount depends on your viewer and your phone, the goal is that it looks correct when viewed through the viewer, not just looking at the naked screen.

**Comment by RajeshJadav** [comment]
But when i am viewing through cardboard viewer it is not displaying properly and display different images in cardboard viewer. I am using Lenovo K3 note which has VR mode feature if i use phone's VR mode then it does not have padding and curve and images look properly in cardboard viewer.

**Comment by nathanmartz** [comment]
The problem may be that we don't have the Lenovo K3 note in our device database and it is reporting erroneous DPI information. What do you mean the phone has a "VR mode feature"? What does enabling this feature do? Also, which cardboard viewer are you using? Did you pair it (using the settings gear)?

**Comment by nathanmartz** [comment]
PS - I just checked and the Lenovo K3 Note does not have a real gyro and so likely the head tracking will not be good. This doesn't have anything to do with your viewer problem, but thought I would pass along the information.

**Comment by RajeshJadav** [comment]
can i make VrPanoramaview full screen and remove padding and curve?

**Comment by nathanmartz** [comment]
The next SDK update will include an ability to make the view fullscreen,
but it will still have the padding and curve as those are a function of the
distortion correction logic, which is not optional.

**Comment by flybear528** [comment]
you can set 2 VrPanoramaviews in your layout;this is my way to get VRmodel
    
panoWidgetView = (VrPanoramaView) findViewById(R.id.pano_view);
    panoWidgetView.setEventListener(new ActivityEventListener());

    panoWidgetView2= (VrPanoramaView) findViewById(R.id.pano_view2);
    panoWidgetView2.setEventListener(new ActivityEventListener());

**Comment by dav-cz** [comment]
@RajeshJadav, we will never make it possible to go in fullscreen stereo mode without the padding and curve, so I'm closing this issue. 
If you think VR rendering on your phone is not correct please file a separate issue focused on that. But since your phone doesn't have a gyro the experience is never going to be great.
