### ISSUE TITLE
unitygvractivity.aar requires READ_PHONE_STATE

### ISSUE THREAD

**Issue by sayangel** [googlevr/gvr-android-sdk#181]
It seems that the READ_PHONE_STATE issue was addressed for most classes, but I'm still getting a request for phone permissions. 

I've narrowed the culprit down to unitygvractivity.aar because including just the .jar doesn't throw the permissions err, so my guess is the manifest also needs the minSdk updated as discussed in: https://github.com/googlevr/gvr-android-sdk/issues/71

**Comment by smdol** [comment]
Can you post this over on the gvr-unity-sdk Issues page?  Also, I just checked and the .aar file has a skeleton manifest in it which does not specify an SDK level, as you suspected.

**Comment by sayangel** [comment]
oops wrong repo. will do!

**Comment by dav-cz** [comment]
Closing this. Corresponding issue on unity repo: https://github.com/googlevr/gvr-unity-sdk/issues/285
