### ISSUE TITLE
Feature Request: Pause Listeners While Reusing the VideoView

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#182]
Currently pause is an async call. It would be useful to have a listener which will tell us when the video is actually paused.  Use case is when multiple video views are on the screen at the same time and you do not want to start B video before A video stops.

**Comment by sigmaxipi** [comment]
We don't plan on adding this functionality. If you need it, consider using the Video360 sample as a starting point for a custom widget. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
