### ISSUE TITLE
how to custom the widget on GvrView?

### ISSUE THREAD

**Issue by xwSurfer** [googlevr/gvr-android-sdk#183]
when I run the treasure hunt sample in my device,:

- the first screen prompted me "Place your phone into your Cardboard viewer“
- then, when i touched it, there is a setting icon at the bottom of the middle of the page

how can i custom above? like, due to job requirements, i must remove the first page or remove the setting icon.

 thanks

**Comment by dav-cz** [comment]
There's currently no official way to do that, and it's very unlikely there will ever be.
We really believe both the transition view and the setting icon are important for the user experience.
