### ISSUE TITLE
Trouble in adding floating buttons in panorama widget view

### ISSUE THREAD

**Issue by Minali-Gilhotra1** [googlevr/gvr-android-sdk#185]
How to add the the floating buttons in VrPanoramaView for the navigation as shown in the image?

![floatingbutton](https://cloud.githubusercontent.com/assets/20831062/17390678/1ede44ea-59c4-11e6-9b0a-d5d22a3d056c.JPG)

**Comment by nathanmartz** [comment]
Hi. This forum is for bugs with the SDK. For "how to" questions please post on StackOverflow or a similar resource.
