### ISSUE TITLE
VR Audio : APIs for sample level processing

### ISSUE THREAD

**Issue by virajkarandikar** [googlevr/gvr-android-sdk#186]
Hello,
Current VR audio sdk APIs provide only file level playback controls (load, play, pause etc.). This limits the use cases in which VR audio can be used. Is there a plan to add low level APIs which will allow processing block of audio data (similar to MediaCodec)?

**Comment by nathanmartz** [comment]
Hi. Can you tell us a bit more about the specific kinds of effects you are trying to achieve?

**Comment by virajkarandikar** [comment]
Say there is a app where compressed audio in ambisonic format is streamed over network. Received stream needs to be decoded first and then processed through VR audio engine before rendering. There is no way to process a chunk of PCM data through VR audio engine with current APIs.

As per my understanding, current APIs only work with audio files embedded in the app.

**Comment by jkammerl** [comment]
You are correct. The current Android API is designed to provide a simple, high-level spatialization engine that allows to playback sound objects and ambisonic soundfields from APK assets/SD card and the processing of raw PCM buffers is not supported atm. But it is interesting to hear that there's demand for it. Are you planning to implement an AudioTrackRenderer for the ExoPlayer?  Are you using our Android Java or NDK API?

**Comment by virajkarandikar** [comment]
I don't have answer to your first question right now as we are still exploring. Right now we are experimenting with Java, but might move to NDK in future.

**Comment by virajkarandikar** [comment]
I see that Youtube also streams ambisonic audio and renders with spatial effect. How does it do that? How can one implement similar functionality in a custom app?

**Comment by jkammerl** [comment]
As previously discuss, the current API doesn't allow for the processing of PCM buffers. We'll consider providing corresponding methods in future releases.

**Comment by virajkarandikar** [comment]
Any chance of this getting supported in next release ?

**Comment by virajkarandikar** [comment]
Any update on this ?

**Comment by lindenle** [comment]
:+1: any updates?

**Comment by jkammerl** [comment]
We are currently working on a separate spatial audio API that reads in PCM buffers of surround sound as well as ambisonic soundfield content to render binaural stereo. It is designed to be integrated into media players to enable head-tracked binaural audio. It will be part of the GVR spatial audio components soon.

**Comment by gtStation** [comment]
@jkammerl 
So playing an MP4 with ambisonic will be possible through the GVR SDK?
Do you have a rough (or better) estimation of when will it be released? (beta release?)

**Comment by virajkarandikar** [comment]
@jkammerl that is good to know. looking forward to it.

**Comment by jkammerl** [comment]
We just released it! Please take a look at the GvrSurround [Java](https://developers.google.com/vr/android/reference/com/google/vr/sdk/audio/GvrAudioSurround) and [native C](https://developers.google.com/vr/android/ndk/reference/class/gvr/audio-surround-api) API. It has been designed to binaurally render surround sound/ambisonics PCM buffers of varying buffer sizes in 360 video player applications. Fyi, we are currently working on wrapper code that will facilitate the integration into the Exoplayer.

**Comment by gtStation** [comment]
@jkammerl is there an ETA for the Exoplayer wrapper?

**Comment by virajkarandikar** [comment]
@jkammerl Thanks! API working as expected!

**Comment by lindenle** [comment]
@jkammerl Have the examples been updated? We are having some trouble figuring out how to use the API correctly.

**Comment by virajkarandikar** [comment]
I think this issue can be closed now.

**Comment by jkammerl** [comment]
The Exoplayer V2 recently added a wrapper for the GvrSurround API (see [announcement](https://medium.com/google-exoplayer/spatial-audio-with-exoplayer-and-gvr-cecb00e9da5f) here). We are working on more sample code. In the meantime, here is their [integration code](https://github.com/google/ExoPlayer/blob/a9079f67aa031649edfa7427e0fa96bf65efa1ac/extensions/gvr/src/main/java/com/google/android/exoplayer2/ext/gvr/GvrAudioProcessor.java).
