### ISSUE TITLE
Feature Request: Full screen should be configurable to landscape only.

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#187]
We are trying to have 360 video look the way youtube does. By that I mean I should be able to have a playlist of videos with a framed portrait videos.  When I press full screen the video should become landscape and fullscreen.  This is similar to https://github.com/googlevr/gvr-android-sdk/issues/135 but with one caveat.  Say I have my phone locked as portrait, I would like to be able to press the full screen button in youtube and see a landscaped full screen view. Unfortunately if I do this with a VR view, I instead get a video that is facing sideways.

Proposal: Allow the full screen mode to take a configuration which a client will be able to pass in the direction that is "bottom".  Otherwise it seems like we won't be able to show a full screen landscape view whenever someone has their phone locked to portrait.

**Comment by dav-cz** [comment]
I'm not sure I fully understand this request, in particular " if I do this with a VR view, I instead get a video that is facing sideways."

If I run our sample apps (pano and video) with phone locked in portrait mode, and then I press fullscreen, the VR View goes fullscreen and the pano or video content appear with what seems a correct orientation.  i.e  the bottom of the video corresponds to the bottom of the phone (where the back/home/recent Android nav buttons are) when I hold my phone in portrait orientation.

**Comment by digitalbuddha** [comment]
Sorry for confusion. I want to be able to lock in portrait but when I press the full screen button, I'd like to have the bottom of the view be landscape rather than portrait.  Most  video players only show landscape full screen and I'll like GVR to act this way as well. (See youtube UI as example)

**Comment by digitalbuddha** [comment]
Hey, I can explain the bug a little better. If I have activity rotation turned on and rotate my phone. I can observe that the video is now sideways.  I don't believe it is correct for the gvr to lock in what direction is bottom even after the activity has destroyed and recreated.  If I had to guess I'd say the problem is that there is a Singleton maintaining the state of direction across rotation.  Please fix to ease in the creation of custom controls that face the same direction as the video does (upon rotation)

**Comment by sigmaxipi** [comment]
I think this specific issue has been fixed. We improved rotation handling for VrView, but there are still some bugs because rotation is tricky on Android. If your specific issue isn't fixed, consider using the Video360 sample as a starting point to create a custom widget. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
