### ISSUE TITLE
Disabling Cardboard Button

### ISSUE THREAD

**Issue by dwinnbrown** [googlevr/gvr-android-sdk#192]
Anyone know of a way of disabling the cardboard button on android in java?

Thanks

**Comment by nathanmartz** [comment]
I assume you are talking about VR view? If so, we have no plans to allow developers to remove that feature. Otherwise there's not very much "VR" to it at all :)

**Comment by dwinnbrown** [comment]
I was talking about the ViddeoView - just wandered because we can disable it in iOS
