### ISSUE TITLE
VR Audio support for external file

### ISSUE THREAD

**Issue by niusounds** [googlevr/gvr-android-sdk#193]
Hello,

`createSoundfield(String filename)` can only read audio from asset files in apk.
I want to read external file! (somewhere in /sdcard/ like path)
Is there a plan to add this feature?

**Comment by JayaWei** [comment]
I also have the same problem.

**Comment by jkammerl** [comment]
Loading sound files from the SD card should work. Please make sure that you add 
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
to you manifest and since Android N, you also need to trigger an intent to ask to user to grand external storage permission.

**Comment by niusounds** [comment]
I tried these codes

```java
GvrAudioEngine audioEngine = new GvrAudioEngine(getContext(), GvrAudioEngine.RenderingMode.BINAURAL_HIGH_QUALITY);
final File file = new File(Environment.getExternalStorageDirectory(), "Ambi.wav");
int ambisonicId = audioEngine.createSoundfield(file.getAbsolutePath());
```

but `ambisonicId` is `-1`. I added `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` in AndroidManifest.xml. targetSdkVersion is 19.

I tried some methods, finally I found that these codes run successfully. (It plays strange distorted sound. But it may be other problem, not a bug in GVR library.)

```java
GvrAudioEngine audioEngine = new GvrAudioEngine(getContext(), GvrAudioEngine.RenderingMode.BINAURAL_HIGH_QUALITY);
final File file = new File(Environment.getExternalStorageDirectory(), "Ambi.wav");
final String filename = file.getAbsolutePath();
audioEngine.preloadSoundFile(filename);
int ambisonicId = audioEngine.createSoundfield(file.getAbsolutePath());
```

API Document says *Ambisonic soundfields do not need to be preloaded*. I think it is not needed to call `preloadSoundFile`. Is it wrong?

**Comment by niusounds** [comment]
This issue will be the same topic with #197 so I close here.
