### ISSUE TITLE
GvrView.StereoRenderer$onRendererShutdown() not called.

### ISSUE THREAD

**Issue by Carlos-CR** [googlevr/gvr-android-sdk#194]
The renderer shutdown callback is not being called, ever, neither in my own apps nor on the sample ones, such as treasure hunt. I've tried this on Samsung Note 4, S6, S7, Nexus 5 and Nexus 5X with the same result in all of them.

It's simple to reproduce given the treasure hunt demo has a log call inside the callback that is never printed. 

Any suggestion as to how to release OpenGL resources in the meantime?

**Comment by dav-cz** [comment]
Do you this problem with the latest version that was pushed last week? 
https://developers.google.com/vr/android/release-notes

**Comment by Carlos-CR** [comment]
Alright, seems with the latest push it is indeed resolved. My fault for just checking the "Releases" section and taking the Jun 11 for granted. Sorry for the inconvenience.

**Comment by dav-cz** [comment]
No worries! Just curious, which "Releases" section are you referring to? (or in general if something is not clear on our site let us know)

**Comment by Carlos-CR** [comment]
In the main Github page for the project, "<> Code", right above the files, there's a rundown listing number of commits, branches, contributors and releases. In the releases section, there are only 2 releases listed, latest one being from Jun 11th.

**Comment by dav-cz** [comment]
Thanks for this feedback. 
That is confusing indeed, we should do a better job tagging these updates.
