### ISSUE TITLE
How to Programmatically move camera?

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#195]
When loading a 360video I wanted to show a preview of movement. By that I mean I would like to programmatically drag 30 degrees left and then 30 degrees right. Is there a way to force the camera to move within the video?  Think of it as a preview mode.

**Comment by sigmaxipi** [comment]
If you want more complex touch & gyro controls, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
