### ISSUE TITLE
VR Audio : Ambisonic soundfield playback broken with v0.9.0 (0.8.0 onwards)

### ISSUE THREAD

**Issue by virajkarandikar** [googlevr/gvr-android-sdk#197]
Ambisonic soundfield rendering is full of glitches with v0.9.0. I had to revert to commit c85649fc3c001a5e96e9c96a73d67e6385680574 for proper playback of ambisonic soundfield. This commit corresponds to v0.8.0.

Verified above behavior with custom app as well as sample Treasurehunt app (modified to load soundfiled).

**Comment by jkammerl** [comment]
Are you preloading the ambisonic soundfield prior to playback? Could you share more information about the platform/phone you are using?

**Comment by virajkarandikar** [comment]
Using 0.9.1
- Without preloadSoundFile(), createSoundfield() fails.
- With preloadSoundFile(), createSoundfield() works but audio is full of glitches.

Using 0.8.0
- createSoundfield() & playback works without any issues with or without preloadSoundFile().

Checking on Nexus9 with Android 7.0 NRD90.

**Comment by jkammerl** [comment]
Thanks for the info. I'm able to reproduce this bug. We'll work on a fix for the next release.

**Comment by virajkarandikar** [comment]
Any update on when this will be fixed ?

**Comment by jkammerl** [comment]
It should already have been fixed in v1.0. Please let us know if you still encounter any problems.

**Comment by DungLai** [comment]
Hi jarivk, could you please show me how to playback after createSoundField? 

I use `gvrAudioEngine.playSound(soundFieldId, true);` but they produce white noise only.

I'm using v1.120.0, Samsung galaxy S7, android 7.0.

**Comment by Raisongran** [comment]
@DungLai, I had same problem. Make sure that your sound is in mono format.

**Comment by DungLai** [comment]
@Raisongran No ambisonic can't be mono format. It's 4 channels wav file. Make sure bit depth is 32 otherwise they will produce white noise.
