### ISSUE TITLE
Unable to find how to redirect to my desired link.

### ISSUE THREAD

**Issue by AnkitAndroaid** [googlevr/gvr-android-sdk#198]
I am able to play VR video in my application from internal storage as well as from remote URI. But what i need is i want to redirect my app users to my desired link when they touch "i" or information view (You can have a look at the view i am talking about) . Currently user is redirected to a default link which shows information about Google VR. I do not want this. Please help me out of this issue. Thanks.
![cropped](https://cloud.githubusercontent.com/assets/13251443/17545918/2a5a7134-5efd-11e6-9a46-e186ec3290a1.png)

**Comment by nathanmartz** [comment]
I'm sorry but we do not allow changing this element of VR View. If you want
complete control over this UI you'll need to implement your own 360
playback on top of the low level GVRView class.

**Comment by AnkitAndroaid** [comment]
@nathanmartz  Is there a way or method to hide this icon without implementing my own 360 playback. Because this is not giving a good UX in my app.

**Comment by sigmaxipi** [comment]
The UI inside the VR View widgets is designed to be consistent across apps. Your best option is to have a link outside the VR View that is appropriately labeled and goes to your desired destination.
