### ISSUE TITLE
Is there a way to hyperlink between different Panoramas like in Google StreetView?

### ISSUE THREAD

**Issue by kchecker** [googlevr/gvr-android-sdk#199]

**Comment by nathanmartz** [comment]
Not currently but it's a feature we have discussed in the past. For now
you'd need to implement it yourself using head orientation (new to 0.9) and
you own hotspot logic.

**Comment by kchecker** [comment]
Thanks for your response. 

Are you aware of a similar solution in Javascript or a Web based library for doing interlinked Panoramas like StreetView?

**Comment by nathanmartz** [comment]
I am not, which is why we plan to add support for this (in VR view native and web).
