### ISSUE TITLE
Documentation in https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/Distortion.html#getApproximateInverseDistortion(float,%20int) has wrong code

### ISSUE THREAD

**Issue by sp-1234** [googlevr/gvr-android-sdk#201]
https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/Distortion.html#getApproximateInverseDistortion(float,%20int)

There's this line of code:

         float maxFovHalfAngle = 50.0f * Math.PI / 180.0f;

It does contain compile error:
> error: incompatible types: possible lossy conversion from double to float

It could be fixed by changing it to:

    final double maxFovHalfAngle = 50.0 * Math.PI / 180.0;

Where is that code located? I'm asking because I could make a pull request.

**Comment by nathanmartz** [comment]
This is just sample code, but thanks for the bug report.

**Comment by sp-1234** [comment]
You did not fix the issue—the code on the linked page is still the same as before.
So why did you close the issue? 🐼
