### ISSUE TITLE
HeadTransform/Orientation not updated on the Galaxy Tab 4 10.1

### ISSUE THREAD

**Issue by RikHeijdens** [googlevr/gvr-android-sdk#203]
One of our customers reported to us that they weren't able to "look around" in our application on a Galaxy Tab 4. They haven't reported any issues with other devices. I haven't managed to verify this behavior as I don't have a Galaxy Tab 4, but it sounds like an device specific issue with the accelerometer.

**Comment by nathanmartz** [comment]
Yes, this device doesn't have a gyro, which we require for head tracking. You should make a gyro required in your app manifest.
