### ISSUE TITLE
support for livestreaming over MPEG-DASH .mpd

### ISSUE THREAD

**Issue by MegaThomas** [googlevr/gvr-android-sdk#204]
Could you please support the MPEG-DASH also? DASH is similar to HLS and a lot of people choose it too.

**Comment by nathanmartz** [comment]
Thanks for the feature request. We have this in our internal tracker, but it's a ways out. Right now we're doing HLS because most people want both iOS and Android.

**Comment by MegaThomas** [comment]
Thank you, I think I'll probably customize ExoPlayer myself. :sweat_smile:

**Comment by githubQueen** [comment]
@MegaThomas did you find a way to customize ExoPlayer? I'm also interested in receiving a Dash-Livestream and display it in VR Mode. Would be helpful if you could share some information :)

**Comment by MegaThomas** [comment]
Nope, since the `VrVideoView` is in the .jar file, I can't modify it directly.

**Comment by SrujithPoondla** [comment]
did any one found a way to get DASH support in VR SDK or any one worked on that could you please share the code?

**Comment by b95505017** [comment]
ExoPlayer + [MD360Player4Android](https://github.com/ashqal/MD360Player4Android)

**Comment by abhi2015** [comment]
Do we have support for adaptive decoding in the player i.e. support for adaptive bit rate profiles (SMIL)?

**Comment by sigmaxipi** [comment]
DASH support has been added to the VrView sample. See https://github.com/googlevr/gvr-android-sdk/tree/master/samples/sdk-simplevideowidget/src/main/assets for sample videos.

If you want support for other video formats, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
