### ISSUE TITLE
Include ExoPlayer as gradle dependency

### ISSUE THREAD

**Issue by jayspringfield** [googlevr/gvr-android-sdk#207]
I have an app that requires a newer version of ExoPlayer than the one that's bundled with videowidget.aar, which includes ExoPlayer as class files.  Can you guys make make this dependency configurable so that we can override it as necessary?  Is there a workaround in the mean time?

**Comment by ryango** [comment]
are you getting duplicate dex?
can try excluding the dependency from the aar and if the versions aren't that different you might get lucky

http://stackoverflow.com/questions/23640030/gradle-exclude-specific-files-inside-dependency

(should probably open source the sdk! :))

**Comment by jayspringfield** [comment]
My app would crash because another library it included for video streaming used methods missing from the older version of ExoPlayer.  If I included the newer one in my build.gradle file, I would get ZipExceptions because of the duplicate classes.

I ended up unzipping the aar and then the classes.jar inside of it, deleting the ExoPlayer classes and putting the whole thing back together.  I could then include ExoPlayer in build.gradle.  Everything seems to be working fine as far as I can tell (but anyone else who tries this does it their own risk!).

Moving forward, it's bad SDK practice to include class files from 3rd party libraries due to this type of conflict, especially when you're using gradle and those classes are available in a public maven repo.  Can't you just remove that source from the videowidget build path and use something like this:

`compile 'com.google.android.exoplayer:exoplayer:r1.5.7'`

**Comment by nathanmartz** [comment]
Yes, this is a bug on our side. We're working to get it fixed for the next release. Until then the workaround described here is the best.

**Comment by dav-cz** [comment]
@jayspringfield, yes we'll do exactly that in our next release. 
Not an excuse, but it was very easy for us to miss this as ExoPlayer is developed at Google and therefore super easy to pull in and compile with our internal build system.

**Comment by jayspringfield** [comment]
No worries, guys.  I realize it's early on for this SDK and sometimes things just get done the quick and dirty way.  Looking forward to the future releases.

**Comment by sigmaxipi** [comment]
The new SDK has exoplayer as an external dependency.

**Comment by ManojJangra** [comment]
Please  suggest me, IMA ads  dependency  for new exo player.
