### ISSUE TITLE
Crash, if both use “gvr-unity-sdk” and "gvr-android-sdk"

### ISSUE THREAD

**Issue by solomon2** [googlevr/gvr-android-sdk#208]
“gvr-unity-sdk” hava "unityvractivity.jar" ，"com.google.vr.cardboard.UiLayer"  in it.
"gvr-android-sdk" hava  “common.aar” ,also hava "com.google.vr.cardboard.UiLayer"  .

So, When I use android VrPanoramaView，it call  “gvr-unity-sdk”, so Crash

Please Help me to solve it , we are very anxious. 

Thank your very much! 

（PS:  It seems gvr-ios-sdk and gvr-unity-sdk also hava same problem）

**Comment by smdol** [comment]
Let's handle this on the gvr-unity-sdk Issues page, where I've posted a question for you.
