### ISSUE TITLE
fail to load vr video

### ISSUE THREAD

**Issue by iknow4** [googlevr/gvr-android-sdk#210]
when load  a vr video,i got the error message as follow
com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, MediaFormat(1, video/avc, -1, 1341518, 3840, 2160, 0, 1.0, -1, -1, null, 71137733, false, -1, -1, -1, -1, -1)

**Comment by nathanmartz** [comment]
What device is this on? There's a good chance the video is higher
resolution than your phone can decode.

**Comment by iknow4** [comment]
Device is MEIZU-M578C,and android version is 5.1
what is your suggestion about this question?

**Comment by nathanmartz** [comment]
I don't have information on that device, but I bet if you make a 1080p or 720p version of this video, it will play.

My recommendation is that if you want maximum compatability, you need two versions of each video - one that is max res and another that is 1080p. You serve the 1080p one by default and the max res one on devices that you know can handle the higher resolution.

**Comment by kamol0001tk** [comment]
Fixing
