### ISSUE TITLE
Configure button within the Cardboard Viewer on KitKat (4.4.2) shows a dialog with no buttons

### ISSUE THREAD

**Issue by TylerMcCraw** [googlevr/gvr-android-sdk#211]
After running a video in a VrVideoView and clicking on the cardboard viewer button, there is a settings button that shows up in the middle of the cardboard viewer.
Clicking on this settings button displays a dialog/popup that has a title "Configure" with no buttons or message.
On Android Marshmallow and Android Lollipop, there is no issue. It's only an issue on KitKat as far as I can tell.

See screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/1115167/17867292/ded592e6-6877-11e6-844e-99a9b3d9c0c0.png)

Any idea how I can fix this temporarily? Or is this an issue with the dialog that displays when an intent for the Google Cardboard app is fired?

**Comment by jdduke** [comment]
Thanks for the report, Tyler. We're tracking this internally and will try to have a fix with the next release. If I might ask, which Android phone model exhibits this issue?

**Comment by sb-tylermccraw** [comment]
That's great!
The model of the phone is:
Verizon HTC One M9 LTE
HTC6535LVW

Let me know if you need anything else.

**Comment by TylerMcCraw** [comment]
That's great!
The model of the phone is:
Verizon HTC One M9 LTE
HTC6535LVW

Let me know if you need anything else.

**Comment by jdduke** [comment]
Unable to repro on a few of the KitKat devices we have lying around. Would you mind sharing the "adb logcat" output when you click on the settings button? It may give some hints as to whether there are missing resources with the popup dialog

**Comment by TylerMcCraw** [comment]
I tried checking for logs, but, unfortunately, no logs are printed when I click on the settings icon button which shows the Configure dialog.

I did notice that when I press the back button after this dialog is already displayed, there are two logs. They may not be helpful though.
```
08-25 09:21:11.344 29476-29476/com.smashingboxes.threesixtyvideoplayerdemo W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
08-25 09:21:11.344 29476-29476/com.smashingboxes.threesixtyvideoplayerdemo E/ViewRootImpl: sendUserActionEvent() mView == null
```

**Comment by TylerMcCraw** [comment]
Actually, I just realized that I completely told you the wrong device before.
I have so many test devices on my desk right now that I think I just got confused about which one had the issue between the time that I saw the issue and when I actually reported it.
Sorry about leading you on a wild goose chase 😬 

Could you try reproducing on a Samsung Galaxy S5?
Model is: SAMSUNG-SM-G900A
The issue is definitely on this device.

**Comment by jdduke** [comment]
Thanks for the details Tyler, and which Android version are you running on the S5 (5.0? 5.0.1?)?

**Comment by jdduke** [comment]
Hi @TylerMcCraw , I wasn't able to repro this but I also don't have access to the exact same device/build. Can you confirm whether the issue is still reproducible for you, with the latest SDK drop?

**Comment by abhi2015** [comment]
Getting the same issue on a galaxy S3 running Android 4.4 
![image](https://cloud.githubusercontent.com/assets/10726463/19965051/ccba0666-a1cd-11e6-96ad-51ce6d613eff.png)

**Comment by dav-cz** [comment]
FYI we've been able to reproduce this bug Samsung S5 and Nexus 4, both running Android 4.4.2.
It looks like the UI theme gets broken for some reasons on these devices, potentially due to some GL texture corruption. At this point it's pretty hard to know if it's something we can fix in the short term or not.

**Comment by ponychen** [comment]
I'm getting the same issue on Samsung Galaxy Note 8.0 (GT-N5110) running Android 4.4.2.

**Comment by jdduke** [comment]
Given the lack of repro, there's not much we can do on our end. If somebody could attach a bug report which captures the repro, that would be helpful. Thanks.
