### ISSUE TITLE
setTransitionViewEnabled has no effect

### ISSUE THREAD

**Issue by ryango** [googlevr/gvr-android-sdk#212]
In the sample simplepanowidget sample (on 0.9.1), I added setTransitionViewEnabled(false) in onCreate.
![image](https://cloud.githubusercontent.com/assets/1054881/17941074/be2bc338-69ff-11e6-9b8a-f81cdd3d0422.png)

still get this view
![image](https://cloud.githubusercontent.com/assets/1054881/17941112/e52dceae-69ff-11e6-8d06-a926433ac65f.png)

per the release notes from 0.7
> Added a transition screen, which guides users to put their phone into their Cardboard viewer and fades into your 3D scene when it detects that the phone is in landscape left orientation. If you want to enable the transition screen in your app, call CardboardView's setTransitionViewEnabled(true).

Sounds like this should be disabled by default but seems to be enabled by default

Reverting to 0.7 still seems to have this same behavior, so it appears it never worked

**Comment by nathanmartz** [comment]
The 0.7 release notes are out of date. There currently is, by design, no way to disable the VR transition screen.

**Comment by ryango** [comment]
Ah that's pretty disappointing. We're building a buttonless experience that goes from mono to stereo via rotation and the mono->stereo transition is really nice without the transition view and very confusing with some screen popping up in between.

The SDK is awesome and I'm happy to have it instead of having to write all the hard stuff from scratch, however it would be a lot more useful if it were more configurable. Probably going to have to roll this from scratch before shipping unless you change your mind :).

Additionally, it looks like the setTransitionViewEnabled in GvrView works (setting it in the treasure hunt sample is effective) so this is inconsistent within the sdk. Kind of a bummer to have a no-op function in an SDK that claims to do something very specific.

WORKAROUND: For those reading this, you can also unzip the common aar, modify the transition view xml to customize it and then rezip it.

cd <location of common.aar>
mkdir explode
cd explode
cp ../common.aar .
unzip ../common.aar .
rm common.aar
(modify res/layout/transition_view.xml keeping all ids present)
zip -ur ../common.aar *

and you have your own custom transition view

**Comment by ryango** [comment]
Additionally we want to advance through multiple items using this sdk and having that screen pop up every time is nonsense and an awful ux

**Comment by nathanmartz** [comment]
Just wanted to give an update here. We're discussing more internally, but I think we'll be able to be more flexible with transition screens in an upcoming release. The aperature (divider, gear, etc) will still be "baked in" but we'll be working to make them less obtrusive while in VR.

**Comment by ryango** [comment]
That's awesome! Thanks Nathan. I think it is fair to have the divider and gear as that gives people an entry point to changing their viewer.

**Comment by ryango** [comment]
Thanks again. I think this is a great step to enabling a lot more experiences to be built on your sdk. Looking forward to seeing what people build and keep up the great work.
