### ISSUE TITLE
request: TextureView implementation

### ISSUE THREAD

**Issue by ryango** [googlevr/gvr-android-sdk#213]
Putting the widgets in a scrolling view leads to the same problems you see with putting a VideoView in a ListView (viewport lag, inaccurate viewport). Would be nice to have a TextureView implementation so we can actually embed these (or open source the sdk so I can do it :))

**Comment by ryango** [comment]
also realize that this might incur unacceptable delay and if you've already evaluated this please close and my apologies

**Comment by dav-cz** [comment]
We actually tried that but the issue was that TextureView was consuming a lot of CPU cycles.
The good news is that it seems the GLSurfaceView lag and black borders look fixed on Android N.
