### ISSUE TITLE
How to use GvrAudioEngine and VrVideoView to play online video at the same time?

### ISSUE THREAD

**Issue by markya0616** [googlevr/gvr-android-sdk#214]
As titile. We'd like to have the spatial audio and vr video at the same time, but don't know how to implement it.

**Comment by nathanmartz** [comment]
This is not currently supported, but is something we are looking into. What format is your spatial audio in currently?

**Comment by palfu** [comment]
Any format supported, using GvrAudioEngine and VrVideoVidew at the same time? mono、stereo or ambi?

**Comment by jkammerl** [comment]
The GvrAudioEngine supports the playback of mono, stereo and ambisonics audio assets. It is however not possible to synchronize audio playback from GvrAudioEngine with VrVideoVideo. 

To address this issue and are currently working on adding support for the processing of raw PCM buffers. This will enable the integration of the Google spatialization libraries directly into the audio pipelines of video decoders. Stay tuned!
