### ISSUE TITLE
Support the live streaming through RTSP?

### ISSUE THREAD

**Issue by leonardokidd** [googlevr/gvr-android-sdk#217]
Does the vrvideowidget support RTSP? I tried several rtsp uri with default option, but it doesn't work. It seems like just ignored the "rtsp://..../" part. I know VideoView supports rtsp, but why vrvideoview doesn't? Could please support the rtsp? Thanks

**Comment by ryango** [comment]
i think it uses exoplayer underneath which i dont think supports rtsp

https://github.com/google/ExoPlayer/issues/55

**Comment by leonardokidd** [comment]
Thanks for your reply. I'm trying to build a low latency live streaming and the latency of hls is more than 10s. Because it uses exoplayer, do you think http-flv may satisfy the requirements? Any advices? Thanks again.

**Comment by nathanmartz** [comment]
We don't have any plans to support live video in VR View. You can roll your own 360 viewer using the lower level GVR View classes, though.
