### ISSUE TITLE
Does GVR plan to support asynchronous time warp? 

### ISSUE THREAD

**Issue by xdf103** [googlevr/gvr-android-sdk#219]
Asynchronous time warp (ATW) can reduce judder and improve VR experience. Does GVR have any plan to implement this feature?

**Comment by sigmaxipi** [comment]
This feature in GVR is called [Async Reprojection](https://developers.google.com/s/results/?q=setAsyncReprojectionEnabled&p=%2Fvr%2F).

**Comment by xdf103** [comment]
How to enable Async Reprojection? Is there any requirement for using it?

**Comment by nathanmartz** [comment]
Async reprojection only works on Daydream ready phones, the first of which
come out later this year. You can find more information in this IO talk:
https://www.youtube.com/watch?v=9MIa1lviO_s
