### ISSUE TITLE
VrPanoramaView Loses Touch Tracking after setOnTouchListener 

### ISSUE THREAD

**Issue by humingw** [googlevr/gvr-android-sdk#227]
Android 7.0 Beta
GVRSDK 0.9.0

VrPanoramaView  touch tracking stops working if a custom touch listener is set. Here is the usage scenario:

```
tapDetector = new GestureDetectorCompat(context, this);
....
panoramaView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (tapDetector.onTouchEvent(event)){
                    return false;
                }
                return true;
            }
        });

```

If above `setOnTouchListener` is removed, the touch tracking works. But I need this `tapDetector` to detect some event like double tap.  Is it known issue? Any suggestion?

**Comment by sigmaxipi** [comment]
If you need a custom touch listener, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
