### ISSUE TITLE
How to zoom-in or zoom-out?

### ISSUE THREAD

**Issue by weiyideai520** [googlevr/gvr-android-sdk#229]
When I use VrPanoramaView ,find can touch to pan,but can not touch to zoom-out or zoom-in.

**Comment by nathanmartz** [comment]
We don't support zoom in/out as that's not really natural (or necessary) once you go into VR.

**Comment by ryannichols** [comment]
Not in VR, but the question was for Pano, where you might have something that's easy to see in full VR, yet is difficult and small in pano mode (especially in portrait). We've seen this behavior quite a bit in pano and been asked for it often by users.

**Comment by Mudin** [comment]
Did you find any solution?
