### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by lukassruc** [googlevr/gvr-android-sdk#230]
I want to modify and distribute one sample application. 
I will comply with the terms of the license, but I don´t know what to do with the headers. 
The LICENSE, README, and same other files begins with sentence: "Copyright (c) 2016, Google Inc.".
Should I exchange the name of the licensor for my name? Or should I maintain the original form?

**Comment by nathanmartz** [comment]
I'm sorry but we can't give legal advice here beyond what is included in the repository.

**Comment by lukassruc** [comment]
Of course, I do not expect a real legal advice. I wanted only non-binding solution that is practically used.
(I have already read many information about apache license, but I stil don´t know how to deal with this)
