### ISSUE TITLE
The method setVRModeEnabled() is removed from GvrView?

### ISSUE THREAD

**Issue by WeixiangZhang** [googlevr/gvr-android-sdk#231]
I didn't find setVRModeEnabled() in v0.9.1 release. 
Is it removed from GvrView class? If it does, how can I disable vr mode ??

Thanks.

**Comment by jdduke** [comment]
setVRModeEnabled() has been renamed to setStereoModeEnabled(). For more context see the release notes @ https://developers.google.com/vr/android/release-notes.
