### ISSUE TITLE
GVRVIDEOVIEW Failed in Cardboard Mode

### ISSUE THREAD

**Issue by ghenzhimura** [googlevr/gvr-android-sdk#232]
i have a problem with gvrvideoview. 360 video work so well on normal mode. but when i change it into cardboard mode, it failed. sometimes blank screen sometimes the video is freezing. i have database all the 360 videos on my server. so its running online/streaming. when one video failed, the other video failed too. any solution?

**Comment by nathanmartz** [comment]
Can you share a few links to the videos that fail to un in cardboard mode? What phone are you using to test?

**Comment by dav-cz** [comment]
Closing this until a video link is provided so this can be reproduced.
