### ISSUE TITLE
getHeadRotation not working

### ISSUE THREAD

**Issue by myflashlab** [googlevr/gvr-android-sdk#240]
I'm calling `getHeadRotation` like below but nothing happens. nothing, not even any error messages!

``` java
_imgView = (VrPanoramaView) findViewById(R.id.vr_image_view);

// other settings to finally make the 360 image shown...

float[] yawAndPitch = {90.0, 90.0};
_imgView.getHeadRotation(yawAndPitch);
```

Am I doing something wrong? Any hint would be appreciated.

**Comment by sigmaxipi** [comment]
[VrWidgetView.getHeadRotation](https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/common/VrWidgetView.html#getHeadRotation(float[])) returns the current rotation of the user's head. It will set the `yawAndPitch` variable that you pass into it. If you Log that variable, do you see it changing?

**Comment by myflashlab** [comment]
You were right! Thanks. The look of the method mislead me, However, when the device orientation happens, the returning float[] numbers are always 0.0 and 0.0. I wonder if you have faced a similar problem also?

**Comment by Ornolfr** [comment]
It seems that this method now returns void. And by invoking it with different float values nothing changes. Any info how could rotation angles be get/set?

**Comment by sigmaxipi** [comment]
If you want more complex touch & gyro controls, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
