### ISSUE TITLE
Library name mismatch in documentation "Getting started page" for android sdk

### ISSUE THREAD

**Issue by R1ck77** [googlevr/gvr-android-sdk#241]
The Getting Started page:

https://developers.google.com/vr/android/get-started

keeps referrring to the old `core.aar` nomenclature instead of using `base.aar` (2 recurrences)

Cheers

**Comment by sigmaxipi** [comment]
Fixed. Thanks for the note.

**Comment by R1ck77** [comment]
Thank you! Keep up the good work, looking forward for the news in a couple of days ;-)
