### ISSUE TITLE
google-vr-service

### ISSUE THREAD

**Issue by gn00618777** [googlevr/gvr-android-sdk#242]
Hi 
I not sure I can post this question here, I want to know does any source code about google vr service?
and I found this author, his "google vr service emulator" includes  
**https://github.com/domination/gvr-services-emulator/blob/master/services/gvr-emulator/src/main/java/com/google/vr/vrcore/controller/ControllerService.java**

import com.google.vr.vrcore.R;
import com.google.vr.vrcore.controller.api.ControllerServiceConsts;
import com.google.vr.vrcore.controller.api.ControllerStates;
import com.google.vr.vrcore.controller.api.IControllerListener;
import com.google.vr.vrcore.controller.api.IControllerService; 

but I still can't find any source code about this, I think those api above have been included in *.aar ?
Hope anyone can tell me kindly. Thank you.

**Comment by nathanmartz** [comment]
Hi. We don't provide source for the gvr library.
