### ISSUE TITLE
Device specific issue for 'LeEco Le 1s'

### ISSUE THREAD

**Issue by CAMOBAP795** [googlevr/gvr-android-sdk#243]
I faced with device specific issue for http://www.gsmarena.com/leeco_le_1s-8055.php

Nothing special in logs, but UI looks like this:
- For https://github.com/googlevr/gvr-android-sdk/tree/master/samples/sdk-treasurehunt
  ![Android GVR SDK](https://cloud.githubusercontent.com/assets/2169738/18588018/60fe3f70-7c2d-11e6-8e91-44bcc900c40c.jpg)
- For Unity app
  ![Unity GVR SDK](https://cloud.githubusercontent.com/assets/2169738/18588019/60fe747c-7c2d-11e6-9cdd-4cca1d83089b.JPG)

Is this right place to post such bugs?
What additional info can I provide?

**Comment by nathanmartz** [comment]
This is exactly the right place to post this kind of issue. Thank you!

**Comment by smdol** [comment]
In the first picture, the phone was in portrait mode when the SDK asked for its screen resolution, which is used to compute the physical phone size, so it got a taller-than-wide result.  In the second photo, this shows that the phone is reporting an incorrect PPI (in this case, too low), which makes the phone seem much smaller than it really is.  One can see evidence of this in the first picture as well.

**Comment by CAMOBAP795** [comment]
@smdol looks like you right (almost), this device have next specification display spec `5.5 in, IPS, 1080 x 1920 pixels, 24 bit`

And market helper apps and `adb shell dumpsys display` reports 440 DPI

But https://www.sven.de/dpi/ reports `400.53 PPI`

*AFAIK `DPI` and `PPI` in context of phone screens the same, correct me if I'm wrong.

**Comment by jdduke** [comment]
There have been quite a few changes and improvements in the SDK over the past number of months. Are you still able to reproduce the problem on this device?

**Comment by jdduke** [comment]
Feel free to re-open if this remains an issue. In general, devices that do not accurately report their DPI will manifest similar visual artifacts. We can whitelist them if there's sufficient demand.
