### ISSUE TITLE
Stereo render not work

### ISSUE THREAD

**Issue by chr314** [googlevr/gvr-android-sdk#244]
the app is a simple image viewer,
after update to aar stereo mode not work properly, with stereo mode disabled its work fine, in stereo mode i cant change anything(size etc) and show the images upside down and the eyes is merged, i tried older version problem not fixed

in stereo mode code in onDrawEye, onSurfaceChanged, onSurfaceCreated etc not work
i removed most of my code and had the same result in stereo mode only with this GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, bmp, 0);

![screenshot_20160917-161856](https://cloud.githubusercontent.com/assets/6598377/18608519/37f32786-7cf4-11e6-819e-a544b73a18a6.png)

**Comment by jdduke** [comment]
@chr314 does this issue still reproduce with the latest (1.40.0) SDK?

**Comment by chr314** [comment]
I will try tomorrow

**Comment by chr314** [comment]
@jdduke  the problem not fixed

**Comment by jdduke** [comment]
Which headset and phone (device + Android version) are you using?

**Comment by jdduke** [comment]
Also, do you see the same issue on your phone using the SDK TreasureHunt sample?

**Comment by chr314** [comment]
hello @jdduke sorry for late reply
im using nexus 5x
with samples its working fine i had problem with rendering 2d images
i have rewritten the code with different way and its working now

**Comment by jdduke** [comment]
OK, thanks for the update, glad it's working!
