### ISSUE TITLE
Let VrPanoramaView can show image like ImageView

### ISSUE THREAD

**Issue by solomon2** [googlevr/gvr-android-sdk#248]
Why not don't let VrPanoramaView can show image like ImageView. It show panoramic image like  panoramic preview will  be good. 

In lot of scene，we neek both VrPanoramaView  and ImageView. and now have to change them to show.When loading image in network, It will scintillation black befor show VrPanoramaView  and loading twice image in network.

**Comment by nathanmartz** [comment]
Thanks for the note, but we're focused on VR, not on all image formats.
