### ISSUE TITLE
How can I extends vr video player with  gaze-based control buttons like a App called "UtoVR"?

### ISSUE THREAD

**Issue by wilixx** [googlevr/gvr-android-sdk#249]
I want to add a video player function like Utovr, to control video play by gazing button for a while.

The function can be seen through the newest version of a Chinese App called UtoVR, I have trouble to build it by using google vr api. Hope someone can give me some ideas.
Thank you.

**Comment by nathanmartz** [comment]
Hi. Questions like this are better posted for StackOverflow as this forum is just for issues and bugs in the actual SDK.
