### ISSUE TITLE
Wrong Artifact in releases

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#251]
Hey guys, I think you uploaded the wrong version under releases https://github.com/googlevr/gvr-android-sdk/releases for version  1.0

When I grabbed the zip, it had a libraries folder with files last updated aug 8th.  Cloning the repo gives the new libraries.

**Comment by digitalbuddha** [comment]
also we needed to add following dependency compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'

**Comment by nathanmartz** [comment]
Thanks for the heads up. We're looking into this issue now.

**Comment by digitalbuddha** [comment]
If it helps what we noticed was different is that the artifact in releases tab does not have the set volume method

**Comment by nathanmartz** [comment]
OK. This issue should be fixed now.
