### ISSUE TITLE
Why always-on settings/back/alignment UI in SDK 1.0.0?

### ISSUE THREAD

**Issue by svenhenrik** [googlevr/gvr-android-sdk#252]
Reading the release notes for the 1.0 SDK and I have to question your judgement on this one:

> GvrView.setAlignmentMarkerEnabled and GvrView.setSettingsButtonEnabled methods have both been removed. The UI layer is now completely enabled by default in stereo mode, and disabled when stereo mode is disabled.

My app is a video player, and my users are very sensitive to anything disturbing the immersion. Light leaking in from the configuration button and alignment marker has been a common complaint. 

I see you've toned down the size of the alignment marker and moved the configuration button up, but you've also added an always-on back button. I fail to see the point of having always-on bright UI elements that you can't/aren't supposed to interact with on the screen in stereo mode.

Ideally I'd like to see the disabled methods return, but I'm not holding my breath. 

Might I at least suggest reducing the brightness of the icons, auto hiding after a delay/show on touch, or maybe using the proximity sensor to detect when the phone is in a headset?

**Comment by nathanmartz** [comment]
Thanks for the feedback. We don't plan to let devs disable this UI in the future, but we do want to make sure the standard UI works well for applications like yours (hence the changes in this release). Thanks for the additional ideas. We'll look into them for future releases.

**Comment by svenhenrik** [comment]
Closing the issue immediately doesn't exactly inspire confidence that you'll actually look into it, but thanks for the response.

**Comment by nathanmartz** [comment]
Sorry, closed because we have a tracker for this internally and there are similar suggestions in other open threads here.

**Comment by svenhenrik** [comment]
Ok, sounds great. Thanks again! :)

**Comment by ajavamind** [comment]
Adding my view of this issue: The alignment marker and settings button are now seen in larger field of view viewers. Developers must be able to control this visual distraction and be able to remove its display.

**Comment by sp-1234** [comment]
You could at least open the source code so that developers can change things themselves if you can't.
