### ISSUE TITLE
GvrView's setUseProtectedBuffers vanished

### ISSUE THREAD

**Issue by R1ck77** [googlevr/gvr-android-sdk#253]
`setUseProtectedBuffers` just disappeared during the transition to v1.0.0 without warning/deprecation (not an issue as 0.9.x where beta versions, so that's life) or mention in the release notes (there should _definitely_ be something there...).

Best of luck with the "coming out" as 1.0.0 anyway, and keep up the good work!

**Comment by sigmaxipi** [comment]
Thanks for the heads up. We'll update the release notes.

**Comment by dav-cz** [comment]
Release notes for v1.0.0 were updated.
