### ISSUE TITLE
Protobuf dependency is an alpha version

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#257]
Hey guys, Protobuf dependecy is version 3.0.0-alpha-7, is it fine to release into a production application?  Could we instead go with a stable release?

**Comment by sigmaxipi** [comment]
com.google.protobuf.nano:protobuf-javanano:3.1.0 is out now so you can update to that. But it's the same code in both of the jars so you can stick with alpha-7 if you want.
