### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.protobuf.nano.InvalidProtocolBufferNanoException

### ISSUE THREAD

**Issue by SeLoRBIS** [googlevr/gvr-android-sdk#258]
I update gvr-android-sdk because some functionnality works on a ONO but not on a Samsung S7 👍 
`Error inflating class com.google.vr.sdk.widgets.pano.VrPanoramaView`. 
When i want to load an activity : 
`
public class VrPanoramaActivity extends AppCompatActivity {
...
@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.vr_pano_layout);
...
`

But now with the new sources i have this error when i want run the app : 
`Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
java.lang.ClassNotFoundException: com.google.protobuf.nano.InvalidProtocolBufferNanoException`

**Comment by SeLoRBIS** [comment]
Sorry for this issue, i read the new : samples-sdk-simplevideowidget project and now we have two libraries to add in the build.gradle : 
`
compile 'com.google.android.exoplayer:exoplayer:r1.5.10'
compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
`

**Comment by nathanmartz** [comment]
I think the issue was these missing dependencies, so I'm closing the issue. Please reopen if it's actually unresolved.
