### ISSUE TITLE
Transition View needs alignment marker

### ISSUE THREAD

**Issue by ajavamind** [googlevr/gvr-android-sdk#262]
It would help if the transition view screen had an alignment marker when placing the phone in a Cardboard viewer. This way a user can put the phone in a viewer without needing the transition view to disappear (which sometimes happens when the viewer lies flat on a surface) and then have  to readjust the phone in the viewer.

Also it would be helpful if you could provide developers with the capability to use custom transition view screens.
thank you

**Comment by nathanmartz** [comment]
Thanks for the suggestion. We are likely be more flexible with transition views in an upcoming update.
