### ISSUE TITLE
DASH support 

### ISSUE THREAD

**Issue by SrujithPoondla** [googlevr/gvr-android-sdk#263]
Now this sdk is supporting HLS, is there any way to get support for DASH as exoplayer supports DASH?
Is there any other way to play dash 360 degree videos

**Comment by nathanmartz** [comment]
We don't currently support DASH but we're looking into it for Android. iOS
will be HLS only for the forseeable future.

**Comment by SrujithPoondla** [comment]
Thanks for the answer, I have another question regarding libraries you provided as .aar files. Is there any way i can get source code of those .aar files?

**Comment by nathanmartz** [comment]
We don't provide source for this library, and there are other open threads that discuss it in more detail.
