### ISSUE TITLE
Cannot move the scene up and down

### ISSUE THREAD

**Issue by barisaraci** [googlevr/gvr-android-sdk#265]
Hey, in VrPanoramaView, I cannot move the scene up and down but only right and left. It looks like a common situation, is this a bug?

**Comment by nathanmartz** [comment]
It's not a bug but it is a feature we're looking to add. Closing this out as it's already tracked elsewhere here.

**Comment by solomon2** [comment]
@nathanmartz    this feature not has yet ， when you prepare to add?
