### ISSUE TITLE
Can I set viewport size by using `base`, `common` dependencies?

### ISSUE THREAD

**Issue by lecion** [googlevr/gvr-android-sdk#266]
In my project, my module uses some libraries:
compile project(':audio')
compile project(':base')
compile project(':common')

My Activity extends GvrActivity and it enter fullscreen by default. Is there any way to set viewport size? I don't want to use fullscreen in some cases. Thanks a lot!

**Comment by dav-cz** [comment]
GvrActivity is a very simple class that indeed goes into fullscreen by default.

You can try using GvrView instead. It is generally designed with fullscreen in mind and anything else than fullscreen will look strange in stereoscopic mode. But assuming you want to render in monoscopic mode (using setStereoModeEnabled(false)) then it might probably do what you want?

**Comment by lecion** [comment]
@dav-cz thx a lot.
