### ISSUE TITLE
setAlignmentMarkerEnabled method is removed in 1.0, alternative is needed

### ISSUE THREAD

**Issue by sp-1234** [googlevr/gvr-android-sdk#269]
The marker between eyes is visible on some glasses and I need possibility to remove it, now how to do this?
setAlignmentMarkerEnabled(false) used to work until 1.0

**Comment by jdduke** [comment]
We'll be tweaking the size and making these UI elements less prominent for the next release.

**Comment by sp-1234** [comment]
So where is it? There were several releases since then, and these forced UI controls are still too big and too bright and look gross when using cardboard.

To be honest, I am wondering, do you even test this SDK on yourselves?…

**Comment by sigmaxipi** [comment]
We've changed the Overlay to automatically fade to dark grey after a while.
