### ISSUE TITLE
GvrAudioEngine.createSoundfield without preloading

### ISSUE THREAD

**Issue by niusounds** [googlevr/gvr-android-sdk#270]
Document in [GvrAudioEngine.createSoundObject](https://developers.google.com/vr/android/reference/com/google/vr/sdk/audio/GvrAudioEngine.html#createSoundObject(java.lang.String)) says:

     Note that the sample needs to be preloaded and must only contain a single audio channel (mono).

But it seems work properly even if I didn't preload sound file in v1.0.1. It seems that document should be updated. right?

**Comment by niusounds** [comment]
In addition, [GvrAudioEngine.createStereoSound](https://developers.google.com/vr/android/reference/com/google/vr/sdk/audio/GvrAudioEngine#createStereoSound(java.lang.String)) fails when sound is not preloaded. It is not written in document.
Is this behavior expected? or bug?

**Comment by jkammerl** [comment]
The documentation for [GvrAudioEngine.createSoundfield](https://developers.google.com/vr/android/reference/com/google/vr/sdk/audio/GvrAudioEngine.html#createSoundfield(java.lang.String)) correctly says:

> Ambisonic soundfields do *not* need to be preloaded. They are directly streamed and rendered from the compressed audio file.

createSoundfield/createSoundObject/createStereoSound fist look into the internal sample cache if the soundfile has been preloaded. If it's not found, then it initializes the playback using streamed decoding. 

Streamed playback should also work for createStrereoSound. Could you provide more details how it fails? Does it return an invalid sound id?

**Comment by niusounds** [comment]
Sorry, I made a mistake. I wanted to write [GvrAudioEngine.createSoundObject](https://developers.google.com/vr/android/reference/com/google/vr/sdk/audio/GvrAudioEngine.html#createSoundObject(java.lang.String)).

**Comment by niusounds** [comment]
> Streamed playback should also work for createStrereoSound. Could you provide more details how it fails? Does it return an invalid sound id?

I tried these codes (simplified from my actual project's code)

```java
// with preloading
audioEngine.preloadSoundFile("bgm.ogg");
int soundId = audioEngine.createStereoSound("bgm.ogg");
// soundId = some valid id
audioEngine.playSound(soundId, true); // success
```

```java
// without preloading
int soundId = audioEngine.createStereoSound("bgm.ogg");
// soundId = GvrAudioEngine.INVALID_ID
audioEngine.playSound(soundId, true); // failure
```

`createSoundObject` works correctly in both case.

```java
// with preloading
audioEngine.preloadSoundFile("se.ogg");
int soundId = audioEngine.createSoundObject("se.ogg");
// soundId = some valid id
audioEngine.playSound(soundId, false); // success
```

```java
// without preloading
int soundId = audioEngine.createStereoSound("se.ogg");
// soundId = some valid id
audioEngine.playSound(soundId, false); // success
```

**Comment by jkammerl** [comment]
Thanks for the detailed analysis. That's helpful! Originally the support for stereo playback has been mostly designed for music streaming but I don't see why it also shouldn't work with preloaded sound files. I'll run some more tests and if I can reproduce this issue, we'll fix it in the next release.

**Comment by jkammerl** [comment]
I ran some tests but couldn't reproduce the bug. Stereo sound playback works with and without preloading for me. Do you have a minimal example on github that reproduces this bug?

**Comment by niusounds** [comment]
I created an Android project for reproducing this issue.
https://github.com/niusounds/GvrAudio-issue

Please see [com/eje_c/gvraudioproblem/MainActivity.java#20](https://github.com/niusounds/GvrAudio-issue/blob/master/app/src/main/java/com/eje_c/gvraudioproblem/MainActivity.java)
