### ISSUE TITLE
Changing render mode to render by request

### ISSUE THREAD

**Issue by kpilyugin** [googlevr/gvr-android-sdk#272]
We have an application which works in both VR and non-VR modes, and in non-VR mode we'd like to disable continuous rendering to reduce battery usage. 

With old version of Cardboard SDK, that was made by directly calling GLSurfaceView method setRenderMode. But now we don't have access to GLSurfaceView and there is no such method
in GVRView, so it's not clear now to achieve the same functionality with new version of SDK.

**Comment by jdduke** [comment]
Hi @kpilyugin. We don't have any immediate plans to expose the setRenderMode API, though if there is additional demand from more developers we may consider it.

You might be interested in some of our lower-level APIs, like GvrLayout and GvrApi, which let you install your own GLSurfaceView or custom SurfaceView into the VR pipeline. See also the guide @ https://developers.google.com/vr/android/ndk/gvr-ndk-walkthrough. If you prefer not to work with native code, there are complete Java bindings to the native APIs, documented @ https://developers.google.com/vr/android/ndk/jni/reference/com/google/vr/ndk/base/GvrApi. We'll be releasing a sample in an upcoming release which implements some of the GvrView functionality in terms of the lower-level Java GvrApi + GvrLayout bindings.

**Comment by jdduke** [comment]
Per the workaround suggested by using GvrApi + GvrLayout bindings directly, I'm going to go ahead and close this request. The sample mentioned will actually be part of this month's SDK release.
