### ISSUE TITLE
Google VR Service(com.google.vr.vrcore)

### ISSUE THREAD

**Issue by smallccn** [googlevr/gvr-android-sdk#273]
Hi, 

When I check the factory image which is downloading from https://developers.google.com/android/nexus/images, we can find Google VR Service is preloaded. 
But after compile the source code of Android N(android-7.0.0_r6), I can't find Google VR Service in device. 
How can I get the source code or apk files for this package? 
Will you add it in new release?

That's all.
Thank you.

**Comment by nathanmartz** [comment]
That's right. The images are a superset of of the binaries created when compiling Android source. We don't supply raw APKs or source for the Google VR Service.
