### ISSUE TITLE
Set the time when calling gvr_get_head_space_from_start_space_rotation

### ISSUE THREAD

**Issue by lingkang1988** [googlevr/gvr-android-sdk#274]
How to set the time in gvr_get_head_space_from_start_space_rotation in order to get the smooth video playing experience when the phone is in motion. It seems zero is best after several times' trying...

**Comment by jdduke** [comment]
Hi @lingkang1988, our typical recommendation is to add ~50 milliseconds to the *current* time at the start of your frame.  There's an example of how to do this in our NDK TreasureHunt sample @ https://github.com/googlevr/gvr-android-sdk/blob/master/ndk/demos/treasurehunt/app/src/main/jni/vr/gvr/demos/treasure_hunt/jni/treasure_hunt_renderer.cc#L385.

**Comment by dav-cz** [comment]
Updated link:

https://github.com/googlevr/gvr-android-sdk/search?utf8=%E2%9C%93&q=kPredictionTimeWithoutVsyncNanos
