### ISSUE TITLE
VrVideoView shows black screen

### ISSUE THREAD

**Issue by KhegayIV** [googlevr/gvr-android-sdk#275]
I'm using VrVideoView to show mono video in 360. Sometimes I get this situation: audio plays, but video not showing, it's just black screen. Noticed on Nexus 9, Samsung S7 (quite rarely) and LG G3 (Very often). Sometimes on G3 i get a static frame - just some color gradient, while audio still playing.
Also, when I close fragment with video on G3 when this black screen appears, application just hangs. Hanging doesn't happen with other devices or when there's a gradient.

Logs at time of video loading, when I get black screen on G3:

> 10-18 16:24:13.604 16000-16000 I/ExoPlayerImpl: Init 1.5.10
> 10-18 16:24:13.648 16000-16409 E/SphericalMetadataMP4: Failed to extract metadata string from mp4.
>                                                        java.io.IOException: Invalid atom size: -1513166924
>                                                            at com.google.vr.jump.preview.model.SphericalMetadataMP4.extract(SphericalMetadataMP4.java:102)
>                                                            at com.google.vr.jump.preview.model.SphericalMetadataMP4.extract(SphericalMetadataMP4.java:61)
>                                                            at com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.parseMetadataFromVideoInputStream(VrVideoPlayerInternal.java:463)
>                                                            at com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.openUri(VrVideoPlayerInternal.java:284)
>                                                            at com.google.vr.sdk.widgets.video.VrVideoView.loadVideo(VrVideoView.java:187)
>                                                            at /_mypackage_/.playback.VrPlaybackFragment$VrVideoViewSource.lambda$new$0(VrPlaybackFragment.java:332)
>                                                            at /_mypackage_/.playback.VrPlaybackFragment$VrVideoViewSource.access$lambda$0(VrPlaybackFragment.java:0)
>                                                            at /_mypackage_/.playback.VrPlaybackFragment$VrVideoViewSource$$Lambda$1.call(Unknown Source)
>                                                            at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:66)
>                                                            at rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.call(ScalarSynchronousObservable.java:192)
>                                                            at rx.internal.util.ScalarSynchronousObservable$3$1.call(ScalarSynchronousObservable.java:120)
>                                                            at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:222)
>                                                            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
>                                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
>                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
>                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
>                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>                                                            at java.lang.Thread.run(Thread.java:818)
> 10-18 16:24:13.650 16000-17416 I/VrWidgetRenderer: Native renderer has just been destroyed. Dropping request.
> 10-18 16:24:13.741 16000-17446 I/OMXClient: Using client-side OMX mux.
> 10-18 16:24:13.743 16000-17446 E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
> 10-18 16:24:13.758 16000-17449 I/SoftAAC2Ex: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
> 10-18 16:24:14.124 16000-17416 I/VrWidgetRenderer: Native renderer has just been destroyed. Dropping request.

**Comment by sigmaxipi** [comment]
Can you play the video with other video players on the device? Also, you could try reencoding the video using Handbrake or some other tool in case it's a format issue.

**Comment by amalcev** [comment]
Yes, we've tried different formats and tools.

As for Handbrake tool, we have tried to encode videos using it and we have similar behavior like with congo.mp4 file (which comes with SDK sample).
However it's also not perfect, please have a look on sample app with congo.mp4:
https://cloud.noveogroup.com/index.php/s/KIedRQvTNogd9zS
(test made on LG G3 Android 5)

This Handbrake-encoded files we have only one issue - video is grayed from time to time. 

We've also tried to play all our test videos and congo.mp4 in default LG G3 video player, it plays all of them perfectly without such issues (not taking into account that default player doesn't support 360 videos and plays them as plain videos).

**Comment by jdduke** [comment]
There have been quite a few tweaks to ExoPlayer (the library we use to handle video playback) in the intervening months. Does the latest SDK resolve the issue you had observed?

**Comment by jdduke** [comment]
Feel free to re-open if this continues to be an issue. Thanks.

**Comment by fhcampbell** [comment]
Has this been solved?
