### ISSUE TITLE
Possible memory leak in NDK sample

### ISSUE THREAD

**Issue by scorpeeon** [googlevr/gvr-android-sdk#277]
I'm currently developing a native Daydream/Cardboard app and and for that I'm using the NDK samples (treasurehunt, controllerpaint) as the best (and only?) references I could find.

In the treasurehunt project there's the method `TreasureHuntRenderer::LoadGLShader()`
A new int is created:
`int* compileStatus = new int[1];`

And as far as I can tell it's never deleted.
I don't think it's a huge issue as it's only a single int and this method is probably not called very often, still it seems like a leak.

What's also a bit strange is that multiple functions are implemented in both treasurehunt and controllerpaint, and in some of them there are minor differences. For example controllerpaint has a `Utils::BuildShader` which does essentially the same thing as the mentioned `TreasureHuntRenderer::LoadGLShader()` but it does so a bit differently (it's not creating a new int and so there should be no leak there). Other methods that can be found in both samples are for instance: MatrixToGLArray(), MatrixMul(), PerspectiveMatrixFromView(), MatrixVectorMul().
In most cases I found the treasurehunt's code to be newer/better (for instance it's using C++11 style literals for shader codes), but not always.

**Comment by jdduke** [comment]
Thanks for the feedback @scorpeeon, we'll be sure to address this in an upcoming release. A few of the samples have evolved over time, so there are some rough edges and redundancies that do need to be addressed.

**Comment by scorpeeon** [comment]
This issue looks to be fixed in the improved sample app in v1.10.0, so I think it can be closed

**Comment by nathanmartz** [comment]
Thanks!
