### ISSUE TITLE
Removal of GvrView.setSettingsButtonEnabled, and general button cluttering causes lack of immersivness and light discomfort

### ISSUE THREAD

**Issue by R1ck77** [googlevr/gvr-android-sdk#284]
On some wide-angle headsets (especially good quality ones, which is ironic...) the top left and top right icons for respectively, "back" and "configure" are visible while watching VR content.

Besides being downright annoying and useless in VR mode, they provide some light discomfort, as looking at them delivers each eye a different view.

Now, I know you explicitly removed the option to hide the configure button and the middle line (which btw looks very nice now that's shorter) in 1.0.0, but it was a really bad call, so please reconsider it, as:
- it could have been acceptable when there was only one button at the bottom center (under the nose), not after moving it at the corners where they are now visible.
- it might be considered as arrogant toward the developers ("we force you to keep our stuff on your screen, because we know better")
- they provide little of no benefit to the user. You even provide a transition screen _to allow them to put the visor_ **before** _the VR content shows up_, so how are they supposed to operate the buttons anyway?

My next task is to navigate the view hierarchy to disable the buttons through reflection, if possible, or to recreate the GVRView from scratch, if required, if it isn't possible, but I'd rather avoid that... :)

Suggested workarounds: 
- re-instate the `setSettingsButtonEnabled` and add a `setBackButtonEnabled` (was there really a point to add a back button in the first place???)

Also consider providing a standard intent, to fire up the VR configuration activity as a complement to the "gear button" for apps/situations where it makes sense to have the VR configured _before_ it's actually on the user's face, for a 2D UI integration (sorry for my ignorance if you already did: I didn't check.. :) )?

 Anyway, despite the arguing, still a big fan, so keep up the good work! ;-)

**Comment by nathanmartz** [comment]
This has already been discussed at length in a few other threads here, but
a quick recap is that while we won't be making these elements optional we
are going to make them less obtrusive, hiding them while users are in VR,
etc.

The back button exists because many users aren't familiar with the swipe
down to show system bar  on phones without physical buttons and without
that they didn't know how to exit the app and felt "trapped" in VR. Not
knowing how to leave makes them not want to go into VR again.

BTW - what phone and viewer are you using?

**Comment by R1ck77** [comment]
Sorry if this was discussed somewhere else: I just checked the opened issues, not the closed ones (my bad) and I didn't found it there.

The phone + VR combination I'm using is:  Homido + Nexus 5. I get people on the store complaining about the central line, just figure if I post the app with *"everbuttons"* on.

About the back button, maybe I didn't explain myself clearly, when I said 

> was there really a point to add a back button in the first place???

I didn't mean that it couldn't be useful for the user, but that's 101 stuff that shouldn't have place in the SDK.

If you want to create a VR application you have to deal with OpenGL (or Vulkan...), perspective matrices, and all sort for stuff: someone who can't add a button in the top left corner of a layout with a simple `finish()` in the `setOnClickListener`'s body in less than 5" *is never going to be in the target of your SDK*. Stuff like that might make sense for the Unity/Unreal SDK, more aimed at people with graphics skill set.

Creating this sort of stuff for the the lazy developers (and I'm proudly in the pack), and allowing them to disable it, is a nicety, but forcing people to keep on *turns it into a constraint*, something that can get in the way. 

It's a one size-fits-all approach that can't match all requirements: think about people developing VR apps with full withe background...

Anyway, if you plan to make the overlay button disappear after a while, I guess it would solve the issue nicely, at least for me.

In the meantime, is there any chance to have the id or locations of the views in question? I don't think it will be that hard to find them, but not having to do it would be very nice...

**Comment by nathanmartz** [comment]
Thanks for your feedback here. I can't share the specifics of the view hierarchy here or guarantee that they won't change in the future, but if you look around at other posts here you'll find others who have successfully dug through the view hierarchy.

**Comment by R1ck77** [comment]
Thanks!
