### ISSUE TITLE
24bit depth precision problem

### ISSUE THREAD

**Issue by v14gh** [googlevr/gvr-android-sdk#285]
Hi,

I'm using GoogleVR SDK 1.0.1 on Android.

I need a 24bit depth buffer for correctly rendering our scenes, so I specified it as minimum requirement by calling GvrView.setEGLConfigChooser(8,8,8,8,24,0). The OpenGL surface is correctly created with a 24bit ZBuffer, but when distortion correction is enabled and the SDK sets up the GL context for us to draw into a framebuffer backed by a texture (as opposed to drawing directly to the surface), it creates the render target with a 16bit depth buffer only (GL_DEPTH_COMPONENT16), even if the hardware would support render targets with 24bit depth components (OES_Depth24 GL extension).

This results in our scenes getting rendered with reduced z precision, when distortion correction is enabled. (Tested on: SONY Xperia Z1 Compact)

Could you please confirm if this behavior is for some reason by design or a bug in the SDK?

Also, as a workaround, would it be safe to detach and destroy the depth renderbuffer from the SDK's render target and recreate it with a 24bit internal format?

Thanks!

**Comment by jdduke** [comment]
Hi @v14gh, thanks for the feedback. This is bit of an oversight in the SDK. We've tried to keep the GvrView API as tight and streamlined as we can, but there are some gaps, e.g., inconsistencies between the output surface format and the (offscreen) render target format. We'll look into exposing some API hooks to resolve this, or try to do something slightly more intelligent for the next SDK release.

One thing to note is that it's perfectly acceptable for the surface and app render targets to have different formats, e.g., the output surface might have 0 depth as long as the app's render target has a suitable depth component.

**Comment by jdduke** [comment]
We've gone ahead and added an API for this, to be included with the next release several weeks from now. Check the release notes for details on usage. Cheers.

**Comment by v14gh** [comment]
Hi @jdduke,

Thanks for the information, looking forward to the changes in the next release!

**Comment by sp-1234** [comment]
Anyway it's better to eschew built-in distortion correction and do it yourself using vertex displacement technique, because it's faster and can give higher quality picture.

**Comment by jdduke** [comment]
> Anyway it's better to eschew built-in distortion correction and do it yourself using vertex displacement technique, because it's faster and can give higher quality picture.

This may be true for Cardboard apps, but low-latency Daydream-compatible apps require use of async reprojection, which is itself incompatible with vertex-based distortion.

You can now configure the depth/stencil format of the offscreen framebuffer using [GvrView.setDepthStencilFormat()](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView.html#setDepthStencilFormat(int)). Note that the integer argument doesn't map to a GL format, rather it maps to one of the predefined formats specified by [BufferSpec.DepthStencilFormat](https://developers.google.com/vr/android/reference/com/google/vr/ndk/base/BufferSpec.DepthStencilFormat).

**Comment by sp-1234** [comment]
> async reprojection

What is it?

**Comment by jdduke** [comment]
Async reprojection, as implemented in the GVR SDK, does the following:

- Creates a separate "reprojection" render thread for drawing to the screen (decoupling app framerate from display framerate, ensuring 60 fps, making app frame submission "async")
- Enables reprojection of the app framebuffer using the latest headpose at the last possible moment before rendering
- Enables rendering directly to the front buffer for the reprojection thread (for low-latency rendering)

See also issue #219 .
