### ISSUE TITLE
Controller aar does not specify minsdk

### ISSUE THREAD

**Issue by anakin78z** [googlevr/gvr-android-sdk#289]
Same issue as #71, only with the new controller library. 
As the Controller aar does not specify a min sdk, the app ends up requesting the READ_PHONE_STATE permission by default. A quick fix to this is to specify a min sdk higher than 3.

**Comment by jdduke** [comment]
Thanks for the report @anakin78z, we'll be sure to get this fixed in the next SDK release. Apologies for the oversight.

**Comment by jdduke** [comment]
This should be fixed with the latest 1.10.0 release, thanks again for the feedback.
