### ISSUE TITLE
How to further augment the capabiltites of the VR View

### ISSUE THREAD

**Issue by s1mar** [googlevr/gvr-android-sdk#290]
Hello,
Is it possible to add hot-spots or transition markers in a VR view to change it's texture or background image. Currently,I'm trying to create this custom functionality in unity but it's getting pretty cumbersome,If such a feature already exists in this sdk then I'll be able to make my app in the android studio quite swiftly!!

**Comment by nathanmartz** [comment]
We don't support hotspots in the native VR view but the [web version](github.com/googlevr/vrview) supports exactly what you want.

**Comment by dekemega** [comment]
is there any change on this topic ..

**Comment by jdduke** [comment]
No change at the moment, and no concrete plans to support this for the native VR views.

**Comment by sigmaxipi** [comment]
Also consider the new Video360 sample if you want to create a panorama viewer with more functionality. See https://developers.google.com/vr/android/samples/video360 for more details.
