### ISSUE TITLE
Can't play stream from HLS without audio.

### ISSUE THREAD

**Issue by yijianwang** [googlevr/gvr-android-sdk#292]
I tried to play stream from HLS without audio through the SimpleVrVideoActivity, but failed.
I found it can play stream which has audio using the same way.
And I can play mp4 from asset without audio.

Only the HLS stream without audio can't be played, which is weird.

Did I miss some required setting, or it is just the limitation of this SDK?

`          Options options = new Options();
          options.inputType = Options.TYPE_MONO;
          options.inputFormat =  Options.FORMAT_HLS;
          Uri liveAddress = Uri.parse("http://XXX.XXX.XXX.XXX/hls/test.m3u8");
//          videoWidgetView.loadVideoFromAsset("test.mp4", options);
          videoWidgetView.loadVideo(liveAddress, options);`
This is my setting.

Update:
I tried to combine the HLS stream and the audio from my microphone, then it works. Very weird! It seems to require audio as input along with the video.

**Comment by dav-cz** [comment]
Thanks for the report. This should be fixed in our next release.

**Comment by dav-cz** [comment]
This is fixed in v1.20.0, thanks again for the report!
https://developers.google.com/vr/android/release-notes

**Comment by yijianwang** [comment]
Awesome! Thank you!
