### ISSUE TITLE
Activity Lifecycle issue causes crash in NDK samples

### ISSUE THREAD

**Issue by gpx1000** [googlevr/gvr-android-sdk#293]
When an android device changes orientation, usually the activity is destroyed and recreated with a new orientation layout.  This causes a problem when nativeDestroyRenderer(nativeTreasureHuntRenderer); is called from Java.  This can happen before the thread is attached or other objects are finished creating themselves and the result is immediate crash on load.
I highly recommend changing the onDestroy() java call to use isFinishing() to check if we really want to destroy C objects or not.

The way to quickly test this is the attach a pixel device, let the screen go to sleep so the app starts in the background, then wake the app.  Observe that it crashes as written.  Place if(isFinishing()) { at line 142 of MainActivity.java and notice that it doesn't crash.

**Comment by jdduke** [comment]
Thanks for the feedback, @gpx1000. It's actually an oversight on our part to not have added the `orientation` value to that sample's `android:configChanges` manifest attribute. This will be fixed in the next SDK update.

**Comment by jdduke** [comment]
This should be resolved with the latest 1.10.0 release, thanks for the feedback.
