### ISSUE TITLE
NDK GVR Audio IsSoundPlaying(AudioSourceId) returns incorrect result

### ISSUE THREAD

**Issue by radvani** [googlevr/gvr-android-sdk#294]
In the NDK GVR Audio, if you preload and play a sound, then after the sound completes IsSoundPlaying should return false. However, it still returns true. This makes it impossible to tell whether an AudioSourceId is still valid or not. 

(Note that IsSoundPlaying works correctly if you manually Stop a sound; it only fails if you let a sound finish to completion).

Making this worse, if you attempt to ResumeSound() on an invalid AudioSourceId, the system hard crashes. There must be a way to tell if an AudioSourceId is still valid, otherwise we don't know when it's safe to resume a sound.

This is blocking behavior for our application, so we are moving to using low-level audio (OpenSL ES) until this is resolved.

**Comment by radvani** [comment]
In addition, it's unclear in the documentation what IsSoundPlaying is supposed to return if a sound is paused. Is a paused sound playing? Or does IsSoundPlaying only refer to whether an AudioSourceId is valid? We need a way to differentiate the three sound states: paused, playing, and invalid.

**Comment by jkammerl** [comment]
Thanks for your bug report. I agree with you that this ambiguity between paused and stopped is unfortunate and obviously a crash should never happen for an invalid function argument. In the current release IsSoundPlaying should return false when it is paused as well as when it is stopped. We'll investigate this in more detail and work on a fix for the upcoming release.

**Comment by jkammerl** [comment]
With the latest update, we added a IsSourceIdValid() method which allows you to determine if a source handle is in a playable state. The crash has been fixed too. Thanks again for your valuable feedback!
