### ISSUE TITLE
"This Cardboard application is not compatible with Daydream headsets"

### ISSUE THREAD

**Issue by jbrown101st** [googlevr/gvr-android-sdk#295]
I have an activity for video playback that extends GvrActivity and uses GvrView, it also accepts input from the Daydream controller without any issue. The error only occurs when the Headset option in the VR Settings is set to "Daydream View". If it is set as a "Cardboard" headset everything is perfect and the controller works.

I've tried all of the manifest settings for daydream compatibility (like in the ndk controllerpaint sample) without any success.

I can provide any other info needed. Thanks!

**Comment by sigmaxipi** [comment]
We haven't released the new APIs to enable Cardboard apps to run on Daydream View. This will be part of the next SDK release. For now, you'll need to only use your Cardboard app on a Cardboard headset.

https://github.com/googlevr/gvr-android-sdk/issues/286 tracks this issue.

**Comment by jdduke** [comment]
Hi @jbrown101st , would you mind posting you Activity manifest bits here (redacted where appropriate)? In theory it should be possible to create a Daydream-compatible, GvrView-based app using the current public SDK, assuming you're using the existing [Controller API](https://developers.google.com/vr/android/reference/com/google/vr/sdk/controller/package-summary).

Internally, validating that an Activity is Daydream-compatible requires that:

1. The DAYDREAM `<intent-filter>` category is specified, `<category android:name="com.google.intent.category.DAYDREAM" />`
2. The Activity is exported (this is the default assuming your Activity has an `<intent-filter>`
3. An *action* is specified for the `<intent-filter>`, e.g., `<action android:name="android.intent.action.MAIN" />`.

**Comment by jbrown101st** [comment]
Simple mistake on my part. I was able to get it working by specifying the activity as the action inside the intent filter (previously had android.intent.action.Main). Just a heads up for anyone with a similar issue.
```
<intent-filter>
<action android:name="activities.PlaybackActivity" />
<category android:name="com.google.intent.category.DAYDREAM" />
<category android:name="com.google.intent.category.CARDBOARD" />
</intent-filter>
```

**Comment by jclova** [comment]
I know this thread has been closed, but I don't think following command fixes the issue.
```
<intent-filter>
<action android:name="activities.PlaybackActivity" />
<category android:name="com.google.intent.category.DAYDREAM" />
<category android:name="com.google.intent.category.CARDBOARD" />
</intent-filter>
```
Above code will now force users to pair a Daydream Headset & controller. You cannot continue without pairing a controller. What if you don't have a Daydream headset (at the moment) and just want to view using the cardboard headset (and possibly one that does not have a QR code)? On non-Pixel phones, a default cardboard value is being used to play in the VR mode. However, on Pixel phone, you either get:
1. "_This Cardboard application is not compatible with Daydream headsets_" error without above code in the AndroidManifest.
2. "_Place your phone into the Daydream headset_" + "_To get started, aim forward and hold the Home button_" message and **cannot continue without paring** with above code in the AndroidManifest

Is there a solution?

**Comment by jdduke** [comment]
Hi @jclova. If you don't have a Daydream headset, and you try to run an app which is *both* Daydream and Cardboard-compatible (as indicated in your manifest), then the app should run without any problems, in Cardboard mode. The "default" headset is Cardboard, on both Pixel and non-Pixel phones.

> "This Cardboard application is not compatible with Daydream headsets"

You'll only see this if you've explicitly paired a Daydream headset, and the app does *not* define DAYDREAM in the manifest.

> "Place your phone into the Daydream headset" 

You'll see this in 2 cases:
  1) You've explicitly paired a Daydream headset, and the app *does* define DAYDREAM in the manifest.
  2) You've paired a Cardboard headset, and the app *only* defines DAYDRAEM in the manifest. In that case, we actually first show a warning saying that the app may not be compatible with your Cardboard headset.

**Comment by jclova** [comment]
@jdduke 
Assuming the app has enabled both Daydream & Cardboard:
```<intent-filter>
<action android:name="activities.PlaybackActivity" />
<category android:name="com.google.intent.category.DAYDREAM" />
<category android:name="com.google.intent.category.CARDBOARD" />
</intent-filter>
```
Steps:
1. Launch the app (from the Pixel phone)
**Result**: OK, plays in the cardboard
2. Launch a daydream app
3. Launch the app (from the Pixel phone)
**Result**: Ask you to insert into daydream viewer. Only way to view in the cardboard is to select settings -> Scan QR code -> Scan a cardboard QR code.

If we could at least select 'default' cardboard option without scanning QR code, then it will be good. However, without having a cardboard without QR code around, you're stuck.

Please let me know if I am only seeing this issue.

**Comment by jdduke** [comment]
> However, without having a cardboard without QR code around, you're stuck.

Are you asking this from a development perspective? Or from a regular user's perspective? All (or nearly all) Cardboard devices have a QR code embedded on the device, so this shouldn't really be a problem for most users.

If you're just talking about the difficulty of switching back and forth for development, there are plenty of Cardboard QR codes on the internet you could use. Alternatively, you can clear the app cache/data for Google VR Services. We might consider adding a "shortcut" default option, as you suggested, though we haven't really seen the need so far.

**Comment by jakemharris** [comment]
I'm having the same issue. I have an augmented reality application and I'm using cardboard for head tracking to only show my AR when looking a certain direction and then just load camera view. For some reason, only with pixel phones, it wont launch this activity without paring daydream. IT works fine like pokemon go for all phones EXCEPT the pixel. I get "This Cardboard application is not compatible with Daydream headsets". I have updated the manifest to include:
 <action android:name="activities.PlaybackActivity" />
<category android:name="com.google.intent.category.DAYDREAM" />
<category android:name="com.google.intent.category.CARDBOARD" />
</intent-filter>
however, now it wants to pare a daydream headset and tries to force daydream when all I want to do  is show the camera view with my AR. Again, all other phones and devices work perfectly like pokemon go without any problems. Its just the Pixel phones :(

**Comment by jdduke** [comment]
Hi @jakemharris, can I ask which API you're using for your AR app? Are you using GvrView? Or GvrLayout? If you don't need stereo/VR capabilities, try calling "setStereoModeEnabled(false)" on GvrView or GvrLayout (whichever one you're using).

**Comment by hiwarren** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.test"
    android:installLocation="preferExternal"
    android:versionCode="1"
    android:versionName="1.0">

    <supports-screens
        android:anyDensity="true"
        android:largeScreens="true"
        android:normalScreens="true"
        android:smallScreens="true"
        android:xlargeScreens="true" />
    <uses-feature
        android:name="android.software.vr.mode"
        android:required="true" />

    <application
        android:banner="@drawable/app_banner"
        android:icon="@drawable/app_icon"
        android:isGame="false"
        android:theme="@style/AppTheme"
        android:label="@string/app_name"
       >
        <activity android:name=".MainActivity"
            android:theme="@style/UnityThemeSelector"
            android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale|layoutDirection"
            android:enableVrMode="@string/gvr_vr_mode_component"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:resizeableActivity="false"
            android:screenOrientation="landscape">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
                <category android:name="com.google.intent.category.DAYDREAM" />
            </intent-filter>
        </activity>
        <activity
            android:theme="@style/UnityThemeSelector"
            android:name="net.hocheng.dist.unity.UnityPlayerActivity"
            android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale|layoutDirection"
            android:enableVrMode="@string/gvr_vr_mode_component"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:resizeableActivity="false"
            android:screenOrientation="landscape">
            <intent-filter>
                
                
                <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
                <category android:name="com.google.intent.category.DAYDREAM" />
            </intent-filter>

            <meta-data
                android:name="unityplayer.UnityActivity"
                android:value="true" />
            <meta-data
                android:name="com.google.android.vr.icon"
                android:resource="@drawable/vr_icon_front" />
            <meta-data
                android:name="com.google.android.vr.icon_background"
                android:resource="@drawable/vr_icon_back" />
        </activity>

        <meta-data
            android:name="unityplayer.SkipPermissionsDialog"
            android:value="true" />
        <meta-data
            android:name="unity.build-id"
            android:value="02b1f859-f049-41b7-9e5a-fef7ed31f2b8" />
        <meta-data
            android:name="unity.splash-mode"
            android:value="0" />
        <meta-data
            android:name="unity.splash-enable"
            android:value="False" />
    </application>
    <uses-feature android:name="android.software.leanback" android:required="false" />
    <uses-sdk
        android:minSdkVersion="24"
        android:targetSdkVersion="26" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-feature android:glEsVersion="0x00020000" />
    <uses-feature
        android:name="android.hardware.vulkan"
        android:required="false" />
    <uses-feature android:name="android.hardware.vr.high_performance" />

    <uses-permission android:name="android.permission.INTERNET" />

    <uses-feature
        android:name="android.hardware.touchscreen"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.touchscreen.multitouch"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.touchscreen.multitouch.distinct"
        android:required="false" />
</manifest>

**Comment by hiwarren** [comment]
Intent intent = new Intent( MainActivity.this, UnityPlayerActivity.class);
 startActivity(intent);

I have the same problem.
