### ISSUE TITLE
Support for VertecDisplacementCorrection

### ISSUE THREAD

**Issue by Consti10** [googlevr/gvr-android-sdk#296]
There is little or no information available about how "DistortOffscreenFramebufferToScreen()" actually works. However, I would assume it renders the OffscreenFramebuffer as a Texture onto a distortet mesh, when AsyncReprojection is enabled it translates the mesh a little bit before Rendering to match the newest Head Position, and with ScanlineRacing enabled it renders the meshes directely into the frontbuffer carefully timed with vsync. This encapsulates a lot of difficult tasks in one function, which makes it verry easy to use but doesn't let you optimize your code to your specific vr app. Imagine an app that already handles the distortionCorrection in the vertexShader to increase performance, but also wants to reduce latency further by rendering to the frontBuffer. There is currently no way to achieve this, because there's not enough info available about how to render to the frontBuffer on Android. Are you going to openSource the gvr_api code, or at least provide lower-level functions to it,  especially rendering to the FrontBuffer on Android Devices that support it ?

**Comment by nathanmartz** [comment]
Your explanation of how that function behaves in Daydream mode is correct. However, to get below 20ms motion-to-photon latency you actually have to have both async reprojection and scanline racing. Vertex shader distortion, although a great technique for Cardboard apps, isn't compatible with async reprojection. Given that vertex shader distortion + scanline racing won't get you low enough latency to be a Daydream application we don't expose and API that enables that combination.
