### ISSUE TITLE
Building with Nsight Tegra for Visual Studio instead of Android Studio?

### ISSUE THREAD

**Issue by gouletr** [googlevr/gvr-android-sdk#297]
Hi all,

Thanks for the nice SDK, really appreciate this effort and where it is going.

Our engine uses Nsight Tegra for Visual Studio to support the Android platform, and its been working great for us so far. It is currently configured to package with Gradle. 99% of the engine code is in C++ (NDK), with a very thin layer of Java for the bootstrap with Android system.

Usually, linking with 3rd party API is pretty trivial, only requiring us to link with additional `.so` files. In the case of GVR, it seems we only need to link with `libgvr.so` and `libgvr_audio.so`, if I am not mistaken? But there is also this `common_library.aar` file which we must import/link with, correct?

Talking with the Nvidia engineers, they suggested we could import `common_library.aar` by adding the following to our `build.gradle` file:
```
dependencies {
    compile files('/libs/common_library.aar')
}
```

* Is this sufficient?
* Do we need to care about the other `.aar` files under the libraries folder, if we only build native?

Thanks!

**Comment by sigmaxipi** [comment]
The common.aar contains Java code and resources used by the NDK so it will need to be linked into your project. Your suggested `build.gradle` changes to include `common.aar` should work. However, I think your syntax is slightly off. I was using

```
dependencies {
    compile (name: "audio", ext: "aar")
    compile (name: "base", ext: "aar")
    compile (name: "common", ext: "aar")

    compile 'com.google.protobuf.nano:protobuf-javanano:3.1.0'
}
```
in the module's `build.gradle` and

```
allprojects {
    repositories {
        jcenter()

        // Location of the .aar files for the SDK
        flatDir {
            dir "${project.rootDir}/libraries"
        }
    }
}
```
in the root `build.gradle` to get the module to depend on the .aar.

In the next release, we're consolidating the NDK & SDK build systems so the exact way to include the GVR NDK in your own project will change, but what you're doing should work for now.

**Comment by gouletr** [comment]
@sigmaxipi Thanks for the reply. I'm confused a little, can you confirm if I still need to link with:

https://github.com/googlevr/gvr-android-sdk/blob/master/ndk/lib/android_arm/libgvr.so

**Comment by gouletr** [comment]
Also, forgot to mention, now when I unpack my packaged `.apk` app, I now see this in the `/lib/armeabi-v7a` folder:
```
libgvr.so
libgvr_audio.so
libgvrbase.so
libmain_android.so
libvraudio_engine.so
```
is that correct, missing anything? I'm asking because now that we _believe_ we link properly with those `.aar` files, we get an instant crash upon loading the app stating that it can't load `libmain_android.so`, which worked fine before we link with GVR.

**Comment by sigmaxipi** [comment]
You should only have `libgvr.so` and `libgvr_audio.so` in your APK along with your own app's library. Those are the two NDK libraries. The other two libraries are for the SDK and come in via `base.aar` and `audio.aar` which you don't need in your NDK app. In the next GVR release, we'll merge the NDK & SDK to avoid this confusion. You should avoid everything outside the `ndk/` directory in this repository for now since those are part of the SDK.

You'll need to link against `gvr` and `gvr_audio` in order to get your app's own native code to compile and link successfully: https://github.com/googlevr/gvr-android-sdk/blob/master/ndk/demos/treasurehunt/app/build.gradle#L29. And you'll need `ndk/lib/common_library.aar` to get the NDK-specific Java code. Use `ndk/demos/treasurehunt/` as a starting point.

The error caused when loading `libmain_android.so` might be due to having multiple architectures in your APK. Do you have armeabi and arm64 in your APK?

**Comment by gouletr** [comment]
@sigmaxipi ok thanks for clarifying, I was indeed importing files from the `libraries` folder. Now I only link with `ndk/lib/android_arm/libgvr.so` and `ndk/lib/android_arm/libgvr_audio.so`, and gradle is only including `ndk/lib/common_libraries.aar`.

Now I verified the content of the `.apk` and I only see one folder under `lib` named `armeabi-v7a`, which now only contains `libgvr.so`, `libgvr_audio.so` and `libmain_android.so`.

But I still get the same crash, logcat only reporting:
```
I art     : Late-enabling -Xcheck:jni
W ActivityThread: Application com.autodesk.stingray is waiting for the debugger on port 8100...
I System.out: Sending WAIT chunk
I art     : Debugger is active
I System.out: Debugger has connected
I System.out: waiting for debugger to settle...
I System.out: waiting for debugger to settle...
I System.out: waiting for debugger to settle...
I System.out: waiting for debugger to settle...
I System.out: waiting for debugger to settle...
I System.out: waiting for debugger to settle...
I System.out: waiting for debugger to settle...
I System.out: debugger has settled (1403)
I art     : Background sticky concurrent mark sweep GC freed 3231(167KB) AllocSpace objects, 0(0B) LOS objects, 67% free, 414KB/1285KB, paused 16.352ms total 138.398ms
I Stingray: [Activity] Starts Stingray with file server host
D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app/com.autodesk.stingray-2/lib/arm/libmain_android.so
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.autodesk.stingray, PID: 11202
E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.autodesk.stingray/com.autodesk.StingrayActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/com.autodesk.stingray-2/lib/arm/libmain_android.so
E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2518)
E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5460)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:182)
E AndroidRuntime: 	at com.autodesk.StingrayActivity.onCreate(StingrayActivity.java:23)
E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6237)
E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
E AndroidRuntime: 	... 9 more
```

**Comment by gouletr** [comment]
Ah I found the issue! Sorry for the noise, I'm still very new to Android development. I was just missing this in my Activity:

```
static {
	System.loadLibrary("gvr");
	System.loadLibrary("gvr_audio");
}
```

Thanks for all the help!
