### ISSUE TITLE
Feature request: VrVideoView controls in stereo mode

### ISSUE THREAD

**Issue by enginegl** [googlevr/gvr-android-sdk#298]
At present time we have no access to VrVideoView's StereoRenderer. How can we create custom video controls for VrVideoView like YouTube does?
Any plans for future releases?

![YouTube screenshot](https://cloud.githubusercontent.com/assets/3976062/20525786/b5a9c12c-b0c9-11e6-8c04-814e0b434a3f.jpg)

Thanks.

**Comment by nathanmartz** [comment]
If you want a custom player you need to build it on top of the lower level GVRView.
