### ISSUE TITLE
android.view.InflateException: Binary XML file line #44: Error inflating class com.google.vr.sdk.widgets.video.VrVideoView

### ISSUE THREAD

**Issue by vadimneta** [googlevr/gvr-android-sdk#299]
Hello,
I get error while using VR

android.view.InflateException: Binary XML file line #44: Error inflating class com.google.vr.sdk.widgets.video.VrVideoView

This is my Layout:

<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true">

    <LinearLayout
        android:layout_width="match_parent"
        android:orientation="vertical"
        android:layout_height="wrap_content">
    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/gorilla_info"
        android:layout_marginTop="@dimen/activity_vertical_margin"
        android:layout_marginStart="@dimen/activity_horizontal_margin"
        android:layout_marginBottom="@dimen/activity_vertical_margin"
        android:id="@+id/textView" />

   

        <com.google.vr.sdk.widgets.video.VrVideoView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:scrollbars="none"
            android:layout_height="250dip"/>

        
        <SeekBar
            android:id="@+id/seek_bar"
            style="?android:attr/progressBarStyleHorizontal"
            android:layout_height="32dp"
            android:layout_width="fill_parent"/>
        <TextView
            android:id="@+id/status_text"
            android:text="Loading Video..."
            android:layout_height="wrap_content"
            android:layout_width="fill_parent"
            android:textSize="12sp"
            android:paddingStart="32dp"
            android:paddingEnd="32dp"/>

       
    </LinearLayout>
</ScrollView>

This  is my Build.gradle (Module: app):

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.google.devrel.vrviewapp"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            ndk {
                abiFilters "armeabi", "armeabi-v7a", "x86"
            }

        }
    }
}

dependencies {
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'

    compile project(':gvr-android-sdk/libraries:common')
    compile project(':gvr-android-sdk/libraries:commonwidget')
    compile project(':gvr-android-sdk/libraries:panowidget')
    compile project(':gvr-android-sdk/libraries:videowidget')

    compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
}

I'ts failed on all devices
What's the problem?

Thanks!

**Comment by esseak** [comment]
Hi @vadimneta 
I got same error when I start a new project. Then I try create a VrVideoView programmatically I get more error details,"not found com.google.android.exoplayer", so I add dependency compile 'com.google.android.exoplayer:exoplayer:r1.5.10' as same as google's vr sdk samples in my Build.gradle file and then VrVideoView show in my android phone.
It works for me.

**Comment by vadimneta** [comment]
Thank you very much ,
It did the trick!
It works!
