### ISSUE TITLE
any api to bypass head tracking?

### ISSUE THREAD

**Issue by weicui1** [googlevr/gvr-android-sdk#302]
GoogleVr is so cool even being used as normal 360 photo viewer.

Is it possible user only view the photo by touch? Is any existing api can be called before loading ,then the sensorEvent can be ignored or not register the listener for sensor?

Seems there was similar question ,but I can not find the answer.

Thanks!

**Comment by jdduke** [comment]
Hi @weicui1, can you be more specific about which API you're using? Are you using the VrPanoramaView? Or GvrView?

**Comment by weicui1** [comment]
Hi, I was using VrPanoramaView. And just wonder if it can be used as some normal 360 imageviewer widget in android apps. For example, being set some initial viewpoint and user can only adjust viewpoint via touch and drag on picture. thanks

**Comment by dav-cz** [comment]
Thanks for the feedback. 
Unless there's a massive demand for this feature, I'm afraid we'll have to say no to this to keep our API surface focused on VR, which is our primary use case. 
The embedded rendering mode is there to give users a preview of what the VR mode is. If we provide an option to disable sensor tracking, then our library starts to become a standard, generic photo viewer library, and clients will gradually want more and more features that go with that assumption. Which would then result in less time for us to implement truly VR oriented features. Hope you understand!
