### ISSUE TITLE
How can I download older SDK versions fo google cardboard?

### ISSUE THREAD

**Issue by sunjinbo** [googlevr/gvr-android-sdk#303]
Since v0.8.0, Google VR SDK for Android renamed its APIs and did some big changes, for porting my codes easily and quickly, I need to find some older sdk versions, such as v0.7.0, v0.6.0 or more ahead. But after searching the tags of googlevr/gvr-android-sdk, I can't find anyone. Could you give me some help how to find them from Github? Thank you!

**Comment by sigmaxipi** [comment]
We refactored the location of .aars for .8, but you can always see the full repo history at https://github.com/googlevr/gvr-android-sdk/commits/master. The .6 release is at https://github.com/googlevr/gvr-android-sdk/commit/7fa8fc70fc7434938b09dea5df25465a610b70ef and the .7 release is at https://github.com/googlevr/gvr-android-sdk/commit/6f712333b790f2fb250c854d923da474d47d0558.
