### ISSUE TITLE
 The black screen will flash, new VrPanoramaView add to framelayout

### ISSUE THREAD

**Issue by DeloDuan** [googlevr/gvr-android-sdk#304]
How can we not flash？

**Comment by dav-cz** [comment]
Please reopen with clear instructions on how to reproduce this.

**Comment by sharukhmohammed** [comment]
I have the same issue, I have a Fragment with VrPanoramaView as a background. Screen flashes and it's either black or white (Black for `onResume or redrawing` & White for 
`Bitmap bitmap = Bitmap.createBitmap(containerView.getWidth(),containerView.getHeight(),
Bitmap.Config.ARGB_8888);
        Canvas c = new Canvas(bitmap);
        containerView.draw(c);`
