### ISSUE TITLE
Cardboard, Qr code, Lenovo Vibe Z2 Pro (K920)

### ISSUE THREAD

**Issue by Borys637** [googlevr/gvr-android-sdk#305]
Throughout the week, I'm trying to create QrCode program Cardboard. All action strictly according to instructions. And so, that's when you set up the data: Screen to lens distance (mm) -50, Inter-lens distance (mm)-60, Screen vertical alignment- center. The result is two large screens, as it is written in the instructions.  These data are the majority of users. I get the code. But after scanning the code on the phone screen I see two very small windows in the center bottom of the screen. Other phone model works for me very well. Cause?
I compared the data of my phone screen and similar others. There is a difference.
I concluded that the program did not take into account this Cardboard phone model, so the code generation it right on the screen, and when reading the code - it's different.
Experimentally, I made  settings. It worked, but the numbers are not really great at setting. Screen to lens distance (mm) -150, Inter-lens distance (mm)-220, Screen vertical alignment- center.
Someone already had similar problems? What decision was made?
Borys, Ukraine, Uzhgorod.

**Comment by jdduke** [comment]
Hi @Borys637 , did you find a solution to your problem?

**Comment by Borys637** [comment]
Hello! I did not expect that someone is interested in my problem ...)
The solution to my problem came after many trials and tests of similar phones firmware.
The problem is in the phone Lenovo Vibe Z2 Pro (K920). The phone is registered in the data error screen resolution. Screen resolution 1440 * 2560 DPI. The pixel density - 490 DPI. xdpi / ydpi - 160/160. It is not right! Therefore, when I first start the program, I honestly pointed cardboard 490 DPI. Adjust the screen was correct, but after reading Qr code I see two tiny screen ..... and should be something that I set up. Then again, I installed the program and introduced a 160 DPI. Now everything has turned out well. When setting up or after setting up the same screen.
If I try to contact the technical support for Lenovo, then this phone is already out of production and I probably no help (((...
My friend  had the same problem with the phone Zte z7max 5,5 fhd.  xdpi / ydpi - 403/160. It is impossible to create a Qr code.
In principle, such a lot of options and I think, that may Cardboard program developers should review the algorithm coding .....

**Comment by jdduke** [comment]
Yeah, there are a number of devices that misreport their DPI, which can result in incorrect rendering at runtime. Sometimes it's only slightly off, but other devices actually override the native display resolution, while still reporting the native DPI.

I'll see if we can add these devices to our DPI override whitelist.

**Comment by Borys637** [comment]
I do not quite understand the last - "I'll see if we can add these devices
to our DPI override whitelist."



2016-12-15 20:24 GMT+02:00 Jared Duke <notifications@github.com>:

**Comment by jdduke** [comment]
There are a number of devices which misreport their DPI, and we have an internal whitelist we use to "fix" the DPI.

**Comment by Borys637** [comment]
So, the problem is solved with a DPI. https://forum.xda-developers.com/k920
  .... and everything was working as it is necessary!
https://forum.xda-developers.com/k920/development/rom-cyanogenmod-14-1-t3488879
.

2017-01-14 0:50 GMT+02:00 Jared Duke <notifications@github.com>:
