### ISSUE TITLE
Only working with fullscreen mode in some contexts

### ISSUE THREAD

**Issue by joaocraveiro** [googlevr/gvr-android-sdk#307]
When using a camera view or a screen recording app the VrVideoView only works if I go into fullscreen mode (otherwise stays transparent). I guess there are shared resources that are only being requested when going into fullscreen. Any ideas on how to solve/force this?

**Comment by sigmaxipi** [comment]
This complex functionality is beyond the scope of the VrView widgets. You'll need to develop a custom app using https://github.com/googlevr/gvr-android-sdk/issues/510 as a starting point to add more functionality.
