### ISSUE TITLE
How to display or hide the vignette on VR mode with the latest cardboard SDK?

### ISSUE THREAD

**Issue by sunjinbo** [googlevr/gvr-android-sdk#310]
Old cardboard SDK has CardboardView.setVignetteEnabled() API to display or hide the vignette on VR mode, but I can't anymore find it in GvrView class, what is the alternate API for it?

**Comment by nathanmartz** [comment]
That API doesn't exist anymore. The vignette enables performance optimizations so you don't want to disable it ever.
