### ISSUE TITLE
Daydream official controller model asset

### ISSUE THREAD

**Issue by gpx1000** [googlevr/gvr-android-sdk#311]
I found them in the Unreal SDK, however, it would be nice to have the ability to actually adhere to the design recommendations using just the ndk in gvr-android-sdk: 
https://developers.google.com/vr/distribute/daydream/design-requirements#UX-C1

**Comment by sigmaxipi** [comment]
Thanks for the note. You can also get the model from the [Unity repo](https://github.com/googlevr/gvr-unity-sdk/tree/master/GoogleVR/Models) but we'll add it to the assets directory of this repo.

**Comment by dthian** [comment]
Just a quick follow up - are the controller assets available yet for the Android SDK? I've been looking around through the Android documentation but can't seem to find one. If not, is there a rough time frame date of when they would be made available? And finally, would they be available in Obj formats as well? Thanks!

**Comment by sigmaxipi** [comment]
You should use the assets in the [Unity repo](https://github.com/googlevr/gvr-unity-sdk/tree/master/GoogleVR) for now. I will add those assets to this repo in the future. The files are C4D & FBX models with PNG textures so most modeling tools will be able to convert them to OBJ.

**Comment by sigmaxipi** [comment]
FBX model at https://github.com/googlevr/gvr-android-sdk/tree/master/assets/controller
