### ISSUE TITLE
Unable to switch to "mono" mode using the NDK/GvrLayout

### ISSUE THREAD

**Issue by achuvm** [googlevr/gvr-android-sdk#316]
Hi,

I'm trying to use the GVR NDK/GvrLayout to build our application and there doesn't seem to be a way to switch from stereo/vr mode to mono mode.

The SDK has GvrView.getStereoModeEnabled() which sounds like it will do what I want, but there doesn't seem to be a way to do it using the NDK/GvrLayout.

Will this omission be included in a future release?

Thanks,

**Comment by jdduke** [comment]
Hi @achuvm, is this for a Daydream-compatible app? Or just a generic Cardboard app?

**Comment by achuvm** [comment]
Hi @jdduke this is for an app we hope will support both. Thanks,

**Comment by achuvm** [comment]
Hi, is there any update on this issue?

**Comment by jdduke** [comment]
For now, can you try using GvrLayout.setStereoModeEnabled()? That will effectively disable the UI layer and other Daydream/VR-specific features. However, you may still run into issues if you enable async reprojection and then try to render directly to your Surface while in mono mode.

**Comment by achuvm** [comment]
Hi @jdduke, the issue is that GvrLayout (from the NDK) doesn't have a setStereoModeEnabled() method which we can call.

The SDK uses the GvrView which does have a setStereoModeEnabled() method, but we're using the NDK rather than the SDK.

**Comment by jdduke** [comment]
GvrLayout.setStereoModeEnabled is a hidden method (i.e., you can call it, but it's undocumented), which is why I suggest it only with reservation, to see if it might meet your needs. If there is sufficient demand, we may standardize it and make it part of the public API.

**Comment by achuvm** [comment]
Ahh, found it. We were using the 1.02.0 version of the SDK which didnt have it. Upgraded to the 1.10.0 version of the SDK and I see it now. Thanks!
