### ISSUE TITLE
Using VrVideoView in a project that already depends on (a different version of) ExoPlayer

### ISSUE THREAD

**Issue by jschm1** [googlevr/gvr-android-sdk#320]
Hi,

I'm trying to include the VrVideoView in a project that already depends on ExoPlayer version 2.0.4 for general video playback purpose.

This results in an inflation exception, when trying to initiate the Activity showing the VrVideoView:
    
    Didn't find class "com.google.android.exoplayer.TrackRenderer"

Supposedly because VrVideoView depends on ExoPlayer version 1.5.10, and Gradle will resolve to the latest version 2.0.4 in my project.

The problem is that my implementation around ExoPlayer (for general video playback purpose) won't work with the older version of ExoPlayer which VrVideoView needs, and VrVideoView won't work with the new ExoPlayer version that my project needs.

Using the Gradle feature for excluding transitive dependencies, seems not to be an option here, since it would force VrVideoView to use the new version of ExoPlayer, which is already the case, as a consequence of the Gradle version conflict resolving policy. (Please correct me if I'm wrong, but this is what I am seeing when experimenting with transitive dependence exclusion).

Any idea on how to solve this, is greatly appreciated. Reverting back to the old version 1.5.10 of ExoPlayer in my project (or simply allowing the transitive dependency to pass through) is a last resort, and not preferred.

Would a single jar-with-dependencies version of the VrVideoView module solve this?

Thanks for reading this far.
Cheers.

**Comment by sigmaxipi** [comment]
Exoplayer is supposed to support both v1 & v2 in the same project: https://medium.com/google-exoplayer/exoplayer-2-x-new-package-and-class-names-ef8e1d9ba96

Can you try manually adding ExoPlayer v1 to your project and checking if it gets included in the final set of class files? You can check the list of classes by examining the `MODULE/build/intermediates/.../jars/main.jar` file.

**Comment by jschm1** [comment]
Hi Sigmaxipi, thanks for your reply.

I might be including a wrong Gradle dependency for version 2 of ExoPlayer. It has the same Gradle id and artifact name as version 1 (only version differs):

   compile 'com.google.android.exoplayer:exoplayer:r2.0.4'

VrVideoView uses this version in it's POM file:

   com.google.android.exoplayer:exoplayer:r1.5.10

If I include both, Gradle will simply pick the latest version 2.0.4.
Is there another v2 specific Gradle dependency for ExoPlayer version 2?

When I look under app/build/intermediates/exploded-aar/com.google.android.exoplayer/exoplayer/
there's only one subfolder with "r2.0.4/jars". In this folder, there's a classes.jar with ExoPlayer 2 in it (com.google.android.exoplayer2.*)

I guess it comes down to the Gradle problem I mentioned above, with identical ids and artifact names for V1 and v2?

**Comment by sigmaxipi** [comment]
You'll need to perform some extra steps to get Gradle to include both versions: http://stackoverflow.com/questions/29374885/multiple-version-of-dependencies-in-gradle

I haven't tried this so I'm not sure how well it works with ExoPlayer. If it doesn't work, try opening an issue on the Exoplayer GitHub repo regarding multiple version support.

You can also wait for the next version of the SDK which should have Exoplayer 2.x support: https://github.com/googlevr/gvr-android-sdk/issues/278

**Comment by sigmaxipi** [comment]
After some more experimenting, I wasn't able to get Gradle to pull in both versions of Exoplayer. You can check with the Exoplayer team if they have a workaround or wait for https://github.com/googlevr/gvr-android-sdk/issues/278

**Comment by jschm1** [comment]
Alright, thanks for heads up!
