### ISSUE TITLE
How to get player status with using VrVideoView?

### ISSUE THREAD

**Issue by oscchun** [googlevr/gvr-android-sdk#321]
Hi,

i making my application playing VR video or VR streaming with gvr-android-sdk.
but I cannot find any way to know VrVideoView status(playing, paused, etc,..).
anybody knows save my day?

**Comment by AlvaroFalcon** [comment]
Did you solve this?

**Comment by tuananhcwrs** [comment]
I have the same question.
Did you solve it @sechunOH ?
