### ISSUE TITLE
build failed with an exception

### ISSUE THREAD

**Issue by SnowMusic** [googlevr/gvr-android-sdk#322]
Failed to sync Gradle project 'gvr-android-sdk'
Error:Broken pipe.
The Gradle daemon may be trying to use ipv4 instead of ipv6.
<a href="https://sites.google.com/a/android.com/tools/knownissues?pli=1#TOC-Gradle-Sync-Failed:-Broken-Pipe">More info (including workarounds)</a>

**Comment by SnowMusic** [comment]
android studio v2.2.3
jdk1.8
mac os.
gradle 2.14.0

**Comment by sigmaxipi** [comment]
Are you able to build other Gradle-based projects? This looks like a general problem with your machine's build setup.

**Comment by SnowMusic** [comment]
no.only this project

**Comment by SnowMusic** [comment]
i can build other project with success.

**Comment by jdduke** [comment]
Hi @SnowMusic, are you still running into this issue with the latest release?

**Comment by jdduke** [comment]
Happy to re-open with additional details or if this is still reproducible.
