### ISSUE TITLE
I want to know about the license,Do we need license for this lib.

### ISSUE THREAD

**Issue by prateekjain2104** [googlevr/gvr-android-sdk#324]

**Comment by nathanmartz** [comment]
We can't give legal advice beyond what's in the license file.

**Comment by zilet** [comment]
Want to revisit this one. Is the license the same for the parts of the library that are closed source?

**Comment by jdduke** [comment]
Have a look at the [NOTICE](https://github.com/googlevr/gvr-android-sdk/blob/master/NOTICE) as a complete listing of all licenses for code included in our samples and the binaries for the GVR SDK.
