### ISSUE TITLE
VR Button size

### ISSUE THREAD

**Issue by electmk** [googlevr/gvr-android-sdk#328]
VR Button show very small
https://goo.gl/nXzBDh
Is there any way to change button size ??

**Comment by dav-cz** [comment]
No, and I don't think it's something we're planning to add. 

If you really want to customize things, here are some ways you could explore (untested, non-official, "maybe broken in the future" etc):
1) disable the standard VR button and create your own that you'd place on top of the view
2) or access the current VR button with some view.getChildAt() calls, then call setLayoutParams with your new width, height on it.
