### ISSUE TITLE
Is it possible to split the player & render stuff?

### ISSUE THREAD

**Issue by b95505017** [googlevr/gvr-android-sdk#332]
If we have our player e.g. MediaPlayer, ExoPlayer (v1 or v2), or any custom player which has something like `setSurface` API. It would be nice if GVR handles only the rendering stuff. Especially if our player is put in the Service.

This concept is pretty much like this project:
https://github.com/ashqal/MD360Player4Android

**Comment by xieqiupeng** [comment]
As a follow up.

**Comment by jdduke** [comment]
Hi @b95505017, we'll be release a video player sample in the next SDK release, which shows how to use the [low-level video viewport API](https://developers.google.com/vr/android/ndk/gvr-ndk-walkthrough#using_video_viewports). This is particularly relevant if you'd like to play *protected* content, though the API is functional only on Daydream-ready phones.

If you simply want to inject a Surface into your scene, you might try using [GvrView](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView) + drawing a [SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture.html)-backed GL quad.

**Comment by sigmaxipi** [comment]
Consider using the Video360 sample as a starting point. It uses Android basic MediaPlayer, but you can swap that out of any custom media player that renders to a Surface. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
