### ISSUE TITLE
Persistent camera drift after OnPause -> OnResume

### ISSUE THREAD

**Issue by bri-bri** [googlevr/gvr-android-sdk#335]
This bug appears to have been introduced in version 1.0.1. It is reproducible in 1.0.3 and 1.10.0 as well.

Any time an activity is resumed after being paused, the view will start to drift at a variable speed in a variable direction (though it's usually primarily horizontal and rarely with rotation) upon OnResume. This is reproducible every time I minimize the app or switch activities - on all phones I've tested on. Minimizing and reopening the TreasureHunt demo is the easiest way to preview this bug.

I've been unable to fix the issue after a number of efforts to recenter the view, destroy and reinitialize, or reset renderers. If the GvrActivity OnPause method is skipped however, this doesn't happen.

**Comment by Fenchelbach** [comment]
Have you found a solution or a workaround yet?

**Comment by jdduke** [comment]
@bri-bri just to be clear, are you saying this drift is *not* present in the 1.0.0 release? Or the 0.9.0 release?

Also, could you please add more details about your setup, e.g., phone model, Android build version, etc...? And do you experience the same drift in the SDK/NDK samples? Thanks.

**Comment by jdduke** [comment]
Sorry, that last comment was, do you experience the same drift in *all* the SDK/NDK samples. Also, are you using a Daydream headset? Or a Cardboard headset?

**Comment by SoumyaBasheer** [comment]
I have the same issue of Persistent camera drift after OnPause -> OnResume as @bri-bri  specified.
I have used 1.10.0 version.I have tested in Galaxy S6,note 3 ,Nexus.I have the same issue in  TreasureHunt sample.Does any other faces the same issue?Have any solutions?

**Comment by SoumyaBasheer** [comment]
@jdduke I am experiancing this in TreasureHuntSample which  extends GvrActivity and implements StereoRenderer

**Comment by SoumyaBasheer** [comment]
@bri-bri Is it fixed?Any update?

**Comment by jdduke** [comment]
@SoumyaBasheer does this issue occur for you with the [1.0.0 SDK release](https://github.com/googlevr/gvr-android-sdk/tree/v1.0.0)?

**Comment by bri-bri** [comment]
Apologies for the delayed response. I have been using 1.0.0 to avoid this issue; but this won't be possible now because of the Daydream publishing requirement to use version 1.10.0+.

The drift doesn't occur for me with the 1.0.0 SDK Release; it only happens on 1.0.1, 1.0.3, and 1.10.0.

I have tested and reproduced on both Galaxy S6 and Galaxy S7 phones in a cardboard viewer. I've reproduced with the SDK/NDK TreasureHunt demo, as well as in my own Native Android App, and with the Unity GoogleVR Demo scenes built for android.

**Comment by SoumyaBasheer** [comment]
@jdduke I have checked  1.0.0 SDK release TreasureHunt  sample..the drift does not occur for it.but as @bri-bri  specified have to use 1.10.0 for Daydream publishing requirement

**Comment by jdduke** [comment]
Thanks for the update, narrowing the regression range between 1.0.0 and 1.0.1 is very helpful. We're looking into this internally, and will post an update with our findings.

**Comment by koubiak** [comment]
Hi,

I just wanted to let you know that we landed a partial fix in 1.20 which
should mitigate the issue.  The problem should be fully fix in the
following release.

I am keeping the issue open for the moment.
Thanks again for bringing this to our attention.
Pierre

**Comment by jdduke** [comment]
A great number of tracking-related fixes have gone into our tracking pipeline in the past year, thanks for bringing this to our attention.
