### ISSUE TITLE
Controller emulator cannot connect to Nexus 6P

### ISSUE THREAD

**Issue by Cbaoj** [googlevr/gvr-android-sdk#340]
I followed the guide https://developers.google.com/vr/daydream/controller-emulator. Every step seems perfectly followed but my controller phone always shows "Waiting for connection" (it's a 5.0 Android). My daydream phone is Nexus 6P. Since 6P is not an official day-dream ready phone, is it possible it's no longer supported or is it even blocked by SDK/VR service?   Would like to hear your advice if I should try more times or switch to a Pixel immediately.

**Comment by jdduke** [comment]
In theory the 6P should still work properly with the emulator, however, the controller+emulator path is not officially supported (or tested) on pre-N devices. Can you try upgrading your 6P to Android Nougat (7.0+) and get back to us?

**Comment by Cbaoj** [comment]
Thanks for the reply.  the Nexus6P is running image 7.0.0 (NBD91K) actually.

**Comment by jdduke** [comment]
Hey @Cbaoj , could you try again with the latest (1.40.0) emulator APK, and the latest version of Google VR Services? Thanks.

**Comment by jdduke** [comment]
Closing without further feedback or error logs.
