### ISSUE TITLE
Guidance on Controller Arm Model

### ISSUE THREAD

**Issue by dthian** [googlevr/gvr-android-sdk#341]
Hi, i need some guidance on how to implement an Arm model for the Daydream controller as required by: https://developers.google.com/vr/distribute/daydream/design-requirements#UX-C1. Apologies if this is the wrong place for such a question.

Background / Problem:
I'm trying to develop a daydream application with the Android NDK with controller interactions for the Pixel, using ControllerApi from references like [1]. However, there doesn't seem to be any GVR Arm Model helper class we can use in the Android Daydream SDK / NDK, nor is there any documentation guidance on Daydream's SDK documentation site. 

As such, my questions are:
1) Is there a GVR Arm Model helper class, or is this something that developers would implement themselves individually? If the latter, is there documentation on how this can be done?
2) If we do implement it ourselves, could we simplify the problem by assuming:
- A fixed point for the Elbow joint in absolute space (an assumed Vector3f position)
- Forearm and Hand Length
So as to then calculate the controller location / rotation based on the rotation around the wrist + Elbow? Or is there a separate recommended approach?

[1] - https://developers.google.com/vr/android/ndk/reference/group/controller#gvr_controller_state_create

**Comment by gpx1000** [comment]
I just finished implementing an arm model.  I took heavily from the implementation that is in Unreal daydream sdk.
If you look at UpdateFromTorso and UpdatefromController functions in their Unreal or Unity SDK's you'll see how they're doing it.  It's actually a really simple system that uses the two known quaternions (head view direction and controller direction) and assumes positions exactly as you'd expect (rotate + translate).

**Comment by jdduke** [comment]
Hi @dthian, thanks for the feedback. We're hoping to consolidate and standardize our arm model as part of the public GVR SDK/NDK, though we don't have a definitive timeline for releasing this.

The API wasn't included with the initial 1.0 launch as we didn't feel like we'd perfected the implementation, and wanted to get some initial feedback from Unity/Unreal developers before pushing it out more broadly. @gpx1000's suggestion should be a good starting point, and I'll update this thread when we have more to share.

**Comment by svenhenrik** [comment]
I noticed the new (1.20) SDK still doesn't seem to have an arm model, but a place holder for the API?

Any chance you could fill us in a bit on the status? I was hoping the Android SDK would be more on par with the Unity SDK feature wise before the restrictions on the Daydream store were lifted, but now I'm torn between waiting for a proper arm model in the SDK or implementing my own to fill the requirements.

**Comment by jdduke** [comment]
Apologies for the delayed response. We're still working on this, though we don't have a concrete ETA.

**Comment by dthian** [comment]
I've been looking at unity's version at [1]. However, it seems like unity is performing the calculations based on a left-handed coordinate system. Is there a right-handed version of this? If not, what would be the proper way to translate this into a right handed system? Thanks!

[1] - https://github.com/googlevr/gvr-unity-sdk/blob/master/GoogleVR/Scripts/Controller/GvrArmModel.cs

**Comment by dthian** [comment]
update: I've found Unreal's GVR model at [1]. And will be giving that a shot as well. This class seems to be following the same coordinate space as the GVR SDK, so that may be a win for right-handed versions.

[1] - https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/Runtime/GoogleVR/GoogleVRController/Source/GoogleVRController/Private/ArmModel/gvr_arm_model.cpp

**Comment by niusounds** [comment]
I have ported arm model to Java from Unreal's C++!
https://gist.github.com/niusounds/ceaa9034a4e8f62902de1ab654b180a3

**Comment by svenhenrik** [comment]
Great work niusounds! A question before I try integrating it: I see that you don't use the gyro input, I'm guessing you can't pass acceleration in the update data either? Does it still give a decent result?

**Comment by gpx1000** [comment]
I'm working on a tutorial series that uses both GearVR and Daydream to control a drone from a VR app.  I *just* covered how to do the arm model.  http://www.gpxblog.com/2017/04/build-custom-arm-model-for-vr.html  It is originally taken from the same Unreal C++ code as above.  I extrapolated it a bit and made it also work for the GearVR controller.  Enjoy.

**Comment by nathanmartz** [comment]
gpx1000, thanks for sharing. I think this issue is resolved now.

**Comment by svenhenrik** [comment]
The blog post is very helpful, but it uses the acceleration readings from the controller, which is only available in the NDK library if I'm not mistaken. Any chance we could have methods corresponding to GetAccel and GetGyro in gvr::ControllerState in the Android SDK any time soon?

**Comment by gpx1000** [comment]
It should be a fairly easy process to rewrite the entire thing in Java.  you need to know the current orientation of the controller and the current angular acceleration.  Technically you don't really need the accel, but that makes the resulting arm model not natural in the way it moves.
There are a few problems with this method, it doesn't completely work for all positions of your arm for one. If you need highly accurate tracking, I'd look for adding in other solutions to get 6DOF.  Qualcomm's VR has Leap inbuilt for such capabilities.  I've also had success putting tango phones in hands, as well as Vive tracking.  For most usecases however, this process should work pretty well.

**Comment by svenhenrik** [comment]
Thanks gpx1000, but the problem is that the Java SDK does not have any access methods to get the acceleration from the controller. I could of course include the native library and do a native call to GetAccel(), but it would be nice if it was also exposed in the Controller Java class.

**Comment by jdduke** [comment]
Hey folk, the arm model has seen a good amount of iteration internally, but we've finally converged on something and we should be ready to expose this in the public API within the next release or two. Thanks for your patience.

**Comment by nikhilcheruku12** [comment]
jdduke I was wondering if the controller arm model has been released yet.

I have been using The Google VR SDK for android in conjunction with OpenGL to code my app. I need to use a controller laser pointer to implement some of the functionalities. I have looked at the Google VR SDK for android and there doesn't seem to be any support for this in the API. I know that there is support in the android SDK. Does anyone know how I can implement the controller pointer part with the SDK for android?

WHat do you think is the best way to proceed. Is it possible to integarate unity or unreal code solely for the controller laser pointer part while coding the rest with the gvr-sdk?

**Comment by jdduke** [comment]
The arm model will be included in the upcoming SDK release (in several weeks). This will initially only be exposed through the native controller C API.

**Comment by mgatelabs** [comment]
In the 1.70 release?  So is it just me, or does the new Controller object in java not implement the arm?

**Comment by jdduke** [comment]
@mgatelabs: Yes, due to time constraints the arm model API was released first only as part of the native APIs. We'll be working to add support for the Java APIs as well. Apologies for the hassle.

**Comment by rawnsley** [comment]
@jdduke +1 for Java SDK support ASAP. There's not much sense in mandating the use of an arm model if everyone uses a different model.
