### ISSUE TITLE
I can't see my application on Daydream Library

### ISSUE THREAD

**Issue by mdelacalle** [googlevr/gvr-android-sdk#343]
HI.
I'm trying to develop a Daydream app. I'm using this directive on manifest ->   <category android:name="android.intent.category.DAYDREAM" />

When I'm launch my app the Daydream menu is not launched and I can't find my app on Daydream library menu. If I use the same directive with Cardboard I have no problem and the app is on Cardboard library.

If I deploy Treasure Hunt I have no problem with this.

What I'm doing wrong??

Thanks!!

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="brownietech.com.mapvr">

    <uses-sdk
        android:minSdkVersion="24"
        android:targetSdkVersion="24" />

    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true" />

    
    <uses-permission android:name="android.permission.VIBRATE" />
    
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    
    <uses-feature
        android:name="android.hardware.sensor.accelerometer"
        android:required="true" />
    <uses-feature
        android:name="android.hardware.sensor.gyroscope"
        android:required="true" />

    
    <uses-feature
        android:name="android.software.vr.mode"
        android:required="false" />
    
    <uses-feature
        android:name="android.hardware.vr.high_performance"
        android:required="false" />

    
    <application
        android:name=".GRApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:supportsRtl="true"
        >
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:enableVrMode="@string/gvr_vr_mode_component"
            android:resizeableActivity="false"
            android:theme="@style/VrActivityTheme"
            android:screenOrientation="landscape">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.DAYDREAM" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data android:name="com.google.android.vr.icon"
                android:resource="@drawable/ic_vr_icon" />
        </activity>
    </application>

</manifest>

**Comment by sigmaxipi** [comment]
You need `com.google.intent.category.DAYDREAM` but you have `android.intent.`... in your manifest.

**Comment by mdelacalle** [comment]
OMG!
Thanks!
