### ISSUE TITLE
Is there a way to get real-time sensor value from gvr-android-sdk?

### ISSUE THREAD

**Issue by sunjinbo** [googlevr/gvr-android-sdk#344]
My VR app has a button, I want to develop a feature that this button would moving follow the head tracking, how can I get current real-time sensor value? I can use it to set the position while rendering the button.

**Comment by sigmaxipi** [comment]
Do you just want the head pose? If so see the TreasureHunt samples which use head orientation as input. If you want raw sensor data, you would need to use the standard [Android Sensor API](https://developer.android.com/guide/topics/sensors/sensors_motion.html#sensors-motion-rotate)
