### ISSUE TITLE
Can I get the VrVideoView's source code?

### ISSUE THREAD

**Issue by weiyongbang** [googlevr/gvr-android-sdk#345]
Can I get the VrVideoView's source code?

**Comment by sigmaxipi** [comment]
We're not going to publish the VrView's source code. It has complex internal dependencies on Google code  and crossplatform components so people won't be able to build it.

We are looking at publishing a minimal sample that demonstrates how to create a 360 image & video viewer using the general GVR SDK. This will provide much of the desired VrView functionality but without the dependencies.
