### ISSUE TITLE
Can a seekTo(time) method and a finished callback be added to GVR Audio

### ISSUE THREAD

**Issue by achuvm** [googlevr/gvr-android-sdk#346]
Based on the Android/iOS Audio NDK, I can stop, start and pause audio, but there doesn't seem to be a way to seekTo(time) in the audio API.

Also, adding a finished callback would be helpful for determining when audio has finished playing.

Thanks,

**Comment by jkammerl** [comment]
Thanks for reaching out. Adding seeking support is already on our radar. I also like your suggestion to add a "source finished" callback. I'll discuss it with our team.
