### ISSUE TITLE
Hotspots in Android & iOS

### ISSUE THREAD

**Issue by cuxxie** [googlevr/gvr-android-sdk#349]
Is there any way or API provided to add Hotspots in VR View or Panorama View?
It is already implemented for the Web version. But it doesn't exist in Android or iOS Version.

example for web version: http://googlevr.github.io/vrview/examples/hotspots/

Thanks!

**Comment by dav-cz** [comment]
Thanks for your feedback!
We currently have no plans to do something similar on Android or iOS. It would add a lot of surface to the API and it would only be for panoramas, while most of our usage is on videos.

**Comment by michelePap** [comment]
@dav-cz Has anything changed about adding hotspot?
I started using vrview for the web but i could only use the two default cardboard viewer, so i decided to look at android sdk, but there are no hotspot implementation.

**Comment by dekemega** [comment]
Hi ,
me too i wanna add hotspots to make the navigation between scenes easier ... please add hotspot support

**Comment by MukeshKumarS** [comment]
Hi,
please add hotspot support

**Comment by sigmaxipi** [comment]
The VrView widgets are meant as simple 360 viewers for apps that don't have complex requirements for viewing 360 media. If you want more functionality such as hotspots, consider using the Video360 sample as a starting point. See #510 for more info.

**Comment by munjliew** [comment]
did anyone find an alternative?

**Comment by ganico** [comment]
@sigmaxipi is there any reference to do this feature on video360?

**Comment by sigmaxipi** [comment]
https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/VrVideoActivity.java#L296 is the code that handles Daydream controller events.  You'll need to replace that code with whatever input mechanism you want. Then have `SceneRenderer.setControllerOrientation` and `SceneRenderer.handleClick` figure out how to map the events to a hotspot. `CanvasQuad.translateClick` is one example that converts from controller orientation to touch events on a floating 2D quad.

**Comment by ganico** [comment]
do I really need to use the VrVideoActivity? or I can apply the same function on VideoActivity since I don't need the Daydream type of view. or is there a function on VideoActivity to get the (x,y,z) coordinates? so I can do some computation something like this (please see attached file) this is what I did on iOS.. i'm trying to replicate it here..
<img width="945" alt="screen shot 2019-02-26 at 09 24 37" src="https://user-images.githubusercontent.com/7714293/53380472-7adb6b80-39a8-11e9-89c1-db1a95cfd4cc.png">

**Comment by sigmaxipi** [comment]
You'll want to listen for touches in `MonoscopicView.onTouch`. That code only tracks drags, but it could be modified to detect taps.

**Comment by ganico** [comment]
yeah!! I saw that already, alright.. So i'll try that part to check the touches.. Thank you so much again for your quick quick response.

**Comment by ganico** [comment]
@sigmaxipi any idea how to convert MonoscopicView.onTouch into world coordinate?

**Comment by andmizi** [comment]
> 嗨，
> 我也想添加热点，使场景之间的导航更容易...请添加热点支持

hi，Do you have a new solution，help me~

**Comment by ikimiler** [comment]
> did anyone find an alternative?

hi，Do you have a new solution，help me~
