### ISSUE TITLE
NDK Audio API - head position

### ISSUE THREAD

**Issue by windbagjacket** [googlevr/gvr-android-sdk#350]
Hi,

In the NDK audio API, is the matrix provided to gvr_audio_set_head_pose supposed to represent rotation _and_ position? I ask because while I can play sounds at different locations relative to the head, I can't move the head position itself - it is stuck at (0,0,0). I do hear the sound change as I rotate my head, but if I multiply my rotation matrix with a translation and pass that to gvr_audio_set_head_pose, there is no change.

The comments in gvr_audio.h suggest there was once separate functions to set the head position and rotation but they are no longer present. Looking at the Java SDK these functions are there too. In the NDK samples the head position doesn't change so I can't check those for reference.

Any ideas?

Thanks!

**Comment by jkammerl** [comment]
Apologies for the confusion. You are correct, it seems our header comments haven't been updated during a recent refactoring of the API. We'll fix this in our next release. In the meantime, please take a look at how the head rotation is applied to the audio engine in the NDK treasure hunt example:
https://github.com/googlevr/gvr-android-sdk/blob/master/samples/ndk-treasurehunt/src/main/jni/treasure_hunt_renderer.cc#L545

Here, the head view matrix is an affine 4x4 transformation matrix which combines a rotation matrix and a translation vector. See also https://en.wikipedia.org/wiki/Affine_transformation
