### ISSUE TITLE
I want my VRPanorama view to stop scrolling when my image finishes instead of showing black 

### ISSUE THREAD

**Issue by asuxus** [googlevr/gvr-android-sdk#352]
![device-2017-01-30-165722](https://cloud.githubusercontent.com/assets/20643396/22421923/b87ae616-e70f-11e6-951f-9c71c5577831.png)

I want my image to scroll only Vertocally just like Facebook without showing Black circle.
This happens when i place my device on desk. When i pick up in front of my eye it shows correct

Thanks in advance

**Comment by sigmaxipi** [comment]
What is the source image that you are using? You need to have an equirectangular projected image that covers the entire sphere. If you use Cardboard camera to capture the image, it won't capture the top and bottom of the sphere so the widget shows black in that area. You can edit the image to replace the black part with whatever content you want.
