### ISSUE TITLE
VrPanoramaView: Fullscreen mode is upside down

### ISSUE THREAD

**Issue by p-fischer** [googlevr/gvr-android-sdk#356]
Steps to reproduce:
- Hold device in reverse landscape mode.
- Start in embedded mode.
- Hit Fullscreen Button

observed:
- Image in fullscreen mode is flipped, gyroscope control is flipped as well, UI controls are correct

Tested on Nexus 5 and Nexus 9

**Comment by sigmaxipi** [comment]
This is fixed now.
