### ISSUE TITLE
Is it possible to use a non-Daydream controller?

### ISSUE THREAD

**Issue by PsycheDoot** [googlevr/gvr-android-sdk#357]
I wanted to prototype an android game using the Unity engine. Normally I use the latest version of unity and have no problems using usb controllers for input reading, however none of my GVR demos have controller support. I assume this is because of the Google VR/Daydream service tie-in. Is it possible to use the GVR sdk and have usb/bluetooth controller support?

**Comment by sigmaxipi** [comment]
In general, you can use any standard Android APIs with GVR including custom usb/bluetooth controllers. Since this is a Unity-specific issue, you should open an issue on the [GVR Unity tracker](https://github.com/googlevr/gvr-unity-sdk/issues).
