### ISSUE TITLE
None of the Sample Apps work

### ISSUE THREAD

**Issue by DCarretero59** [googlevr/gvr-android-sdk#358]
None of the sample applications seem to work, each of them present the following error.

Error:(39, 13) Failed to resolve: com.google.vr:sdk-panowidget:1.20.0

With thir corresponding reference, seems they have not been updated to reflect 1.20.0 change

**Comment by dav-cz** [comment]
Thanks for the report! 
The new v1.20.0 AARs are now correctly pushed to bintray, which should solve this issue. 

Please re-open if that's not the case, thanks again.
