### ISSUE TITLE
Update GVR Viewer Params in VrVideoView

### ISSUE THREAD

**Issue by aarshaw** [googlevr/gvr-android-sdk#359]
I'm trying to update the view based depending on what viewer the user has, after they scan a QR code similar to cardboard app's switch viewer function. 

I'm able to read the params from the QR but I'm not able to update the view based on these. Is there a way to update the viewer params of a VrVideoView? 

I've seen there is the following in VrView, is it possible to implement this in VrVideoView?

    updateGvrViewerParams(GvrViewerParams gvrViewerParams)

**Comment by aarshaw** [comment]
Basically looking for an Android equivalent to `setViewerParamsFromUrl:withCompletion:` from the iOS API

**Comment by keakalamudo** [comment]
+1

**Comment by sigmaxipi** [comment]
Why are you directly updating the viewer params? The VrView widgets have a setting icon that shows up in VR mode and can be used to update the viewer params.

**Comment by aarshaw** [comment]
It's not obvious enough that it's there and what functionality it has.

We want to allow the user to setup the app and configure their viewer params in an onboarding section before they enter VR mode.

**Comment by sigmaxipi** [comment]
Try calling [GvrUiLayout.launchOrInstallGvrApp(this)](https://developers.google.com/vr/android/ndk/jni/reference/com/google/vr/ndk/base/GvrUiLayout.html#launchOrInstallGvrApp(Activity)) inside your Activity. That will mimic clicking on the Settings button and launch the Cardboard Settings or Google VR Settings.

**Comment by sigmaxipi** [comment]
If you want more control of the user experience, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
