### ISSUE TITLE
updating so files from distribution

### ISSUE THREAD

**Issue by gpx1000** [googlevr/gvr-android-sdk#360]
I wanted to point out a bug in the current extractNDK task.  When a new release is made (going from 1.10.0 to 1.20.0) the exractNDK task will believe that it doesn't need to run if it was run on a project before the upgrade.  The reason for this is gradle will detect the outputs of the copy task, discover that they are in the right place and decide the task is up to date.
To fix this, there's two options.
1.) tell gradle that the task is "always" out of date:
outputs.upToDateWhen { false } //can also craft logic here to capture the event of changing version numbers and return that.
2.) delete the files anytime there's a clean:
task deleteGoogleVRNDK(type: Delete) { delete 'pathToSoLibs' }
clean.dependsOn(deleteGoogleVRNDK)

Failing to do something will create a possible state where the so files are not infact updated while the JAR files are.

**Comment by sigmaxipi** [comment]
Thanks for the note. I'll update the build to properly handle clean operations.

**Comment by gpx1000** [comment]
Maybe a better thought so not every full rebuild would require getting the zip files would be to craft a way to only require the task reupdate itself when the md5 sum has changed something like this:
1.) place manifest showing md5sum for ndk libs as an artifact in your maven.
2.) modify the extractNDK task to have one extra line inside the blank closure:
task extractNDK {
outputs.upToDateWhen { 
//compare md5 of local file against one listed in manifest artifact; exercise left for reader.
}
}

It's slightly more work but it would make it so there's no extra unzipping necessary and would model correctly when the outputs are indeed out of date.  It shouldn't really matter for most projects, and honestly this is much easier to do with a plugin to intellij to properly handle the ndk libs inside aars.  But the missing piece is having a MD5 manifest artifact to compare against.

**Comment by sigmaxipi** [comment]
If you can come up with a simple code snippet to do this, I'll add it to the build. I'm used to [blaze](https://bazel.build/) which properly handles caching dependencies so I'm not sure what the best option is in gradle. But I think updating the clean task should be sufficient for now.

**Comment by gpx1000** [comment]
I was considering writing a plugin as I have other projects that face the similar problem of ndk libs inside aar files.  If I do that, I'll open source it and you're welcome to use it.
For now, I'll see if I can come up with some simple gradle to do what I'm talking about sometime tonight or this weekend.  There's many small things that I wish gradle would do out of the box.
Are you in need of any snippets to do the first part? (add md5sum manifest to an artifact that maven can publish) or are you good there?

**Comment by gpx1000** [comment]
Please see pull request #361

**Comment by sigmaxipi** [comment]
Thanks for the alternative solution. However, it's more heavyweight than I would like for the SDK sample. I'm going to go with the option of adding a proper clean task to the main build.gradle file. Other teams might have more complex build systems and I don't want to entangle them with Gradle dependency rules. The proper solution is for the NDK to support .so dependencies in .aars, but this will have to suffice until then.

```
task deleteNdk(type: Delete) {
    delete "${project.rootDir}/libraries/"
}
clean.dependsOn(deleteNdk)
```
