### ISSUE TITLE
Invalid C API in gvr_audio.h

### ISSUE THREAD

**Issue by pbnjay** [googlevr/gvr-android-sdk#363]
These two functions use pass-by-reference in the C API which fails to compile.

    void gvr_audio_set_soundfield_rotation(gvr_audio_context* api,
                                       gvr_audio_source_id soundfield_id,
                                       const gvr_quatf& soundfield_rotation);

    void gvr_audio_set_head_pose(gvr_audio_context* api,
                             const gvr_mat4f& head_pose_matrix);

It appears these can be easily changed to pointers in the headers - my code doesn't crash but I haven't been able to test thoroughly yet. API changes should be OK since any people like me using C would be unable to use these without changes anyway.

**Comment by jdduke** [comment]
Thanks for the feedback @pbnjay. You're absolutely right, that is not valid C and appears to have slipped through the cracks. We'll be sure to fix with the next release. Cheers.
