### ISSUE TITLE
Render 360 video to the screen and save to a file

### ISSUE THREAD

**Issue by jmgirven** [googlevr/gvr-android-sdk#364]
Is it possible to use e.g. a `VrVideoView` to take a 360 degree video file and both render it to the screen for the user to see and save what the user is seeing to a regular (not 360) video file at the same time? I guess `VrVideoView` is too high level for that. I have also looked at the sdk-videoplayer sample, which seems more promising, but doesn't seem to support my Nexus 5X, so I can't play around with it too much.

I was to save the users experience of watching the 360 video for playing back in non-360 players. What steps would you recommend to achieve this?

**Comment by sigmaxipi** [comment]
Are you just trying to record video of the app while it's running? Take a look at [adb screenrecord](https://developer.android.com/studio/command-line/adb.html#screenrecord).

**Comment by jmgirven** [comment]
Thanks, but no, this would be a feature of the product. I feel like I want to write the decoded, visually corrected frames of a 360 video to a surface. Then take one copy of that surface and display it to the screen. And another to write to a file with MediaCodec or similar. Both being responsive to the users position, accelerometer, etc.

**Comment by sigmaxipi** [comment]
This is beyond the design of VrVideoView, but it should still be doable using `adb screenrecord`. If you run the sdk-simplevideowidget sample, enter fullscreen mode, and run `adb screenrecord`, isn't the result what you want?

**Comment by jmgirven** [comment]
I can't run `adb screenrecord` in a production app, on a user I don't knows device, right?

**Comment by sigmaxipi** [comment]
You can run `adb screenrecord` on a production app as long as the phone has debugging enabled. But you won't be able to run in on arbitrary user devices.

Video recording functionality won't be part of the widget's feature set. There are screen recording apps on the Play Store and you can also add this functionality to your app: http://stackoverflow.com/questions/15244009/android-screen-recorder-code-example
