### ISSUE TITLE
Sometime resumeTracking not work.

### ISSUE THREAD

**Issue by dbsGen** [googlevr/gvr-android-sdk#368]
I pause tracking in onStop, and resume it in onStart.

    @Override
    protected void onStart() {
        super.onStart();
        gvrLayout.getGvrApi().resumeTracking();
    }

    @Override
    protected void onStop() {
        super.onStop();
        gvrLayout.getGvrApi().pauseTracking();
    }

But, when I move app to background and resume the app	 several times, the screen will be frozen.
And I move app to background again, it will work fine this time.

And I write this test code, to test it.

    @Override
    public void onBackPressed() {
        gvrLayout.getGvrApi().pauseTracking();
        gvrLayout.getGvrApi().resumeTracking();
    }

Press the back button several times, the screen will be frozen too.

**Comment by koubiak** [comment]
Do you know if rendering is frozen or tracking is frozen? If you have an
animation in your app is it still playing and only the pose does not get
updated?

**Comment by dbsGen** [comment]
@koubiak ,Tracking is frozen,rendering is ok.

**Comment by jdduke** [comment]
Hi @dbsGen, are you still experiencing this issue with the latest SDK? Also, on what Android device (including OS version) did you observe the issue? Thanks.

**Comment by jdduke** [comment]
Closing without further repro steps or details.
