### ISSUE TITLE
starting the application with the phone in portrait results in cube appearing to your right

### ISSUE THREAD

**Issue by fcoulombe** [googlevr/gvr-android-sdk#37]
Basically if you start the application in portrait mode (just holding the phone sideways), i noticed that the world seems to be rotated anywhere between 90 to 180 degrees.

starting the applicaiton in landscape always results in the cube being in front of you but if you start it in portrait... the cube tends to be to your right.

**Comment by dav-cz** [comment]
Should be fixed in v0.8, thanks!
