### ISSUE TITLE
Traqcking is lost

### ISSUE THREAD

**Issue by dvdobrovolskiy** [googlevr/gvr-android-sdk#371]
Sometimes (often, like one of ten times I ran app) it lost tracking so screen is locked in one position and does not respond on device movement or touch events. Restart (not pause and resume) helps and VrVideoView works normally.

PS Android 6.0
compile 'com.google.vr:sdk-videowidget:1.20.0'

**Comment by jdduke** [comment]
Hi @dvdobrovolskiy, any chance you could share a bug report (adb bugreport video_tracking.zip) or some logs which capture the problem? Thanks.
