### ISSUE TITLE
Pull flow address cannot resolve

### ISSUE THREAD

**Issue by KevinWard0910** [googlevr/gvr-android-sdk#372]
In the old play 4096 * 2048 p video on your mobile phone can't get to the url, the same phone and video, VLC player can only broadcast audio above, video interface is black screen

**Comment by sigmaxipi** [comment]
What is the specific URL you are having problems with? Can Exoplayer decode that video format? Try to view it with the Exoplayer sample: https://github.com/google/ExoPlayer
