### ISSUE TITLE
VrVideoView and YouTube

### ISSUE THREAD

**Issue by davidj028** [googlevr/gvr-android-sdk#373]
Are there plans to support YouTube videos with the VrVideoView?

Right now there doesn't appear to be a good way to directly launch a 360/VR/Cardboard YouTube video inside an android app.

If you use the VrVideoView, YouTube URLs do not appear to work with either the FORMAT_DEFAULT or FORMAT_HLS options. If you use the YouTube API, there doesn't appear to be 360/VR/Cardboard support.  You could use an intent to open the video in the YouTube app itself, but there isn't a way to default to Cardboard view, not to mention your forcing the user to leave your app.

Does Google plan to address this?

Thanks!

**Comment by jplgarcia** [comment]
I´d really like to know that. I need to be able to play a vrVideo on my app and do more stuff at the same time!

**Comment by sigmaxipi** [comment]
There's no plans to support directly viewing YouTube videos inside VrView. Using an intent to open YouTube (or YouTube VR for Daydream) are the best options.
