### ISSUE TITLE
Performance reduced popup

### ISSUE THREAD

**Issue by windbagjacket** [googlevr/gvr-android-sdk#374]
While running some VR content I'm seeing "Performance reduced. To cool phone, remove from headset and close app." quite often.

Is there a way to supress this warning - or to prevent the performance nerf?

Thanks.

**Comment by sigmaxipi** [comment]
Is this your app that has the problem? You should should use [sustained performance mode](https://developer.android.com/reference/android/view/Window.html#setSustainedPerformanceMode(boolean)) to reduce the phone's power draw.

**Comment by jdduke** [comment]
Unfortunately, there's no way to explicitly suppress thermal throttling other than reducing the workload of your app. The simplest way is to enable sustained performance mode per @sigmaxip's suggestion, and tuning your app workload accordingly.
