### ISSUE TITLE
onLoadError(String errorMessage) with a null errorMessage

### ISSUE THREAD

**Issue by Lannylanlol** [googlevr/gvr-android-sdk#379]
Hi,
the callback of onLoadError always gives null on String errorMessage, so I can't detect the type of error. There is a way to detect the type of error?
Thanks a lot

**Comment by sigmaxipi** [comment]
Do you see any errors in the log? And what was the media file you were trying to load? Can you load it using Android's built in media viewers or the two sample VrView apps?

**Comment by irajuneau** [comment]
We are also experiencing this issue on 1.80.0. It appears to be triggered by a low level error. Most of the time the video content works, however sometimes it doesn't. It happens with some regularity on a Galaxy Note 4 running 6.0.1 (Samsung-SM-N910V). The content it struggles with can be found @ http://cnnios-f.akamaihd.net/i/cnn/big/360/vr/2017/09/23/egypt-tomb-luxor-discovery_1636224_,960x540_2500,416x240_200,480x270_400,640x360_600,640x360_800,768x432_1500,1280x720_3500,1920x1080_5904,.mp4.csmil/master.m3u8

I have attached an error log as well. It appears to be triggered on the line that begins with 09-25 14:13:11.802 27075-27075/com.cnn.mobile.android.phone.debug E/VrVideoPlayer:

This error only happens in a minority of the time it is called, maybe once every 20 calls or so it will provide this error. However, once it is encountered the first time, it appears that almost every other call to the content will fail after.
[google_issue.log](https://github.com/googlevr/gvr-android-sdk/files/1330423/google_issue.log)

**Comment by jdduke** [comment]
We depend directly on ExoPlayer (https://github.com/google/ExoPlayer) for loading video, and there have been quite a few updates to that library since September. Feel free to re-open the issue if the loading behavior is still flaky.

**Comment by BakytzhanAkzhol** [comment]
Hello, I have small a request to a developers of this library. I have no other way. VrVideoWidget removed in the version @1.9.0. I know it. I still can't get any exception from function onLoadError, when ExoPlayer is crashed and then it send null message to function onLoadError.
Can you add try-catch **NullpointerException** in this code from **VrVideoListener** and **VideoLooperListener**.

```
  public void onLoadError(String errorMessage) {
    
        String var10000 = TAG;
        int var2 = this.hashCode();
        
        try{
        Log.e(var10000, (new StringBuilder(25 + String.valueOf(errorMessage).length())).append(var2).append(".onLoadError: ").append(errorMessage).toString());
        }catch(NullPointerException e){
        e.printstacktrace();
         }
         }
    }
```
