### ISSUE TITLE
Cardboard on Samsung S7 Nougat gives wrong FOV/Viewport

### ISSUE THREAD

**Issue by achuvm** [googlevr/gvr-android-sdk#380]
We're seeing this issue with our app and we're also seeing it with the Within VR and Google Cardboard Demo Apps (see image attached) using the Mattel ViewMaster Cardboard Headset (https://www.amazon.com/View-Master-Virtual-Reality-Starter-Pack/dp/B011EG5HJ2)

We don't have any other non-Daydream Nougat devices to see if this is a general issue with non-Daydream Nougat devices

![within_s7](https://cloud.githubusercontent.com/assets/21074927/23914473/4736c88e-08a3-11e7-807a-24799361ec89.png)
![cardboard_demo_s7](https://cloud.githubusercontent.com/assets/21074927/23914474/47390f18-08a3-11e7-97b5-13ba1cacb47d.png)

**Comment by jdduke** [comment]
By chance, do you have display scaling configured on our S7 (configured in the "Display" section of Android settings)? We've seen some issues related to custom display scaling configurations, and will be rolling out a fix as part of the broader Google VR Services release to all N devices.

**Comment by achuvm** [comment]
Hi Jared,

Thanks! That fixed it for us, the phone was set to 1080p (vs the native 1440p).
