### ISSUE TITLE
Get Coordinates

### ISSUE THREAD

**Issue by s1mar** [googlevr/gvr-android-sdk#381]
Any ideas on how to get the coordinates(yaw,pitch,roll) from a pano image on an onTouch event

**Comment by sigmaxipi** [comment]
You can add a [ROTATION_VECTOR](https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_ROTATION_VECTOR) or similar sensor to your app to record the current orientation. Then you can turn that orientation into yaw, pitch, roll when you need to.

**Comment by sigmaxipi** [comment]
Consider using the Video360 sample as a starting point for building your own pano viewer with custom touch input. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
