### ISSUE TITLE
Noisy output with Audio Surround Renderer API in v1.30.0

### ISSUE THREAD

**Issue by virajkarandikar** [googlevr/gvr-android-sdk#382]
I had written a sample app using Audio Surround Renderer API using v1.20.0 which was playing audio fine for 1st order ambisonic rendering. With v1.30.0 it gives noisy/glitchy audio output. Only change I did in my app is updating the version number of VR SDK dependencies in app's build.gradle from 1.20.0 to 1.30.0.

**Comment by jkammerl** [comment]
Thanks for the report. We'll take a look at this asap.

**Comment by jkammerl** [comment]
Hi, I ran some tests but am not able to reproduce any glitchy output. Could you give us more detailed instructions how to reproduce this issue?

**Comment by virajkarandikar** [comment]
Audio is fine with v1.40 Java API.
