### ISSUE TITLE
Do VrVideoView support HLS's url?

### ISSUE THREAD

**Issue by wangkangmao** [googlevr/gvr-android-sdk#383]

**Comment by wangkangmao** [comment]
Do VrVideoView support HLS?

**Comment by sigmaxipi** [comment]
If you install the simplevideowidget sample, try ` adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity  -d "file:///android_asset/hls/iceland.m3u8" --ei inputFormat 2 --ei inputType 2`

Are you having trouble with HLS videos?

**Comment by wangkangmao** [comment]
@sigmaxipi thanks，has now been resolved
