### ISSUE TITLE
HI,Where to find the old-version cardboard sdk ?

### ISSUE THREAD

**Issue by nicholas-yangding** [googlevr/gvr-android-sdk#384]
i want to review the source about the old-version cardboard sdk, but i find nowhere it placed.So the Q is,
 where to find the olds? 
Any help would be pleased ,thanks~!

**Comment by nicholas-yangding** [comment]
oh,  by the way, this hub only resever the version >= 0.8f,  I want to find the older version <0.8

Thanks!

**Comment by nicholas-yangding** [comment]
anyone could answered me?

**Comment by sigmaxipi** [comment]
You should be able to get it via the [commit history](https://github.com/googlevr/gvr-android-sdk/commits/master).

For example, the Dec 10 2014 commit: https://github.com/googlevr/gvr-android-sdk/commit/22eb99d345e1974171930b8b6e3da1171431fd24

`git log` and `git checkout 22eb99d345e1974171930b8b6e3da1171431fd24` will let you do the same thing on a local repo.
