### ISSUE TITLE
Why is a 50ms prediction offset time used in the samples?

### ISSUE THREAD

**Issue by MortimerGoro** [googlevr/gvr-android-sdk#385]
Hello,

I have a question about prediction time to be used when calling gvr_get_head_space_from_start_space_rotation(). Why is a 50ms value used in the samples? I can't find any documentation about this, only see it as a recommended value. 

For example if in a specific app there is about 4ms delay between calling  gvr_get_head_space_from_start_space_rotation() and gvr_submit_frame() (without vsync) should I use 4ms prediction offset or 50ms offset? why?

Thanks in advance

**Comment by sigmaxipi** [comment]
You also need to account for the time between frame submission and when the rendered image is sent to the physical pixels on the display. +50ms is a good estimate.

**Comment by MortimerGoro** [comment]
Thanks, I thought that physical pixels latency was smaller.
