### ISSUE TITLE
Audio Surround Renderer NDK API outputs corrupt audio

### ISSUE THREAD

**Issue by virajkarandikar** [googlevr/gvr-android-sdk#386]
Hi,

I am using Surround Renderer NDK API (v 1.30.0) in my app. I am creating gvr_audio_surround_context with below properties:
surround_format = GVR_AUDIO_SURROUND_FORMAT_SURROUND_STEREO (1)
num_input_channels = 2
frames_per_processing = 240
sample_rate_hz = 48000

I call AddInterleavedInput() with 240 PCM samples and call GetInterleavedOutput() to get back 240 samples. But the output samples seem corrupt. 1st half samples of the output 240 samples seem proper, but 2nd half is total silence. I believe I am calling the APIs correctly (there is no sample code for NDK usage).

I tried same configuration with Java API and there the output was proper. So I am suspecting something wrong with NDK APIs?

Any guidnace on how to debug/fix this?

**Comment by virajkarandikar** [comment]
@jkammerl Can you please provide some help here?

**Comment by jkammerl** [comment]
The Exoplayer project recently [announced support ](https://medium.com/google-exoplayer/spatial-audio-with-exoplayer-and-gvr-cecb00e9da5f) for the GvrSurroundRenderer API. 
Here's their [integration code](https://github.com/google/ExoPlayer/blob/a9079f67aa031649edfa7427e0fa96bf65efa1ac/extensions/gvr/src/main/java/com/google/android/exoplayer2/ext/gvr/GvrAudioProcessor.java). If you have more questions, please let us know.

**Comment by virajkarandikar** [comment]
Thanks @jkammerl
I am facing this issue with NDK APIs. I am able to use java surround API.

**Comment by virajkarandikar** [comment]
@jkammerl Can you reopen this issue?

**Comment by jkammerl** [comment]
virajkarandikar@ I ran some tests and it worked well for me. Note that the JAVA API uses buffer sizes in bytes (which is easier to use in the context of ByteBuffers) and the C API uses samples. Is it possible that this is mixed up in your code? If not, please share some sample code that allows us to reproduce the issue.

**Comment by virajkarandikar** [comment]
Here is my NDK code http://www.chopapp.com/#7lt94dyq

Below is the log for my usage. NDK API doesn't produce any output for every alternate input frame. Also the output when played is very noisy.

04-03 17:44:30.897 607-5663/com.example.vkarandikar.vrrender E/SurroundDecoder: surround_format 1 input_channels 2 frames_per_buffer 512 sample_rate 44100
04-03 17:44:31.071 607-5663/com.example.vkarandikar.vrrender E/SurroundDecoder: NULL
04-03 17:44:31.103 607-5663/com.example.vkarandikar.vrrender D/SurroundDecoder: in 512 output 1024
04-03 17:44:31.104 607-5663/com.example.vkarandikar.vrrender E/SurroundDecoder: NULL
04-03 17:44:31.107 607-5663/com.example.vkarandikar.vrrender D/SurroundDecoder: in 512 output 1024
04-03 17:44:31.108 607-5663/com.example.vkarandikar.vrrender E/SurroundDecoder: NULL
04-03 17:44:31.113 607-5663/com.example.vkarandikar.vrrender D/SurroundDecoder: in 512 output 1024
..........
04-03 17:44:32.813 607-5663/com.example.vkarandikar.vrrender D/VRRender: Playback finished

**Comment by virajkarandikar** [comment]
@jkammerl any update on this?

**Comment by jkammerl** [comment]
I looked at your code. I believe you a mixing up the metrics of your size variables (bytes/samples). 
In line 49:
audioSurroundApi->AddInterleavedInput(in, input_len);
You are calling AddInterleavedInput which takes in the number of samples. Assuming input_len contains the number of samples of your "in" buffer, the following memcpy seems wrong since you are multiplying it by SAMPLE_SIZE_IN_BYTES. 
memcpy(out, in, input_len * OUTPUT_CHANNELS * SAMPLE_SIZE_IN_BYTES);

If you still think there is a bug on our side, I'll reopen the issue.

**Comment by virajkarandikar** [comment]
@jkammerl Your doubt is understandable. But that is not the case. "input_len" contains the number of stereo samples as expected by AddInterleavedInput(). SAMPLE_SIZE_IN_BYTES is defined as 2 in the same source file. So memcpy() is copying correct number of bytes from input to output. Also the playback is fine with memcpy() code enabled. But playback is glitchy with SDK processed output.

I am going to check with v1.60.1. Will update after that.
