### ISSUE TITLE
Open view image VR sometime, view is blurry

### ISSUE THREAD

**Issue by acv-truongvv** [googlevr/gvr-android-sdk#387]
Hi,
I use GVR for view image 360. 
Android 6.0 
After the eight time I put it on, I started to see that the graphic quality was degrading. Image is blurry.
![image_blue](https://cloud.githubusercontent.com/assets/14326210/24281303/15acbe1a-108a-11e7-9972-5547818a0fb4.png)
![image_nomarl](https://cloud.githubusercontent.com/assets/14326210/24281304/15b35f0e-108a-11e7-82f2-d3a54f0eaf31.png)

Please check.

**Comment by sigmaxipi** [comment]
What is the memory usage of your app? See https://developer.android.com/studio/profile/investigate-ram.html for more details.
