### ISSUE TITLE
Left/right eye distinction in shaders

### ISSUE THREAD

**Issue by dthian** [googlevr/gvr-android-sdk#388]
Hi all,

Context: I'm working on creating a stereoscopic image with my app built mostly in Android NDK, using the GVR NDK. As such, I'm hoping to use different shader behavior for each eye, so as to access different texture coords to be rendered. 

Question: Would it be possible to tell which eye is being rendered from within the vertex / fragment shader, say by accessing a global shader value? Is there existing support for this? Or perhaps there already exists a "stereoscopic image option" in the NDK that i might have missed?

Many thanks,
Daniel

**Comment by sigmaxipi** [comment]
There is no global shader value for this, but you could define it yourself. When using the NDK, you would have a [DrawEye](https://github.com/googlevr/gvr-android-sdk/blob/0c1b111683ad0e76102fad7c2cc431ab355f02f6/samples/ndk-controllerpaint/src/main/jni/demoapp.cc#L375) function in your code. You could set a uniform in your shader based on this value.

You could also have a different scene graph for each eye consisting of mostly the same objects, but have two different nodes for the mesh that is different for each eye.

Another option I've used for stereo video is to have the mesh encoded as an array of [x,y,z, leftU, leftV, rightU, rightV]. Then I use the same shader for both eyes but have a call similar to `glVertexAttribPointer(textureAttributeId, size, type, stride, pointerToData + (eye == LEFT) ? 3 : 5)`. That allows using one array for all the data in the mesh but only adjusts the offset based on eye being rendered.

**Comment by dthian** [comment]
Awesome, thanks!
