### ISSUE TITLE
No Action_down in ontouchevent

### ISSUE THREAD

**Issue by mjsibbald** [googlevr/gvr-android-sdk#39]
I've updated to the latest version, but I'm not getting the ACTION_DOWN event anymore in the onTouchEvent. 

Anyboday else notice this? Is there a way to get it?

Maik

**Comment by guanshan** [comment]
In  CardboardView.java, the  function onTouchEvent has been implemented like this：

public boolean onTouchEvent(MotionEvent e) {
		if (this.cardboardViewApi.onTouchEvent(e)) {
			return true;
		}
		return super.onTouchEvent(e);
}

so， If you want get the ACTION_DOWN event，override it.
