### ISSUE TITLE
simplevideowidget will crash with HTC M9+

### ISSUE THREAD

**Issue by p4689428** [googlevr/gvr-android-sdk#390]
my device is HTC M9+ wiht OS 6.0.1
I find implevideowidget will crash when return from CardBoard app
the scenario is
1. build and install simplevideowidget app
2. excite simplevideowidget app
3.click CardBoard button
4.click CardBoard setup  button and open CardBoard app
5.return simplevideowidget  app
and then APP crash

but it seems ok with samsung S6

Could anyone help me?

thank you.
[vr_error.txt](https://github.com/googlevr/gvr-android-sdk/files/878672/vr_error.txt)

**Comment by jdduke** [comment]
Thanks for the report, we'll start the investigation.

**Comment by jdduke** [comment]
Unfortunately, this issue appears to be with the phone's GPU driver. Please give it a try with the Android N update for this phone, and re-open the issue if it's still a problem.
