### ISSUE TITLE
How to make the sample program used  pictures

### ISSUE THREAD

**Issue by miqt** [googlevr/gvr-android-sdk#391]
It is this :https://github.com/googlevr/gvr-android-sdk/tree/master/samples/sdk-simplepanowidget/src/main/assets 

How do I get a other images like these?

**Comment by niteshxor** [comment]
use image array to open random images

**Comment by sigmaxipi** [comment]
See https://developers.google.com/vr/concepts/vrview for details about the video format. You will need a camera that supports 360 capture and can export equirectangular images.

**Comment by miqt** [comment]
thanks
