### ISSUE TITLE
How can I give some clickable points in VR panorama cardboard image  view in Android?

### ISSUE THREAD

**Issue by niteshxor** [googlevr/gvr-android-sdk#392]

**Comment by sigmaxipi** [comment]
The VrView widgets don't support this sort of click detection. You could add it yourself using something like https://github.com/googlevr/gvr-android-sdk/issues/381, but the better option is to use the general GVR SDK if you want more UI.

**Comment by niteshxor** [comment]
any reference please give me link or example

**Comment by sigmaxipi** [comment]
Consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
