### ISSUE TITLE
GVR(Java) performance problem on Nexus6P and Pixel XL

### ISSUE THREAD

**Issue by alexeysuvorov** [googlevr/gvr-android-sdk#393]
Hello, during investigating our performance problems with Pixel XL and Nexus 6P I found that the problem is not in our code. I made a video with comparison SDK and NDK very basic sample from google (treasure hunt) when you can see a huge difference in performance. Please find video uploaded to youtube: https://www.youtube.com/watch?v=GETPU5ACAJQ

Steps to reproduce: 
- Add any code which shows FPS
- Download GoogleVR SDK repo with samples and run Java OpenGL version on Nexus6P or PixelXL

Expected: FPS is about 60
Actual: FPS is about 30 on Nexus and 40 on Pixel XL

C++ version is ok on both devices and constantly shows 60 FPS.
On Samsung S5, S6, S7, Nexus 5, 5X Java version works great and FPS is 60.

I know I complain about devices with big resolution, but you have no such problems in c++ version, so I believe it is a bug and it should be fixed.

Thanks.

**Comment by sigmaxipi** [comment]
Try https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView.html#setRenderTargetScale(float) with a number less than 1. 

The Java TreasureHunt sample uses the default of 1. The C++ uses a [half that size](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/ndk-treasurehunt/src/main/jni/treasure_hunt_renderer.cc#L561). However, [it uses MSAA to compensate](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/ndk-treasurehunt/src/main/jni/treasure_hunt_renderer.cc#L381). This results in a tradeoff between clarity and app FPS. Depending on your specific scene, you should experiment with various configurations.

**Comment by alexeysuvorov** [comment]
We still see huge difference between NDK and SDK on Nexus 6P when we make buffer smaller:
NDK
#  render target scale: 1
fps: 26.973026, avg. frame time: 35
fps: 27.053141, avg. frame time: 37
fps: 26.785715, avg. frame time: 32
fps: 27.158098, avg. frame time: 36
fps: 27.397261, avg. frame time: 32
fps: 27.667984, avg. frame time: 32
fps: 27.722773, avg. frame time: 33
fps: 28.292683, avg. frame time: 30
fps: 34.179688, avg. frame time: 30

# render target scale: 0.5
fps: 59.820538, avg. frame time: 16
fps: 60.098522, avg. frame time: 14
fps: 54.848186, avg. frame time: 21
fps: 59.880241, avg. frame time: 15
fps: 59.760956, avg. frame time: 16
fps: 59.642147, avg. frame time: 16
fps: 60.000000, avg. frame time: 15

SDK
# MSAA off, renderTargetScale 1
fps: 22.504892, avg. frame time: 35
fps: 23.210833, avg. frame time: 38
fps: 22.977022, avg. frame time: 33
fps: 22.931206, avg. frame time: 36
fps: 23.391813, avg. frame time: 31
fps: 23.437500, avg. frame time: 30

# MSAA x2, # render target scale: 0.5
fps: 27.722773, avg. frame time: 30
fps: 28.375734, avg. frame time: 31
fps: 28.855721, avg. frame time: 34
fps: 26.706232, avg. frame time: 31

**Comment by jdduke** [comment]
Interesting, thanks for the report. Is it only the 6p which continues to struggle using the smaller render target scale, or does the Pixel XL show similar numbers?

**Comment by alexeysuvorov** [comment]
Pixel XL usually 20% better than Nexus 6P, but overall situation is still not good enough for immersive VR experience.
Data above is for treasure hunt when you have about 50 cubes. Let me know if you want me to upload this sample somewhere.

**Comment by sigmaxipi** [comment]
I added the timing code from https://www.youtube.com/watch?v=GETPU5ACAJQ and ran the SDK sample on my Pixel XL. I had an fps of 60 with an avg frame time of 2-3. I made no other configuration changes to the sample.

Do you have any system configurations on your Pixel that might interfere with app rendering?

Also, could you try profiling the NDK & SDK samples with either [Android Device Monitor's Method Profiling ](https://developer.android.com/studio/profile/traceview.html) or [SysTrace](https://developer.android.com/studio/profile/systrace.html)? Those tools should show why the sample was running slowly. Note that when running the method profiler, it will take 6-8ms to render a frame but the run time for `CardboardViewNativeImple.nativeOnDrawFrame` should match the `onNewFrame` to `onFinishFrame` time in your code.

**Comment by alexeysuvorov** [comment]
Hello, after your message we was confused and decided to look around on our side. We made same test on another Mac and another Ubuntu PC with same pixel. It is kind of magic, but we could finally see 60 FPS in treasurehunt with one cube. 

But difference between SDK and NDK is still huge even if we make target scale 1 for ndk. I made a [diff](https://github.com/googlevr/gvr-android-sdk/files/910613/patch.diff.zip) for master branch to demonstrate changes we made.

We made 80 cube draw and can see 20-25 fps difference between SDK vs NDK

### NDK
04-10 18:38:48.432 20055-20100/? D/MainActivity: fps: 57.884232, avg. frame time: 15
04-10 18:38:49.433 20055-20100/? D/MainActivity: fps: 57.942059, avg. frame time: 15
04-10 18:38:50.448 20055-20100/? D/MainActivity: fps: 59.113300, avg. frame time: 16
04-10 18:38:51.464 20055-20100/? D/MainActivity: fps: 57.086613, avg. frame time: 14
04-10 18:38:52.468 20055-20100/? D/MainActivity: fps: 59.760956, avg. frame time: 11
04-10 18:38:53.483 20055-20100/? D/MainActivity: fps: 59.113300, avg. frame time: 7

### SDK
04-10 18:39:45.516 20300-20356/? D/TreasureHuntActivity: fps: 39.370079, avg. frame time: 19
04-10 18:39:46.520 20300-20356/? D/TreasureHuntActivity: fps: 38.844620, avg. frame time: 20
04-10 18:39:47.523 20300-20356/? D/TreasureHuntActivity: fps: 39.920158, avg. frame time: 20
04-10 18:39:48.554 20300-20356/? D/TreasureHuntActivity: fps: 36.821705, avg. frame time: 20
04-10 18:39:49.572 20300-20356/? D/TreasureHuntActivity: fps: 36.345776, avg. frame time: 19
04-10 18:39:50.594 20300-20356/? D/TreasureHuntActivity: fps: 36.238983, avg. frame time: 20
04-10 18:39:51.595 20300-20356/? D/TreasureHuntActivity: fps: 35.928143, avg. frame time: 20
04-10 18:39:52.597 20300-20356/? D/TreasureHuntActivity: fps: 35.964035, avg. frame time: 20

Let's drop Nexus from this equation - nobody use it anyway.

**Comment by sigmaxipi** [comment]
With the 80 `drawCube` calls per eye, you will start running into Java + GL related overhead. If you change the timing method to only cover the GL calls, the 80 `drawCube` Java calls will be using more CPU than the 80 C++ `drawCube` calls. If you implement this sample without any VR code and have 2*80 `drawCube` calls, you'll see the same problem. Also note that the `drawCube` call will also call `isLookingAtObject` which performs Matrix math. These operations involve JNI calls so they add extra overhead if used frequently.

**Comment by alexeysuvorov** [comment]
Sounds reasonable.
