### ISSUE TITLE
Audio Surround Renderer NDK API outputs noisy audio

### ISSUE THREAD

**Issue by virajkarandikar** [googlevr/gvr-android-sdk#394]
Hi,

I am using Surround Renderer **NDK** API (v 1.40.0) in my app. Here is my NDK code http://www.chopapp.com/#7lt94dyq

Below is the log for my usage. NDK API doesn't produce any output for every alternate input frame. Also the output when played is very noisy.

**04-03 17:44:30.897 607-5663/com.example.vkarandikar.vrrender E/SurroundDecoder: surround_format 1 input_channels 2 frames_per_buffer 512 sample_rate 44100**
04-03 17:44:31.071 607-5663/com.example.vkarandikar.vrrender E/SurroundDecoder: NULL
04-03 17:44:31.103 607-5663/com.example.vkarandikar.vrrender D/SurroundDecoder: in 512 output 1024
04-03 17:44:31.104 607-5663/com.example.vkarandikar.vrrender E/SurroundDecoder: NULL
04-03 17:44:31.107 607-5663/com.example.vkarandikar.vrrender D/SurroundDecoder: in 512 output 1024
04-03 17:44:31.108 607-5663/com.example.vkarandikar.vrrender E/SurroundDecoder: NULL
04-03 17:44:31.113 607-5663/com.example.vkarandikar.vrrender D/SurroundDecoder: in 512 output 1024
..........
04-03 17:44:32.813 607-5663/com.example.vkarandikar.vrrender D/VRRender: Playback finished

I tried same configuration with Java API and there the output was proper. So I am suspecting something wrong with NDK APIs?

Any guidnace on how to debug/fix this?

**Comment by jkammerl** [comment]
This is a duplicate to issue #386
