### ISSUE TITLE
Will VrVideoView support FileDescriptor?

### ISSUE THREAD

**Issue by v-b7** [googlevr/gvr-android-sdk#399]
I'm trying to open a video from an external storage ( sample Uri: `content://com.android.externalstorage.documents/tree/5AA6-3A2F%3A/document/5AA6-3A2F%3AVIDEO.MP4` ) but it seems that VrVideoView can only load files from internal storage.

I tested with MediaPlayer and it can access the video through a FileDescriptor. Could VrVideoView do the same?

**Comment by sigmaxipi** [comment]
There are no plans to add support for FileDescriptors. If you want to add this functionality to your app, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
