### ISSUE TITLE
eye view inverse

### ISSUE THREAD

**Issue by codeanticode** [googlevr/gvr-android-sdk#400]
The Eye class provides the [getEyeView()](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/Eye.html#getEyeView()) method to retrieve the current eye's view transformation. A common situation is, I think, to calculate the inverse of this matrix in order to obtain the "object matrix" that one can use to express a vector in the object coordinate system. A particular application of this transformation is ray intersection with axis-aligned bounding boxes. So, I'm wonder if adding a getEyeViewInverse() method could be a worthwhile enhancement. Thank you!

**Comment by jdduke** [comment]
Thanks for the suggestion. At this point, we're likely not going to extend the Eye class all that much, but you can use the built-in [Matrix.invertM()](https://developer.android.com/reference/android/opengl/Matrix.html#invertM(float[], int, float[], int)) Android method.
