### ISSUE TITLE
The use requirements of sdk-audio-1.40.0.aar

### ISSUE THREAD

**Issue by hankewei** [googlevr/gvr-android-sdk#401]
We want to use libgvr_audio.so in commercial projects.
Is the owner of the library Google company?
Can we use it only to follow the Apache License(Version 2.0) which is indicated by https://github.com/googlevr/gvr-android-sdk/blob/master/LICENSE ?
If there are any additional requirements, please let me know.

**Comment by jdduke** [comment]
Apologies, but we cannot offer any specific legal guidance. The linked Apache License is the correct one for our project, the code contained therein and its use in any dependent projects. On a more general note, there are many commercial projects which use libgvr_audio.so.
