### ISSUE TITLE
Cannot move the scene up and down 

### ISSUE THREAD

**Issue by solomon2** [googlevr/gvr-android-sdk#402]
Hey, in VrPanoramaView,  cannot move the scene up and down , I rember in early version ,it can be  up and down .

**Comment by chaseout** [comment]
Having the same issue here.Did you find any solution for this?

**Comment by vokhuyet** [comment]
same issue ?
anybody can tell me solution to fix it ? please

**Comment by sigmaxipi** [comment]
The vertical touch tracking was never publicly exposed in our APIs because it doesn't work well with the gyro input. Some people noticed an internal flag for this, but that code was not meant to be public.
