### ISSUE TITLE
i cannot load this video bu default config.

### ISSUE THREAD

**Issue by SnowMusic** [googlevr/gvr-android-sdk#403]
my team use VR device record this video. but when i use simplevideowidget to play this vr video,it told me error like this "error loading video:null".the source is this "http://vr.bandaoapp.com/2017%E5%B9%B4/%E4%B8%A4%E4%BC%9A/%E4%BA%BA%E5%A4%A7oss.mp4".i don't know what mistake do i make,who can help me.Ps:i think this issue do not need log.

**Comment by sigmaxipi** [comment]
I pushed the video to my phone and then ran `adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -d "file:///sdcard/vr/videos/人大oss.mp4"`. The video played as expected. Are you able to view the video using the phone's built-in video viewer via `adb shell am start -a android.intent.action.VIEW -t video/mpeg   -d "file:///sdcard/vr/videos/人大oss.mp4"`?

**Comment by SnowMusic** [comment]
adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity  -d "http://vr.bandaoapp.com/2017%E5%B9%B4/%E4%B8%A4%E4%BC%9A/%E4%BA%BA%E5%A4%A7oss.mp4"     i use this. it toast "error loading video:null",too

**Comment by SnowMusic** [comment]
after now i try this on my device,mi-4c API21 ,it worked.but when i did this on my HM-NOTE API19,it faild.

**Comment by sigmaxipi** [comment]
Does the video work on your HM-NOTE using the built-in Photos app? You can use `adb shell am start -a android.intent.action.VIEW -t video/mpeg -d "file:///sdcard/vr/videos/人大oss.mp4"` to load it. That video is 4096x2048 which might be too large for old devices. You could try resizing it to 1920x960 and see if it works.

**Comment by sigmaxipi** [comment]
Also, what does the error in logcat say?
