### ISSUE TITLE
White "tearing" lines sometimes appear

### ISSUE THREAD

**Issue by ian-wevr** [googlevr/gvr-android-sdk#404]
Our application is currently rendering via a GL context we create ourselves by calling eglCreateContext(). We set async reprojection on our activity's onCreate in Java and later call gvr_initialize_gl() on our rendering thread with the relevant context. Often our rendering is fine, but we sometimes see white "tears" that are aligned to the scan out of the phone display. We've seen this occasionally in other apps as well, but some apps never seem to exhibit this problem.

**Comment by ian-wevr** [comment]
We've also noticed that gvr_frame_submit() seems to change our GL state which causes our rendering problems if we don't force the states back to known values. Is this expected? Is there a specification of what GL states may cange after gvr_frame_submit()?

**Comment by jdduke** [comment]
Hi @ian-wevr, I'll make sure one of our developers follows up on this soon, both with respect to the tearing as well as the GL state mutation.

**Comment by ian-wevr** [comment]
Thanks, jdduke.

Adding a little more info:

The white "tear" lines seem to be highly timing dependent. When we disable sustained performance mode their frequency is vastly reduced. When we have background activity (e.g. our app downloads in the background) they are more prevalent.

**Comment by Gousetis** [comment]
Hey @ian-wevr, I'll give you a bit of background info but I'll need a bit more data to help debug the issue.

White tear lines/speckles means that the asynchronous thread is being stalled/blocked for much longer than usual. There are a number of possible reasons, and some of the debug logging can help narrow it down.

Can you get a logcat while the speckles/tears are visible, but with the "enable developer logs" and "enable performance monitoring" options enabled. If you capture a huge log, just give me a five or six second period of timestamps that show the speckling.

The most likely culprit is that you're got some un-preemptable GL work on your application thread. Do you use a compute shader? Do you have a small offscreen render target that consumes the majority of your GPU load (e.g. some sort of expensive lighting pass). Do you use another GL context to render content and/or use Android to render a View heirarchy into a separate buffer?

**Comment by Gousetis** [comment]
I would not expect gvr_frame_submit to change any state when asynchronously reprojecting. When you are not asynchronously reprojecting (e.g. normal cardboard flow) there is quite a bit of state change. But I assume you are asynchronously reprojecting, since you're seeing tearing artifacts, yes?

**Comment by ian-wevr** [comment]
@Gousetis, my apologies for the delay in response. Yes, we are asynchronously reprojecting. We don't use a computer shader, have no separate render targets and only a forward pass, and don't use another GL context to render content -- only the context gvr_initialize_gl() is called in.

However, we decode videos with hardware support, and we perform background downloading. When both of these occur at once, the speckling seems to occur frequently.

I'll get you a logcat as soon as I can -- I'm not familiar with the "enable developer logs" and "enable performance monitoring" options and can't seem to find documentation -- where should I be looking for these or their documentation?

**Comment by ian-wevr** [comment]
Aha, didn't realize Daydream had its own developer settings! Wish I knew about these earlier in development for Daydream. :)

**Comment by ian-wevr** [comment]
Closing this for now -- despite getting this issue consistently for months, it seems to have disappeared on our side and we haven't been able to replicate it over the course of a week. There's a lot of moving pieces, some beyond our control, so I can't begin to fathom how this has resolved itself.

Thanks for the help/feedback! I'll reopen this issue should the problem return in a way we cannot resolve.

**Comment by jdduke** [comment]
Hi @ian-wevr. It's possible this issue was resolved with a recent Google VR Services push (version 1.5).
