### ISSUE TITLE
WARNING! Message telling me to install google vr services. 

### ISSUE THREAD

**Issue by kesefworld** [googlevr/gvr-android-sdk#405]
Hi, I am building vr games and I also have this problem. I have (as far as I know) the latest google VR sdk version 1.30. To test my apk I build and run it to my galaxy s7 edge and when I run the game that google warning comes up. Like I said I'm using the latest sdk version so why am I still seeing this warning message? Thanks in advance

**Comment by jdduke** [comment]
Have you installed Google VR Services from https://play.google.com/store/apps/details?id=com.google.vr.vrcore&hl=en?

**Comment by kesefworld** [comment]
Yes and I actually deleted the 1.30 version from my source folder and installed the 1.40 version and I still have that problem.  I am wondering, is there any settings I have to perform on my phone in order to stop the message from appearing?

**Comment by jdduke** [comment]
> Yes and I actually deleted the 1.30 version from my source folder and installed the 1.40 version and I still have that problem.

Right, but I'm talking about the *app* Google VR Services, available from the Play Store. This is separate from the Google VR SDK that you're using to compile your app. Have you installed the app from the Play Store? If so, can you please capture a bug report: `adb bugreport vrservices_warning.zip`.

**Comment by binoculars88** [comment]
Is there a way to disable this message? My app works 100% fine even if Google VR Services isn't installed, but the user experience is so much worse when this warning pops up...

**Comment by nathanmartz** [comment]
binoculars88, what device are you seeing this behavior on? What version of the SDK are you using?

**Comment by kesefworld** [comment]
On my Samsung 7 edge

**Comment by binoculars88** [comment]
nathanmartz, I'm using this in a Cordova app. Both [Novonity Plugin VR](https://github.com/TivonChen/novonity-plugin-vr) (which uses `com.google.vr:sdk-videowidget:1.10.0`) and [Cordova VR Plugin](https://github.com/jleszczynski/cordova-vr-player) show the popup message on Android N+. Is there a way to disable the warning? Player works fine without Google VR Services too...

**Comment by jdduke** [comment]
Hi @binoculars88. The latest videowidget release should no longer trigger this message. Can you give it a try?

**Comment by altaiirdesmond** [comment]
I'm having the same problem. Already installed the latest SDK but cannot download the google vr services in my device and it says "your device isn't compatible with this version". 

I'm using 
- Android-N 7.0
- Samsung J5 Prime

**Comment by koubiak** [comment]
We do not support the Samsung J5 Prime at the time. See
https://www.google.com/search?q=ARCore+list+of+supported+devices&oq=ARCore+list+of+supported+devices&aqs=chrome..69i57.5834j0j7&sourceid=chrome&ie=UTF-8
for a list of supported devices.

**Comment by Roselynn39** [comment]
I use a Samsung tablet that this message shows on. I am not a tech person at all, how do I get rid of it?  I don't even use apps much, email, google, etc.  It comes up EVERYTIME I open up the tablet and on everything I use.  Have to hit cancel twice.  Started after viewing a condo "tour" on a website.  HELP ME, PLEASE.  What is a videowidget?  Please remember, I won't understand much other than 1,2,3 in simple terms.

**Comment by Roselynn39** [comment]
It is asking me to go to the Google play store and install app.  Don't like the sound of that nor do I think it would help like jdduke talks about.  Thanks in advance.

**Comment by jdduke** [comment]
@Roselynn39: Which web browser (including version) are you using that triggered this message? Chrome currently requires the installation of Google VR Services in order to use the latest VR functionality. Is it not available with your tablet?

**Comment by jdduke** [comment]
Regardless, we're planning to remove the installation prompt on devices that aren't Daydream-ready. Expect a fix in the next SDK release (targeting mid-February).

**Comment by jdduke** [comment]
The latest release should no longer trigger this prompt.

**Comment by i3games** [comment]
It still triggers the prompt on non-daydream devices like the Moto G5 on Chrome 71

**Comment by yihanseattle** [comment]
I'm running 'com.google.vr:sdk-base:1.190.0'. It still triggers the prompt. Please let us know if there is anything we can do manually to disable the dialog prompt. Thanks

**Comment by sigmaxipi** [comment]
@i3games Chrome requires the installation of VR services even for non-Daydream devices when using VR functionality in Chrome

@yihanseattle what app are you seeing this with?

**Comment by i3games** [comment]
> @i3games Chrome requires the installation of VR services even for non-Daydream devices when using VR functionality in Chrome
> 
Where can I report this bug?

**Comment by yihanseattle** [comment]
> @i3games Chrome requires the installation of VR services even for non-Daydream devices when using VR functionality in Chrome
> 
> @yihanseattle what app are you seeing this with?

Hey @sigmaxipi , I'm just running the HelloVRActivity from `sdk-hellovr` sample on a custom device. The device I'm running on does not have google play services. But I was able to bypass by installing `Google VR Service` and enable the `Google VR Service`. I'm not sure how to bypass the prompt without installing `Google VR Service`. It would be great if you could give me any suggestions. Thanks!

**Comment by sigmaxipi** [comment]
Which custom device? Is this a consumer phone? Or does it have a custom build of Android?

**Comment by yihanseattle** [comment]
@sigmaxipi It has a custom build of Android 7.1. Do you happen to know how to disable the prompt programmatically? why it's still showing? Or Google VR SDK will show the prompt on a device with custom build of Android? Thanks!

**Comment by sigmaxipi** [comment]
Does your custom build have the flags set in https://android.googlesource.com/platform/frameworks/native/+/android-7.1.1_r58/data/etc/android.hardware.vr.high_performance.xml ? Those cause the apps to try to enable Daydream rendering which requires Google VR Services.

**Comment by yihanseattle** [comment]
Hey @sigmaxipi , you are right! We no longer see the warning prompt after removing the flags in the OS. That was the cause! Thank you so much!
