### ISSUE TITLE
Wrong orientation of vrVideoView

### ISSUE THREAD

**Issue by Lannylanlol** [googlevr/gvr-android-sdk#406]
Hi, 
I display vrVideoView in Activity with an orientation set to "sensorLanscape". 
When I rotate the device, all the layout of the activity works fine and rotate correctly, BUT the vrVideoView rotate showing the video upside down.
There is a way to block the rotation of the vrVideoView?
any helps?
Thanks in advance

**Comment by Lannylanlol** [comment]
Note: I need to use the DisplayMode set to EMBEDDED, which causes the issue. I tried to use display Mode set to FULLSCREEN MONO and the vrVideoView rotates correctly. 
Is there a way to avoid the rotation for the Embedded display mode as the FULLSCREEN MONO does?
Thanks

**Comment by sigmaxipi** [comment]
The best way is to recreate the Activity as suggested in https://github.com/googlevr/gvr-android-sdk/issues/355. Or you could recreate the just the View.

**Comment by sigmaxipi** [comment]
If you need more control over the layout, consider using https://github.com/googlevr/gvr-android-sdk/issues/510
