### ISSUE TITLE
On Daydream, the rendered surface can be dragged

### ISSUE THREAD

**Issue by nfrechette** [googlevr/gvr-android-sdk#407]
On daydream (works with the NDK sample treasure hunt for example), if you press in the black part where the eye divider is and drag with your finger, the image will move. It recenters once you release it.

Minor annoyance.

**Comment by jdduke** [comment]
So, this only happens when you've paired a Daydream headset. We actually use the touch contact with the Daydream View headset to automatically align the displayed image. This allows convergence if the phone is slightly misaligned in the headset.
