### ISSUE TITLE
It there any way to lock gyro in VrVideoView?

### ISSUE THREAD

**Issue by AnNEDoMini** [googlevr/gvr-android-sdk#409]
Eg for cases where developer wants users to hold still, for some time, then unlock moving. Or some method like "setHeadRotation" with "use with caution" mark (to avoid gimbal lock, edge cases etc).

**Comment by nathanmartz** [comment]
I'm sorry but we don't support this and don't current play to.

**Comment by AnNEDoMini** [comment]
Maybe just expose gyro/rotation related methods?
