### ISSUE TITLE
multiview questions

### ISSUE THREAD

**Issue by gpx1000** [googlevr/gvr-android-sdk#410]
The https://developers.google.com/vr/android/ndk/gvr-ndk-rendering#1_query_for_multiview_support page is a little lax on details for usage.  I'm hoping to ask some questions to help clear up my understanding:
1.) Why is gvr_api->IsFeatureSupported(GVR_FEATURE_MULTIVIEW); considered better than:
    const char * allExtensions = (const char *)glGetString( GL_EXTENSIONS );
    if ( allExtensions != NULL )
    {
        SupportMultiView = strstr( allExtensions, "GL_OVR_multiview2" ) &&
                           strstr( allExtensions, "GL_OVR_multiview_multisampled_render_to_texture" );
    }
It would seem that either gives the desired results, is something else checked under the hood as the later is more portable to engines working with other platforms.
2.) I noticed that the docs say ensure a single set of drawcalls for both eyes.  Shouldn't that read ensure a single drawcall for both eyes per frame?  I.e. the idea is:

if(SupportMultiView) {
drawFrame();
} else {
drawLeftEyeFrame();
drawRightEyeFrame();
}

3.) As far as my understanding goes, Multiview depends upon not being used in Immediate mode; that should be incompatible and only immediate mode usage should happen to a separate GLContext rendered to a texture.  That said, what is the process with working with external textures (i.e. videos).  I'm assuming external_texture will work everywhere that multiview extension is found and thus should be in all Daydream compatible drivers.

**Comment by prideout** [comment]
1) We recommend calling `IsFeatureSupported` rather than checking for extensions directly because Google VR Services may need to blacklist the feature on certain devices. 

2) Correct, a single draw call corresponds to both eyes.  The sequence of draw calls that composes the scene needs to occur only once.

3) It's fine to mix several types of `BufferViewport` objects in a single swap chain.  One can be an external surface, while another is a multiview buffer.

**Comment by gpx1000** [comment]
Thanks for the clarifications.
It would seem problematic that the GLDriver is saying an extension is supported and yet it really shouldn't be used; as if it's not supported, the driver shouldn't advertise it in the first place.  Thus, I'm a bit surprised by the desire to blacklist the GL feature on certain devices.  However, will accommodate and on Daydream devices have the code run the check. 
The other two responses align with my expectations, Thanks again!

**Comment by nathanmartz** [comment]
Sounds like this issue is resolved.
