### ISSUE TITLE
Custom exoplayer instance

### ISSUE THREAD

**Issue by AntonAFA** [googlevr/gvr-android-sdk#411]
Hey there! 
I am looking on your simplevideowidget example. As i understand your VrVideoView have a VrVideoView that is actually have an instance of VrVideoPlayer (which is actually an exoplayer wrapper) and VrVideoRenderer (which is implementation of exoplayers BaseRenderer). I am wondering why this VrVideoPlayer and VrVideoRenderer are package local, so i cant have access to them from outside of the VrVideoView.
What should i do if i want to use exoplayer interfaces such as ExoPlayer.EventListener, MetadataRenderer.Output. For example i want to receive state changes like Buffering and Ready and tracks info. 
- How can i do so?
- Do you intend to expose exoplayer instance?
- Also, i wanted to ask how you prioritise to update GVR whith newly released exoplayer versions?
Will be grate to receive your feedback.

**Comment by sigmaxipi** [comment]
We don't have any plans of exposing our Exoplayer functionality due to its tight integration with various parts of our code. We are working on a sample that demonstrates how to implement many of the VrView features that people want including swapping out the Exoplayer instance or customizing it.

**Comment by AntonAFA** [comment]
Thanks for reply. When do you plan to release the sample? Also if it is possible right now to swap the instance of the exoplayer, can you please provide me with some code snippet of doing so?
