### ISSUE TITLE
Error initializing tiles

### ISSUE THREAD

**Issue by dri94** [googlevr/gvr-android-sdk#413]
When trying to load the VrPanoramaViews in a list, the first one will load, but the others get an error as follows:
```
E/VrPanoramaEventListener: 116164141.onError Error initializing tiles
E/VrEventListener: 116164141.onLoadError: Error initializing tiles
```

There is no documentation on this issue

**Comment by dri94** [comment]
I have tested this on code that is known to work and has previously worked 100%. This issue is happening on a stock Google Pixel.

**Comment by jdduke** [comment]
Please re-open with a full bug report or more complete logs. Thanks!
