### ISSUE TITLE
Will cardboard device support async reprojection ?

### ISSUE THREAD

**Issue by tairtec** [googlevr/gvr-android-sdk#414]
I compiled the sdk-videoplayer example, but my phone is not Daydream-Ready. I can not see anything but the sound.

Here is the error info :
```
E/GvrLayoutImpl: Only Daydream devices support async reprojection. Cannot enable video Surface.
E/WatchVideoActivity: UnsupportedException: Async Reprojection not supported. Async Reprojection Video Surface not enabled.
```

Will cardboard device support async reprojection ?

**Comment by sigmaxipi** [comment]
Asynchronous Reprojection requires a strong integration between the app, operating system, and hardware. This functionality is only limited to Daydream Ready devices right now. If you run a Cardboard app on these devices, you can enable async reprojection in the Cardboard app and the performance will improve, but `setAsyncReprojectionEnabled` will fail on non-Daydream Ready devices right now.

**Comment by jdduke** [comment]
@Anton111111 : That's correct, the current sample only supports Daydream-ready phones.
