### ISSUE TITLE
when is the best time to call gvr_audio_surround_set_head_rotation?

### ISSUE THREAD

**Issue by hankewei** [googlevr/gvr-android-sdk#415]
As far as I know, gvr audio surround does not create internal threads.
For the immediacy of senor data, when is the best time to call gvr_audio_surround_set_head_rotation?
Which function should be immediately located behind gvr_audio_surround_set_head_rotation? gvr_audio_surround_add_interleaved_input, gvr_audio_surround_get_available_output_size_samples, or 
gvr_audio_surround_get_interleaved_output?

**Comment by jkammerl** [comment]
Good question! You are correct, the GvrAudioSurround class is single-threaded. To keep the latency of the head rotation at a minimum, you should set the most recent head orientation sample right before you call gvr_audio_surround_get_interleaved_output which triggers the internal processing of the input buffers.

**Comment by hankewei** [comment]
Thank you for your answer.
As you say, gvr_audio_surround_get_interleaved_output triggers the internal processing of the input buffers.
Then, gvr_audio_surround_get_available_output_size_samples only calculates the number of available output frames.
Is that so?

**Comment by hankewei** [comment]
@jkammerl 
Thank you for your answer.
As you say, gvr_audio_surround_get_interleaved_output triggers the internal processing of the input buffers.
Then, gvr_audio_surround_get_available_output_size_samples only calculates the number of available output frames.
Is that so?
