### ISSUE TITLE
about sensor

### ISSUE THREAD

**Issue by RalfNick** [googlevr/gvr-android-sdk#417]
If I want to implement the sensor fusion into c++ code, the algorithm is in the packge “com.google.vr.sdk.base.sensors”, is there anyone who have done this? Thanks !

**Comment by koubiak** [comment]
What are you trying to do? Are you trying to implement  your own sensor
fusion in c++ or are you trying to use GVR's sensorfusion in c++?

**Comment by RalfNick** [comment]
I build a opengl demo, but is c++ code , and i want to use theGVR's sensorfusion in c++.

**Comment by YunzhongTianjing** [comment]
@RalfNick ,Something you maybe want:
https://developers.google.com/vr/android/ndk/download
https://github.com/googlevr/gvr-android-sdk/tree/master/libraries/headers/vr/gvr/capi/include

**Comment by sigmaxipi** [comment]
You won't be able to use GVR's sensor fusion code like that. Android does have an [NDK sensor API](https://developer.android.com/ndk/reference/group___sensor.html). You can use that an implement sensor fusion on top of it. See smus.com/sensor-fusion-prediction-webvr/ for more info on how to implement sensor fusion.
