### ISSUE TITLE
Stereo rendering works incorrectly in SDK version 1.40 for some viewer profiles.

### ISSUE THREAD

**Issue by kpilyugin** [googlevr/gvr-android-sdk#418]
After updating SDK to latest version (1.40.0), noticed an issue with stereo rendering on following device: Galaxy Tab S 8.4 (SM-T700), Android 5.0.2. 
When selecting some cardboard viewer profiles (e.g. first one from http://www.hypergridbusiness.com/faq/vr-headset-qr-codes/), we see two small points instead of usual eye views.

**Comment by nathanmartz** [comment]
I'm sorry but we don't support tablets in the cardboard SDK.
