### ISSUE TITLE
VrWidgetView.setSensorTrackingEnabled(boolean)

### ISSUE THREAD

**Issue by tao1** [googlevr/gvr-android-sdk#419]
Hi,

I would like to disable sensor tracking and use only touch tracking in some circumstances. For example it is not convenient to move around to watch a 360 video in public transport. If sensor tracking is disabled, touch tracking should move also head yaw in addition of pitch.

Kind regards,

Laurent.

**Comment by isagorr** [comment]
setPureTouchTracking() in v1.60

**Comment by tao1** [comment]
Many many thanks !
Notice this method is not yet documented: https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/common/VrWidgetView

**Comment by Charles6666** [comment]
You are watching all the Issue there putting in me.from no reason

**Comment by tao1** [comment]
I guess you are watching all conversations on your side Charles6666. I doubt I can do that on my side.

There's a small bug when using setPureTouchTracking(true), video starts with a 180 degrees offset, meaning you don't see video center at start but the opposite direction. Furthermore this offset remains when you drag video using touch gestures, I mean getHeadRotation() still has a 180 degrees offset.
