### ISSUE TITLE
Samsung Galaxy S6, vibrate produces extra bogus sensor clicks

### ISSUE THREAD

**Issue by RubenGarcia** [googlevr/gvr-android-sdk#42]
I tested the latest git as of today on different telephones.
The Samsung Galaxy S6 gets two or three calls of onCardboardTrigger.
I think this is due to the vibrator being too strong and that affecting the magnetic sensor.

I fixed it by commenting the 
vibrator.vibrate(50);
line which ends the method.

If more people find the issue on different phones, the line should be commented out globally, or at least some comment added to the source code.

**Comment by dav-cz** [comment]
Thanks for your report Ruben, we'll look into that.

Do you use a headset with a magnet? or a Cardboard v2 with conductive tape that touches the screen?

**Comment by RubenGarcia** [comment]
I don't know. 
I'm using the cardboard from 
http://mini.com/360

**Comment by jdduke** [comment]
Legacy Cardboard devices with magnetic sensors are no longer officially supported by the SDK.
