### ISSUE TITLE
Left and right camera view can not be full screen

### ISSUE THREAD

**Issue by YoungBill** [googlevr/gvr-android-sdk#420]
I use unity develop android applications. I have some functions to use the user authorized, I found that if the user does not authorize, such as not allowed READ_EXTERNAL_STORAGE, then the left and right camera view is full screen, when the user allows permission, the left and right camera view becomes smaller, no full screen Will this question how to solve

**Comment by YoungBill** [comment]
anyone can help me?

**Comment by nathanmartz** [comment]
For cardboard apps we require those permissions for the viewer pairing to be read and written properly.
