### ISSUE TITLE
Error playing HLS live stream

### ISSUE THREAD

**Issue by germanmunoz** [googlevr/gvr-android-sdk#421]
I'm playing around with the simplevideowidget included in the SDK, and I keep getting this error when playing an HLS live stream (via Wowza Streaming Engine) on a Samsung S7 connected to a Windows PC via USB. The video I'm playing is 480p, so nothing too heavy:

Error loading video: com.google.a.a.n: Couldn't match #EXTINF:([\d\.]+)\b in #EXTINF:-0.68,

Together with this error:

196696591AdaptiveMediaSourceEventListener.onLoadError com.google.a.a.n: Couldn't match #EXTINF:([\d\.]+)\b in #EXTINF:-0.68,

Any advice would be appreciated. Not even sure what kind of error this is. I try playing the same video in VOD form via Wowza, and it plays fine. The live streaming it with HLS is what gives me issues,

Stack trace from Android Monitor:
05-09 22:05:48.661 3470-3884/? D/ConnectivityService: updateCapabilities: oldCap = [ Transports: WIFI Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -64], newCap = [ Transports: WIFI Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -63]
05-09 22:05:48.661 3470-3884/? D/ConnectivityService: rematching NetworkAgentInfo [WIFI () - 502]
05-09 22:05:48.661 3470-3884/? D/ConnectivityService:  network has: NetworkAgentInfo{ ni{[type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "ARM-2G", roaming: false, failover: false, isAvailable: true]}  network{502}  lp{{InterfaceName: wlan0 LinkAddresses: [fe80::8ef5:a3ff:fe00:59d4/64,192.168.0.19/24,]  Routes: [fe80::/64 -> :: wlan0,192.168.0.0/24 -> 0.0.0.0 wlan0,0.0.0.0/0 -> 192.168.0.1 wlan0,] DnsAddresses: [192.168.0.1,] Domains:  MTU: 0 TcpBufferSizes: 524288,1048576,2097120,524288,1048576,4194240}}  nc{[ Transports: WIFI Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -63]}  Score{60}  everValidated{true}  lastValidated{true}  created{true} lingering{false} explicitlySelected{false} acceptUnvalidated{false} everCaptivePortalDetected{false} lastCaptivePortalDetected{false} }
05-09 22:05:48.671 3968-4171/? D/NetworkController: onReceive: intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 bqHint=4 VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) }
05-09 22:05:48.681 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=13, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] satisfies: true nri.isRequest: false
05-09 22:05:48.691 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=21, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ] satisfies: true nri.isRequest: false
05-09 22:05:48.711 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=36, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ] satisfies: true nri.isRequest: false
05-09 22:05:48.711 3968-3968/? D/QSTileView: handleLabelStateChanged() label = Wi-Fi cellWidth 272
05-09 22:05:48.711 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=38, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ] satisfies: true nri.isRequest: false
05-09 22:05:48.721 11354-11354/com.google.vr.sdk.samples.simplevideowidget E/VrVideoPlayer: 196696591AdaptiveMediaSourceEventListener.onLoadError com.google.a.a.n: Couldn't match #EXTINF:([\d\.]+)\b in #EXTINF:-0.68,
05-09 22:05:48.721 3470-4194/? D/SecContentProvider2: query(), uri = 15 selection = getToastGravityEnabledState
05-09 22:05:48.731 3470-3884/? D/ConnectivityService: Network NetworkAgentInfo [WIFI () - 502] was already satisfying request 1. No change.
05-09 22:05:48.731 3470-4233/? D/SecContentProvider2: query(), uri = 15 selection = getToastEnabledState
05-09 22:05:48.731 3470-3500/? D/SecContentProvider2: query(), uri = 15 selection = getToastShowPackageNameState
05-09 22:05:48.741 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=39, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ] satisfies: true nri.isRequest: false
05-09 22:05:48.751 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=5, legacyType=-1, [] ] satisfies: true nri.isRequest: false
05-09 22:05:48.751 11354-11354/com.google.vr.sdk.samples.simplevideowidget E/SimpleVrVideoActivity: Error loading video: com.google.a.a.n: Couldn't match #EXTINF:([\d\.]+)\b in #EXTINF:-0.68,
05-09 22:05:48.761 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=4, legacyType=-1, [ Transports: WIFI Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] satisfies: true nri.isRequest: false
05-09 22:05:48.761 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=3, legacyType=-1, [ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] satisfies: false nri.isRequest: false
05-09 22:05:48.761 3470-3884/? D/ConnectivityService:   checking if request is: NetworkRequest [ id=6, legacyType=-1, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VP

**Comment by nathanmartz** [comment]
We don't support live streaming HLS in the VR View widgets.
