### ISSUE TITLE
DJI video stream

### ISSUE THREAD

**Issue by hrmsa** [googlevr/gvr-android-sdk#422]
Hello,
I want to render video stream form dji drone in vr mode using gvr.. the video stream is in surfacetexture can you help me to achieve this.. i will really appreciate your help

**Comment by jdduke** [comment]
Hi @hrmsa, we're working on a sample for generalized video support. In the meantime, you can simply draw your SurfaceTexture as a quad in your scene using the usual GVR APIs (e.g., GvrView).
