### ISSUE TITLE
VrPanoramaView does not scroll in any direction 

### ISSUE THREAD

**Issue by uzubari** [googlevr/gvr-android-sdk#423]
I am working with a tablet which has 1080x1920 resolution and running android 5.1.1 (API level 22).
I have compiled the sdk-simplepanowidget example. 
The example run as expected on a physical phone and on the simulator but it is not possible to drag the image in any direction on the tablet. The VrPanoramaView shows only a portion of the panorama, it is not possible to change the visible area.

The  app does not give any error message and there is not any exception in logcat.

**Comment by jdduke** [comment]
In general, tablets aren't well supported by the Daydream/Cardboard APIs. At some point we might revisit this. Sorry for the trouble.
