### ISSUE TITLE
VrPanoramaview: Different configuration in Cardboard Camera and View

### ISSUE THREAD

**Issue by codelurch** [googlevr/gvr-android-sdk#424]
I made a panorama photo in Cardboard Camera app. Displaying it in 3D view works as desired. Both eyes are rendered ok.
![cardboard](https://cloud.githubusercontent.com/assets/13132228/26123490/6194b97a-3a7b-11e7-8c5f-260f2c8b651e.jpg)

I converted the image with the service https://storage.googleapis.com/cardboard-camera-converter/index.html
![cardboard-converted](https://cloud.githubusercontent.com/assets/13132228/26123489/6193ab5c-3a7b-11e7-82e6-70133e7e97a4.jpg)

Displaying the image in the VrPanoramaView / 3D view displaces both eye viewports about nearly 50% of the image width. This is far away of a 3D effect...
![cardboard_screen](https://cloud.githubusercontent.com/assets/13132228/26123491/61953eb8-3a7b-11e7-9324-4d7706952dc5.jpg)

Hardware is Samsung S7.

**Comment by jdduke** [comment]
What if you change your screen resolution back to the native resolution? Does that resolve the issue?

See also the discussion @ https://github.com/googlevr/gvr-unity-sdk/issues/421. You might try installing [Google VR Services](https://play.google.com/store/apps/details?id=com.google.vr.vrcore&hl=en) to see if that helps?

**Comment by codelurch** [comment]
Had installed the VR Services without success. Indeed it helped to change resolution as discussed in 421. Thanks for the quick answer. I didn't find this discussion.

Is there a chance to give the user feedback about problematic config like checking supported setups/resolution?

**Comment by jdduke** [comment]
We're actually rolling out an update for Google VR Services that will prompt the user to update their resolution to native, but we'll only do that for Daydream-ready devices like the S8. In the meantime, my suggestion would be to *not* enable VR mode (Activity.setVrModeEnabled()) on the S7.
