### ISSUE TITLE
how to modify the VrPanoramaView rotation angle

### ISSUE THREAD

**Issue by thiagooo0** [googlevr/gvr-android-sdk#425]
hi. i am developing a vr app for a new vr devices. 
 when i use the VrPanoramaView to show a picture, i find that the picture is rotated by 90 degrees。
 in my deivices, the methods Display.getRotation() return 3.and in normal phone , Display.getRotation() return 0. 
Do I have any way to change the initial rotation degree?

**Comment by sigmaxipi** [comment]
What device are you seeing this problem on?

**Comment by jdduke** [comment]
Feel free to re-open with additional details or context for the problem.
