### ISSUE TITLE
movements are rotated on Nexus 9 

### ISSUE THREAD

**Issue by p-fischer** [googlevr/gvr-android-sdk#426]
I updated from 1.2.0 to 1.4.0 and detected a strange problem with the Nexus 9, which did not exist before the update:

When I move the device horizontally, the camera moves vertically and vice versa. After the movement - when holding the device steady -  the camera slowly fades from the wrong camera position to the correct one.

The behavior is correct though on Samsung Galaxy S5 and Nexus 5.

**Comment by jdduke** [comment]
Thanks for the report. Tablets aren't officially supported on the Cardboard/Daydream platform. Can I ask what the use-case is for the app you're testing? Are you using a panoramic widget? Or GvrView?

**Comment by p-fischer** [comment]
I'm using VrPanoramaView - just as the sample app `simplepanowidget` does

**Comment by sigmaxipi** [comment]
Tablets aren't support for the VrView widget,s but consider using the Video360 sample as a starting point for a custom app. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
