### ISSUE TITLE
About orientation-pitch is reversed

### ISSUE THREAD

**Issue by RalfNick** [googlevr/gvr-android-sdk#428]
I use the daydream package "base.aar" in unity, then the getLastHeadView() is called, and then i get quaternion through 'HeadTransform', and i pass the quaternion to the camera in unity .When i test the orientation, One of the orientation is wrong, yaw  and roll  are right ,but the pitch is wrong, when i turn to sky, i look  the ground. when i turn to the ground , i look the sky . How can i get the right orientation? Which file  should i modify? The "HeadTransform" or “HeadTracker”? 

Thanks!

**Comment by nathanmartz** [comment]
Can you explain what you are doing here? It sounds like you are trying to manually integrate the GVR SDK into Unity? If so, it's already integrated in 5.6 and above.

**Comment by miraleung** [comment]
Are you using the GVR Unity SDK? We no longer need to use base.aar; the native libs have become part of the Unity engine as of 5.6.

**Comment by RalfNick** [comment]
I know that. I just want to understand the algorithm , and i hope i can  do something, such as optimization algorithm！And i have another question, the native libs are part of the Unity engine and android ! The aar package is for the android. I want to know the difference between native libs and aar when used in android. Though native libs can be used in android , and what the aar is used for? Thanks a lot!

**Comment by sigmaxipi** [comment]
This is probably a right-handed vr left-handed issue. OpenGL is right-handed but Unity is left-handed. So you'll need to convert if you are trying to use GVR (which is right-handed like OpenGL and other parts of Android) in Unity.

See https://answers.unity.com/questions/38924/unity-is-a-left-handed-coordinate-system-why.html . Using the Android GVR SDK inside Unity isn't supported. You should use the GVR Unity SDK directly. But if you do use the Android GVR SDK, you'll need to make sure all the conversions are correct.
