### ISSUE TITLE
Failed to resolve: com.google.vr:sdk-base:1.60.1

### ISSUE THREAD

**Issue by micdic** [googlevr/gvr-android-sdk#431]
I've faced this problem downloading the latest version of git code GVR Android SDK v1.60.1

Android Studio 2.3.2 cannot find  some gradle dependencies such as:

in file  ..\gvr-android-sdk\samples\sdk-controllerclient\build.gradle

...
dependencies {
    compile 'com.google.vr:sdk-base:1.60.1'
    compile 'com.google.vr:sdk-controller:1.60.1'
}

**Comment by reganking** [comment]
Experienced the same issue on AS 2.3 beta (updating to 3 now). 

Check https://bintray.com/google/googlevr/sdk-audio which indicates 1.60.1 isn't available yet (mentioned by https://stackoverflow.com/a/44199529).

Solution: Change ALL instances from 1.60.1 to 1.60.0 ... if just changing dependencies for one sample project, gradle will still complain.

You may get additional dependency issues for com.android.support:support-annotations:25.2.0 and com.android.support:support-core-utils:25.2.0 if you're building the videowidget sample.

**Comment by reganking** [comment]
Additional dependency issues might be resolved with update to "Google Repository" and "Android Support repository" in the Android SDK Manager. Worked here for AS 2.3 beta.

**Comment by micdic** [comment]
I've changed all the projects  instances from 1.60.1 to 1.60.0 and it now compiles correctly.
Thanks really for yuor support. @reganking
