### ISSUE TITLE
Ability to use the sdk for offline rendering

### ISSUE THREAD

**Issue by diegodorado** [googlevr/gvr-android-sdk#433]
I wonder if it is possible to use the SDK to render spatialized audio.
I am talking about creating a program, without GUI, that can receive by argument a wav file path, and some spatialization parameter, to generate a new wav file making use of GVR spatialization capabilities.

I am writing in the android-sdk repository, but what I really need is to be usable under linux machines.
A python binding would be great, but otherwise a C++ way to do this would suffice for my needs.
Is this the right place to ask? Is there another GVR tool for this purpose?

**Comment by jkammerl** [comment]
Our native APIs are available for Android and iOS. Linux is currently not supported. 
On Android, you could use our [GvrSurround API ](https://github.com/googlevr/gvr-android-sdk/blob/master/libraries/headers/vr/gvr/capi/include/gvr_audio_surround.h) to process raw PCM buffers and write the output into a soundfile.
