### ISSUE TITLE
setPureTouchTracking() crashes in VrPanoramaRenderer

### ISSUE THREAD

**Issue by p-fischer** [googlevr/gvr-android-sdk#434]
I updated to version `1.60.0` and tried that new method `setPureTouchTracking()` however that leads to an immediate app crash producing the following stack trace:
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.nativeSetPureTouchTracking(long, boolean) (tried Java_com_google_vr_sdk_widgets_pano_VrPanoramaRenderer_nativeSetPureTouchTracking and Java_com_google_vr_sdk_widgets_pano_VrPanoramaRenderer_nativeSetPureTouchTracking__JZ)
  at com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.nativeSetPureTouchTracking(Native Method)
  at com.google.vr.sdk.widgets.common.VrWidgetRenderer$SetPureTouchTrackingRequest.execute(VrWidgetRenderer.java:322)
  at com.google.vr.sdk.widgets.common.VrWidgetRenderer.executeApiRequestOnGlThread(VrWidgetRenderer.java:257)
  at com.google.vr.sdk.widgets.common.VrWidgetRenderer.onSurfaceCreated(VrWidgetRenderer.java:120)
  at com.google.vr.sdk.widgets.pano.VrPanoramaRenderer.onSurfaceCreated(VrPanoramaRenderer.java:63)
  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

**Comment by sigmaxipi** [comment]
This isn't a supported method in the SDK. You should only use methods that are documented on [the dev site](https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/common/VrWidgetView). This method is only implemented for the video widget rather than the image widget which is why you're seeing a crash.

**Comment by p-fischer** [comment]
Hi @sigmaxipi , thank you for your answer.

Since I'm desperately looking for a way to make vertical panning available for panoramas, I'm willing to test experimental API too. Do you know if that method will be implemented for `VrPanoramaRenderer` eventually?

More importantly: Do you know an existing way, how the camera can be moved vertically via touch gestures?

**Comment by darsor** [comment]
I'm also try to use pure touch-controlled mode on a panorama. This seems like a basic feature, since the panorama isn't very useful without it.

If there is another workaround, let us know!

**Comment by p-fischer** [comment]
I tested this again with version `1.80.0` and "pure touch tracking" mode is now implemented for `VrPanoramaView` :)

In general, I would really appreciate version change logs and if the GitHub issues would be updated with that kind of information.

**Comment by sigmaxipi** [comment]
That API is still a private method so you shouldn't rely on it. If you want a pure touch-controlled 360 media player, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
