### ISSUE TITLE
VrVideoView freezing on large downloaded videos

### ISSUE THREAD

**Issue by markusekblad** [googlevr/gvr-android-sdk#435]
For a long time we've had this issue where our large video files freeze when played in VR mode, the sound will play but the video is either completely frozen or freezes every few seconds. The videos usually work in regular fullscreen mode. HLS Streaming works fine in both modes. The downloaded videos play perfectly in the GVR iOS SDK.

It's happening on a lot of android devices, I currently have a Huawei Honor 8 and a Samsung S6 to test on and it's the same on both.

android:largeHeap is set to "true" in the manifest

One example is this 999 MB video in 4096x2048 resolution
https://video-cdn.dn.se/M/V/M/v/MvkzMHsb6EGY4YAdOigx9Q_src.mp4?v=1&token=0f1ea9a4324e6248b49e2

Looking at the media information in VLC it reports the following:
Codec: H.264 MPEG-4 AVC (part 10) (avc1)
Resolution: 4096x2050
Display resolution: 4096x2048
Frame rate: 50
Decoded format: Planar 4:2:0 YUV

Any suggestions on how to fix this is welcome.

**Comment by sigmaxipi** [comment]
This might be due to the high resolution of the video. Can you try reencoding to a smaller resolution? 4k is 3840x2160 and might work better.

**Comment by jdduke** [comment]
Feel free to re-open if you're seeing the same problem after reencoding to a smaller resolution.
