### ISSUE TITLE
Using Controller Laser Pointer Functionality With Google Daydream

### ISSUE THREAD

**Issue by nikhilcheruku12** [googlevr/gvr-android-sdk#436]
I have been using The Google VR SDK for android in conjunction with OpenGL to code my app. I need to use a controller laser pointer to implement some of the functionalities. I have looked at the Google VR SDK for android and there doesn't seem to be any support for this in the API. I know that there is support in the android SDK. 

Does anyone know how I can implement the controller laser pointer part with the SDK for android?

**Comment by jdduke** [comment]
Hi @nikhilcheruku12, you're absolutely right that the controller assets aren't included in the GVR SDK, though we do embed the assets in the Unity/Unreal GVR SDKs. We'll see about fixing this discrepancy.

In the meantime, we will be including a new API for arm model support in the next SDK release.

**Comment by famagusta** [comment]
I see a new version is out (1.70.0). Has the support for arm model been added?

**Comment by mgatelabs** [comment]
The Controller & ControllerManager classes have been added, and they provide details on the orientation and button status, but the position information seems broken.  The sample https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-controllerclient/src/main/java/com/google/vr/sdk/samples/controllerclient/ControllerClientActivity.java may be helpful, but it seems a bit broken.

**Comment by jdduke** [comment]
The Java APIs do not currently support the arm model. It is accessible via the native APIs, though it looks like our devsite docs don't yet reflect the addition. The API is described here: https://github.com/googlevr/gvr-android-sdk/blob/master/libraries/headers/vr/gvr/capi/include/gvr_controller.h#L226.
