### ISSUE TITLE
Integrating unity with Android

### ISSUE THREAD

**Issue by nikhilcheruku12** [googlevr/gvr-android-sdk#437]
I want to be able to use the File Selector UI API from the unity SDK. I have coded the rest of the app with google VR SDK for android and don't want to switch to implement the whole thing again just for one feature. I was wondering if there is a way to integrate the sdk with android .

**Comment by sigmaxipi** [comment]
There isn't an easy way to bring in a single Unity component into an Java VR app. You can create a new Unity Activity with the File Selector and then use the standard Android Intent system to send data between the two Activities, but this will result in a cross-Activity transition and will be slightly slower than implementing your own File Selector UI in Java.
