### ISSUE TITLE
com.google.vr:sdk-audio:1.60.1 can not find  

### ISSUE THREAD

**Issue by Howard9891** [googlevr/gvr-android-sdk#438]

**Comment by Howard9891** [comment]
compile 'com.google.vr:sdk-audio:1.60.1'
compile 'com.google.vr:sdk-base:1.60.1'

**Comment by hannesa2** [comment]
Hava a look to https://stackoverflow.com/questions/44230509/cant-build-an-official-example-from-google/44340736#44340736 Here you see the workaround

**Comment by sigmaxipi** [comment]
Sorry. There was a publishing error. This should be fixed now.

**Comment by Howard9891** [comment]
Ok thanks
