### ISSUE TITLE
Zooming the Panorama View

### ISSUE THREAD

**Issue by xrogerio** [googlevr/gvr-android-sdk#439]
Does anyone know how to zoom the pano image on the fullscreen mode (of course) via gesture, or know about some future implementation? Thanks in advance.

**Comment by axel20000** [comment]
I'm wondering the same thing.

**Comment by oliguo** [comment]
me too

**Comment by sigmaxipi** [comment]
Zooming isn't going to be supporte in VrView. If you want this functionality, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info. You can change the FOV used by `MonoscopicView` to effectively zoom the virtual camera.
