### ISSUE TITLE
Release notes link incorrect.

### ISSUE THREAD

**Issue by gpx1000** [googlevr/gvr-android-sdk#440]
It looks like the spatial media link that describes the updated HRTF in 1.6.1 is pointing to the threading issue from 1.4.0.
My best guess is the intention was to link it to here: https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md  As that's where the code seems to point for information.

**Comment by jkammerl** [comment]
Thanks for reporting the wrong link. We'll fix it soon! In the meantime, here's the correct one: https://github.com/google/spatial-media/tree/master/spatial-audio
