### ISSUE TITLE
What is the default viewport setting in the PanoViewer widget?

### ISSUE THREAD

**Issue by rfn123** [googlevr/gvr-android-sdk#441]
What is the default field of view/ focal length of the viewport in e.g. the PanoViewer sample? 
I've tried it on different mobile devices and the field of view for the same picture seems the same to me. So does the field of view of the viewports rather depend on the resolution on the provided panorama image than on the dpi of the screen?

**Comment by sigmaxipi** [comment]
Are you referring to the 2D mode or VR mode? The 2D mode uses 110 as the FOV on the long axis and adjusts the short axis based on the aspect ratio. In VR mode, the FOV is dependent on the distortion correction which is calculated from the viewer parameters.

**Comment by rfn123** [comment]
@sigmaxipi Yes I was actually referring to the VR mode, thanks for your reply! Is there any way to see how the FOV is calculated there?

**Comment by sigmaxipi** [comment]
There's no way to see the internals of VrView since we aren't planning on open sourcing it. But you can look at Video360 for more info one way of configuring the field of view for magic window UIs. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
