### ISSUE TITLE
Q / how am i write code about permission request?

### ISSUE THREAD

**Issue by miraclehwan** [googlevr/gvr-android-sdk#442]
hi, all.
I need to permisstion(READ & WRITE). so I used permisstion request dialog. 
but Daydream didn't recommend it. so I found [Method(exitFromVR)](https://developers.google.com/vr/android/ndk/jni/reference/com/google/vr/ndk/base/DaydreamApi.html#exitFromVr(Activity,%20int,%20Intent))

but I don't know how am i write code.
Please let me know sample code.

# refer to this image
<img src = 'https://user-images.githubusercontent.com/20110093/27716081-b2f143ba-5d76-11e7-999d-7ac3ecc8075c.png'>

**Comment by sigmaxipi** [comment]
`exitFromVr` is the correct API. When you want to exit, call that method. with a unique `requestCode`. The SDK will show an intermediate screen and then call your Activity with [Activity.onActivityResult](https://developer.android.com/reference/android/app/Activity.html#StartingActivities) using that request code. At this point, the user has removed the phone from their headset so it's safe to perform a standard Activity launch using `startActivity` and an Intent targeting your 2D Activity. Then have your 2D Activity request permission via `ActivityCompat.requestPermissions`. Once the permissions are granted, launch your VR Activity.

**Comment by miraclehwan** [comment]
@sigmaxipi 
Thank you for your comment.
Could I get a sample code please? I want to refer sample code.
