### ISSUE TITLE
Please let me know how am i use [exitFromVR] method.

### ISSUE THREAD

**Issue by miraclehwan** [googlevr/gvr-android-sdk#447]
Hi, all
I can used [launchVrHomescreen](https://developers.google.com/vr/android/ndk/jni/reference/com/google/vr/ndk/base/DaydreamApi.html#launchVrHomescreen())
but I can't use [exitFromVR](https://developers.google.com/vr/android/ndk/jni/reference/com/google/vr/ndk/base/DaydreamApi.html#exitFromVr(Activity,%20int,%20Intent)) method. because it is detected error about Null object refernce.

if do you have how to do use, please let me know.
I used GVRf SDK. so 'getContext' same 'mGVRContext.getContext'.
Sorry for my english is not good.

## below my code
```

        static DaydreamApi Dapi;

        mGVRContext.getActivity().runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Dapi = DaydreamApi.create(mGVRContext.getContext());
            }
        });

    public void testExit(){
//        Dapi.launchVrHomescreen();
        Activity test_activity = new testActivity();
        Dapi.exitFromVr(test_activity, 1, null);
       
    }

    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == 1) {
            if (resultCode == RESULT_OK) {

            }
        }
    }
```

## Error Log
```
07-17 16:10:44.924 32630-32630/daehwankim.com.mediaplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: daehwankim.com.mediaplayer, PID: 32630
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.vr.ndk.base.DaydreamApi.exitFromVr(android.app.Activity, int, android.content.Intent)' on a null object reference
                                                                                at daehwankim.com.mediaplayer.Main.testExit(Main.java:934)
                                                                                at daehwankim.com.mediaplayer.Main$1$1.run(Main.java:314)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```

**Comment by jdduke** [comment]
Hi @miraclehwan, DaydreamApi.create() will only return a valid instance if you're running on a Daydream-ready phone. Otherwise it returns null. What model phone are you using?

**Comment by miraclehwan** [comment]
I used pixel phone.
Do you have example code?
I try to exitfromvr. But i got a pendingintent null point error. So I create another solve the problem.
Coulde you check my another solve the problem code?

I want publishing my app in daydreamstore.

**Comment by jdduke** [comment]
You cannot pass null as the PendingIntent argument. You need to use something like:

`
Intent permissionsIntent = new Intent(context, /* insert activity class here */);
PendingIntent pendingPermissionsIntent = PendingIntent.getActivity(context, 0, permissionsIntent, PendingIntent.FLAG_ONE_SHOT);
`

Where you use the appropriate class/ComponentName for the Activity that will request the permission.

**Comment by miraclehwan** [comment]
@jdduke 
Thank you for your code.
I can move to 2D Activity. but I can't show prompt.

<img src="https://user-images.githubusercontent.com/20110093/28345273-230c25f6-6c64-11e7-9fa8-2fd19467ac9a.png" />

How can i show prompt ??

**Comment by ECSGuy** [comment]
Just from what is on the website currently (not sure if you already solved this), but here is the text before the image you posted (the one about 'Prompt the user to remove their phone'):

------------------------------------------------
This is meant to be a very rare occurrence, and only for a small set of circumstances. One reason might be needing to prompt the user to accept a dangerous permission. Unfortunately, currently dangerous permissions can only be accepted with 2D monoscopic dialog boxes. **This won’t be addressed with in-VR dialog boxes until the next version of Android.** Another reason might be displaying a webview, for a login process with a third party that requires the web.

When making this transition, **your app must do the following:**

Prompt the user to remove their phone.
Detect the orientation change to portrait to switch over to 2D.
Provide the user with a button to return them to VR.

--------------------------------------------------------------------------

So in your game/app (either with Android widgets or your own game rendering a UI) you must do the prompting (e.g. drawing the UI screen telling the user to remove their headset, etc). It looks like they plan to address permissions later...

Matt

**Comment by jdduke** [comment]
@miraclehwan: The only existing prompt to exit VR is provided by [DaydreamApi.exitFromVr().](https://developers.google.com/vr/android/reference/com/google/vr/ndk/base/DaydreamApi.html#exitFromVr(android.app.Activity, int, android.content.Intent)). Did that not work for you?

**Comment by sigmaxipi** [comment]
See the new Video360 sample for information on how to use this API: https://developers.google.com/vr/android/samples/video360#permissions_and_hybrid_vr_app_flow
