### ISSUE TITLE
libraries/jni/ directory missing from repository

### ISSUE THREAD

**Issue by rishi-rranjan** [googlevr/gvr-android-sdk#451]
In the ndk samples, build.gradle refers to libraries/jni/ to find GVR .so files but these are missing from the repository. Where can we find these .so files? 

[build.gradle](https://github.com/googlevr/gvr-android-sdk/blob/v1.60.1/samples/ndk-treasurehunt/build.gradle)

`        ldFlags.add("-L" + file("${project.rootDir}/libraries/jni/arm64-v8a").absolutePath)
        ldFlags.add("-L" + file("${project.rootDir}/libraries/jni/armeabi-v7a").absolutePath)
        ldFlags.add("-L" + file("${project.rootDir}/libraries/jni/x86").absolutePath)`

**Comment by jdduke** [comment]
See https://github.com/googlevr/gvr-android-sdk/blob/532b73c745e61256232176951e657694664ef122/settings.gradle#L13. You need to run the extractNdk() step first.
