### ISSUE TITLE
ndk-treasurehunt and ndk-controllerpaint compilation fails due to missing gvr.so

### ISSUE THREAD

**Issue by rishi-rranjan** [googlevr/gvr-android-sdk#452]
NDK samples don't compile. Below is the error message.  Where can I find gvr.so? I don't see it under gvr-android-sdk\libraries. 

aarch64-linux-android/bin/ld.exe: cannot find -lgvr

**Comment by jdduke** [comment]
You'll need to run the extractNdk() step to pull the libraries out of the .aar file. See also https://github.com/googlevr/gvr-android-sdk/blob/532b73c745e61256232176951e657694664ef122/settings.gradle#L13.
