### ISSUE TITLE
sdk videoplayer can't start due to libgvr.so tombstone

### ISSUE THREAD

**Issue by libinta** [googlevr/gvr-android-sdk#453]
I downloaded the sdk code from master, built with android studio2.3.3, and install on nexus 9 7.1.1.
The videoplayer app crashed at starting due to libgvr.so. The simplevideowidget app is fine.

The crash shows:

07-28 12:59:45.937 602-613/? I/ActivityManager: Start proc 4337:com.google.vr.sdk.samples.videoplayer/u0a93 for activity com.google.vr.sdk.samples.videoplayer/.WatchVideoActivity
07-28 12:59:45.941 4337-4337/? I/art: Late-enabling -Xcheck:jni
07-28 12:59:45.974 602-1098/? I/ActivityManager: Start proc 4351:com.google.android.apps.photos/u0a76 for broadcast com.google.android.apps.photos/.experiments.phenotype.AppUpgradeBroadcastReceiver
07-28 12:59:46.023 4337-4337/? D/AndroidNCompat: Sustained performance mode is not supported on this device.
07-28 12:59:46.023 4337-4337/? D/AndroidNCompat: VR mode is not supported on this N device.
07-28 12:59:46.031 4337-4337/? W/SdkConfigurationReader: VrParamsProvider returned null params, using defaults.
07-28 12:59:46.034 4337-4337/? V/GvrLayoutFactory: Dynamic library loading disabled, using built-in GvrLayout implementation.
07-28 12:59:46.042 694-694/? W/asset: Asset path /data/app/com.google.vr.sdk.samples.videoplayer-1/base.apk is neither a directory nor file (type=1).
07-28 12:59:46.042 694-694/? E/ResourcesManager: failed to add asset path /data/app/com.google.vr.sdk.samples.videoplayer-1/base.apk
07-28 12:59:46.042 694-694/? W/PackageManager: Failure retrieving resources for com.google.vr.sdk.samples.videoplayer
07-28 12:59:46.042 694-694/? W/asset: Asset path /data/app/com.google.vr.sdk.samples.videoplayer-1/base.apk is neither a directory nor file (type=1).
07-28 12:59:46.042 694-694/? E/ResourcesManager: failed to add asset path /data/app/com.google.vr.sdk.samples.videoplayer-1/base.apk
07-28 12:59:46.042 694-694/? W/PackageManager: Failure retrieving resources for com.google.vr.sdk.samples.videoplayer
07-28 12:59:46.060 4337-4337/? D/ConfigUtils: Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device_params (No such file or directory)
07-28 12:59:46.065 4337-4337/? I/GVR: [vr/gvr/capi/src/gvr.cc:99] Initialized GVR version 1.70.0
07-28 12:59:46.068 4337-4371/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
07-28 12:59:46.075 602-2035/? I/CwMcuSensor: CwMcuSensor::flush: fd = 267, sensors_id = 0, path = /sys/class/htc_sensorhub/sensor_hub/flush, err = 0
07-28 12:59:46.081 4337-4337/? D/GvrLayoutFactory: Loaded GvrLayout from SDK.
07-28 12:59:46.085 4337-4337/? E/WatchVideoActivity: UnsupportedException: Async Reprojection with Video is unsupported.
07-28 12:59:46.119 1433-1944/? I/Icing: Usage reports 8 indexed 0 rejected 0 imm upload false
07-28 12:59:46.143 245-245/? D/WVCdm: Instantiating CDM.
07-28 12:59:46.158 4337-4337/? I/ExoPlayerImpl: Init ExoPlayerLib/2.4.0 [flounder_lte, Nexus 9, htc, 25]
07-28 12:59:46.182 4351-4351/? W/System: ClassLoader referenced unknown path: /system/app/Photos/lib/arm64
07-28 12:59:46.187 1433-1944/? I/Icing: Usage reports 0 indexed 0 rejected 0 imm upload true
07-28 12:59:46.200 1433-1944/? I/Icing: Usage reports 0 indexed 0 rejected 0 imm upload false
07-28 12:59:46.216 2695-4304/? I/UpdateIcingCorporaServi: UpdateCorporaTask done [took 690 ms] updated apps [took 689 ms] 
07-28 12:59:46.219 4337-4377/? D/ConfigUtils: Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device_params (No such file or directory)
07-28 12:59:46.262 4337-4385/? I/OpenGLRenderer: Initialized EGL, version 1.4
07-28 12:59:46.262 4337-4385/? D/OpenGLRenderer: Swap behavior 2
07-28 12:59:46.483 4337-4381/? W/VideoCapabilities: Unrecognized level 0 for video/x-vnd.on2.vp8
07-28 12:59:46.501 4337-4381/? I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
07-28 12:59:46.507 4337-4381/? D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.64002a, video/avc] [OMX.Nvidia.h264.decode, video/avc] [flounder_lte, Nexus 9, htc, 25]
07-28 12:59:46.679 4337-4377/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xffffffffffffff80 in tid 4377 (GLThread 322)
                                       
                                       [ 07-28 12:59:46.679   187:  187 W/         ]
                                       debuggerd: handling request: pid=4337 uid=10093 gid=10093 tid=4377
07-28 12:59:46.717 4392-4392/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-28 12:59:46.717 4392-4392/? A/DEBUG: Build fingerprint: 'google/volantisg/flounder_lte:7.1.1/N4F27I/4072761:user/release-keys'
07-28 12:59:46.717 4392-4392/? A/DEBUG: Revision: '0'
07-28 12:59:46.717 4392-4392/? A/DEBUG: ABI: 'arm64'
07-28 12:59:46.718 4392-4392/? A/DEBUG: pid: 4337, tid: 4377, name: GLThread 322  >>> com.google.vr.sdk.samples.videoplayer <<<
07-28 12:59:46.718 4392-4392/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffffffffff80
07-28 12:59:46.718 4392-4392/? A/DEBUG:     x0   00000074223a7e40  x1   ffffffffffffff80  x2   1ffffffffffffff8  x3   00000074234429e8
07-28 12:59:46.718 4392-4392/? A/DEBUG:     x4   0000000000000000  x5   0000000000000000  x6   000000003cee1111  x7   0000000000000000
07-28 12:59:46.718 4392-4392/? A/DEBUG:     x8   00000074234429e8  x9   00000000021951a0  x10  0000000000000001  x11  0000000000000000
07-28 12:59:46.718 4392-4392/? A/DEBUG:     x12  000000000000053a  x13  0000000000000360  x14  000000000000000c  x15  2e8ba2e8ba2e8ba3
07-28 12:59:46.718 4392-4392/? A/DEBUG:     x16  0000007437887978  x17  0000007441a83b80  x18  0000007422a2ced8  x19  0000007423b89c60
07-28 12:59:46.718 4392-4392/? A/DEBUG:     x20  000000742298f098  x21  0000007423b89c38  x22  000000743eff6fa0  x23  00000074233f7800
07-28 12:59:46.718 4392-4392/? A/DEBUG:     x24  0000007433bb7000  x25  000000742298f0a0  x26  000000743eff6fa8  x27  fffffffffffffff8
07-28 12:59:46.718 4392-4392/? A/DEBUG:     x28  000000742298f0c0  x29  0000007423b8a1d8  x30  00000074376e3348
07-28 12:59:46.718 4392-4392/? A/DEBUG:     sp   0000007423b89ba0  pc   ffffffffffffff80  pstate 0000000060000000
07-28 12:59:46.721 4392-4392/? A/DEBUG: backtrace:
07-28 12:59:46.722 4392-4392/? A/DEBUG:     #00 pc ffffffffffffff80  <unknown>
07-28 12:59:46.722 4392-4392/? A/DEBUG:     #01 pc 000000000005a344  /data/app/com.google.vr.sdk.samples.videoplayer-2/lib/arm64/libgvr.so
07-28 12:59:46.722 4392-4392/? A/DEBUG:     #02 pc 0000000000045bcc  /data/app/com.google.vr.sdk.samples.videoplayer-2/lib/arm64/libgvr.so
07-28 12:59:46.722 4392-4392/? A/DEBUG:     #03 pc 0000000000045c68  /data/app/com.google.vr.sdk.samples.videoplayer-2/lib/arm64/libgvr.so (gvr_frame_submit+100)
07-28 12:59:46.722 4392-4392/? A/DEBUG:     #04 pc 0000000000051eec  /data/app/com.google.vr.sdk.samples.videoplayer-2/lib/arm64/libgvr.so (Java_com_google_vr_ndk_base_GvrApi_nativeFrameSubmit+128)
07-28 12:59:46.722 4392-4392/? A/DEBUG:     #05 pc 000000000035f538  /data/app/com.google.vr.sdk.samples.videoplayer-2/oat/arm64/base.odex (offset 0x33e000)
07-28 12:59:46.897 1044-1044/? E/NetworkScheduler.SR: Invalid parameter app
07-28 12:59:46.897 1044-1044/? E/NetworkScheduler.SR: Invalid package name : Perhaps you didn't include a PendingIntent in the extras?
07-28 12:59:47.071 1433-1888/? I/Icing: Usage reports 0 indexed 0 rejected 0 imm upload false
07-28 12:59:47.079 1433-1888/? I/Icing: Usage reports 0 indexed 0 rejected 0 imm upload false
07-28 12:59:47.205 1433-1888/? I/Icing: Indexing C9FBCA171A44FB10FDE7911E937BC1240B138650 from com.google.android.gms
07-28 12:59:47.286 1433-1888/? I/Icing: Indexing done C9FBCA171A44FB10FDE7911E937BC1240B138650
07-28 12:59:47.287 1433-1888/? I/Icing: Indexing BDF67CDBB914ED84881B307892E9A4335E89EE9B from com.google.android.googlequicksearchbox
07-28 12:59:47.334 1433-1888/? I/Icing: Indexing done BDF67CDBB914ED84881B307892E9A4335E89EE9B
07-28 12:59:47.663 602-4403/? W/ActivityManager:   Force finishing activity com.google.vr.sdk.samples.videoplayer/.WatchVideoActivity
07-28 12:59:47.667 602-619/? I/BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
                                             
                                             [ 07-28 12:59:47.667   187:  187 W/         ]
                                             debuggerd: resuming target 4337
07-28 12:59:47.671 602-615/? I/VrManagerService: VR mode disabled

Can you please help?

Thanks.

**Comment by jdduke** [comment]
Thanks for the report, but the VideoPlayer is only supported on Daydream-ready devices (the Nexus 9 is not Daydream-ready). Execution on unsupported devices will often result in undefined behavior (see the restriction @ https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-videoplayer/src/main/AndroidManifest.xml#L21).

**Comment by libinta** [comment]
Thanks. Which portion is not supported on Nexus 9? Does the stream portion? Since the samplevideowidget seems play ok

**Comment by jdduke** [comment]
This VideoPlayer sample uses some special APIs for drawing protected content to externally-managed Surfaces, a path which is unsupported on non-Daydream devices. The videowidget uses a very different rendering approach.
