### ISSUE TITLE
only black rectangle show on screen in sdk-videoplayer sample

### ISSUE THREAD

**Issue by moonfan** [googlevr/gvr-android-sdk#454]
I have got all of the samples work on Huawei Mate 9 Pro excepted  sdk-videoplayer. The audio work just fine,however,only black rectangle show on screen for both eyes. I have even tried integrating the sample with exoplayer source code to track the process of downloading&decoding&rendering(Mediacodec stuff), everything work just fine inside exoplayer.

Please help to work this sample out on Huawei Mate 9 Pro, thanks in advance!

**Comment by jclova** [comment]
Similar. I ran this sample app on Pixel phone and I only see a black screen with a spinning wheel (not animating) in the center. No sound either.
From the source, I only modified the build tool version to "25.0.3".

**Comment by jdduke** [comment]
@moonfan: Can you share which version of Google VR Services you have installed? And what Android build you're using? Thanks. If you could capture and share a bug report, that would be even better.

**Comment by jdduke** [comment]
There was an issue with the VideoPlayer sample on Huawei devices, but it should have been fixed in the latest 1.80.0 release. Can you try again with the updated libraries?

**Comment by jclova** [comment]
Screenshot: http://imgur.com/a/tt1n8
Pixel phone: Android 7.1.2
Android Studio: 3.0 beta 1
Source code: Latest 1.80.0 release

Only modified build too version to '25.0.3'

Dependency versions:
    compile 'com.google.android.exoplayer:exoplayer:r2.4.0'
    compile 'com.google.android.exoplayer:extension-gvr:r2.4.0'
    compile 'com.google.vr:sdk-base:1.80.0'
    compile 'com.google.vr:sdk-common:1.80.0'

**Comment by moonfan** [comment]
@jdduke The latest 1.80.0 release works fine now, thanks for your help!
