### ISSUE TITLE
VrPanoramaView image scrolls only in cylindrical form

### ISSUE THREAD

**Issue by aNnYvIrUs** [googlevr/gvr-android-sdk#455]
VrPanoramaView image scrolls only in cylindrical form how it can be moves in 360 degree(Spherical form)... please help me for this problem.

**Comment by ytplylm** [comment]
I have the same problem.

**Comment by sigmaxipi** [comment]
If you want more complex touch & gyro controls, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
