### ISSUE TITLE
VrVideoPlayer in ndk?

### ISSUE THREAD

**Issue by cjayanth95** [googlevr/gvr-android-sdk#457]
I am trying to play an equirectangular projection video using ndk. (Trying to build a videowidget with ndk.) Is there a VrVideoPlayer equivalent in ndk?

**Comment by sigmaxipi** [comment]
There is no NDK version of the VrView widgets. However, consider using the Video360 sample as a starting point. It's pure Java, but it demonstrates the OpenGL and math required to render a 360 video in VR. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
