### ISSUE TITLE
TreasureHunt-NDK draw error when using multiview

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-android-sdk#458]
Here is the log:
08-04 15:35:32.739 11526-11526/? D/TreasureHuntCPP: Viewer type: CARDBOARD
08-04 15:35:32.899 11526-11661/? D/TreasureHuntCPP: Using multiview.
08-04 15:36:25.729 11787-11787/? D/TreasureHuntCPP: Viewer type: CARDBOARD
08-04 15:36:25.869 11787-11884/? D/TreasureHuntCPP: Using multiview.
08-04 15:36:25.929 11787-11884/? W/TreasureHuntCPP: GL error @ Drawing cube: 1280

SDK version:
dependencies {
    compile 'com.google.vr:sdk-audio:1.70.0'
    compile 'com.google.vr:sdk-base:1.70.0'
}

I tried with xiao mi 5 and Oppo r9 Plus.

**Comment by jdduke** [comment]
Thanks for the feedback, we're investigating internally.

**Comment by prideout** [comment]
Multiview is an experimental feature on non-Daydream devices, if they happen to support the relevant OpenGL extensions.

Going forward, we will only support this feature on Daydream-ready devices, since other devices don't necessarily pass our OpenGL driver conformance tests.

**Comment by jdduke** [comment]
The next SDK release should properly restrict multiview only to whitelisted devices that are known to support the feature. Apologies for any confusion.
