### ISSUE TITLE
updateCardboardDeviceParams/updateScreenParams

### ISSUE THREAD

**Issue by yolanother** [googlevr/gvr-android-sdk#46]
The documentation says that calling updateCardboardDeviceParams and updateScreenParams will be reflected in the next new frame, but this doesn't seem to happen. I have only been able to get these methods to do anything by calling them in onCreate before the GL surface is created.

"Updates the screen parameters of the device inserted in the Cardboard. Changes will be effective from the first frame after this call."

**Comment by smdol** [comment]
Which version of Android (on which phones) are you seeing the problem?

**Comment by yolanother** [comment]
This one I know I'm seeing on the same L devices as the other thread that is going, but I believe I also experienced this with the note 5 as well. I can get the updates to apply if I remove the cardboardview  and recreate it.

**Comment by jdduke** [comment]
Note that you'll also need to call these methods *after* you call onResume() on the GvrView. The documentation has been updated to reflect this.
