### ISSUE TITLE
VrPanoramaView's memory leak?

### ISSUE THREAD

**Issue by momoandy** [googlevr/gvr-android-sdk#461]
I used VrPanoramaView.shutdown() after Activity's onDestroy,but also exist memory leak. I see sdk code, then use VrPanoramaViewsetEventListener(null) and VrPanoramaView.loadImageFromBitmap(null, null). The  memory leak is missing. I want to ask, all that is really or my mistake? who can tell me?

**Comment by yinleunglai** [comment]
I also get this leak issue.

**Comment by jdduke** [comment]
Can you provide more details about the leak? Do you still see the leak in the latest SDK?

**Comment by jdduke** [comment]
Happy to reopen the issue if it's still reproducible with the latest SDK (there have been a large number of changes/fixes since August).
