### ISSUE TITLE
Upload failed Duplicate declarations of permission android.permission.READ_EXTERNAL_STORAGE with different maxSdkVersions.

### ISSUE THREAD

**Issue by ECSGuy** [googlevr/gvr-android-sdk#462]
Hey guys,
  I'm going to ask about this here as it clearly pertains to our apps trying to be Google VR apps, etc. though I am sure this hits regular, non-VR apps as well.

  To begin with, we're using the Google VR NDK version 1.70 (latest from today, at least) and NVidia's Tegra development tools (as it best integrates with our pipeline, etc.)

  I cannot, for the life of me, find out where this nasty little bastard permission is getting added:
...
    <android:uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />
...
  I've searched my entire hard drive for ANY possible inclusion of the READ_EXTERNAL_STORAGE with the troubling android:maxSdkVersion="18" addition and NOTHING comes up.

  The reason I need this permission removed is that the Google Play Console will not let me upload my APK claiming (rightfully so! - see attached image).
<img width="485" alt="capture" src="https://user-images.githubusercontent.com/17238641/29052402-b123beb4-7b9e-11e7-8f52-b9d05549bb8e.PNG">

  I've tried tools:node="replace" all the way to tools:node="remove"... I just get this nonsense:
"android:uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at nsight_tegra_manifest.xml:24 to remove other declarations but no other declaration present" (perhaps I am setting this incorrectly, but, um, I feel like the manifest is fairly robust here...)  I say nonsense because THIS is the final merged manifest (snippet) no matter WHAT I do:
...
    <uses-sdk
        android:minSdkVersion="24"
        android:targetSdkVersion="24" />
    
    <uses-feature
        android:glEsVersion="0x00030000"
        android:required="true" />
    
    <uses-feature
        android:name="android.hardware.sensor.accelerometer"
        android:required="true" />
    <uses-feature
        android:name="android.hardware.sensor.gyroscope"
        android:required="true" />
    <uses-feature
        android:name="android.hardware.vr.high_performance"
        android:required="true" />
    <uses-feature
        android:name="android.software.vr.mode"
        android:required="true" />
    
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <android:uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />

    <application
        android:hasCode="True"
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/VrActivityTheme" >
...

  My only conclusion is that this is either NVidia's tools (I've written them as well, plus I'll send them the link to this report) or it's in the Google Android toolset buried deep where.... I don't know what to say here :).

  I'm just hoping that this is a trivial mistake on my end.  I've upgraded, cleaned out files, moved projects to different machines, etc.

  Nothing works; I keep getting this absolutely ridiculous, hidden, AUTO-MAGIC nonsense.

  Here's a version of the merging log:
-- Merging decision tree log ---
manifest
ADDED from nsight_tegra_manifest.xml:3:1
	package
		ADDED from nsight_tegra_manifest.xml:4:11
	android:versionName
		ADDED from nsight_tegra_manifest.xml:6:11
	xmlns:tools
		ADDED from nsight_tegra_manifest.xml:7:11
	android:versionCode
		ADDED from nsight_tegra_manifest.xml:5:11
		INJECTED from nsight_tegra_manifest.xml:0:0
		INJECTED from nsight_tegra_manifest.xml:0:0
	xmlns:android
		ADDED from nsight_tegra_manifest.xml:3:11
uses-sdk
ADDED from nsight_tegra_manifest.xml:8:3
MERGED from com.google.vr:sdk-audio:1.70.0:3:5
MERGED from com.google.vr:sdk-base:1.70.0:5:5
MERGED from com.google.vr:sdk-common:1.70.0:3:5
MERGED from com.google.vr:sdk-base:1.70.0:5:5
MERGED from com.google.vr:sdk-common:1.70.0:3:5
	android:targetSdkVersion
		ADDED from nsight_tegra_manifest.xml:8:40
		INJECTED from nsight_tegra_manifest.xml:0:0
		INJECTED from nsight_tegra_manifest.xml:0:0
	android:minSdkVersion
		ADDED from nsight_tegra_manifest.xml:8:13
		INJECTED from nsight_tegra_manifest.xml:0:0
		INJECTED from nsight_tegra_manifest.xml:0:0
application
ADDED from nsight_tegra_manifest.xml:9:3
	android:hasCode
		ADDED from nsight_tegra_manifest.xml:9:86
	android:label
		ADDED from nsight_tegra_manifest.xml:9:16
	android:icon
		ADDED from nsight_tegra_manifest.xml:9:49
	android:theme
		ADDED from nsight_tegra_manifest.xml:10:16
activity#[my package name]
ADDED from nsight_tegra_manifest.xml:11:5
	android:screenOrientation
		ADDED from nsight_tegra_manifest.xml:14:15
	android:enableVrMode
		ADDED from nsight_tegra_manifest.xml:17:15
	android:label
		ADDED from nsight_tegra_manifest.xml:12:15
	android:launchMode
		ADDED from nsight_tegra_manifest.xml:15:15
	android:resizeableActivity
		ADDED from nsight_tegra_manifest.xml:18:15
	android:configChanges
		ADDED from nsight_tegra_manifest.xml:16:15
	android:icon
		ADDED from nsight_tegra_manifest.xml:13:15
	android:name
		ADDED from nsight_tegra_manifest.xml:11:15
meta-data#android.app.lib_name
ADDED from nsight_tegra_manifest.xml:20:7
	android:value
		ADDED from nsight_tegra_manifest.xml:20:54
	android:name
		ADDED from nsight_tegra_manifest.xml:20:18
meta-data#com.google.android.vr.icon
ADDED from nsight_tegra_manifest.xml:21:7
	android:resource
		ADDED from nsight_tegra_manifest.xml:21:60
	android:name
		ADDED from nsight_tegra_manifest.xml:21:18
meta-data#com.google.android.vr.icon_background
ADDED from nsight_tegra_manifest.xml:22:7
	android:resource
		ADDED from nsight_tegra_manifest.xml:22:71
	android:name
		ADDED from nsight_tegra_manifest.xml:22:18
android:uses-permission#android.permission.READ_EXTERNAL_STORAGE
ADDED from nsight_tegra_manifest.xml:24:7
IMPLIED from nsight_tegra_manifest.xml:3:1 reason: com.google.vr.sdk.base requested WRITE_EXTERNAL_STORAGE
	tools:node
		ADDED from nsight_tegra_manifest.xml:24:88
	android:name
		ADDED from nsight_tegra_manifest.xml:24:32
intent-filter#android.intent.action.MAIN+android.intent.category.LAUNCHER+com.google.intent.category.DAYDREAM
ADDED from nsight_tegra_manifest.xml:25:7
action#android.intent.action.MAIN
ADDED from nsight_tegra_manifest.xml:26:9
	android:name
		ADDED from nsight_tegra_manifest.xml:26:17
category#android.intent.category.LAUNCHER
ADDED from nsight_tegra_manifest.xml:27:9
	android:name
		ADDED from nsight_tegra_manifest.xml:27:19
category#com.google.intent.category.DAYDREAM
ADDED from nsight_tegra_manifest.xml:29:9
	android:name
		ADDED from nsight_tegra_manifest.xml:29:19
uses-feature#0x00030000
ADDED from nsight_tegra_manifest.xml:34:3
	android:glEsVersion
		ADDED from nsight_tegra_manifest.xml:34:17
	android:required
		ADDED from nsight_tegra_manifest.xml:34:50
uses-feature#android.hardware.sensor.accelerometer
ADDED from nsight_tegra_manifest.xml:36:3
	android:required
		ADDED from nsight_tegra_manifest.xml:36:70
	android:name
		ADDED from nsight_tegra_manifest.xml:36:17
uses-feature#android.hardware.sensor.gyroscope
ADDED from nsight_tegra_manifest.xml:37:3
	android:required
		ADDED from nsight_tegra_manifest.xml:37:66
	android:name
		ADDED from nsight_tegra_manifest.xml:37:17
uses-feature#android.hardware.vr.high_performance
ADDED from nsight_tegra_manifest.xml:38:3
MERGED from com.google.vr:sdk-base:1.70.0:15:5
MERGED from com.google.vr:sdk-base:1.70.0:15:5
	android:required
		ADDED from nsight_tegra_manifest.xml:38:69
	android:name
		ADDED from nsight_tegra_manifest.xml:38:17
uses-feature#android.software.vr.mode
ADDED from nsight_tegra_manifest.xml:39:3
MERGED from com.google.vr:sdk-base:1.70.0:13:5
MERGED from com.google.vr:sdk-base:1.70.0:13:5
	android:required
		ADDED from nsight_tegra_manifest.xml:39:57
	android:name
		ADDED from nsight_tegra_manifest.xml:39:17
uses-feature#0x00020000
ADDED from com.google.vr:sdk-base:1.70.0:6:5
MERGED from com.google.vr:sdk-base:1.70.0:6:5
REJECTED from nsight_tegra_manifest.xml:6:5
	android:glEsVersion
		ADDED from com.google.vr:sdk-base:1.70.0:6:19
	android:required
		ADDED from com.google.vr:sdk-base:1.70.0:6:52
uses-permission#android.permission.READ_EXTERNAL_STORAGE
ADDED from com.google.vr:sdk-base:1.70.0:9:5
MERGED from com.google.vr:sdk-base:1.70.0:9:5
	android:name
		ADDED from com.google.vr:sdk-base:1.70.0:9:22
uses-permission#android.permission.WRITE_EXTERNAL_STORAGE
ADDED from com.google.vr:sdk-base:1.70.0:10:5
MERGED from com.google.vr:sdk-base:1.70.0:10:5
	android:name
		ADDED from com.google.vr:sdk-base:1.70.0:10:22
----
And here's the output from the tool itself:
1>  All input files are considered out-of-date for incremental task ':processReleaseManifest'.
1>  Loading library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-audio\1.70.0\AndroidManifest.xml
1>  Loading library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-base\1.70.0\AndroidManifest.xml
1>  Loading library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-common\1.70.0\AndroidManifest.xml
1>  Loading library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-base\1.70.0\AndroidManifest.xml
1>  Loading library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-common\1.70.0\AndroidManifest.xml
1>  Merging main manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\nsight_tegra_manifest.xml
1>
1>  Merging library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-audio\1.70.0\AndroidManifest.xml
1>  Merging manifest with lower com.google.vr:sdk-audio:1.70.0:2:1
1>  Merging uses-sdk with lower com.google.vr:sdk-audio:1.70.0:3:5
1>  Merging library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-base\1.70.0\AndroidManifest.xml
1>  Merging manifest with lower com.google.vr:sdk-base:1.70.0:2:1
1>  Merging uses-sdk with lower com.google.vr:sdk-base:1.70.0:5:5
1>  Merging uses-feature#android.software.vr.mode with lower com.google.vr:sdk-base:1.70.0:13:5
1>  Merging uses-feature#android.hardware.vr.high_performance with lower com.google.vr:sdk-base:1.70.0:15:5
1>  Merging library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-common\1.70.0\AndroidManifest.xml
1>  Merging manifest with lower com.google.vr:sdk-common:1.70.0:2:1
1>  Merging uses-sdk with lower com.google.vr:sdk-common:1.70.0:3:5
1>  Merging library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-base\1.70.0\AndroidManifest.xml
1>  Merging manifest with lower com.google.vr:sdk-base:1.70.0:2:1
1>  Merging uses-sdk with lower com.google.vr:sdk-base:1.70.0:5:5
1>  Merging uses-feature#0x00020000 with lower com.google.vr:sdk-base:1.70.0:6:5
1>  Merging uses-permission#android.permission.READ_EXTERNAL_STORAGE with lower com.google.vr:sdk-base:1.70.0:9:5
1>  Merging uses-permission#android.permission.WRITE_EXTERNAL_STORAGE with lower com.google.vr:sdk-base:1.70.0:10:5
1>  Merging uses-feature#android.software.vr.mode with lower com.google.vr:sdk-base:1.70.0:13:5
1>  Merging uses-feature#android.hardware.vr.high_performance with lower com.google.vr:sdk-base:1.70.0:15:5
1>  Merging library manifest [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\exploded-aar\com.google.vr\sdk-common\1.70.0\AndroidManifest.xml
1>  Merging manifest with lower com.google.vr:sdk-common:1.70.0:2:1
1>  Merging uses-sdk with lower com.google.vr:sdk-common:1.70.0:3:5
1>TRACKEDTOOLTASKWRAPPER`1 : warning : [the path to my files]\Tegra-Android\GoogleVR_Final\build\nsight_tegra_manifest.xml:24:7 Warning:
1>  	android:uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at nsight_tegra_manifest.xml:24 to remove other declarations but no other declaration present
1>  Merging result:WARNING
1>  [the path to my files]\Tegra-Android\GoogleVR_Final\build\nsight_tegra_manifest.xml:24:7 Warning:
1>  	android:uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at nsight_tegra_manifest.xml:24 to remove other declarations but no other declaration present
1>  Merged manifest saved to [the path to my files]\Tegra-Android\GoogleVR_Final\build\intermediates\manifests\full\release\AndroidManifest.xml
-------------------------------------------------------------------------------------------------------

.... help?

Matt

**Comment by ECSGuy** [comment]
Quick update, NVidia have confirmed that they are NOT injecting any permissions, etc.  Just a quick shout out to Daniel Horowitz and Mikhail Filimonov; thank you SO much for answering so quickly!  And, er, sorry I'm grumpy... :|

**Comment by sigmaxipi** [comment]
Each .aar has its own AndroidManifest.xml and the READ_EXTERNAL_STORAGE permission comes from https://github.com/googlevr/gvr-android-sdk/blob/master/libraries/sdk-base-1.70.0.aar where it's used to store a shared viewer profile on the sdcard. However, that has `<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="19"/>`. and no `maxSdkVersion`

You can try using `aapt dump permissions $THE_APK` to see if this is the issue or try to track down which library is adding that permission to the final APK.

**Comment by ECSGuy** [comment]
sigmaxipi,
  THANK YOU!  I'll run the tool as soon as I can (travelling right now)....  (I'm chomping at the bit to check these!!)

Matt

**Comment by ECSGuy** [comment]
Apologies; I've had a family emergency for the past week or so.  I'll get back to you on this asap; thanks again for answering!

**Comment by ECSGuy** [comment]
Hey sigmaxipi,
  It looks like my partner, Francois, found a way around this.  I didn't have the override (tools:* statement) in the right place.  It must be AFTER the application:

...
</application>
  <android:uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="replace" />
...

  Anyhow, we aren't able to locate the exact place/binary where the extraneous permission is inserted.  Our guess at this point is the com.android plug-in for gradle somehow contributing this (we leave the version at the default; when I tried changing this lots of other dependencies on gradle versions complained, etc.)

  I hope this is some kind of help to anyone else that isn't able to get around this issue.  Thanks, sigmaxipi for your help!

Matt
