### ISSUE TITLE
Lock Gyro values

### ISSUE THREAD

**Issue by bipin-logic** [googlevr/gvr-android-sdk#465]
I'm facing a problem regarding Google VR SDK. I have a scenario in which I need to set the orientation of my camera to certain values but it seems like SDK is overriding all of my values with Device's gyro values.From what I think, I need to disable the values coming in from gyro. I first tried to disable the gyro explicitly but it doesn't seem to work then I tried going through SDK scripts which wasn't of much help.

Thank you for any help in advance.

**Comment by nathanmartz** [comment]
Head tracking is a fundamental part of the VR SDK. If you don't want head tracking, but to shut down GVR.

**Comment by bipin-logic** [comment]
Thank you, Nathan, for your reply.
