### ISSUE TITLE
I would like to play audio with GvrAudioEngine, but some wav files does not work 

### ISSUE THREAD

**Issue by newerZGQ** [googlevr/gvr-android-sdk#467]
Do I need to do something about the file?

**Comment by jkammerl** [comment]
We use Android's media codec APIs to decode sound files. The list of supported formats can be found here:
http://developer.android.com/guide/appendix/media-formats.html
For wav files, only 8- and 16-bit linear PCM with sampling rates of 8000, 16000 and 44100 Hz are supported.
