### ISSUE TITLE
VrPanoramaView goes blank on switch from Stereo to Mono mode

### ISSUE THREAD

**Issue by jkane001** [googlevr/gvr-android-sdk#468]
I've implemented VrPanoramaView in our app, and load the pano image directly into Mono, Full-screen mode when the user taps a button. The image is loaded (via Picasso) from a remote server, into a BitMap, which is loaded into the view, with no problems. I can hit the goggles icon to get to stereo mode, and that all works fine as well.

However, when I hit the icon to return to mono full-screen mode, the full screen 360 shows up for a second, and then goes completely blank, and nothing happens from there. I can close the view, and return to the view that houses the button that launched the VR, so the app isn't really hung or crashed, but it's a weird user experience. 

BTW, you can go back into the VR view just fine, it loads properly, and acts the same the second (and more) viewing.

**Comment by jdduke** [comment]
Hi @jkane001, any chance you can share an APK that has the minimal repro? We haven't been able to repro the problem on our end. A bug report might also help. Thanks.

**Comment by jkane001** [comment]
Actually, I think it's been fixed somewhere along the way, because I cannot reproduce it on my own project anymore. The only change I've made to the pano is updating the library to the latest.

Thanks, and sorry for not closing this before - I never noticed that the problem went away!

**Comment by jdduke** [comment]
No worries, thanks for the update!
