### ISSUE TITLE
How to render 360 degree video in samples-sdk-videoplayer?

### ISSUE THREAD

**Issue by moonfan** [googlevr/gvr-android-sdk#469]
I have tried samples-sdk-videoplayer demo and found that the video was rendered on a rectangle area and it's not a 360 degree video. If I have a 360-degree video in equirectangular projection, how can I render it on sphere and make it looks like a VR video? Is there any API function I can use?
Any sample code would be appreciated, thanks in advance for your help.

**Comment by jdduke** [comment]
We'll be releasing a new sample in the next SDK release which is dedicated to 360 video rendering. The existing samples-sdk-videoplayer sample is focused primarily on rendering (flat) DRM-protected video using a fast path on Daydream devices.
