### ISSUE TITLE
Android N+ black screen when use AsyncReprojection

### ISSUE THREAD

**Issue by Spider100** [googlevr/gvr-android-sdk#471]
I have this issue on my samsung gallaxy s8 that support Android N. Screen goes black when AsyncReprojection is enabled. Is there any additional change or specific render state that i need to set when AsyncReprojection mode is enabled?

Additionaly using AndroidCompat.setVrModeEnabled(this, true); causes crash on samsung gallaxy s8  (nexus 4 works fine). Any ideas why?

Is there any profit of use AsyncReprojection when my app work in stable 60fps ?

**Comment by jdduke** [comment]
Any chance you could capture and attach a bug report? Thanks. setVrModeEnabled() shouldn't crash either, as long as you have the latest install of Google VR Services.

Enabling async reprojection also allows frontbuffer rendering, which should reduce motion-to-photon latency.

**Comment by dustinkerstein** [comment]
I can't speak to your first issue, but the second issue sounds like this https://github.com/googlevr/gvr-unity-sdk/issues/671 - Can you replicate this crash when setting your S8 to WQHD?

**Comment by jdduke** [comment]
Without further comment it's hard to diagnose. Feel free to re-open with more details.
