### ISSUE TITLE
gvr_create() crashing (Android NDK)

### ISSUE THREAD

**Issue by TheDeveloperGuy** [googlevr/gvr-android-sdk#473]
I'm calling gvr_create(...) from my Android native (C++) code. I'm passing it the JNI environment, the application context and the class loader correctly, but it causes an exception. Finding an example anywhere on the great big internet that uses this function has not been possible.

So, how to call this function on Android? Is it supposed to work?

What I want is to use the GVR head tracking and that's it (and from what I can see it should be possible with a GVR context). Is this even possible or am I wasting my time?

**Comment by nathanmartz** [comment]
In the GVR SDK, head tracking and stereo rendering are fairly tightly coupled. We do not formally support one without the other, and it's likely to be a lot of work for you to try to work around that.

**Comment by TheDeveloperGuy** [comment]
@nathanmartz Thanks! My content is being rendered and lens corrected etc. already, so I could use the GVR rendering to display my content, without any distortion or anything else done to it, right?

The GVR head-tracking is vastly superior to any kind of built-in orientation tracking on Android, so I'd like to use it.
