### ISSUE TITLE
Using enableAsyncReprojectionVideoSurface or setAsyncReprojectionEnabled(true)

### ISSUE THREAD

**Issue by mug797** [googlevr/gvr-android-sdk#474]
Hello, I am hoping its ok to ask a question here, sorry if its not. I had  a question regarding when to use enableAsyncReprojectionVideoSurface and what benefits it has over setAsyncReprojectionEnabled. It uses ExternalSurfaceListener, I am not sure I understand what is referred to as an external surface. Thanks

**Comment by jdduke** [comment]
Hi @mug797. You should only use the enableAsyncReprojectionVideoSurface() variant if you need to either show DRM-protected or high fidelity video in your application. The external Surface here represents the Surface into which the application can decode the video content, which is then composited by the GVR distortion pipeline.
