### ISSUE TITLE
Sampling from a texture does not work when binding to texture unit 0 or 1 using OpenGL ES 2.0

### ISSUE THREAD

**Issue by nlebeck** [googlevr/gvr-android-sdk#475]
I wrote a simple app using a GvrView and OpenGL ES 2.0 that draws a triangle on the screen and colors it using a hardcoded 2x2 texture in RGBA format. Sampling from the texture only works when the texture is bound to texture unit 2 or higher. When using texture unit 0 or 1, the triangle does not appear on screen. When I switch the app from using a GvrView to using a normal GLSurfaceView, texture units 0 and 1 work fine.

My test app has a dependency on version 1.80.0 of the GVR SDK, and I am running the app on a Nexus 7 (2013) tablet and using the Android Studio 3.0 beta on Windows.

It sounds like the problem might be a bug related to [this issue](https://github.com/googlevr/gvr-android-sdk/issues/28) (which is where I got the idea of trying texture unit 2).

I’ve attached a zip file with the Java source file for a short single-activity app that reproduces the bug (along with its manifest in case something is missing there). If you run the code as written, you should see a single multicolored triangle appear in both eyes. To see the problem, change the code to use texture unit 0 instead of 2: change the glActiveTexture() call on line 94 to take GLES20.GL_TEXTURE0, and change the glUniform1i() call on line 107 to set the “texture” uniform to 0 instead of 2. After making those changes, the screen for both eyes is completely black.

[texture-issue-files.zip](https://github.com/googlevr/gvr-android-sdk/files/1308005/texture-issue-files.zip)

**Comment by prideout** [comment]
Hi Niel, you can use texture unit 0 if you re-bind the texture in the `onDrawEye` method:

    GLES20.glActiveTexture(GLES20.GL_TEXTURE0);
    GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, this.textures[0]);
    ...
    GLES20.glDrawArrays(GLES20.GL_TRIANGLES, 0,
        triangleCoords.length / POS_COORDS_PER_VERTEX);


On Cardboard devices, GVR resets the active texture binding on every frame in order to perform distortion and composition. For performance reasons, it does not restore the previous texture binding. We'll work on documenting this behavior.

Does this fix the issue?

**Comment by nlebeck** [comment]
Hi Philip, re-binding the texture fixed the problem. Documentation of that behavior would be great. Thanks!
