### ISSUE TITLE
Support for time warp per eye when you submit frame

### ISSUE THREAD

**Issue by mug797** [googlevr/gvr-android-sdk#476]
Hello,

I wanted to know if there was a way to do different time warps per eye? I mean, if there was a way to just update one eye with a given headpose when you submit frame and keep the other eye as is? 

Thanks in advance your help.

**Comment by nathanmartz** [comment]
We don't have any built in support for that, no. You would need to manually copy the texture for one eye and render that instead of the scene.

**Comment by mug797** [comment]
Thanks for the super quick response. :-)

Will I need to turn off timewarp (disable async reprojection) to do this? From what I understand, for every vsync google vr sdk will do timewarp on the submitted frame correct? For which it will use the headpose passed in the submit call of the frame?

Thanks again.
