### ISSUE TITLE
Gradle 'gvr-android-sdk-master' project refresh failed

### ISSUE THREAD

**Issue by adwilme110** [googlevr/gvr-android-sdk#478]
Gradle 'gvr-android-sdk-master' project refresh failed

**Comment by jdduke** [comment]
Can you be more specific about the failure you're seeing?

**Comment by LoSealL** [comment]
@jdduke Got a same issue, where error message came out as: 

> Error:Exception thrown while executing model rule: BaseComponentModelPlugin.Rules#createVariantData(ModelMap<AndroidBinaryInternal>, ModelMap<AndroidComponentSpec>, TaskManager) > afterEach()

> Consult IDE log for more details (Help | Show Log)

**Comment by deepuprs** [comment]
Any Solution for this?
I am facing same issue.

**Comment by sigmaxipi** [comment]
Can you provide more details about your development setup? We haven't been able to reproduce this issue.

Have you seen this issue with older revisions of the SDK? Does a clean checkout of the git repo + a command line gradle build work?

**Comment by deepuprs** [comment]
This issue happens in below setup.
Android Studio v3.0.1
gvr-android-sdk v1.120.0
build.gradle ==> classpath 'com.android.tools.build:gradle-experimental:0.11.1
gradle/wrapper/gradle-wrapper.properties ==> distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

It got resolved after downgrading the gradle version to:
build.gradle ==> classpath 'com.android.tools.build:gradle-experimental:0.9.3
gradle/wrapper/gradle-wrapper.properties ==> distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

**Comment by LoSealL** [comment]
I can build the project successfully now.
With
- gvr-android-sdk v1.120.0
- Android Studio 3.0.1
- gradle 4.1
- com.android.tools.build:gradle-experimental:0.11.1

Some issues came from connection timeout while resolving dependencies.
