### ISSUE TITLE
Does gvr_audio_surround_get_available_output_size_samples only calculate the number of available output frames?

### ISSUE THREAD

**Issue by hankewei** [googlevr/gvr-android-sdk#479]
As you  say, #415 gvr_audio_surround_get_interleaved_output triggers the internal processing of the input buffers. Then, gvr_audio_surround_get_available_output_size_samples only calculates the number of available output frames. Is that so?

**Comment by jkammerl** [comment]
gvr_audio_surround_get_available_output_size_samples returns the number of samples available in the output buffer. Since it outputs a stereo audio stream, you'll need to divided that number by two to get the available output frames.
