### ISSUE TITLE
Need API to toggle low persistence mode off to reduce flicker

### ISSUE THREAD

**Issue by Adam-VisualVocal** [googlevr/gvr-android-sdk#480]
The flicker produced by Daydream capable phones when in VR is quite noticeable and detracts from the user experience. This [slow motion YouTube video](https://youtu.be/iJJ_LSDNz0c) shows a simple Cardboard app created in Unity running on several phones. The Daydream capable phones, such as the Pixel and S8+, show a huge amount of flicker while the non-Daydream phones do not.

On Pixel phones, the user can reduce the flicker by changing the display settings. However, the S8 has no such setting. Developers need an API for toggling low-persistence mode on and off so we can provide the best (low flicker) experience for our users.

**Comment by jdduke** [comment]
Hi @Adam-VisualVocal. The "flicker" you observe is a function of the low persistence display setting when entering VR mode. Low persistent reduces motion blur, and makes for a crisper VR experience.

That said, some users are particularly sensitive to this flicker. It can be disabled globally by navigating to Android Settings -> Display -> When device is in VR -> Reduce flicker. Hope that helps.

**Comment by Adam-VisualVocal** [comment]
Thanks, but that only works on the Pixel phones. On the Samsung Galaxy S8 series there is no setting to reduce flicker as far as I know. Because some OEMs aren’t exposing this setting, we need an API to control it programmatically.

**Comment by jdduke** [comment]
> On the Samsung Galaxy S8 series there is no setting to reduce flicker as far as I know. Because some OEMs aren’t exposing this setting, we need an API to control it programmatically.

I agree that this needs to be addressed. I've flagged the issue internally and we'll be passing it along to Samsung (and other OEMs) to see about exposing this user setting more broadly.

> It only makes the display dim and flickery for 100% of the people I've shown this to.

Just curious, do you show it to them out of the headset? Or only in the headset? The flicker is far more apparent when looking at the phone as you would normally look at them outside of the headset, from a distance of a foot or two+. So the experience as viewed from several feet away (as captured in the video) may not translate directly to the experience in the headset.

**Comment by Adam-VisualVocal** [comment]
For the moment, ours is a Cardboard app so we're using a range of viewers. Yes, the flicker is visible without a viewer but it's very visible with a viewer as well. Our app is used to viewr architectural renders, which frequently are done in shades of grey. Unfortunately, those shades tend to accentuate the flicker even more.

**Comment by jdduke** [comment]
> For the moment, ours is a Cardboard app so we're using a range of viewers

If you don't absolutely need low-latency rendering, you could stop enabling VR mode (and also not use async reprojection, if you were doing so previously). Enabling VR mode is what puts the device into low-persistence mode, and is really only required for Daydream apps that use async reprojection.

**Comment by Adam-VisualVocal** [comment]
Is there a way to still use Cardboard in stereo without enabling VR?

**Comment by jdduke** [comment]
So, there are two slightly different knobs here:

1) Android's "VR" mode (enabled via [Activity.setVrModeEnabled](https://developer.android.com/reference/android/app/Activity.html#setVrModeEnabled(boolean, android.content.ComponentName), or [AndroidCompat.setVrModeEnabled](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/AndroidCompat.html#setVrModeEnabled(android.app.Activity, boolean))) - This is an *Android*-specific setting which puts the system in a state highly tailored to immersive VR experience, e.g., enabling low-persistence on the display, adjusting clock rates, etc... It's not actually immediately involved in stereo renering.
2) GvrView's "Stereo" mode (enabled via [GvrView.setStereoModeEnabled](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView.html#setStereoModeEnabled(boolean)) - This is what actually enables stereo, per-eye rendering callbacks in the VR composition pipeline.

For historical reasons, the two APIs are orthogonal, and you can safely use GVR's "Stereo" mode for Cardboard apps without enabling Android's "VR" mode (the latter having been introduced in Android N, available only on certain phones).

**Comment by Adam-VisualVocal** [comment]
Very interesting. Thanks for that. I'll have to see if I can use that in Unity.

**Comment by jdduke** [comment]
Ah, I didn't realize you were using Unity. You might post a note on StackOverflow and/or https://github.com/googlevr/gvr-unity-sdk to see if there's a way to selectively toggle the Android VR mode while still getting stereo Cardboard support.

**Comment by Adam-VisualVocal** [comment]
No. The best we've been able to do is just direct our customers to the display settings on the phone and ask them to switch the "When device is in VR" setting to "Reduce flicker" instead of the default "Reduce blur". That's not ideal obviously and it only works if the phone actually exposes that setting. Pixel phones do and I think Samsung phones do too but I don't know about the other Daydream-capable phones out there.

**Comment by dorcatty** [comment]
@Adam-VisualVocal thanks a lot for your tips. My case is different than yours. We are looking for some low cost Android phones with 'low persistence' enabled to run some GVR scenes. However, when we tested with Huawei P20, there's no 'low persistence' option in the OEM system.  Do you think we can disable this function manually or from Unity3D? While testing with the same GVR scene, our Samsung S9++ works well, we dont have the motion sickness at all.
