### ISSUE TITLE
Can the api gvr_controller_state_get_position be used.

### ISSUE THREAD

**Issue by mug797** [googlevr/gvr-android-sdk#481]
Hey, 

I came across the api gvr_controller_state_get_position and I was wondering how it can be used, if there was any example of it? 
I came across this in the Release notes:
Added gvr_controller_state_get_position API, reserved for future elbow model simulations.
but I didnt find any documentation details in the api list, so I wasnt sure if the api is ok to use? (It does return all 0s when I use it though.)

Thanks in advance,

**Comment by jdduke** [comment]
Hi @mug797 . The position field is used in conjunction with the arm/elbow model. See also the [ApplyArmModel](https://developers.google.com/vr/android/ndk/reference/class/gvr/controller-api#classgvr_1_1_controller_api_1a7bfc57b848d5f9f79af5c384f0b4809b) method.
