### ISSUE TITLE
1.100.0 Release in Github releases area is same commit as 1.80.0

### ISSUE THREAD

**Issue by ian-wevr** [googlevr/gvr-android-sdk#485]
Looks like the 1.100.0 release listed in the Github release area is pointing to the same commit as 1.80.0.

**Comment by jdduke** [comment]
You're absolutely right, this should be fixed now.

**Comment by electmk** [comment]
@jdduke 
Release Notes has not changed since V 1.80
https://developers.google.com/vr/android/release-notes

**Comment by jdduke** [comment]
Right, we're in the middle of migrating our release notes to GitHub (see https://github.com/googlevr/gvr-android-sdk/releases/tag/v1.100.0).
