### ISSUE TITLE
Does VrVideoView support spatial audio? 

### ISSUE THREAD

**Issue by keshwans** [googlevr/gvr-android-sdk#487]
Does **VrVideoView** support spatial audio? 
We are using VrVideoView in Android and GVRVideoView in iOS. 

Thanks

**Comment by jkammerl** [comment]
VrVideoView does not support spatial audio. For an example how to integrate spatial audio rendering directly into ExoPlayer, see the [videoplayer example](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-videoplayer/src/main/java/com/google/vr/sdk/samples/videoplayer/VideoExoPlayer2.java) in the SDK
