### ISSUE TITLE
GVR_FEATURE_MULTIVIEW blacklisted on Android 8?

### ISSUE THREAD

**Issue by MortimerGoro** [googlevr/gvr-android-sdk#491]
Hello,

I had a working multiview sample on the Pixel XL but can't get multiview working after updating to Android 8.0. It seems like it is blacklisted by the SDK:

Pixel XL:
`IsFeatureSupported(GVR_FEATURE_MULTIVIEW) == true `on Android 7.0
`IsFeatureSupported(GVR_FEATURE_MULTIVIEW) == false` after upgrading to Android 8.0

If I disable the IsFeatureSupported check, the sdk crashes with an assertion failure related to multiview being not supported.

**Comment by fernandojsg** [comment]
I was able to reproduce the same issue on a S8

**Comment by nathanmartz** [comment]
Multiview is a very new feature and requires driver support to work robustly. There are some cases where the device is capable but there are driver bugs, and in those cases we have to disable multi-view until the driver bug is fixed.

**Comment by juliet123** [comment]
dont dare update or change my data as im hack
