### ISSUE TITLE
will sample sdk videoplayer works on not daydream ready phone?

### ISSUE THREAD

**Issue by Anton111111** [googlevr/gvr-android-sdk#494]
Hi i tried start videoplayer sample on not daydream ready phone. But it doesn't work.
Is it mean that this sample will work on only daydream phone?

**Comment by jdduke** [comment]
The current videoplayer sample is [Daydream-only](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-videoplayer/src/main/AndroidManifest.xml#L44). The sample requires a specific set of hardware/software features to use the accelerated video path.
