### ISSUE TITLE
side-by-side video

### ISSUE THREAD

**Issue by Anton111111** [googlevr/gvr-android-sdk#495]
Has ability to use gvr-android-sdk to play stereo video side-by-side ?
I understand that google use as standard above-below video. But i wonder is it possible to play side-by-side?
And if it is possible to has some sample or description how to do it?

**Comment by nathanmartz** [comment]
Our standard format is over-under video. It's pretty straightforward to implement SxS yourself, but that's a "how to" question better asked on StackOverflow.
