### ISSUE TITLE
Old method from CardboarView (vrtoolkit) setRestoreGLStateEnabled 

### ISSUE THREAD

**Issue by Anton111111** [googlevr/gvr-android-sdk#496]
I trying to  migrate from old vrtoolkit to new sdk. But i don't see method setRestoreGLStateEnabled in GvrView. I wonder what new method to used instead setRestoreGLStateEnabled ?

**Comment by jdduke** [comment]
Due to the complexity and fragility of the previous implementation of GL state restoration, we were forced to deprecate and remove the API. You'll have to write your app in such a way as to not assume anything about GL state before/after drawing your scene.
