### ISSUE TITLE
Google VR Services and Activity lifecycle

### ISSUE THREAD

**Issue by enginegl** [googlevr/gvr-android-sdk#497]
Hello!
I have 2 activities: 
`<activity
            android:name=".MainActivity"
            android:configChanges="orientation|screenSize"/>`
`        <activity android:name=".VrActivity"
            android:screenOrientation="sensorLandscape"
            android:configChanges="orientation|screenSize"/>`
MainActivity extends AppCompatActivity, VrActivity extends GvrActivity

Scenario:
1) Start MainActivity
2) Start VrActivity
3) Press "back" - return to MainActivity

1st case: Google VR Services are enabled:
<img width="1397" alt="case1" src="https://user-images.githubusercontent.com/3976062/33129189-c5ad62b6-cf97-11e7-8f8e-f74309a5acff.png">

2nd case: Google VR Services are disabled:
<img width="920" alt="case2" src="https://user-images.githubusercontent.com/3976062/33129220-e36ca172-cf97-11e7-9b0b-a7cfd5cf014f.png">

There is apparently some undesired behaviour in case 1 when MainActivity recreated without any reason.

How can I achieve the same behaviour as we can see in 2nd case without disabling Google VR Services?

===

Google Pixel, Android 8.0.0, GVR SDK 1.101.0

**Comment by jdduke** [comment]
Hi @enginegl , could you try changing the VrActivity manifest from

`android:configChanges="orientation|screenSize"`

to

`android:configChanges="orientation|screenSize|uiMode"`

Android O introduces a new "vrheadset" UI mode, which can cause Activity recreation unless you explicitly declare that you handle such a configuration change in your manifest. With our next GVR SDK release, our samples will be updated to indicate the appropriate `configChanges `flags.  If that doesn't work, please re-open the bug. Cheers.

**Comment by enginegl** [comment]
@jdduke thanks, `uiMode` resolves the problem, but only for VrActivity. So, we need to add this flag for both of activities to achieve desired behaviour.

**Comment by jdduke** [comment]
Yes, you'll want to add `uiMode` to any Activity that acts as a transition point into or out of VR.
