### ISSUE TITLE
Open the VR PANO IMAGE from a different position.

### ISSUE THREAD

**Issue by abhishek1508** [googlevr/gvr-android-sdk#499]
Hi,

I am using the google vr sdk to move a Panorama image using touch in the horizontal and vertical directions. I have a requirement, which states that 
Step 1: I open a panorama image and move it any direction.
Step 2: There is a button in my app, which if clicked should change the image to show a new panorama image but from the origin. 

Right now, the new image shows up but it is centered at the position I left the previous image.

I wanted to know if there are any APIs or functions that can be used to open a new image from their starting position.

Please let me know if I didn't explain my question well.

**Comment by sigmaxipi** [comment]
The VrView widgets are meant as simple 360 viewers for apps that don't have complex requirements for viewing 360 media. If you want custom controls, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
