### ISSUE TITLE
GVR_FEATURE_HARDWARE_BUFFERS? new features?

### ISSUE THREAD

**Issue by KIMSUNGHOON** [googlevr/gvr-android-sdk#502]
I know that Google VR service and vrhome have been updated. The Google VR service has confirmed that it is an update to 1.101.0. And after updating from other device.  I found a problem with the screen not coming out. I suspect GVR_FEATURE_HARDWARE_BUFFERS. If you do not support GVR_FEATURE_HARDWARE_BUFFERS, do you have problems with the latest update? And what is the solution? And it works normally in 1.100.0.

**Comment by jdduke** [comment]
GVR_FEATURE_HARDWARE_BUFFERS is a purely option feature, and shouldn't be used in most cases. It's perfectly fine for the platform to report that this feature is unsupported.

Can you add any more details about the failure you're seeing? What Android device/version are you using? Can you include a bug report or logs of the failure? Thanks.

**Comment by jdduke** [comment]
Without more details, it's hard to proceed. Feel free to re-open this bug if you have a concrete use-case that requires this feature, otherwise it's probably not the API you're looking for.
