### ISSUE TITLE
Documentation: wrong reference to setDistortionCorrectionScale

### ISSUE THREAD

**Issue by R1ck77** [googlevr/gvr-android-sdk#503]
The [setMultisampling](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView.html#setMultisampling(int)) page description contains a broken link to a setDistortionCorrectionScale method.

Thank you for your attention

**Comment by jdduke** [comment]
Thanks for the report, you're absolutely right, that should reference setRenderTargetScale(). This has been fixed internally, and will be included in the release after the one that will be pushed next week. Cheers.
