### ISSUE TITLE
Audio API: Is there a builtin way to preload sound asynchronously?

### ISSUE THREAD

**Issue by alculquicondor** [googlevr/gvr-android-sdk#504]
I saw that `gvr_audio_preload_soundfile` is taking some time while loading a ~30s sound file. Is there a builtin way to do it asynchronously? Otherwise, if do not preload (so it streams), will the file be cached after it first finishes playing?

**Comment by jkammerl** [comment]
The current API does not support asynchronous preloading but you can execute this call from a separate thread. Streamed playback is designed to keep the memory footprint low and therefore doesn't perform caching of decoded audio data.
