### ISSUE TITLE
Failed to find Build Tool revision 26.0.0

### ISSUE THREAD

**Issue by SopMar** [googlevr/gvr-android-sdk#506]
I just imported into Android Studio 1.5.1 and getting:

Information:Gradle tasks [clean]
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Android\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
Error:A problem occurred configuring project ':samples-sdk-controllerclient'.
> Exception thrown while executing model rule: BaseComponentModelPlugin.Rules#createAndroidComponents(ModelMap<AndroidComponentSpec>, ServiceRegistry, AndroidConfig, AndroidConfig, ModelMap<BuildType>, ModelMap<ProductFlavor>, ModelMap<SigningConfig>, VariantFactory, TaskManager, Project, AndroidBuilder, SdkHandler, ExtraModelInfo, Boolean)
   > Failed to find Build Tools revision 26.0.0
Information:BUILD FAILED
Information:Total time: 1.299 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

Please let me know, how can I resolve this issue. Thanks in advance

**Comment by jdduke** [comment]
Hi @SopMar, you'll need to make sure that you have version 26 of the Android SDK Build-tools installed with your local Android SDK installation. [Here are some instructions](https://developer.android.com/studio/intro/update.html) to help guide you through the process.
