### ISSUE TITLE
recenterHeadTracker() recenter only horizontal 

### ISSUE THREAD

**Issue by Anton111111** [googlevr/gvr-android-sdk#508]
How i see method getGvrView().recenterHeadTracker(); recenter only horizontal. 
How i can recenter vertical too ?

**Comment by jdduke** [comment]
Hi @Anton111111, it is by design that the recenter behavior is yaw-only. You could implement your own form of pitch recentering by storing a rotation offset at the time of recenter, and applying that to the provided poses thereafter.
