### ISSUE TITLE
VrPanoramaView and VrVideoView

### ISSUE THREAD

**Issue by NathanaelA** [googlevr/gvr-android-sdk#509]
I have tried to create a view with both a Panorama and Video; and the idea was to hide whichever one I didn't need at that moment.      Is this a supported scenario?

However, even though I hide the Video view; the Panorma view then appears to continue rendering the last frame of the video before I stopped it, moving the phone continues rendering that static image properly and it rotates as if that is the image I loaded.   

I opened up the Layout capture in Android studio; and it shows that my video controller is hidden.

![image](https://user-images.githubusercontent.com/850871/34018077-046adb02-e0ee-11e7-852f-60391da592fc.png)

And my Panorama view is visible:
![image](https://user-images.githubusercontent.com/850871/34018262-b117fcae-e0ee-11e7-9f31-af8bd08d17b4.png)

Any ideas?   Is their a way to decouple the two of them?

**Comment by sigmaxipi** [comment]
The VrView widgets are meant as simple 360 viewers for apps that don't have complex requirements for viewing 360 media. If you want to support both images and video in your app, consider using the Video360 sample as a starting poin. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
