### ISSUE TITLE
Orthographic projection

### ISSUE THREAD

**Issue by Anton111111** [googlevr/gvr-android-sdk#511]
We have eye.getPerspective(float zNear, float zFar) to get the perspective projection matrix for this eye
If i want to use Orthographic projection how i can get the orthographic projection matrix for current eye?

**Comment by sigmaxipi** [comment]
Why do you want an orthographic projection for an eye? When viewed in VR, this will not look correct.

If you really need an orthographic projection, you can generate one using [Matrix.orthoM](https://developer.android.com/reference/android/opengl/Matrix.html#orthoM(float[], int, float, float, float, float, float, float)) and tan of the angles stored in the eye's [FieldOfView](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/FieldOfView)

**Comment by Anton111111** [comment]
I want draw something like HUD

**Comment by sigmaxipi** [comment]
You shouldn't use an orthographic matrix for  HUD. It can prevent proper stereo convergence in VR. Instead, considering rendering a quad (or other HUD components) with a rotation based on `onNewFrame`'s `headTransform.getEulerAngles`. This will allow you to lock the HUD to the user's head.

**Comment by Anton111111** [comment]
Thanks you are right ;)
