### ISSUE TITLE
configure vr-viewer without forcing the user to install google-cardboard-app

### ISSUE THREAD

**Issue by aniltirola** [googlevr/gvr-android-sdk#512]
I am using google-vr-android-sdk to show a 360° video. Everythings works fine. Now I would like to configure my viewer programmatically WITHOUT forcing the user to install the google card-board-app. Is this possible? Can anyone point me to more informations or a code-snippet?

**Comment by jdduke** [comment]
Which flavor of the GVR API are you using? Is it VrVideoView? Or GvrView? Or Unity?

There is some related discussion in #490. With GvrView, you could update the parameters to be that of your viewer whenever the app resumes. That approach doesn't override the globally configured viewer.

Alternatively, you can try setting the "default" viewer to be your viewer, but that only works if no global viewer has been configured previously (by way of the Cardboard or Google VR Services apps).

**Comment by jdduke** [comment]
Feel free to re-open if none of the offered suggestions work for you.
