### ISSUE TITLE
Build fails due to included ThrowableExtension in sdk-common.aar

### ISSUE THREAD

**Issue by esminis** [googlevr/gvr-android-sdk#513]
Build fails with this error message:

com.android.builder.dexing.DexArchiveMergerException: com.android.tools.r8.errors.CompilationError: Program type already present: com.google.devtools.build.android.desugar.runtime.ThrowableExtension$NullDesugaringStrategy

It is because com.google.devtools.build.android.desugar.runtime.ThrowableExtension should not be included in aar. As of now only workaround is repackage aar manually

**Comment by sigmaxipi** [comment]
Thanks for the note. For now, repacking the aar is the only workaround. We'll fix this properly for the next release.

**Comment by sigmaxipi** [comment]
This has been fixed in v1.130.0
