### ISSUE TITLE
recenterHeadTracker() and eulerAngles

### ISSUE THREAD

**Issue by Anton111111** [googlevr/gvr-android-sdk#515]
Since I need to implement recenter vertically myself , I did this with eular angles.

I stored current value of eulerAngles[0] and then use it:
```
headTransform.getEulerAngles(eulerAngles, 0);
float anglePitch = Math.toDegrees(-eulerAngles[0] + eulerAnglesCorrection[0]);
float angleYaw = Math.toDegrees(-eulerAngles[1]);

```
Then onDrawEye i use it:
```
Matrix.rotateM(modelMatrix, 0, anglePitch, 1.0f, 0.0f, 0.0f);
Matrix.rotateM(modelMatrix, 0, angleYaw, 0.0f, 1.0f, 0.0f);
```
But i have problem with angleYaw when look up. 
To show this problem i create small video:
[link to video](https://www.youtube.com/watch?v=0YoCtdWRaV0)

How you see at an pitch angle of more than 80 degrees, I have an incorrect yaw angle (and left side swaped with right side ).

If i use quaterion (headTransform.getQuaternion()) all works fine. But how create vertical (pitch) recenter with quaterion? 
Also i want limit yaw rotation (for example user can rotte from -45 to 45). And i don't understand how i can to do it with quaterion. 
Is it even possible?

**Comment by jdduke** [comment]
HI @Anton111111, this kind of question is better suited to [StackOverflow](https://stackoverflow.com/questions/tagged/google-vr).
