### ISSUE TITLE
Get the rotation Angle of the head

### ISSUE THREAD

**Issue by guoyuanzhuang** [googlevr/gvr-android-sdk#516]
I need to add a comment where the user clicks on the VR view, And I'm going to save it, Show this comment.
I'm trying to call videoWidgetView.getHeadRotation();  Why is there no return value, What is the correct way to get it?

**Comment by sigmaxipi** [comment]
You pass in an array to hold the results.
```
float[] yawAndPitch = new float[2];
view.getHeadRotation(yawAndPitch);
float yaw = yawAndPitch[0];
float pitch = yawAndPitch[0];
```

**Comment by guoyuanzhuang** [comment]
Thanks 666
