### ISSUE TITLE
Strange problem with VrVideoView

### ISSUE THREAD

**Issue by Anton111111** [googlevr/gvr-android-sdk#517]
Hello! 
To show problem i create small app:
https://github.com/Anton111111/GVRVideoProblemSample

In this app i show video in TextureView in top of screen with exoplayer.
And in bottom of screen i use VrVideoView.

Result you can see in screenshot:
![photo_2017-12-29_15-15-12](https://user-images.githubusercontent.com/987933/34436911-154aa18c-ecab-11e7-9a31-4961c6f8c92d.jpg)

I wonder what's green in the bottom? How you see exoplayer show this video in TextureView correct.

I tried start this app on 3 phones. And i see this problem only in Huawei nova.
And If i make this video with a lower resolution it works correctly.

**Comment by Anton111111** [comment]
Forgot add link to video.
https://github.com/Anton111111/GVRVideoProblemSample/raw/master/video/3.mp4

**Comment by sigmaxipi** [comment]
What device are you seeing this issue on?

This is a bug in how the video player handles video textures. When Android creates a Surface to decode video, some devices create a Surface that is slightly larger than the actual video. Then they set a matrix on Surface which is exposed in SurfaceTexture.getTransformMatrix. Unfortunately, VrView doesn't check this matrix nor pass it down to the GL code. So the GL code samples garbage outside the video frame and that renders as green pixels at the south pole.

This is complicated to fix in the existing code and it only happens on some devices. You could try resizing the video to find a size that works for the device.

**Comment by Anton111111** [comment]
This issue I see in Huawei Nova (can-l11).
I don't understand what did you mean when say 
"You could try resizing the video to find a size that works for the device." Did you mean resize video file ? I can't resize video file because I get file from server.

**Comment by sigmaxipi** [comment]
Correct, I meant resizing the video file. Since that's not possible, you should considering using the video360 sample which will let you build your own video use the SurfaceTexture's transformation matrix.

**Comment by Anton111111** [comment]
Thanks. I understood.
