### ISSUE TITLE
Dex error when used in conjunction with ARCore Preview 2

### ISSUE THREAD

**Issue by radvani** [googlevr/gvr-android-sdk#518]
Both this library and ARCore Preview 2's SDK use the following three classes:

com.google.android.aidl.BaseProxy
com.google.android.aidl.BaseStub
com.google.android.aidl.Codecs

As a result, if you try to include both libraries in an application (e.g. an application that has both an AR and a VR mode), you get a Dex error. Specifically: 
```
Error converting bytecode to dex:\nCause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/aidl/Codecs;
```

Two questions:
1. Can this be fixed in a future release, or are these libraries incompatible?
2. As a workaround, will it break things if I simply repackage the gvr-common AAR by removing these three classes, instead making it rely on the ARCore equivalents?

Thanks.

**Comment by jdduke** [comment]
Hi @radvani, thanks for the report. 

> Can this be fixed in a future release, or are these libraries incompatible?

Yes, we'll look into fixing this for the next release.

> As a workaround, will it break things if I simply repackage the gvr-common AAR by removing these three classes, instead making it rely on the ARCore equivalents?

Yep, that should work.

**Comment by franckos** [comment]
Same problem here
@jdduke Did you succed on repackage gvr-common without conflicting classes?
Would you be able to send the resulting aar file btw?
Thks in advance

**Comment by jdduke** [comment]
Both the gvr-common.aar and the embedded classes.jar file are simple zip archives. so you should be able to extract the .aar, then the.jar, remove the offending classes, then zip them back up in turn.

The conflicts should be removed (or at least sufficiently obfuscated/altered) in the next release in mid February.

**Comment by ramonaharrison** [comment]
Is there a target date for the release that will remove this conflict?

**Comment by jdduke** [comment]
Yes, we'll be pushing an updated SDK version next week, hopefully by Wednesday.

**Comment by sigmaxipi** [comment]
sdk-common-1.130.0.aar has the fix.
