### ISSUE TITLE
How to properly select views  with controller 

### ISSUE THREAD

**Issue by leapfrog-santosh** [googlevr/gvr-android-sdk#527]
I have looked upon the `video360` sample where there is use of selection by controller. I tried to use the formula given in the sample [CanvasQuad.translateClick](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/rendering/CanvasQuad.java), but couldn't get the desired result. Here is my scenario

1. I have a rectangle with `left=0,right=1824,top=0,bottom=989` with aspect ratio 1.84f, with uniform Z axis = -3f
2. I did some modification in the orthographic projection without changing the z axis such that the new rectangle will be in range `-1,84 to 1.84` in x axis and `1 to -1` in y axis
3. Then to render the rectangle on VR, I simply applied

> view = perspective ( z near 0.1f, far 100 f)  *  eye.getEyeVew
    model = Orthographic transformation to come in range ( -1.84f to 1.84 f : X , 1 to 1f :Y )
    modelview =  view * model

4. To emulate the controller, I used a simple circle  with ( centerX=0, centerY=0, radius =0.004f, zaxis = -3f)
5. Applied following transformation to the circle with controller rotation matrix

> view = perspective ( z near 0.1f, far 100 f)  *  eye.getEyeVew
   controllerMatrix = controller.toRotationMatrix
   modelView =  view * controllerMatrix

My assumption was that, since I was drawing the 3D planes with uniform Z values, I can consider them as a 2D plane for selection. I assumed that the circle 2D coordinate ( left,top,right,bottom) can be used  to check with the plane 2D coordinate ( left,top,right,bottom) and see whether the circle falls in the the plane or not. But due to the `perspective & eye.getEyeView` transformation, the z axis of both the circle and plane changes.
So, my question is for this purpose should I go for `RayCasting` or there is a simple solution for it.
Thank you.

**Comment by sigmaxipi** [comment]
For the type of complicated hit detection you're doing, the sample code won't be sufficient. The sample code only works because there are no transformations of the floating quad or the controller. Since you have multiple matrix operations, you will need to use a hit detection library such as the one in https://github.com/Rajawali/Rajawali

**Comment by leapfrog-santosh** [comment]
@sigmaxipi : Thank you. I tried using the `isLookingAtObject()` method of `TreasureHunt Sample` with minor modification like
`isLookingAtObject(float[] controllerMatrix,float[] objectModel)`
where `objectModel` contains transformed center position of respective grids
and `controllerMatrix` is the matrix obtained from `controller.orientation.toRotationMatrix`. The selection occurs but not in appropriate manner. The only grid that works is the center grid and for other grids, there is wrong selection.
So, I believe the `isLookingAtObject()` may work with minor modification.
