### ISSUE TITLE
No x86_64 native libs

### ISSUE THREAD

**Issue by lkcanal** [googlevr/gvr-android-sdk#528]
Hello,

just got an email of the new requirements for Play developers in 2018 and 2019, where it asks for 64bits native libs. (Content here: https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html)

I noticed that the SDK has x86 32bits native libs but not the x86_64 equivalent (for instance libgvr.so and libgvr_audio.so). Will you add it in the near future ?

Thx in advance.

**Comment by jdduke** [comment]
We don't have any immediate plans, but if you have a strong use-case for shipping an x86 binary on the Play Store we can consider it. Most x86 devices can consume the native arm libraries that we ship.

The x86 libraries that we publish are intended primarily for testing with emulators, where there's no Play Store requirement for embedding both 32 and 64-bit native libraries.

**Comment by ptran-gpfw** [comment]
Hi @jdduke, regarding your comment:

> Most x86 devices can consume the native arm libraries that we ship.

Is this a general Android feature? An x86 Android device like a Chromebook could run an Android app that is packaged with only arm libs?

**Comment by jdduke** [comment]
> Is this a general Android feature?

Not generally, no, though most x86 *phones* that I'm aware of can also execute arm libraries.

> An x86 Android device like a Chromebook could run an Android app that is packaged with only arm libs?

I believe Chromebooks will run some kind of emulation (different than direct binary translation) for arm Android apps, but I'm not 100% sure.

**Comment by esminis** [comment]
> Most x86 devices can consume the native arm libraries that we ship.

Most but not all. The other issue is if APK is already providing other x86_64 libraries then app will only load x86_64 libraries and will not try x86 or Arm libraries

> The x86 libraries that we publish are intended primarily for testing with emulators, where there's no Play Store requirement for embedding both 32 and 64-bit native libraries.

What do you mean there is no requirement to provide 64-bit native libraries, did you read document by Google that we will not be able to upload apps without providing 64-bit native libraries: https://developer.android.com/distribute/best-practices/develop/64-bit

> Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures.

**Comment by Reubenator** [comment]
Is there a resolution to this issue?
I'm seeing the following issue with my app in the Google Playstore re libgvr.so

`Error This release is not compliant with the Google Play 64-bit requirement
The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 101.`

I've tried excluding the library dependency as was suggested but I get the following issue in my app:

`../lib/arm64, /system/lib64]]] couldn't find "libgvr.so"`  

Is there a work around? Are apps based on the Google VR SDK now excluded from the Playstore?

**Comment by Reubenator** [comment]
Hi

I am still seeing issue relating to the 64 bit requirement when referencing the gvr sdk. It's no longer a warning, I see the following error in Google Playstore:

`Error This release is not compliant with the Google Play 64-bit requirement The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 101.`

I've tried excluding *.so library dependencies as was suggested, but I get the following issue in my app:

`../lib/arm64, /system/lib64]]] couldn't find "libgvr.so"`

This suggests there is a stronger dependency on this library than just for "testing emulators"

Surely others are having this issue, seems easy to recreate, are there any workarounds to this issue?

cheers

**Comment by Reubenator** [comment]
> Hi
> 
> I am still seeing issue relating to the 64 bit requirement when referencing the gvr sdk. It's no longer a warning, I see the following error in Google Playstore:
> 
> `Error This release is not compliant with the Google Play 64-bit requirement The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 101.`
> 
> I've tried excluding *.so library dependencies as was suggested, but I get the following issue in my app:
> 
> `../lib/arm64, /system/lib64]]] couldn't find "libgvr.so"`
> 
> This suggests there is a stronger dependency on this library than just for "testing emulators"
> 
> Surely others are having this issue, seems easy to recreate, are there any workarounds to this issue?
> 
> cheers

..I've resolved my own issue. In this case is was because I including the libgvr.so binary library which is referenced by the "com.google.vr:sdk-base:1.190.0" maven package. libgvr.so doesn have 32 bit and 64 bit versions but importantly I was missing this from my android build.gradle:

`android {
    defaultConfig {
        ndk.abiFilters 'armeabi-v7a', 'arm64-v8a'
    }
}`
