### ISSUE TITLE
error in Android Studio: Rendering Problems, com.google.vrtoolkit.cardboard.CardboardView could not be instantiated

### ISSUE THREAD

**Issue by sh39sxn** [googlevr/gvr-android-sdk#53]
Hi,

I'm getting an error when trying to use this github project in Android Studio.
When I open the preview of common_ui.xml the following error is shown:

> Rendering Problems The following classes could not be instantiated:
- com.google.vrtoolkit.cardboard.CardboardView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.NullPointerException   at android.os.storage.StorageManager.getVolumeList(StorageManager.java:872)   at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:83)   at android.os.Environment.getExternalStorageDirectory(Environment.java:337)   at com.google.vrtoolkit.cardboard.ConfigUtils.getConfigFile(ConfigUtils.java:52)   at com.google.vrtoolkit.cardboard.HeadMountedDisplayManager.createScreenParamsFromExternalStorage(HeadMountedDisplayManager.java:271)   at com.google.vrtoolkit.cardboard.HeadMountedDisplayManager.createScreenParams(HeadMountedDisplayManager.java:188)   at com.google.vrtoolkit.cardboard.HeadMountedDisplayManager.<init>(HeadMountedDisplayManager.java:54)   at com.google.vrtoolkit.cardboard.CardboardViewNativeImpl.<init>(CardboardViewNativeImpl.java:96)   at com.google.vrtoolkit.cardboard.ImplementationSelector.createCardboardViewApi(ImplementationSelector.java:35)   at com.google.vrtoolkit.cardboard.CardboardView.init(CardboardView.java:930)   at com.google.vrtoolkit.cardboard.CardboardView.<init>(CardboardView.java:243)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:835)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)   at android.view.LayoutInflater.inflate(LayoutInflater.java:394) Copy stack to clipboard  The graphics preview in the layout editor may not be accurate: 
- Paint.setShadowLayer is not supported. (Ignore for this session) 
Ignore all fidelity warnings for this session 

The cardboard.jar and audio.jar exists in the libs folder of the project. The build.gradle script includes all jar files of the libs folder. I can open the class com.google.vrtoolkit.cardboard.CardboardView.
That's why I don't understand the reason for this error.

Another problem: when I'm running the app on an emulator I can see the message "Pull the magnet when you find an object." for a short time. Then the app breaks. In logcat I see the following message:

> 2-07 20:37:50.814 2032-2032/? I/Choreographer: Skipped 115 frames!  The application may be doing too much work on its main thread.
02-07 20:37:50.902 2032-2073/? A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x73522000 in tid 2073 (GLThread 148)
02-07 20:37:50.980 2032-2039/? W/art: Suspending all threads took: 6.526ms

I'm not sure if these two problems have something in common. If not I can create a separate ticket.

Thank's in advance,
Chris

**Comment by sh39sxn** [comment]
In the meanwhile I have tried the app on a real device which is connected to the pc/android studio.
This way the app works but the rendering problem in android studio still exists.
I want to develop an own app based on this cardboard-java app. I need a solution for this problem.
Does really nobody have the same problem or knows a solution?

**Comment by dav-cz** [comment]
Fixed in v0.8, the View now correctly shows up (blank) in the design preview. Thanks for reporting.
