### ISSUE TITLE
GvrView seems to ignore system screen brightness settings

### ISSUE THREAD

**Issue by cversek** [googlevr/gvr-android-sdk#531]
So the problem is that no matter what the system brightness is set to, when going into VR mode the brightness seem maximized. Not sure if this is relevant, but I need to use the setting display->when in VR mode -> reduce flicker for  my application and I am targeting the Pixel 2XL.  

 I am writing an app that tests night vision, so I need to attain the full range of brightness for the display.  In the beginning of the app I need to "fry" the users eyeballs with a max brightness white screen, then take the brightness of my stimuli down as far as possible without hitting true black.  

The lowest float grayscale value that I could see  while testing in extreme dark (eyes adapted for > 10 min) was around 0.01795, but it seems as though below 0.017 is not visible at all and the cuttoff is abrupt like the pixel just turns off.  My hope was that I could get lower brightness by programatically changing the screen brightness to effect the GVR app, but this seems not possible?  Code is like:
```java
private void setBrightness(final int newBrightness) {
      //https://stackoverflow.com/questions/5161951/android-only-the-original-thread-that-created-a-view-hierarchy-can-touch-its-vi
      //
      runOnUiThread(new Runnable() {
          @Override
          public void run() {
              //Get the content resolver
              cResolver = getContentResolver();
              //try to adjust the brightness setting
              if (checkSystemWritePermission()) {
                  Log.i(TAG, "setBrightness: Setting brightness to " + String.valueOf(newBrightness));
                  //Set the system brightness using the brightness variable value
                  Settings.System.putInt(cResolver, Settings.System.SCREEN_BRIGHTNESS_MODE, Settings.System.SCREEN_BRIGHTNESS_MODE_MANUAL);
                  Settings.System.putInt(cResolver, Settings.System.SCREEN_BRIGHTNESS, newBrightness);
                  //Get the current window attributes
                  WindowManager.LayoutParams layoutpars = getWindow().getAttributes();
                  //Set the brightness of this window
                  layoutpars.screenBrightness = newBrightness / (float) 255;
                  //Apply attribute changes to this window
                  getWindow().setAttributes(layoutpars);
              } else {
                  Log.e("Error", "Cannot adjust system brightness");
              }
              }
      });

  }
```

Would it be possible maybe to attain a larger contrast range by changing the EGL settings, right now I am using the default
```java
gvrView.setEGLConfigChooser(8, 8, 8, 8, 16, 8);
```
could changing this let me access more of the lower range?

**Comment by jdduke** [comment]
Hi @cversek. The VR mode brightness is intentionally decoupled from the regular system brightness, as the user-customized screen brightness doesn't always map well to the VR experience, particularly with a low-persistence display.

That said, there was some [plumbing added in Android O](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/provider/Settings.java#3087) to support adjustment of the VR brightness. We'll look into exposing this plumbing publicly for Android P.

**Comment by cversek** [comment]
Thanks for the info.  The system update might also explain why my stimuli brightness mysteriously doubled overnight.  Yeah, low persistent mode is a real thorn in my side.  The fact that you guys let us turn it off was a major motivator for me to switch away from GearVR.  Giving power back to the developers is totally the way to spur innovation in this largely entertainment driven platform.  In the meantime I guess I can rollback the system or learn how to make custom builds.

**Comment by cversek** [comment]
Just wanted to get confirmation on this:  you weren't suggesting that developers could already change `Settings.System.SCREEN_BRIGHTNESS_FOR_VR` in Android O?  If you were, then maybe some help is needed for this novice Android dev.  I upgraded my API to 27, but  I get this compiler error `Error:(280, 70) error: cannot find symbol variable SCREEN_BRIGHTNESS_FOR_VR`.

**Comment by cversek** [comment]
So, I've been reading up on hidden Settings, seems like the developer can possibly change these with some hoop jumping.  Although my naive attempt:
```java
Settings.System.putInt(cResolver, "screen_brightness_for_vr", newBrightness);
```
crashed my app:
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.neurofieldz.template, PID: 21130
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.neurofieldz.template/com.neurofieldz.template.TemplateActivity}: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
 at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:1851)
at android.provider.Settings$System.putStringForUser(Settings.java:2273)
at android.provider.Settings$System.putIntForUser(Settings.java:2378)
at android.provider.Settings$System.putInt(Settings.java:2372)
```
Any help?  I am highly motivated to get this implementation working and don't care about publishing on the app store.

**Comment by jdduke** [comment]
What Android version is running on your device?

Unfortunately, until this is addressed in Android P, the only way for you to handle this in your app is to scale the brightness/contrast of your assets. I should also note that the ability to disable low-persistence is intentionally left to the user, and not the developer; different users are more susceptible to the side effects of low-persistence.

**Comment by cversek** [comment]
My Pixel 2XL device is running Android 8.1 and I'm currently building my app for API 27.   I'm already scaling my asset brightness but the low end of the scale is still too bright.  From my understanding on the Pixel 2 OLED display the overall screen brightness setting is implemented by PWM around 240Hz - this should work for our app and allow much more brightness variation on the low end.  

Yes, disabling low persistence is a user controlled setting, but we are our own users so to speak (anyway I imagine this can be toggled programmatically with WRITE_SETTINGS permission).  The system will be configured for our special purposes and we will not be distributing through the app store.  With that in mind, is building a custom android SDK a reasonable choice?  Or how about accessing hidden APIs via Java reflection and what can we get away with using the most promiscuous permissions?

**Comment by jdduke** [comment]
@cversek, could you try doing the following: 

1) Disable wifi
2) Clear the data/cache for Google Play Services
3) Clear the data/cache for Google VR Services

The Pixel 2 XL display required some workarounds in the GVR SDK which might impact your ability to hit a certain low brightness threshold. By resetting these settings (and disabling wifi to keep them propagating again), you might be able to achieve a lower value. If that makes a difference for you, feel free to message me offline and we can consider a more direct alternative.

**Comment by jdduke** [comment]
Per offline discussion, this seems to be a function of the device. VR-specific brightness may be exposed in a future Android release.

**Comment by cynicer** [comment]
I'm just facing the same problem. What the hell, why is this (still) a hidden API?
