### ISSUE TITLE
[Feature Request]VrVideoEventListener.onBuffering()

### ISSUE THREAD

**Issue by tao1** [googlevr/gvr-android-sdk#533]
Hi,

It would be very useful to know when video pauses because of buffering, and also when it resumes.

Kind regards,

Laurent.

**Comment by sigmaxipi** [comment]
We aren't planning on adding new features to VrView at this time. You should use [the video360 sample](https://developers.google.com/vr/android/samples/video360) if you need more functionality.

**Comment by tao1** [comment]
This is about a 5 lines addition in your code whereas reimplement all VrView features from video360 sample is pretty big. If only your SDK was open source, I could fork it...
Well, thanks for your response.
