### ISSUE TITLE
Control playback speed

### ISSUE THREAD

**Issue by damianMolinski** [googlevr/gvr-android-sdk#534]
Hi everyone,

First of foremost thanks for amazing and easy to use sdk.

I was wondering if controlling speed of 360 video is even possible using gvr sdk.
What i have i mind is something like this.

Imagine user running on the treadmill with vr headset, let say i know current run speed of user run and i know in what speed video is recorded. My goal is to show correct part of road.

Controlling playback speed seems like solution but i didn't find support for that. Is that even possible or should i look for other technology?

PS.
I know that unity guys have [Autowalk](https://github.com/JuppOtto/Google-Cardboard/blob/master/Autowalk.cs) script.

**Comment by sigmaxipi** [comment]
Take a look at the [Video 360 sample](https://developers.google.com/vr/android/samples/video360). It uses Android's [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) to render video. You cause use `PlaybackParams.setSpeed(float)` to control the speed of the video.

**Comment by damianMolinski** [comment]
Thanks for response,

This is exactly what i was looking for.
