### ISSUE TITLE
Samsung s8 flickering issue. 

### ISSUE THREAD

**Issue by tiger1990** [googlevr/gvr-android-sdk#540]
I am facing screen dim and flickering issue on samsung s8, same integration just working fine on 
other handsets. Tested on Motorola G4,G2,G4+,Xiomi,Lenovo etc.
I am not getting what is the cause. I think might be some OEMS problem or some security concerns.
Please suggest some help for this bug.

**Comment by jdduke** [comment]
The S8's display will enter low-persistence mode when VR mode is enabled. When viewing the display *outside* of a VR headset, this can make it seem like it's flickering unusually. However, when viewed inside the headset, it actually improves the experience by reducing apparent motion blur.
