### ISSUE TITLE
How can I observe LiveData from the GvrActivity?

### ISSUE THREAD

**Issue by jclova** [googlevr/gvr-android-sdk#542]
From the GvrActivity, I have been observing the LiveData change from the Room database.
This is possible because I have been implementing the LifecycleRegistryOwner interface in my activity. However, 'LifecycleRegistryOwner' class is deprecated forcing everyone to extend AppCompatActivity. 

Obviously, I can't extend AppCompatActivity if I am extending GvrActivity. I am afraid soon LifecycleRegistryOwner interface will not be accessible and I cannot use my current LiveData implementation on GvrActivity.

Do you have any solution to this?

**Comment by sigmaxipi** [comment]
You can directly use a [GvrView](https://developers.google.com/vr/reference/android/com/google/vr/sdk/base/GvrView) in a custom Activity. If you need more control, you can also use GvrLayout as demonstrated in the [videoplayer sample](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-videoplayer/src/main/java/com/google/vr/sdk/samples/videoplayer/WatchVideoActivity.java).
