### ISSUE TITLE
Soft keyboard showing when in VR mode

### ISSUE THREAD

**Issue by bluemarvin** [googlevr/gvr-android-sdk#545]
I just upgraded our application that was using 1.120 to 1.130 and now anytime a Text Edit View gets focus, the system soft keyboard covers the screen. Is this a regression or do I need to do something additional to prevent the keyboard from showing. For context we are drawing native android ui elements offscreen to a surface texture for displaying in our 3D scene.

**Comment by jdduke** [comment]
I'm not aware of any specific change that might have caused this. Are you using the GVR SDK directly, or one of the engines (Unity/Unreal)? Is your application manifest identical to what is was previously?

**Comment by bluemarvin** [comment]
It is a native app using the GVR SDK directly. I just tried to verify that 1.130 was the cause but now I can reproduce on 1.120 as well. Something must have changed in my app but I don't see anything obvious. I've tried adding android:windowSoftInputMode="stateAlwaysHidden" to the activity with no effect. So I guess while upgrading to 1.130 is not the issue the fact that the soft keyboard is covering the VR window is still an issue.

**Comment by bluemarvin** [comment]
One additional data point: My app application can switch between a Launcher activity and a Daydream activity. If I switch back and forth once, the soft keyboard seems to stop showing in VR mode when giving focus to a text edit view.

**Comment by sigmaxipi** [comment]
@bluemarvin this is and Android framework issue since GVR doesn't do anything special for the Android IME. Consider overriding the TextView with a custom class that handles all the focus events. Or you might be able to use [TextInputView.setInputType](https://developer.android.com/reference/android/widget/TextView.html#setInputType(int)) to avoid bringing up the keyboard.

**Comment by jdduke** [comment]
Yeah, you might also try explicitly/programatically adjusting focus when the Daydream Activity is shown. Feel free to re-open the issue if you think this is specific to Daydream.

**Comment by bluemarvin** [comment]
For anyone else that run into this issue. TextView.setShowSoftInputOnFocus(false) seems to work.
