### ISSUE TITLE
VrPanoramaView black screen when first load

### ISSUE THREAD

**Issue by fanrenyi** [googlevr/gvr-android-sdk#547]
Some mobile phones appear black screen because VrWidgetView add GLSurfaceView. In order to solve this problem, you can add a GLSurfaceView whose width and height is 0 in the activity's xml.

**Comment by jdduke** [comment]
Does the SDK sample (SimpleVideoWidget) work properly for you?

**Comment by fanrenyi** [comment]
on my mobile，MeiZu, Rom is FlyMe，SDK sample (SimplePanoWidget) work bad, it black screen when first load, the  the SDK sample (SimpleVideoWidget) work OK

**Comment by jdduke** [comment]
Would you mind attaching a bug report that captures the issue on this device? Or sending a bug report to me directly? Thanks.

**Comment by jdduke** [comment]
Hi @fanrenyi, without access to this specific device, and without a bug report, there's no much more we can do.
