### ISSUE TITLE
Don't open navigation panel with swipe on samsung phones

### ISSUE THREAD

**Issue by Anton111111** [googlevr/gvr-android-sdk#548]
This problem good view in https://github.com/googlevr/gvr-android-sdk/tree/master/samples/sdk-treasurehunt

When i start this sample on Samsung phone i can't open navigation bar (swipe from display corner). 
I tested it on Samsung s8, s8+, s9. On other phones (not Samsung) navigation bar is works.

How it can be fixed ?

**Comment by jdduke** [comment]
Hi @Anton111111, for better or worse, this is expected behavior on Samsung devices when the device enters VR mode. You'll have to exit VR via the "X" button in order to use or interact with the system UI.

**Comment by Anton111111** [comment]
But cardboard app from Google play and YouTube don't  have this problem.

**Comment by jdduke** [comment]
Right, those are Cardboard apps, and they may not enable the system VR mode. Daydream apps are required to enable the Android system VR mode.

**Comment by Anton111111** [comment]
Another question. Where in https://github.com/googlevr/gvr-android-sdk/tree/master/samples/sdk-treasurehunt is system VR mode enabled?
Is it manifest parameter or something other ?

**Comment by sigmaxipi** [comment]
https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/src/main/AndroidManifest.xml declares `com.google.intent.category.DAYDREAM` and `com.google.intent.category.CARDBOARD` so the app runs on both Daydream & non-Daydream phones. 

If you only want to support Cardboard mode, you can remove all the Daydream references in the manifest and in `TreasureHuntActivity.java`.

**Comment by Anton111111** [comment]
I've already tried remove com.google.intent.category.DAYDREAM. But it still don't show navigation bar on samsung phones.
