### ISSUE TITLE
Unable to create CardboardDeviceParams from uri

### ISSUE THREAD

**Issue by anakin78z** [googlevr/gvr-android-sdk#55]
W/CardboardDeviceParams: URI "http://goo.gl/nVLoL6" not recognized as cardboard device.

I'm unable to load CardboardDeviceParams from any uri. We would like to default to a specific headset if the user has not selected one using the Cardboard app or the settings button, but I'm unable to get the CardboardDeviceParams.createFromUri function to work. Here's how I'm using it:

CardboardDeviceParams.createFromUri(Uri.parse("http://goo.gl/nVLoL6"));

I've tried expanded urls and get the same error.

**Comment by dav-cz** [comment]
Have you tried unrolling that URL? createFromUri() assumes that the URL is fully unrolled.

FYI we may deprecate that function as it could hurt the ecosystem if developers overrule what users have selected. At least we'll make it no-op if the user has paired a specific viewer.
So I'm curious to hear about your use case, do you plan to bundle your app with your own custom viewer and therefore would like to optimize the experience with that custom viewer?
Thanks!

**Comment by anakin78z** [comment]
I did try unrolling the URL. 

The use case was that we had about a thousand people at the TED conference download a cardboard app for a session and then handed them specific cardboard headsets to use. We wanted the app to default to the settings for the viewer we handed out, since we knew it's the one they would be using, and there wasn't any time during the session to set up each viewer first. 
Ideally we can default to a specific viewer of our choice, which would then be replaced by whatever the user scans, if the user scans a new headset.

**Comment by jdduke** [comment]
Per the original discussion, createFromUri() only works with unrolled Uris, and at the moment we don't have any plans to support automatic unrolling. Note that there is a [native API](https://developers.google.com/vr/android/ndk/reference/group/h-m-d#group___h_m_d_1gacdbc7438587f61749324bff457c7fc7e) that would do the unrolling, though it doesn't work across all devices and its use is discouraged.
