### ISSUE TITLE
Large increase in blocked frames, Unity rigidbody

### ISSUE THREAD

**Issue by davidcox70** [googlevr/gvr-android-sdk#550]
This is a bit of an odd one. I've been struggling with frame rate in a particular scenario with a Samsung S8 SM G950F, and have found this odd issue;

With a scene of non-moving textured objects, where the camera is set to spin at a uniform rate using Unity's Update() and Transform methods, the resulting view works perfectly. However, if I change the way the camera rotates from a transform to a rigid body with some rotational force and no drag (so just an alternative way to spin the camera at uniform speed), then the GVR Performance Hud shows up to 50% blocked frames where the view passes highly textured objects.

This seems odd - I understand that blocked frames are the result of the GPU still being busy computing that last frame, so why would the method to rotate the camera in the exact same scene cause blocked frames? Ultimately, what the camera is being asked to render is the same. It's just how it's angle of rotation is calculated changes.

I tried the same test exporting to Gear VR using the Oculus SDK and the problem of reduced frame rate is not apparent.

I'm confused! So any help gratefully received.

DC

**Comment by jdduke** [comment]
Hi @davidcox70, would you mind filing this on the [Unity-specific GitHub project](https://github.com/googlevr/gvr-unity-sdk)? Thanks!
