### ISSUE TITLE
When HDMI output connected, smartphone screen is disabled

### ISSUE THREAD

**Issue by sexydot** [googlevr/gvr-android-sdk#552]
Hello,
I want to test my app with hdmi output (with dp usb3.0).
When I attach HDMI output cable to smartphone, HDMI output works. But smart phone screen is disabled.
If I want to see both side screen, How can I fix my applications?
Is there any API for this?

Thanks.

**Comment by jdduke** [comment]
There's no API to do this unfortunately. The problem is that the external Display can have different dimensions than the phone Display, so it doesn't always make sense to try to mirror the displays. Can I ask why exactly you need the phone screen functional in this case?

**Comment by sigmaxipi** [comment]
What are you trying to show on the TV? Would [Daydream + Cast](https://support.google.com/daydream/answer/7553433?hl=en) do what you want?
