### ISSUE TITLE
Reticle is not working.

### ISSUE THREAD

**Issue by dkshin** [googlevr/gvr-android-sdk#553]
I succeed build sample-video 360 with exoplayer for cardboard
but, Reticle is not working. It is still there.
Is there a good way?

**Comment by sigmaxipi** [comment]
The reticle will only work if you're using a Daydream device with a controller. For Cardboard, you can use [Treasure Hunt's headTransform.getQuaternion](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/src/main/java/com/google/vr/sdk/samples/treasurehunt/TreasureHuntActivity.java#L425) to control the reticle.

**Comment by dkshin** [comment]
Thank you!!

I used this code!

```
Orientation orientation = new Orientation(headRotation[0], headRotation[1], headRotation[2], headRotation[3]);
orientation.toRotationMatrix(modelReticle);

Matrix.multiplyMM(modelViewProjectionMatrix, 0, viewProjectionMatrix, 0, modelReticle, 0);
```
