### ISSUE TITLE
Toggling AndroidCompat.setVrModeEnabled On then Off destroys the Activity

### ISSUE THREAD

**Issue by achuvm** [googlevr/gvr-android-sdk#554]
We're using the following API to properly handle Daydream and GVR experiences:

https://developers.google.com/vr/reference/android/com/google/vr/sdk/base/AndroidCompat#setVrModeEnabled(android.app.Activity,%20boolean)

However, calling `setVrModeEnabled(activity, false)` causes the `activity` to be destroyed. This happens after we want to exit the VR experience, but remain in the Activity (through React Native which uses the 1 Activity).

Thanks,

**Comment by jdduke** [comment]
Hi @achuvm, can you try adding `uiMode` to the `android:configChanges` attribute in your manifest?

**Comment by achuvm** [comment]
Hi @jdduke,

Ahh that works! Thanks!
