### ISSUE TITLE
When playing 360 videos showing blank screen

### ISSUE THREAD

**Issue by penmatsa** [googlevr/gvr-android-sdk#561]
Getting blank screen when playing 360 videos in vivo V5s with below exception
com.google.vr.sdk.widgets.video.deps.fh$b: Decoder init failed: OMX.MTK.VIDEO.DECODER.AVC, Format(1, null, video/avc, -1, null, [3840, 1920, -1.0], [-1, -1]).

**Comment by sigmaxipi** [comment]
Can you play that video file on the device using any 2d video app? The MT6750 chipset might not be able to handle such a high resolution video.
