### ISSUE TITLE
v1.150.0 still requires 'READ_PHONE_STATE'

### ISSUE THREAD

**Issue by kuanyingchou** [googlevr/gvr-android-sdk#565]
Hi, 

After using the library, our app started to require permission 'READ_PHONE_STATE'.

Our 'app/build/outputs/logs/manifest-merger-global-release-report.txt ' says that the permission is implied since 'com.google.vr.sdk.audio has a targetSdkVersion < 4'.

Maybe #71 is happening again?

**Comment by sigmaxipi** [comment]
It looks like this issue regressed between 1.80 & 1.90 of the SDK. We'll fix this in the next version of the SDK. But the workaround mentioned in #71 should also work if you modify the audio library's AndroidManifest.xml
