### ISSUE TITLE
Is there any plan to play side-by-side stereo video with VrVideoView

### ISSUE THREAD

**Issue by crakaC** [googlevr/gvr-android-sdk#567]
Currently, we can only play over-under stereo video with VrVideoView.
I really want to play side-by-side stereo video with VrVideoView.

**Comment by sigmaxipi** [comment]
VrVideoView is meant for 360 videos and it's not possible to pack those into a side-by-side video file without heavy distortion.

There is no plan to add new functionality to VrVideoView, but there is a new open source video360 sample that you can use to play side-by-side videos: https://github.com/googlevr/gvr-android-sdk/issues/510
