### ISSUE TITLE
Lenovo Mirage Solo Crash

### ISSUE THREAD

**Issue by mgatelabs** [googlevr/gvr-android-sdk#568]
I've been trying to figure out what is going on.  My app "Mobile VR Station" works with standard Daydream, but the Lenovo Mirage Solo always crashes with this stacktrace:

> java.lang.IllegalStateException: 
>   at android.os.Parcel.readException (Parcel.java:1951)
>   at android.os.Parcel.readException (Parcel.java:1889)
>   at aff.transactAndReadException (PG:11)
>   at cjb.a (PG:87)
>   at com.google.vr.ndk.base.VrCoreSdkClient.prepareVr (PG:137)
>   at com.google.vr.ndk.base.VrCoreSdkClient.access$600 (PG:149)
>   at com.google.vr.ndk.base.VrCoreSdkClient$1.onServiceConnected (PG:26)
>   at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1637)
>   at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1666)
>   at android.os.Handler.handleCallback (Handler.java:789)
>   at android.os.Handler.dispatchMessage (Handler.java:98)
>   at android.os.Looper.loop (Looper.java:164)
>   at android.app.ActivityThread.main (ActivityThread.java:6633)
>   at java.lang.reflect.Method.invoke (Native Method)
>   at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:772)

The app is a Java based Daydream app with C++ code to handle the arm model.  It doesn't even seem to reach my code.

**Comment by jdduke** [comment]
Any chance you can attach the surrounding logs (adb logcat) for context? Or send a bug report directly?
