### ISSUE TITLE
Google VR Services Causes Unresponsive Samsung S8 phone

### ISSUE THREAD

**Issue by ajavamind** [googlevr/gvr-android-sdk#569]
A Cardboard only app I developed for viewing stereo photos  https://play.google.com/store/apps/details?id=com.andymodla.apps.vrstereophotoviewer&hl=en_US will crash a Samsung S8 phone locking up touch and flashing the screen. Only by powering down can I get back phone use. Sometimes the display does not flash but shows a photo with the wrong colors, or keeps displaying a photo without touch working. Home button brings back main screen but touch does not work until the phone is powered off or restart. This problem does not usually occur quickly, it may happen after normal use about 10-60 minutes. I do not know if this happens with other Cardboard apps. The app currently uses an old SDK VR version, but when updated to 1.150.0 with Android 26, the same issue occurs (with less wait time for problem to happen).

The only way I prevent the problem is by disabling VR Services Version 1.15.196855678. Since my app is Cardboard only this fallback approach has to be used. I wonder if there is a memory leak in VR services. An app user cannot uninstall the Google VR services app, but a user can fortunately disable in Settings->Apps. 

This problem only happens with S8 (Android 8.0.0 using T-Mobile), it does **not** occur with S7 (Android 7.0). And the problem has not been seen in debug versions of the app, only release.

**Comment by sigmaxipi** [comment]
Can you capture a bugreport using `adb bugreport`? That will provide more info.

Some more steps to try:

* Make sure VR mode isn't enabled by using AndroidCompat.html#setVrModeEnabled(false). VR mode can affect the clock speeds and other low level aspects of the device. The AndroidManifest.xml should also not have any `enableVrMode` entry.
* Make sure `getAsyncReprojectionEnabled` returns false. This affects how the app renders content to the display.
