### ISSUE TITLE
Hooking into IPC between any App and VrCoreListenerService

### ISSUE THREAD

**Issue by Harsh2098** [googlevr/gvr-android-sdk#575]
1. Is it possible to intercept binder/IPC calls between any random VR app (which uses GVR-sdk) and the VrCoreListenerService?

2. Are the calls/messages encrypted between app and the service? (Please, at least tell Yes/No)

I want to apply custom distortion to any VR app using GVR-sdk for my custom headset. Consider we have permissions and this is for development purpose.

**Comment by sigmaxipi** [comment]
In general, the Android Binder system doesn't let you intercept or forge calls without a rooted device.

If your headset is a standard Cardboard headset, you can force Daydream apps to run by [skipping the compatibility check](https://developers.google.com/vr/develop/android/devoptions#skip_vr_entry_screens). This isn't a supported way of using custom headsets and may break in the future, but it should work for now.

**Comment by Harsh2098** [comment]
Thanks !
