### ISSUE TITLE
How can i get 6DOF information in android studio project

### ISSUE THREAD

**Issue by bell-one** [googlevr/gvr-android-sdk#578]
hello, I'd like to use 6DOF head tracking information on my android studio project with mirage solo

on developers.google said add feature about 6DOF in manifest file,
after this how can I get position information in java code?

**Comment by sigmaxipi** [comment]
When your app is configured for 6dof tracking in the manifest, the head transform matrix provided by the SDK will have true 6dof data. Are you not seeing translational components in it?

**Comment by bell-one** [comment]
Well.. maybe I have problem with get total transform data,

I just use orientation data with gearvr framework on my project, 
and with this, I can't get position information

So I just want to use googlevr transform information directly but with this 

I checked treasure hunter example and there, get headtransform with stereorender interface
by overiding onNewFrame..

should I change my class to exnteds Gvrview implements some render interface?
or is there any way to get headtransform without these?

**Comment by sigmaxipi** [comment]
The best option is to contact the GearVR Framework team and ask them to expose position.

You can also use GvrApi.getHeadSpaceFromStartSpaceRotation. See https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-videoplayer/src/main/java/com/google/vr/sdk/samples/videoplayer/VideoSceneRenderer.java#L207 or any of the NDK samples for more info.
