### ISSUE TITLE
Set initial angle of VrPanoramaView

### ISSUE THREAD

**Issue by enigma969** [googlevr/gvr-android-sdk#586]
Hi, 

is it possible to set the initial angle of a VrPanoramaView image? I would like to align the initial angle to the compass direction, but couldn't find any option to do so. 

Thanks

**Comment by sigmaxipi** [comment]
There are no plans to add more functionality to the VrView widgets. But you more complex controls for a 360 media player, consider using the Video360 sample as a starting point. See #510 for more info.
