### ISSUE TITLE
How can I reset yaw orientation of a VrWidgetView / VrVideoView?

### ISSUE THREAD

**Issue by guglie** [googlevr/gvr-android-sdk#589]
How can I reset orientation of a VrWidgetView? In particular VrVideoView.

I've seen that **com.google.vr.sdk.base.GvrView** class has a `recenterHeadTracker()` method, but I don't know if the video widget has an associated **GvrView**.

Another thing that I've found is that the **VrVideoView** has a **VrVideoRenderer** property that has a `nativeSetCameraRotation()` method. Can I use that?

**Comment by sigmaxipi** [comment]
We have no plans to add this functionality to VrWidgetView. Instead we created the video360 sample which demonstrates creating a custom 360 viewer and you can add whatever functionality you need. See #510 for more info.
