### ISSUE TITLE
There is no CardboardActivity extends AppCompatActivity

### ISSUE THREAD

**Issue by matsujun** [googlevr/gvr-android-sdk#59]
We need to extends CardboardActivity to use this SDK, but it does not extends AppCompatActivity.
So we cannot use Support Library.(android.support.v4.app.Fragment, Vector Drawable etc...)

**Comment by dav-cz** [comment]
Have you tried using CardboardView instead of CardboardActivity?

CardboardView does most of the VR work (stereo rendering, head tracking, etc).

**Comment by dav-cz** [comment]
Closing this as we don't plan to make GvrActivity extend AppCompatActivity. 
Having your own Activity that holds a full screen GvrView (formely called CardboardView) is probably the way to go.

**Comment by RamIndani** [comment]
I used CardboardView but I am not able to get head tracking to work. Do you have any pointers. I have created XML element in layout with CardboardView and setting renderer from fragment.

**Comment by nathanmartz** [comment]
Please check out the Treasure Hunt sample, as it shows how to pull all of those pieces together.

**Comment by RamIndani** [comment]
@nathanmartz Treasure Hunt sample sets the setGvrView(gvrView); and extends GvrActivity, setGvrView(GvrView) is not available if you are extending AppCompatActivity or any Fragment.
