### ISSUE TITLE
Interactive 360 image

### ISSUE THREAD

**Issue by savadmv** [googlevr/gvr-android-sdk#591]
I want to create an android app which display multiple 360 Images.I want to show the remaining images as thumbnail above the the image currently displayed .There must some controller (Gaze) So that i can select the next image i want show from thumbnail using that controller .Is there any solution using this sdk??,If not,Please suggest me some other alternative solution for the same problem...Thanks

**Comment by sigmaxipi** [comment]
You can use the [video360 sample](https://developers.google.com/vr/android/samples/video360) as a starting point to create more complex image viewers. The sample only supports the Daydream controller, but you can copy the code from the hellovr samples to add support for gaze input. The sample also shows how to render a floating 2D UI in VR using standard Android Views and you can use that functionality to show thumbnails.

**Comment by savadmv** [comment]
How can i use the **video360 sample**  to Display image

**Comment by sigmaxipi** [comment]
See the documentation at https://developers.google.com/vr/android/samples/video360#ui_and_adb_commands_to_load_media and https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/MediaLoader.java#L42

You will need to run
```
adb shell am start \
  -a android.intent.action.VIEW \
  -n com.google.vr.sdk.samples.video360/.VrVideoActivity \
  --ei stereoFormat 2 \
  -d "file:///sdcard/IMAGE.JPG"
```
