### ISSUE TITLE
WorldSense (6DOF) Frame of Reference

### ISSUE THREAD

**Issue by michaeltheory** [googlevr/gvr-android-sdk#592]
Hi there,

I'm developing on the Java SDK for World Sense on the Lenovo device. The frame of reference for the head position is centered at Y=0.

On other 6DOF systems, and even on the same device in WebXR, the frame of reference puts Y=0 at floor level. I scoured through both the SDK and NDK and couldn't find anything about how to use the "room" frame of reference.

Seeing as how WebXR in Chrome uses the GVR SDK, it must be possible. Can someone point me in the right direction?

**Comment by sigmaxipi** [comment]
https://github.com/googlevr/gvr-android-sdk/blob/master/samples/ndk-hellovr/src/main/jni/hello_vr_app.cc#L453 has
```
float ground_y = gvr_api_->GetCurrentProperties().Get(
                       GVR_PROPERTY_TRACKING_FLOOR_HEIGHT, &floor_height)
                       ? floor_height.f
                       : kDefaultFloorHeight;
```

https://developers.google.com/vr/reference/android/com/google/vr/ndk/base/GvrApi#getCurrentProperties() and https://developers.google.com/vr/reference/android/com/google/vr/ndk/base/Properties.PropertyType#TRACKING_FLOOR_HEIGHT are the matching Java APIs.

However, after looking through the code, I see that there is a bug where the properties isn't refreshed and it's possible for the floor height to change while the app is running as the tracking system adapts. This bug is being tracked internally and will be fixed in an upcoming release.

**Comment by michaeltheory** [comment]
I guess I didn't scour enough :) Thank you!

**Comment by michaeltheory** [comment]
Sorry, trying to use this with Kotlin and struggling a bit with `Value`.

```
private val value = Value()
....
gvrView.gvrApi.currentProperties.get(Properties.PropertyType.TRACKING_FLOOR_HEIGHT, value)
Log.d("GVR", value.asFloat().toString())
```

That seems to prevent rendering with logs like `Missed vsync by 36444us (CPU load is too high)`

Am I using it wrong?

**Comment by sigmaxipi** [comment]
I've attached a patch for code that will go into a future version of sdk-hellovr. I've verified that it works on a Mirage Solo. I'm not familiar with Kotlin and it's not a supported language for GVR, but the snippet you provided appears correct. Does the `.get` call return `true`? And are you calling it each frame? My comment above about the value not refreshing was incorrect and the Java API appears to be working as expected.

[FLOOR_HEIGHT.patch.txt](https://github.com/googlevr/gvr-android-sdk/files/2622384/FLOOR_HEIGHT.patch.txt)

**Comment by michaeltheory** [comment]
Thanks for that. It looks like the code is pretty much the same. My code is never actually getting past the `.get` line, as the float value is never logged. I am calling it every frame.

I'll try a few things including moving that code into a Java class

**Comment by michaeltheory** [comment]
Finally got a chance to try this again, I found the issue. If you're using Kotlin, you must use the full Java syntax of `gvrView.getGvrApi().getCurrentProperties()` even though Android Studio will warn you to change it to `gvrView.gvrApi.currentProperties`

**Comment by sigmaxipi** [comment]
Is this issue specific to the GVR classes? GvrAPI does have some multi-classloader dynamic loading magic under the hood and it may be interfering with Kotlin. While GVR doesn't support other languages, this was the issue of this type that we've heard of.

**Comment by michaeltheory** [comment]
That makes sense. This is the first time I've seen that happen, but from my end I'm all good
