### ISSUE TITLE
Play a 360-degree video taken from the assets folder in "video360" sample

### ISSUE THREAD

**Issue by animis93** [googlevr/gvr-android-sdk#594]
I'm trying to play a 360 video taken from the assets folder via the statement:
`Intent videoIntent = new Intent(Intent.ACTION_VIEW, Uri.fromFile(new File("/android_asset/" + fileName + ".mp4")));`
but when I start the app it gives me the error: 
`Error loading file ... java.io.FileNotFoundException`

I also tried to save the video on the device storage, always receiving the same error.

How can I play a video that is in the assets folder?

**Comment by sigmaxipi** [comment]
Can you read bytes from the file directly? If not, you may be missing permissions or have a typo in the file name.
