### ISSUE TITLE
Viewer QR Code generator on Google's site fails with Firebase exception

### ISSUE THREAD

**Issue by cmdr2** [googlevr/gvr-android-sdk#598]
Hi, apologies if this is not the right project to report to. I'd be happy to be redirected.

As of a few weeks, the official QR code generator for VR headsets on Google's site has not been working. It throws a javascript exception on typing any character in any of the form fields.

URL: https://vr.google.com/intl/en_in/cardboard/viewerprofilegenerator/

The exception is:
```An error has occurred.
undefined is not an object (evaluating '$scope.data.update_timestamp = Firebase.ServerValue.TIMESTAMP')
```

Maybe some credentials expired? Would it be possible to please take a look?

Thanks
~cmdr2

**Comment by sigmaxipi** [comment]
We're investigating this issue. Note that the code for the profile generator is open sourced at https://github.com/google/wwgc

**Comment by virtualguest** [comment]
The Cardboard app to scan the QR code no longer functions on Android. We've tested on Galaxy  S7 and S9 using 15+ QR codes. All return a 'Unrecognised QR code' error. The Cardboard QR scans work on iOS, though.

**Comment by cmdr2** [comment]
@sigmaxipi Thanks, I've submitted a PR with a fix for the issue. It required an update for the Firebase library, and needed to replace Google URL Shortener API with Firebase Dynamic Links. Works fine on my local system now. Hopefully it'll help get the system back online soon. https://github.com/google/wwgc/pull/5

@virtualguest The QR code scanner worked for me last week (HTC One M8), but I would suggest filing a separate issue, to avoid confusion with this one (this issue is for QR code generator not working).

**Comment by sewasewa777** [comment]
#598

**Comment by sigmaxipi** [comment]
The site has been updated.
