### ISSUE TITLE
setConvertTapIntoTrigger(false) disables the onCardboardTrigger callback for the mangetic trigger

### ISSUE THREAD

**Issue by R1ck77** [googlevr/gvr-android-sdk#60]
It looks like the `setConvertTapIntoTrigger` interacts negatively with the original cardboard trigger detection.

Setting it to false:

    setConvertTapIntoTrigger(false);

will prevent **any** magnetic trigger event from being delivered. This yields for both the default `onCardboardTrigger` event in the CardboardActivity, as it is for the `CardboardView` listener.

The bug can be easily reproduced in the `TreasureHunt` sample:

    [...]
    setContentView(R.layout.common_ui);
    CardboardView cardboardView = (CardboardView) findViewById(R.id.cardboard_view);                                                                   
    cardboardView.setRestoreGLStateEnabled(false);
    cardboardView.setRenderer(this);                                                                                                                   
    setConvertTapIntoTrigger(false); // Added by me                                                                                                                   
    setCardboardView(cardboardView);
    [...]

will prevent the magnetic trigger from working.

The issue wouldn't be worth of notice, if there would be a way to distinguish between tap events and trigger events in onCardboardTrigger (at which point, just leaving `setConvertTapIntoTrigger` to true/unset, and filtering the events in the callback would be sufficient to work around the issue).

Thank you for your attention!

**Comment by dav-cz** [comment]
Thanks for the report, we'll look into it. 
We're probably going to just remove setConvertTapIntoTrigger(), since it should be always set to true now that we have way more Cardboard v2-like viewers in the wild than original Cardboard viewers with magnet.
In the meantime I guess I'd say refrain from calling setConvertTapIntoTrigger(false).

**Comment by R1ck77** [comment]
Thank you David!

I'm glad to find out that the magnetic trigger is disappearing (no matter how nice an idea it was, when the project started).

To be honest, the addition of the `setConvertTapIntoTrigger()`, as a feature, still surprises me a bit.

I understand it must be more a nicety to developers (thanks!), rather than a necessity, as I don't see the point to create a workaround for something as simple as:

    mCardboardView.setOnTouchListener(new OnTouchListener() {
        [...]
    }

I mean, it's android 101 stuff: a developer not able to figure that out, isn't probably (yet) in the league for a VR app... :)

Personally, I always kept it set to `false`, as doing so (and setting the `onTouchListener` manually) *is the only way to discriminate the origin of a trigger event*.

That's a nice thing to have, as it allows to filter out magnetic events only (I offer my users an option to do that, and I personally use it).

I know it may look pointless but this is not an uncommon scenario:

- user without proper headset configuration (magnetic trigger reported when not really present)
- big headphones while using the VR app, for more immersion

which usually leads to at least a couple annoying spurious magnetic trigger events. 

Therefore, if you are really going to remove the `setConvertTapIntoTrigger` and make it the default, could you please consider changing the signature of `onCardboardTrigger` to include information about the source of the event (a string or enum of sorts, if not even a luxurious structure with other event details... :) )?

Cheers,
Riccardo

**Comment by dav-cz** [comment]
Thanks for the feedback, and thanks for raising the issue of spurious magnet triggers.
This comforts us in our decision to remove support for magnet trigger detection, as communicated in our v0.8 release notes. Magnet detection has never been 100% reliable, and also takes some cpu load. Most users these days use a cardboard v2 compatible viewer with a touch screen mechanism. Correspondingly, we marked setConvertTapIntoTrigger() as deprecated. I'm therefore closing this issue.
