### ISSUE TITLE
QR Code on Cardboard app for Android doesn't 

### ISSUE THREAD

**Issue by virtualguest** [googlevr/gvr-android-sdk#604]
The Cardboard app to scan the QR code no longer functions on Android. We've tested on Galaxy S7 and 2x S9's using 15+ QR codes. All return a 'Unrecognised QR code' error. The Cardboard QR scans work on iOS, though.

**Comment by sigmaxipi** [comment]
This is fixed in v1.9 of the Cardboard app which is currently rolling out to production. This should be fixed by Wednesday.

**Comment by virtualguest** [comment]
> This is fixed in v1.9 of the Cardboard app which is currently rolling out to production. This should be fixed by Wednesday.

Fantastic, great to hear. Thanks!
