### ISSUE TITLE
Successful build with Unity ARM64 IL2CPP but missing libraries from APK

### ISSUE THREAD

**Issue by axel20000** [googlevr/gvr-android-sdk#607]
I'm new to GVR with Unity and I made a Test APP which works great. I can go VR mode and back normally. I read about Google's policy for August 2019 and 64 bit apps, so I wanted to update my Test APP to practice the procedure.

I followed the instructions on https://developer.android.com/distribute/best-practices/develop/64-bit and I was able to build my APK with IL2CPP backend and ARM64 check (I had to download NDK suggested by Unity).

I ran the Test APP on my phone and this time I couldn't go VR mode. I read logcat and I could see that GVR was not found. Then I checked my APK and I could see there were no GVR files on the "arm64-v8a" folder. I can see "libaudioplugingvrunity.so", "libgvr.so", "libgvrshim.so" and "libgvr_keyboard_shim_unity.so" only in "armeabi-v7a" and x86 folders. I guess the problem is the missing .so files for 64 bit.

I used GoogleVRForUnity_1.180.0.unitypackage for Unity 2018.2.19f1 (which asked me to download NDK 13.1.3345770)

I guess I'm doing something wrong but I can't see what. I'm not really an expert on building, graddle and versions.

**Comment by sigmaxipi** [comment]
Unity issues are tracked at https://github.com/googlevr/gvr-unity-sdk/issues

https://github.com/googlevr/gvr-unity-sdk/issues/1008 tracks 64-bit support.
