### ISSUE TITLE
how to update current panorama image

### ISSUE THREAD

**Issue by ganico** [googlevr/gvr-android-sdk#609]
I'm already using the video360 sample, i'm just wondering is there any other way of loading a new 360/panorama image aside from calling the activity again? (this will trigger by tapping a button for example)

Currently, i'm doing something like this..
val intent = Intent(this, VideoActivity::class.java)
intent.putExtra("panoramaIndex", 5)
startActivity(intent)

the "panoramaIndex" is what I use to determine what image to load, this one is currently working but i'm just wondering if there's a much better way to do this? :)

**Comment by sigmaxipi** [comment]
https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/MediaLoader.java#L266 is the code that sets the loaded bitmap as the texture for rendering. If you hold onto the Surface that is returned there, you can call
```
      Canvas c = displaySurface.lockCanvas(null);
      c.drawBitmap(NEW BITMAP, 0, 0, null);
      displaySurface.unlockCanvasAndPost(c);
```
with the new Bitmap without recreating the Activity.

**Comment by ganico** [comment]
I saw it, alright.. will try it tonight, thanks for the quick response :)
