### ISSUE TITLE
onDrawEye() called with incorrect viewport dimensions the first few times when permission prompt is shown

### ISSUE THREAD

**Issue by scorpeeon** [googlevr/gvr-android-sdk#61]
Hello!

I'm developing an app using Cardboard SDK for Android that uses the phone's camera.
I'm recently trying to target API level 23, which of course requires runtime permission for the camera (and currently also READ_EXTERNAL_STORAGE for the viewer pairing - this might not be longer needed in v0.7.0 is I read it correctly).

So my Activity (which extends CardboardActivity) asks for permissions in onResume() after which onRequestPermissionsResult() is called some time later.
I have some textures which size is dependent on the viewport dimensions in onDrawEye().
In my experience these dimensions normally wouldn't change while the app is running (unless some configs change like turning off VR mode) and I also assumed the framebuffer binding (distortion correction is enabled) in onDrawEye (as documented here: https://developers.google.com/cardboard/android/latest/reference/com/google/vrtoolkit/cardboard/CardboardView.StereoRenderer#public-methods) to be constant - though this is not documented explicitly.
Now the problem is that the first time my app starts (when the prompt appears to either allow or deny the permissions) the first few times when onDrawEye() is called - some of them called before the callback from the permission prompt - the viewport dimensions and framebuffer binding are incorrect, different than a little later on after the permission prompt is closed. I'm guessing this prompt interferes with the Cardboard SDK (or OpenGL) in some unexpected way.
After the permissions are granted (so prompt isn't displayed anymore), the second time the app starts this problem no longer appears, onDrawEye()'s viewport and framebuffer bindings are correct and constant even in the first call.
For instance on Nexus 5, when permission prompt is shown, the first time onDrawEye() is called the viewport dimensions are incorrectly 1302x1550 (later they would be 1129x1230 which should be correct), and the framebuffer binding also changes (typically from 1 to something like 2).

So my question is basically is this is a bug, or is this intended behavior and we should be prepared for weird changes in viewport dimensions in special cases like this?

Also a related question is the same about the framebuffer binding: can it change similarly in weird cases like this?

Is there any indication when these changes can happen? The documentation says about the framebuffer binding in onDrawEye() to query it using glGetIntegerv(GL_FRAMEBUFFER_BINDING, ...). But querying it in every single onDrawEye() might have some performance impact.
For instance I noticed onSurfaceChanged() is called after this permission prompt is closed that might indicate a change like this happened. But it looks like the correct values for viewport dimensions and framebuffer bindings aren't yet restored to their correct/final value when this callback comes, only a few (a pair) onDrawEye() calls later. 

I'm attaching a modified treasure hunt project (with permissions prompts added) where I could reproduce this issue.
[treasurehunt.zip](https://github.com/googlesamples/cardboard-java/files/197437/treasurehunt.zip)

**Comment by dav-cz** [comment]
I think this is expected (if I understand your issue correctly)

What happens is that the viewport dimensions depend on what Cardboard-compatible viewer is currently paired to your phone. In order to read what viewer is paired, the app needs to be granted read access to the S/D card.
The first time onDrawEye is ever called, that permission hasn't been granted yet, so the SDK assumes default viewer params. In the mean time, the permission dialog is shown to the user, user accepts to grant permission, and when the app is resumed the SDK can now read the actual viewer params and resize the viewports accordingly -- hence the different viewport dimensions.

Hope that helps!

**Comment by scorpeeon** [comment]
dav-cz: great idea, I wouldn't think about that. I tested it by granting the storage permission and not granting the camera permission so that the prompt would still appear, and it indeed looks like in this case that onDrawEye() is called with the correct viewport parameters even when the prompt is shown. So it really isn't the prompt interfering, just the temporary lack of storage permission that's causing this.

But this is a bit confusing to me. Based on the changelog I thought the known issue for SDK v0.6.0 for the broken pairing on API 23 was solved in SDK v0.7.0, but apparently this means that it isn't really the case. It's merely a small patch so that when you click the settings icon, it asks for the storage permission, so afterwards it works correctly. But it doesn't solve the problem because as long as you don't click the settings icon, the storage permission is still not granted which is still needed to read the stored Cardboard profile, so an incorrect (default?) profile will be used.
So if I understand it correctly, the only real solution would be changing the storing of the viewer profile to some other place where no storage permission is needed, which was being worked on:
"We're working on a replacement to our current solution of storing the viewer profile on the S/D card."

So is this still a known issue that is still being worked on?

**Comment by dav-cz** [comment]
"""So if I understand it correctly, the only real solution would be changing the storing of the viewer profile to some other place where no storage permission is needed, which was being worked on:"""
Yes you're right, the solution in 0.7.0 is a temporary patch so that there's a way for this work, but it's far from an ideal solution. We're working on a better solution where these parameters are stored in a central place that is *not* the S/D card, stay tuned!

**Comment by scorpeeon** [comment]
Were there changes regarding this in the latest release (v0.8.0)?
I don't see any info in the changelog, but the WRITE_EXTERNAL_STORAGE permission has been removed from the sample app. (though targetSDK got downgraded from 23 to 22...)

**Comment by jdduke** [comment]
Note that Google VR Services is now the primary provider for viewer parameter storage, and is available on all Kitkat+ devices. This application eliminates the need for every client to declare storage permissions.
