### ISSUE TITLE
How to disable multi-touch when interacting with the image.

### ISSUE THREAD

**Issue by ln206** [googlevr/gvr-android-sdk#613]
Hello everyone,

How do I disable multi-touch when interacting with the image? I've tried to use `vrPanoramaView.setMotionEventSplittingEnabled(false);`, but I still have problem with multi-touch.

Reproduce steps:
1. touch and interact with the 360 image with right finger.
2. touch and interact with the 360 image with left finger.
3. stop touching the 360 image with finger while left finger is still touching. 

After these steps, it just jumps to another position in the image.

**Comment by sigmaxipi** [comment]
The VrPanoramaView widgets have been deprecated. You should switch over to the code in the video360 sample which allows more customization. See #510 for more info.
