### ISSUE TITLE
is it possible to represent current FOV

### ISSUE THREAD

**Issue by ganico** [googlevr/gvr-android-sdk#616]
<img width="71" alt="Screen Shot 2019-03-11 at 01 42 30" src="https://user-images.githubusercontent.com/7714293/54089009-1bfdf500-439f-11e9-9661-2188740b34b6.png">

is it possible to show a indicator something like this?? to show where the current view is looking at.. in video360 sample..

**Comment by sigmaxipi** [comment]
The FOV is computed at https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/MonoscopicView.java#L301

**Comment by ganico** [comment]
@sigmaxipi yes, but I wanna get the current value as the user pan or move the device... my question here on #615 you give me this line of code "Matrix.multiplyMM(viewProjectionMatrix, 0, projectionMatrix, 0, viewMatrix, 0);" which i'm not sure how can I extract the current angle that I have.. would you give a sample code to illustrate it?

**Comment by sigmaxipi** [comment]
Answered in https://github.com/googlevr/gvr-android-sdk/issues/615
