### ISSUE TITLE
Gvr view rotated 90 on z axis

### ISSUE THREAD

**Issue by TheBricktop** [googlevr/gvr-android-sdk#617]
Samsung Galaxy S8, oreo, gvr 1.20, everything was good until recently all gvr apps started to rotate view in such manner that up is now pointing right and every rotation is tilted to the right, I'm absolutely stumped, no amount of changing the autorotation options fixes the problem which persist when autorotation is on or off. It seems that when app is starting it starts in correct orientation but when gvr lib kicks in it flips to the right anyway. I'm screwed.

**Comment by sigmaxipi** [comment]
Can you check **VR Settings -> Developer options -> Enable GVR head tracking service** and see if that is enabled? If so, can you disable it and reboot?

**Comment by TheBricktop** [comment]
Ive figured it out myself, with the new update for GVRservices something went sideways, all i had to do was uninstall the services completetly from my phone and then install it again.
Way to go, add it to the FAQ or sth.
