### ISSUE TITLE
Does this SDK support playing remote URIs?

### ISSUE THREAD

**Issue by kvenn** [googlevr/gvr-android-sdk#65]
I've hosted a few monoscopic and stereoscopic .mp4 files which I've tried to play in the `simplevideoviewwidget` sample, but haven't had any luck. I just added in a line to override the local uri with a remote uri:
```java
fileUri = Uri.parse("http://www.myurl.com/360video.mp4");
```

I just got it working with iOS sample where the docs specify that the load method works with remote URL's, but the Android docs for `loadVideo(Uri)` make no such promise. I'm just wondering if there currently is support for playback of remotely hosted `Uri`s (or support in the near future).

Thanks

**Comment by kfung0426** [comment]
+1

I am seeking remote url support too

**Comment by lingkang1988** [comment]
This feature is useful, looking forward to seeing it soon

**Comment by jksfood** [comment]
+1,as soon as possible

**Comment by 5bruce** [comment]
I met the same trouble.It just can play the local video by this method(loadVideo(Uri)).But if your file is too big ,it does work.I want to enter the video link, then you can play video. Do not know how to get. This is my demand is not supported? This function is perfect or. thanks!

**Comment by wwrrss** [comment]
+1 this is a must have!

**Comment by kvenn** [comment]
Just as a follow up to anyone who's interested:
The iOS SDK supports this so I can only imagine it is in the pipeline - this is also version 0.7.0 so I have big dreams for this SDK in the future. So I wouldn't really recommend trying to find a way around it.

BUT if you're really in a pinch (like I was), I got remote URL's to work by building a custom downloader which downloads the .mp4 video resource to the device. Then when it reaches about 10% completion, I start playing the file back using the SDK's `loadVideo(String)` method. I have a catch in the `onError` for `FileNotFoundException`s which tells the system to wait a bit, then resume playback when there has been additional progress on the download. This is pretty much just a crummy buffer implementation.

It worked fine and was easy to write, but was by no means optimal.

**Comment by dav-cz** [comment]
Looks like this feature is popular! Thanks for the feedback, we'll definitely place this high on our TODO list.

**Comment by humhann** [comment]
+1, would be very welcoming to have

**Comment by BrendanParks** [comment]
+1, an out-of-the-box solution to this would be totally awesome

**Comment by Millertoken** [comment]
@dav-cz hello,when this can be completed?And how can i use other mediaplayers play videos on the videowidget?

**Comment by dav-cz** [comment]
We added support for remote URLs (e.g. www.domain.com/file.mp4) in v 0.8. Pretty basic for now as it supports only mono 360, but we'll improve this in future versions.

**Comment by dav-cz** [comment]
By the way, thanks all for the massive feedback on this issue. This has helped up prioritize this even while we were super focused on adding support for NDK and Daydream developer preview.

**Comment by aaronliew** [comment]
@dav-cz , thanks for your effort. I still having issues in playing the video from remote url. The whole screen was black. All I heard was just the audio.  Any solution for this issue?

**Comment by dav-cz** [comment]
Hi @aaronliew, could you create a separate bug for this? with logcat / phone model / android API / whether you have a back screen with a sample video such as http://techslides.com/demos/sample-videos/small.mp4

**Comment by digitalbuddha** [comment]
@dav-cz I'm having trouble playing a remote video due to inability to buffer.  The video in question is: `http://video1.nytimes.com/video/360-demo/cool.mp4`

When I drop the video in as a static asset everything plays perfectly. When trying to stream, the video stops and does not start on its own again.  Is there a way to control how much is download before starting as well as general buffering strategies?

The only code change I made to SimpleVrVideoActivity is to change the url in async task to `        videoWidgetView.loadVideo(Uri.parse("http://video1.nytimes.com/video/360-demo/cool.mp4"),new Options());`

I see that there's some generated code that deals with exoplayer, maybe there are more hooks that can be exposed?

**Comment by dav-cz** [comment]
What phone / Android version are you using? Any thing interesting in logcat?

I'm able to play your video with the sample app on Nexus 5 running Android 5.0.1.

> adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -d "http://video1.nytimes.com/video/360-demo/cool.mp4" --ei inputFormat 1

**Comment by digitalbuddha** [comment]
5x N beta 4. Will confirm on lots of devices on Monday

**Comment by digitalbuddha** [comment]
@dav-cz apologies for posting on an older issue but we did some more tests and the issue is only on N Beta devices.  Just a heads up that there seems to be buffering difference between 5X M & 5X N Beta 4
