### ISSUE TITLE
library-core.aar requiring `READ_EXTERNAL_STORAGE_PERMISSION` without reason

### ISSUE THREAD

**Issue by R1ck77** [googlevr/gvr-android-sdk#72]
This is a slightly more unpleasant relative of  #68, but still not a big deal.

The  "unpleasant" part is that, while in #68 the permission can be safely ignored (it's just in the docs), the inclusion in `library-core.aar`'s manifest trickles into the app and shows on the store (unless conscious effort is made to remove the line into the aar's manifest manually).

Apart from enforcing an unsophisticated practice, as I said: "no big deal".

**Comment by dav-cz** [comment]
The core library actually needs the READ_EXTERNAL_STORAGE permission to access the profile of the currently-paired Cardboard viewer. 

See https://developers.google.com/cardboard/android/get-started#manifest_file

**Comment by R1ck77** [comment]
Nope :) 

`core.aar` requires  `WRITE_EXTERNAL_STORAGE` already, therefore the `READ_EXTERNAL_STORAGE` permission is implied:

[From the READ_EXTERNAL_STORAGE documentation:](http://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE)

    Any app that declares the WRITE_EXTERNAL_STORAGE permission is implicitly granted this permission.

And btw, this doesn't prevent the read permission to show up in the google play store when installing, even if not really needed.

Again, *not a big deal* **at all**, just not the best possible style...

**Comment by dav-cz** [comment]
Oh I see, I didn't realize this bug was about READ_EXTERNAL_STORAGE being redundant. Thanks for clarifying.
Yes, we should get rid of that one too, thanks for reporting.

**Comment by dav-cz** [comment]
Fixed in v0.8. 
WRITE_EXTERNAL_STORAGE is not required, so we just declare READ_EXTERNAL_STORAGE.
