### ISSUE TITLE
Black line appear after back from cardboard view

### ISSUE THREAD

**Issue by sophietsen8634** [googlevr/gvr-android-sdk#74]
After I have clicked the cardboard button on the VrVideoView and back to the previous activity, a black line shown on the screen and never disappear.

![screenshot_2016-04-18-12-18-48](https://cloud.githubusercontent.com/assets/10460670/14598151/8df36b0c-0583-11e6-83d7-b58949a323df.png)
![screenshot_2016-04-18-12-19-03](https://cloud.githubusercontent.com/assets/10460670/14598152/8df3f6e4-0583-11e6-8fb4-a5af5a185cce.png)

**Comment by nathanmartz** [comment]
Is this on a 4.4 phone? If so, it's a known issue and we are working on a
fix.

**Comment by abhi2015** [comment]
@nathanmartz Was this fixed? Currently facing the same issue with gvr SDKv1.0 as well on a Galaxy S4 running 4.4.

**Comment by nathanmartz** [comment]
I think so, yes.
