### ISSUE TITLE
How can i change the movie resources during playing ?

### ISSUE THREAD

**Issue by Rogero0o** [googlevr/gvr-android-sdk#78]

**Comment by sigmaxipi** [comment]
Call `VrVideoView.loadVideo` when you want to change videos. You can test this with the simplevideowidget sample by launching and running `adb shell am start -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -a android.intent.action.VIEW -d file:///sdcard/FILENAME.mp4`. Then use `.seekTo(0)` to reset the position.
