### ISSUE TITLE
Shouldn't bake in com.google.protobuf

### ISSUE THREAD

**Issue by markstubhub** [googlevr/gvr-android-sdk#81]
This causes issues with other libraries that also follow this anti-pattern. I currently have an app that wants to use both libphonenumber and cardboard. Both are baking classes outside their namespace into the jar. If you can't set up an external dependency, then can you not repackage com.google.protobuf so it appears within your namespace and doesn't cause build issues?

**Comment by dav-cz** [comment]
Thanks for flagging and sorry for the inconvenience. We'll try to address this in the next version.

**Comment by sigmaxipi** [comment]
The protobuf libraries have now been extracted.
