### ISSUE TITLE
Google cardboard app not full screen

### ISSUE THREAD

**Issue by bd5155716** [googlevr/gvr-android-sdk#83]
I am going to build a Google Cardboard App for Android.

So I got the sample cardboard project from google and tested it on several device.

On the Samsung Galaxy, it looks good, but in blu or Nexus, it is not full screen.

I do not understand why.

**Comment by nathanmartz** [comment]
Cardboard rendering changes depending on the device you are using and the viewer you have setup. It's not necessarily supposed to always be full screen on every phone, but to look good when you view it in VR.

**Comment by bd5155716** [comment]
![nyegtqnsxyffljxdx_gnc4eyt_1cqo6uqw9lngzkbtq](https://cloud.githubusercontent.com/assets/15129497/15067540/6dedb1c2-1371-11e6-847d-d97049d2631e.jpg)
![1](https://cloud.githubusercontent.com/assets/15129497/15067546/7552e982-1371-11e6-82c1-7eff8c406c9f.jpg)

**Comment by bd5155716** [comment]
@nathanmartz please see above images. It is not what I want.

**Comment by nathanmartz** [comment]
Thanks for posting the images. You said that you saw it on a Nexus device,
too? If so, which one? Also, which viewer do you have paired?

**Comment by bd5155716** [comment]
@naokirodion Thank you for your reply.
It is nexus 4. In Samsung galaxy, it looks good.

**Comment by nathanmartz** [comment]
OK. Odd. Can you send an image of the Nexus 4, too? And can you confirm
that it actually looks wedding when you view the screen through a VR viewer?

**Comment by bd5155716** [comment]
@nathanmartz The first image is one thing of the Nexus 4.
I attached my apk file. 
[New folder.zip](https://github.com/googlesamples/cardboard-java/files/251767/New.folder.zip)

**Comment by bd5155716** [comment]
@nathanmartz Please let me know your thought.

**Comment by chr314** [comment]
I think the sdk recognizes your phone as tablet because this is how cardboard apps look on tablets

**Comment by nathanmartz** [comment]
Yeah. We rely on the phone to report a proper DPI but many do not. We have an internal database of overrides, but it doesn't have that device in it.

 I'm very surprised that you are seeing the problem on the Nexus 4. That's a standard test device for us.

**Comment by bd5155716** [comment]
@naokirodion can you let me know the way to fix this bug? Thank you

**Comment by jdduke** [comment]
Hi @bd5155716, would you mind testing against the latest SDK release? If you're still seeing the problem, feel free to re-open this bug. Thanks.
