### ISSUE TITLE
Cardboard Bazel BUILD files

### ISSUE THREAD

**Issue by sbilkoloft** [googlevr/gvr-android-sdk#86]
Now that Bazel is open source, can you include a BUILD file in the cardboard SDK repo? Our project is built over Bazel and NDK and we'd like to bring cardboard into the mix.

**Comment by dav-cz** [comment]
This is currently blocked by the fact that Bazel doesn't support importing AARs in android builds. 
https://github.com/bazelbuild/bazel/issues/564

**Comment by aj-michael** [comment]
Hi, just as an update on this, we are currently working on AAR import support in Bazel. There are a few problems that we are still thinking about the solutions for, but a limited version of the `aar_import` rule is now available in Bazel. Unfortunately, it does not yet support native libraries in AARs which I've noticed that `libraries/common/base.aar` includes.

**Comment by jdduke** [comment]
We don't have any immediate plans to support Bazel with the public samples. We'll reopen this in the future if that changes. Thanks for the request.
