### ISSUE TITLE
Is there any place to download source code of library ? (commonwidget.aar )

### ISSUE THREAD

**Issue by chuangzai** [googlevr/gvr-android-sdk#87]
I need custom UI. Is there any place to download source code of library commonwidget.aar? Thanks~

**Comment by alexliu-qiyi** [comment]
+1 when could these source code opend?

**Comment by mikulbhatt** [comment]
+1

**Comment by dav-cz** [comment]
No plan to open source the common widget UI code for now, sorry!
(but if you're adventurous you'll notice that our java code is currently not obfuscated)

**Comment by arumani** [comment]
@dav-cz Doesn't customizing UI(replace .png, modify layout.xml, etc.) in .aar file violate license? (unzip -> modify -> zip -> use in apk)
I'm sorry to comment closed issue.
