### ISSUE TITLE
Can't install controller emulator (INSTALL_FAILED_NO_MATCHING_ABIS)

### ISSUE THREAD

**Issue by nirajsanghvi** [googlevr/gvr-android-sdk#88]
I'm having trouble installing the controller emulator for the Daydream Development Kit on a second device. It doesn't seem to like any of the devices I've tried it on (Nexus 6, Galaxy Note 4). The install fails with this message which makes me think the .apk file may not be packaged correctly or setup to handle different CPU architectures: "Failure [INSTALL_FAILED_NO_MATCHING_ABIS]".

I'm using the following link per the dev kit setup instructions:
https://github.com/googlevr/gvr-android-sdk/blob/master/ndk-beta/apks/controller_emulator.apk?raw=true

**Comment by nirajsanghvi** [comment]
Update: Getting failure to install on a Nexus 5 as well.

**Comment by ReedL** [comment]
Seeing very similar issue trying to install the controller emulator with a Nexus 6 and a Nexus 4, although my error message is "[INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]"

**Comment by andna** [comment]
LG G2 also reported with trobule to install the apk.

**Comment by nathanmartz** [comment]
We're looking into this now. We'll post more info here shortly. Sorry for
the inconvenience!

**Comment by phuctk93** [comment]
HI, LG VU II and HTC one M8 have a same issue! Thank you very much GG Team!

**Comment by nirajsanghvi** [comment]
It looks like the updated .apk in https://github.com/googlevr/gvr-android-sdk/commit/0954a01934199b8536755f06688d98e3d2a958e4 has fixed the issue. I was able to install and run the controller emulator on the Nexus 6 and the Galaxy Note 4 successfully. Thanks!

**Comment by nathanmartz** [comment]
Great! Was due to a build process bug. Shouldn't happen again.

**Comment by spawnlt** [comment]
Actually install doesn't work again on the latest version v1.8  (phone NEXUS 5 M 6.0.1). Only got working some older version working v0.8.1
