### ISSUE TITLE
the new version can not play m3u8 video

### ISSUE THREAD

**Issue by Millertoken** [googlevr/gvr-android-sdk#89]
can i use other mediaplayer to paly videos on VideoWidget?

**Comment by nathanmartz** [comment]
Sorry, we don't support swapping media players.

**Comment by dav-cz** [comment]
Closing this issue.
As Nathan said we probably won't support swapping to mediaplayer, but should be able to support m3u8 via ExoPlayer. Filed here https://github.com/googlevr/gvr-android-sdk/issues/89.
Thanks!
