### ISSUE TITLE
Support for Vulkan+Daydream VR on native apps?

### ISSUE THREAD

**Issue by oscarbg** [googlevr/gvr-android-sdk#90]
Hi,
don't know if a stupid question..
but just browsing the code can't search any reference to Vulkan support..
as Vulkan may allow even better support for VR games asking if Google VR NDK SDK allows or not Vulkan as a graphics API?
 if not asking if an app supporting Vulkan+Google VR Daydream will be posible via updated Google VR SDK or also will require platform updates?
i.e. a new version of Android maybe Android O next year..
thanks..

**Comment by nathanmartz** [comment]
There is no Vulkan support in our sdks currently but we definitely agree
that there's a ton of potential for it to improve performance in VR. We'll
be looking into adding Vulkan support in a later SDK update, but no hard
dates to talk about right now.

**Comment by griffin2000** [comment]
Same as @lixiang-robot said. Any updates?

**Comment by jdduke** [comment]
Still nothing concrete to share, but Vulkan support is definitely a high priority item on our radar.

**Comment by oscarbg** [comment]
from IO we know is part on Daydream 2.0 SDK shipping this fall!

**Comment by oscarbg** [comment]
Hi @nathanmartz @jdduke,
Still no news on daydream 2.0 Euphrates with vulkan support.. hope for a release at GDC next week or google I/O 2018 at least,right?
BTW issuse should be kept open..

**Comment by jdduke** [comment]
Hi @oscarbg, we'll be sure to open the issue when we have any updates to share on the matter.
