### ISSUE TITLE
Starting yaw position

### ISSUE THREAD

**Issue by tomrenn** [googlevr/gvr-android-sdk#91]
The [VR View for the web](https://developers.google.com/vr/concepts/vrview#control_parameters) has a `start_yaw` control parameter. I don't see a way to do it in the 0.8.0 release. Is there a way to achieve this or plans to add it in a future release?

**Comment by nathanmartz** [comment]
There is no way to do it in Android presently, but we'll look into that for
the next release.

**Comment by vagnercsouza** [comment]
I also need to set the yaw position at runtime. My app is going to be used inside a car, and the video's center needs to be locked at car's center. That's my suggestion for next release.

Thanks.

**Comment by sigmaxipi** [comment]
If you want more complex touch & gryro controls, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
