### ISSUE TITLE
support for livestreaming over HLS .m3u8

### ISSUE THREAD

**Issue by mikulbhatt** [googlevr/gvr-android-sdk#92]
When are you planning to support livestreaming 360 videos over HLS? Cardboard is already using ExoPlayer library for playback. ExoPlayer is very well designed to support HLS. Are there any plans to start supporting that in googleVR?

**Comment by mikulbhatt** [comment]
any update or plans to support HLS?

**Comment by mikulbhatt** [comment]
@nathanmartz ?

**Comment by nathanmartz** [comment]
We're looking into that now and will have more info in a bit.

**Comment by Millertoken** [comment]
i also want to play m3u8 videos,can you do this first,please?thank you very much.@dav-cz

**Comment by dav-cz** [comment]
@mikulbhatt, @Millertoken, do the URLs that you want to play always end up with .m3u8?

**Comment by lawrencewqy** [comment]
i also want to play .m3u8 videos over HLS, please do this first,thank you .

**Comment by grobm** [comment]
HLS would be nice!

**Comment by mikulbhatt** [comment]
@dav-cz correct, the urls i want to play ends up with .m3u8 for 90% cases

**Comment by dav-cz** [comment]
Looks like HLS is popular!
@mikulbhatt, thanks. We're going to add an explicit option in the API so that the video format can be specified by developers (HLS vs regular container formats like mp4).

Would you (or somebody else on the thread) have a m3u8 test file you could share that we could test against? We tried with a couple of sample files mentioned in the ExoPlayer docs but I'd just want to double check with more files.

**Comment by mikulbhatt** [comment]
@dev-cz you can try this test url - http://yahooios2-i.akamaihd.net/hls/live/224964/iosstream/adinsert_test/master.m3u8

**Comment by dav-cz** [comment]
@mikulbhatt thanks for the link, I just tried and playback works. However that video is not in 360 equirectangular format, so it looks stretched.

For the gvr release update, hopefully we'll have it out sometime next week.

**Comment by mikulbhatt** [comment]
thanks @dav-cz , yes that video is not in 360. Glad it will be available next week. Thanks a lot!

**Comment by jeremysciarappa** [comment]
Thanks for the update. Any chance the new gvr release will have a fix for the 6.0.1 issue listed in #75?

**Comment by azeemmohd** [comment]
@dav-cz : Is the update for HLS playback support out yet?

**Comment by dav-cz** [comment]
This is now working with this morning's update.
Use the loadVideo(url, options) function, with options.inputFormat = Options.FORMAT_HLS.
We still need to update the documentation reference, should happen very soon. In the mean time you can take a look at the code for the sample video app.

In particular @mikulbhatt's HLS stream can now be played using the following command:

adb shell am start -a android.intent.action.VIEW -n com.google.vr.sdk.samples.simplevideowidget/.SimpleVrVideoActivity -d "http://yahooios2-i.akamaihd.net/hls/live/224964/iosstream/adinsert_test/master.m3u8" --ei inputFormat 2

**Comment by abhi2015** [comment]
@dav-cz  Do we have support for adaptive decoding in HLS i.e. playback of streams with adaptive bitrate profiles (SMIL)?

**Comment by jietan** [comment]
@dav-cz Is the HLS streaming supported in the Google VR SDK for IOS? If not, is there any plan to support it? Thanks.
