### ISSUE TITLE
GvrView does not have getGLSurfaceView() method

### ISSUE THREAD

**Issue by ajavamind** [googlevr/gvr-android-sdk#93]
Please add this back as provided in previous 0.7.0 CardboardView class or show a way to get the GLSurfaceView.

**Comment by jdduke** [comment]
Hi @ajavamind, is there a particular API or feature of GLSurfaceView that you require? The getGLSurfaceView() method was technically hidden, and added only as a temporary stopgap measure to ease the transition away from depending on GLSurfaceView directly. Note that we do expose a subset of GLSurfaceView's API directly, e.g., setEGLConfigChooser(), setEGLConfigContext(), and queueEvent().

The primary motiation for removing GLSurfaceView from the public API is that it gives GvrView's implementation a lot more freedom to customize the View hierarchy and tailor the SurfaceView interaction.

If there is need and strong demand, we're open to evolving GvrView's API to accommodate any gaps in functionality that may have been introduced.

**Comment by ajavamind** [comment]
Thanks Jared, I'm able to remove use of GLSurfaceView in the code afterall,
so I don't need getGLSurfaceView() going forward. thanks,

Andy
