### ISSUE TITLE
Separate C and C++ API headers

### ISSUE THREAD

**Issue by astennu** [googlevr/gvr-android-sdk#94]
I see that you have C and C++ API in same header files and it rely on __cplusplus define to select which one should be used. Could you separate these APIs to individual header files. Reason is that I want to use C API from my C++ code rather C++ API and current implementation forces C++ code to use C++ API always.

Reason why I don't want to use C++ API is that it is using std::unique_ptr, std::function etc. which are causing issues in cross-platform codebase.

**Comment by jdduke** [comment]
Hi @astennu , thanks for the feedback.

Can I ask which platform in particular is causing your problems? The current API is only supported on Android, with iOS support forthcoming. Both of these platforms provide C++11-compatible compilers, and have done so for quite some time.

We'll look into splitting out the C++ bits from the C headers in a future release. In the meantime, you can either 1) not include the header on unsupported platforms, or 2) remove the C++ bits from the header.

**Comment by astennu** [comment]
Hello @jdduke, yeah we are currently integrating this new GVR API on Android. Of course looking for same API to iOS as well at some point. Basically our codebase just don't use STL, exceptions, RTTI and other stuff due to cross-platform (mobile, desktop and consoles), speed and code size reasons. Pretty common game technology decisions. Also NDK runtime mix with dozens of different libraries becomes nightmarish if would start to use APIs with STL.

**Comment by jdduke** [comment]
@astennu, with the latest release (0.8.5), defining GVR_NO_CPP_WRAPPER before including the GVR headers will suppress inclusion of the C++ wrapper code. Hope that helps. Cheers.

    #define GVR_NO_CPP_WRAPPER
    #include "gvr.h"

**Comment by astennu** [comment]
At least current master doesn't contain this fix or am I missing something?

**Comment by jdduke** [comment]
You're absolutely right, my mistake. It looks like the GVR_NO_CPP_WRAPPER change missed the branch cut by just a few hours. It will be included in the next (monthly) release. Apologies for the confusion.

**Comment by dav-cz** [comment]
GVR_NO_CPP_WRAPPER is now present in the latest version.
