### ISSUE TITLE
VrVideoView.loadVideo() not working

### ISSUE THREAD

**Issue by baaloo87** [googlevr/gvr-android-sdk#97]
Hi,

I was trying out the simplevideowidget sample and it works if I use `loadVideoFromAsset("congo.mp4")` but if I copy the video file to the device and try `loadVideo(Uri.parse("/sdcard/congo.mp4"))` it fails with a NPE:

`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
  at com.google.vr.sdk.widgets.video.VrVideoPlayerInternal.openUri(VrVideoPlayerInternal.java:252)
  at com.google.vr.sdk.widgets.video.VrVideoView.loadVideo(VrVideoView.java:96)
  at com.google.vr.sdk.samples.simplevideowidget.SimpleVrVideoActivity$VideoLoaderTask.doInBackground(SimpleVrVideoActivity.java:295)
  at com.google.vr.sdk.samples.simplevideowidget.SimpleVrVideoActivity$VideoLoaderTask.doInBackground(SimpleVrVideoActivity.java:290)`

If I do the same on version 0.7 the code works fine.

I tested on Galaxy S5 5.0 and Nexus 5 5.0.1 with the same result.

Any suggestions on how to make it work? Thank you and keep up the good work!

**Comment by sigmaxipi** [comment]
Use file:///sdcard/congo.mp4 as a workaround

**Comment by baaloo87** [comment]
Thank you very much, it works. If this is the way it should be done I suggest to update the reference.

**Comment by nihalmehdi** [comment]
workaround that works for me..
public class DownloadVideoTask extends AsyncTask<String, Void, Uri> {
    String videoUrl ="http://host/test.mp4"
    private VrVideoView vrvideoView;
    private Context context;
    DownloadVideoTask (VrVideoView vrvideoView,Context context)
    {
        this.vrvideoView = vrvideoView;
        this.context = context;
    }

    @Override
    protected Uri doInBackground(String... url) {
        //HttpsURLConnection.setDefaultSSLSocketFactory(new NoSSLv3Factory());
        HttpURLConnection urlConnection = null;
        String fileName = "test.mp4";
        String filepath = context.getFilesDir() + File.separator + fileName;
        File file = null;
        try {
            URL videoUri = new java.net.URL(videoUrl);
            urlConnection = (HttpURLConnection) videoUri.openConnection();
            urlConnection.connect();
            InputStream in = urlConnection.getInputStream();
            FileOutputStream output = context.openFileOutput(fileName, context.MODE_PRIVATE);
            Utility.copyFile(in,output);
        }
        catch (java.net.MalformedURLException mex){
            String test = mex.toString();
            //Toast.makeText("Utility", mex.getMessage(), Toast.LENGTH_LONG);
        }
        catch (Exception ex)
        {
            String test = ex.toString();
            //Toast.makeText("tag",ex.getMessage(),Toast.LENGTH_LONG);
        }
        finally {
            if( urlConnection!= null ) {
                urlConnection.disconnect();
            }
        }

        return Uri.parse(filepath);
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    @Override
    protected void onPostExecute(Uri videoUri) {
        try {
            vrvideoView.loadVideo(videoUri);
            vrvideoView.playVideo();
        }
        catch (Exception ex){
            String msg = ex.getMessage();
            //Toast.makeText(this,"Test",3000)
        }

    }
}

**Comment by dav-cz** [comment]
With v0.8.1, "/sdcard/congo.mp4" is now a valid path, no need for the "file:///" prefix anymore.

**Comment by gvsharma** [comment]
it is working in my nexus and one plus

**Comment by liuhao722** [comment]
soga

**Comment by liuhao722** [comment]
Utility.copyFile(in,output);     
what's this content from jar?

**Comment by liuhao722** [comment]
Under the advice, how to play the network VR video streaming, thank you

**Comment by nihalmehdi** [comment]
It is a below utility method.. that i missed to share earlier..
 public static void copyFile(InputStream in, OutputStream out) throws IOException {
        byte[] buffer = new byte[1024];
        int read;
        while((read = in.read(buffer)) != -1){
            out.write(buffer, 0, read);
        }
    }
