### ISSUE TITLE
PanoramaView inside Listview 

### ISSUE THREAD

**Issue by chuangzai** [googlevr/gvr-android-sdk#98]
when I put PanoramaView inside Listview and move the previous VrPanoramaView to bottom,then highly probable that parts of next PanoramaView will appear in the bottom：
![1](https://cloud.githubusercontent.com/assets/14247916/15500522/a07b83ee-21db-11e6-9d40-52f9e87ae9ac.png)
![2](https://cloud.githubusercontent.com/assets/14247916/15500523/a1e44aa4-21db-11e6-91a6-f8c7fff3fe8d.png)

How can I fix it ?

**Comment by dav-cz** [comment]
VrPanoramaView is not currently designed to perform well in ListView.
It uses GLSurfaceView, and from experience you can't really have more than 3 or 4 of these views rendered at the same time on the screen. Also it's a bit heavy weight as each view will spin its own thread, perform rendering at a high frame-rate, etc. So it will be hard to guarantee a smooth scrolling in these conditions.

That being said, you can find work-arounds. Take a look at what we do in the Cardboard App for Android, in the "Get apps" tab. We have a ListView with regular images, and also one (and only one!) VrPanoramaView. As the user scrolls, we look at the most visible item in the list. For that item, we trigger a LoadImageFromBitmap for the corresponding panorama. When it's loaded, we move the VrPanoramaView at the right position in the list and fade it to 100% visibility.
This way we have something that is smooth and still shows some panorama goodness.

In any case thanks for flagging this, we should add comments in the doc to specify that is not recommended to have more than one or two active VrPanoramaView's in a layout.
Hope that helps.

**Comment by chuangzai** [comment]
@dav-cz Thank you for your help and patience.It's useful for me.

**Comment by dav-cz** [comment]
@chuangzai, you're welcome!
